### ISSUE TITLE
Possibility to add Morteza Bashsiz providers as a drop down to domain page

### ISSUE THREAD

**Issue by ghost** [hiddify/Hiddify-Manager#194]
1. Possibility to add Morteza Bashsiz providers as a drop down to domain page (plus textbox to overwrite it)
2. With auto update fetches the new ips from "http://bot.sudoer.net/best.cf.iran" and set it if provider in the dropdown selected

**Comment by sh4msi** [comment]
This offer is really great
Even better there is a place for this in the settings
- To specify the URL of the source (the default can be the address provided by Morteza)
- Time period to check
- ...
---------------------------

این پیشنهاد واقعا عالیه
حتی بهتر در تنظیمات جایی برای این موضوع وجود داشته باشه
- برا مشخص کردن یو ار ال منبع (پیشفرض میتونه ادرس ارائه شده توسط مرتضی باشه)
- دوره زمانی برای چک کردن 
- ...

**Comment by hiddify** [comment]
اضافه کردنش باعث فیلترشدن سریعش نمیشه؟

**Comment by sh4msi** [comment]
> با سلام، داشتم فکر میکردم چون کلاینت هم دست خودت حتی میشه الگوریتم مرتضی تو ایران اجرا کنی به سرورها بگی چه آی‌پی بهتره. چون بنطر میاد آی‌پی مرتضی که خودش میده سریع لو میره

همونطوری که بالا پیشنهاد دادم نباید این موضوع بصورت هارد کد اجراشه و همیشه از url که مرتضی داده استفاده شه و نشه تغییرش داد، میتونه پیشفرض ماجرا urlی باشه که مرتضی ارائه داده ولی مثلا من نوعی میتونم اسکریپت مرتضی را رو سرور خودم اجرا کنم و url رو در تنظیمات جایگزاری کنم

**Comment by sh4msi** [comment]
در مرحله اول یک نکته اینکه این به احتمال فوق زیاد زمانی که من نوعی اسکنر رو در سرور خودم اجرا کنم با زمانی که شما در سرور خودت اجرا کنی نتیجه متفاوتی در خروجی نشون بده بخصوص پریود اسکن رو خودمون بتونیم مشخص کنیم پس نگرانی خاصی از اون بابت نباید باشه

----
حالتی که میگی هم حتما میتونه نتیجه مطلوبی داشته باشه ولی مشکل اصلی اینکه ux ماجرا رو به شدت میبره زیر سوال و کاربر نهایی رو در دسر میندازه و این شاید برا منی که استفاده شخصی دارم مهم نباشه ولی برا دوستانی که دارن سرویس میدن به خلق الله حذاب نیست 
----
حتی همین ست شدن خودکار ای پی های توسط اسکنر هم خیلی جذاب نیست و کاربر اگه بخواد بهترین سرعت رو داشته باشه باید مدام از طریق لینک اشتراک اپدیت بزنه و بعد تست کنه و بعد متصل شه که خود این  میتونه بهبود پیدا کنه یکی از راهکارهاش ساختارهای هست که دوستانی مثل سیگارو در تویتر اجرا کردن
اومدن ایپی تمیز به نسبت اپراتور و با کال کردن یک url برمیگردونن 
این یعنی دیگه کاربر نیاز نیست با هم بار تغییر اپی اپدیت بزنه (و چون نمیدونه کی قراره تغییر  کنه باید مدام چک کنه)
