### ISSUE TITLE
سوالاتی در رابطه با اسم کاربر

### ISSUE THREAD

**Issue by APT-ZERO** [hiddify/Hiddify-Manager#298]
سلام
اگر دو کاربر ساخته بشه با اسم یکسان اما UUID متفاوت، آیا مشکلی ممکنه ایجاد بشه؟
آیا هنگام انتخاب اسم کاربر میشه از هر واژه ای استفاده کرد؟ چه محدودیت هایی داره از لحاظ تعداد ارقام و کاراکترست
ممنون

**Comment by hiddify** [comment]
مشکلی ایجاد نمیشه 
سوالات را در قسمت سوالات بپرسید بهتره
