### ISSUE TITLE
دامنه های ایرانی

### ISSUE THREAD

**Issue by Sysop0098** [hiddify/Hiddify-Manager#3298]
چیکار کنیم دامنه های ایران مجدد فعال بشه 
یکبار از رو پنل بستیم مجدد باز کردیم دیگه هرکاری کردم نشد ک نشد

**Comment by lymanjre** [comment]
لطفا وارپ را فعال کنید و حالت را روی سایت های ایرانی قرار دهید. اگر سایت ایرانی Iran Access نباشد، باز میشود. این ایشو فعلا بسته میشود در صورت تست وارپ و تکرار مشکل اعلام نمایید. با سپاس از همراهی شما
