### ISSUE TITLE
can I register the geoip and domain suffix config somewhere?

### ISSUE THREAD

**Issue by XopoIII** [hiddify/Hiddify-Manager#3331]
hi, can I register the geoip and domain suffix config somewhere? the settings for silence come with the country of Iran and when you change the config in the client, it can automatically come from the server and overwrite, I would like the necessary routing configs to come from the server immediately

**Comment by amin2plus** [comment]
Hi, you can change your country in the 'Hiddidy Web panel/settings/general settings/country.' If you are in China, the panel will use the CN geoip.

![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/723b4313-87a4-4c7b-a871-fd4395f58042)

however, If you're looking to make more advanced changes, you can find the geoip files at these paths on the server:
`/opt/hiddify-config/singbox/geoip.db`
`/usr/local/share/xray/geoip.dat`
*these files might changes back to their origin whenever you update your panel

**Comment by XopoIII** [comment]
when i set othet country, and refreshed config in app, from server it comes IR :(
