### ISSUE TITLE
ارور اکانت مدیریت ربات تلگرام

### ISSUE THREAD

**Issue by SadraSaad** [hiddify/Hiddify-Manager#3334]
ربات تلگرام مدتیه که برام فایل های بک‌آپ رو نمیفرسته. از طریق خود پنل (تنظیمات> بات تلگرام) که مجددا وارد شدم که ببینم میتونم یوزر بسازم و دسترسی مدیریت دارم بهش یا خیر، با این پیام مواجه شدم.
![Untitled](https://github.com/hiddify/Hiddify-Server/assets/142924311/eecb2cc3-7828-4e2e-b3f8-e4868ebd107c)
ورژن پنلم در حال حاضر 8.6.10ئه. چطور میشه این مشکل رو برطرف کرد؟
این رو هم ذکر کنم که ربات برای یوزرها اوکیه و مشکلی نداره!

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون

**Comment by SadraSaad** [comment]
سلام. روزتون بخیر. ممنونم. رو آخرین ورژن 8.8.95 هم کماکان این مشکل وجود داره!
![image](https://github.com/hiddify/Hiddify-Manager/assets/142924311/88a9397e-9a3b-4c98-8f57-d9f53f64620a)
