### ISSUE TITLE
اتصال ssh

### ISSUE THREAD

**Issue by alie110** [hiddify/Hiddify-Manager#3336]
سلام
ممنون بابت نرم افزار 
اما سوالی که برام پیش اومد این بود 
اتصال SSH و DROPBEAR چطوری انجام میشه؟
توی نکو باکس با این کد انجام میشه 
{
    "client_version": "SSH-2.0-OpenSSH_7.4p1",
    "password": "123456789",
    "server": "0.0.0.0",
    "server_port": 22,
    "type": "ssh",
    "user": "abc"
}
اما یه مشکل که داره اینه که حتما باید آی پی وارد بشه و دامنه رو نمیخونه. ینی جای آی پی دامنه رو که وارد میکنیم کار نمیکنه. 
اگه توضیحی برای اتصال تو این نرم افزار بدین ممنون میشم و میشیم.
تشکر

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
