### ISSUE TITLE
مشکل در باز کردن بعضی سایت ها بخاطر سرتیفیکیت

### ISSUE THREAD

**Issue by amin2plus** [hiddify/Hiddify-Manager#3337]
**Describe the bug**

من تازگی یک سرور جدید نصب کردم بخاطر اینکه پنل آپدیت نمیشد کلا سیستم عامل و پنل هایدیفای رو مجدد نصب کردم
یعنی ورژن 8.6.10 رو نصب کردم و بک آپ قدیمی رو restore کردم که همه چیز هم بدرستی برگشته
مشکلی که هست اینه که توی یک سری سایت های https که میرم بعضیاشون میگن **سرتیفیکیت من** valid نیست.
یک بار هم محتوای پوشه `acme.sh/lib/cert/` و پوشه `ssl/` رو پاک کردم و reinstall زدم ولی باز مشکل باقی هست.

این صفحه ای که سایت هایی که گفتم بهم نشون میدن:

![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/54c56b49-a988-4136-875d-277d62fa0eec)

این هم زمانی که روی دیدن سرتیفیکیتم توی آدرس بار مرورگر میزنم:

![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/15879831-37a9-47ac-97ec-b91284de8ad6)

نکته اینکه من یک سرور دیگه هم دارم که تقریبا یک سالی هست که هایدیفای نصبه داخلش، و با کانفیگ های اون سرور همین سایت هایی که گفتم رو بدون مشکل باز میکنم

**To Reproduce**

حدسم اینه که اسکریپت دریافت سرتیفیکیت عوض شده و مثل قدیمیه بدون مشکل نیست
برای نمونه هم مثلا توی این سایت `https://rethinkdns.com/` که با کانفیگ سرور جدید میرم خطا میگیرم در صورتی که با خاموش بودن فیلترشکن یا استفاده از کانفیگ های سرور قدیمی بدون مشکل باز میشه
حتی وقتی به کانفیگ **سرور جدید** وصل هستم و **لینک ادمین سرور قدیمی** رو میخوام باز کنم این خطا رو میگیرم.

**Expected behavior**

بدون مشکل هر سایتی باز بشه.

**Desktop (please complete the following information):**
 - OS: any OS
 - Browser: all browsers(tested on Chrome, chromium, vivaldi, Firefox)
 - Version: any version

**Smartphone (please complete the following information):**
 - Device: all Devices(tested on Android, iOS, iPad)
 - OS: android, iOS
 - Browser: all browsers(tested on Chrome, Vivaldi, Safari for mobile)
 - Version: any version

**Comment by amin2plus** [comment]
مشکل برطرف شد

**Comment by amirsaam** [comment]
@amin2plus مشکل چطور برطرف شد؟

**Comment by amin2plus** [comment]
> @amin2plus مشکل چطور برطرف شد؟

صبح پاشدم دیدم مشکل برطرف شده ، چون آپدیت خودکار پنل فعاله حدس زدم که توی آپدیت درست شده مشکل

**Comment by amirsaam** [comment]
متاسفانه مشکل برای من کماکان پا برجاست #3359 کلا اگر دامنه رو پشت کلادفلیر نذارم پنل برام باز نمیشه
جالبه که اگر دامنه دیگه ای هم به صورت دایرکت اضافه کنم هم کار نمی‌کنه :))
