### ISSUE TITLE
چه تو نسخه ریلیز و چه تو نسخه دولوپ، اگه کاربری رو ریست زمانی کنی، ریست حجمی هم برای اون کاربر اعمال میشه.

### ISSUE THREAD

**Issue by Mfarahani1914** [hiddify/Hiddify-Manager#3338]

**Comment by Mfarahani1914** [comment]
چه تو نسخه ریلیز و چه تو نسخه دولوپ، اگه کاربری رو ریست زمانی کنی، ریست حجمی هم برای اون کاربر اعمال میشه.

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
