### ISSUE TITLE
مشکل warp+

### ISSUE THREAD

**Issue by mnhiddify** [hiddify/Hiddify-Manager#3340]
سلام سرور جدیدم رو با بکاپ از سرور قدیمی بالا اوردم و وارپ+ درست نیست! سایت های ایرانی رو باز میکنه ولی متاسفانه تو سایت ip.gs ایپی خودمون نشون میده - ورژن پنل قدیم و جدید ۸.۶.۱۰ هستش - سیستم عامل قبلی ابونتو ۲۲.۰۴ و سیستم عامل جدید ۲۰.۰۴

**Comment by crowlink** [comment]
سلام وارپ فقط تو اوبونتو 22 درست کار میکنه تو 20 درست کار نمیکنه

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
