### ISSUE TITLE
مشکل نصب 

### ISSUE THREAD

**Issue by ramin346** [hiddify/Hiddify-Manager#3342]
متاسفانه با چندتا سرور تست کردم هیدیفای نصب نمیشه و این ارور رو میده

Archive:  hiddify-manager.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of hiddify-manager.zip or
        hiddify-manager.zip.zip, and cannot find hiddify-manager.zip.ZIP, period.
bash: install.sh: No such file or directory
Press any key to go  to menu

**Comment by alkstsgv** [comment]
Hello!
I had the same problem. I tested hiddify on ubuntu server 22.04 LTS on 2 anothers VPS different providers and it didn't work. But on Vultr it worked properly with pre-init scripts.

**Comment by lymanjre** [comment]
لطفا مجددا انجام بدید مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
