### ISSUE TITLE
نشون ندادن ورژن پنل

### ISSUE THREAD

**Issue by ea1234567** [hiddify/Hiddify-Manager#3343]
مشکل نشون ندادن ورژن پنل در منوی SSH

این مشکل ساده بعد از گذشت نزدیک 2 ماه و گزارش دادن در تلگرام و گیت هاب هنوز برطرف نشده

پس چرا میگید مشکلات رو حتما ایشو کنید تا برطرف کنیم.الان
این مشکل مطمئنم برطرف کردنش کار یک دقیقه هست
ولی هیچ اقدامی صورت نگرفته
اگر بررسی نمیکنید حداقل بگید چیزی رو ایشو نکنیم

![273312488-49988e12-e8d8-4b63-832f-88c73191b1f0](https://github.com/hiddify/Hiddify-Manager/assets/40317198/2cd5f34d-31a7-400b-8c1c-3375952ded57)

**Comment by amin2plus** [comment]
رفیق تیم هایدیفای به رایگان این پنل رو در اختیارتون گذاشتند، برای بهتر شدن این پرو کار مثبتی که میشه انجام داد اینه که مشکلات رو ایشو کنید تا دوستان دولوپر که لطف میکنن برای این پروژه توی زمان آزادشون زمان میذارن مشکل رو بررسی کنن

میتونی برای برطرف شدن مشکل سرور رو مجدد نصب کنی:
اول خروجی بک آپ رو از پنل هیدیفای دانلود کن، توی پنل هاستت بزنن مجدد سیستم عامل رو برات نصب کنند (معمولا رایگان هست) reinstall OS
حدودا 90% هاست ها خودکار برات اوکی میکنند و چند دقیقه بیشتر طول نمیکشه ، (بعضی هاست ها هم هستند که صرفا یه image نصب رو mount میکنن و خودت باید سیستم عامل رو نصب کنی که کاری نداره و توی یوتوب کلی ویدیوو هست)
سیستم عامل که بالا امد یه `sudo su&&apt update&&apt full-upgrade -y&&apt autoremove -y&&reboot now` بزن و بعد اسکریپت نصب هیدیفای رو اجرا کن، پنل که بالا امد مستقیم برو توی قسمت بک آپ و فایل بک آپی رو بده و بزن تنظیمات؛کاربرا و دامین ها برگردند
کلا 15 دقیقه طول میکشه همه اینا، اگه کاربر زیاد داری یه شب دیر وقت یا صبح خیلی زود بزن کسی متوجه نمیشه، لینک کاربرا هم تغییر نمیکنه

اگه فکر میکنی یک دقیقه ای برطرف میشه مشکل، قطعا میتونی یک دقیقه وقت بذاری و با درخواست pull request به برطرف شدن مشکل کمک کنی

**Comment by ea1234567** [comment]
> رفیق تیم هایدیفای به رایگان این پنل رو در اختیارتون گذاشتند، برای بهتر شدن این پروژه کار مثبتی که میشه انجام داد اینه که مشکلات رو ایشو کنید تا دوستان دولوپر که لطف میکنن برای این پروژه توی زمان آزادشون زمان میذارن مشکل رو بررسی کنن
> 
> میتونی برای برطرف شدن مشکل سرور رو مجدد نصب کنی: اول خروجی بک آپ رو از پنل هیدیفای دانلود کن، توی پنل هاستت بزنن مجدد سیستم عامل رو برات نصب کنند (معمولا رایگان هست) reinstall OS حدودا 90% هاست ها خودکار برات اوکی میکنند و چند دقیقه بیشتر طول نمیکشه ، (بعضی هاست ها هم هستند که صرفا یه image نصب رو mount میکنن و خودت باید سیستم عامل رو نصب کنی که کاری نداره و توی یوتوب کلی ویدیوو هست) سیستم عامل که بالا امد یه `sudo su&&apt update&&apt full-upgrade -y&&apt autoremove -y&&reboot now` بزن و بعد اسکریپت نصب هیدیفای رو اجرا کن، پنل که بالا امد مستقیم برو توی قسمت بک آپ و فایل بک آپی رو بده و بزن تنظیمات؛کاربرا و دامین ها برگردند کلا 15 دقیقه طول میکشه همه اینا، اگه کاربر زیاد داری یه شب دیر وقت یا صبح خیلی زود بزن کسی متوجه نمیشه، لینک کاربرا هم تغییر نمیکنه
> 
> اگه فکر میکنی یک دقیقه ای برطرف میشه مشکل، قطعا میتونی یک دقیقه وقت بذاری و با درخواست pull request به برطرف شدن مشکل کمک کنی

این مشکل با نصب مجدد حل نمیشه
سه تا سرور از سه دیتاسنتر مختلف دارم هر سه این مشکل رو دارن
در ضمن من برنامه نویس نیستم که pull request بزنم ولی اونقدری میدونم که نشون ندادن ورژن مشکلی نیست که بیشتر از یک دقیقه وقت دوولوپر رو بگیره
