### ISSUE TITLE
ریستارت سیستم

### ISSUE THREAD

**Issue by randomguy-on-internet** [hiddify/Hiddify-Manager#3345]
سلام

گزینه ریستارت سیستم در پنل به درستی عمل نمیکند و فقط لاگ رو نشون میده و سرویس ها رو ری استارت نمیکنه.

**Comment by amin2plus** [comment]
![image](https://github.com/hiddify/Hiddify-Manager/assets/31206022/2ce91b27-c2c8-46d0-9095-f6cbb10a0df9)
