### ISSUE TITLE
به روزرسانی نشدن پنل

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Manager#3346]
با سلام و خسته نباشید 
لطفا مشکل آپدیت نشدن پنل رو حل کنید هر سری باید بکاپ بگیریم کل سرور رو پاک کنیم دوباره پنل رو نصب کنیم و بکاپ رو برگردونیم قبلا خودش آپدیت میشد راحت مشکل هم نداشت نمیدونم الان چرا آپدیت پنل رو درست نمیکنید دلیل خاصی داره هر سری هم که ورژن جدید میدید پنل پیغام قدیمی بودن ورژن رو میده و میگه آپدیت کنید که آپدیت نمیشه

**Comment by amin2plus** [comment]
ورژن ubuntu 20.04 رو استفاده میکنی؟

**Comment by alirezarah** [comment]
بله ورژن 20 هست

**Comment by amin2plus** [comment]
چرا 22.04 نه؟ این مشکل توی ubuntu22.04 نیست.

**Comment by alirezarah** [comment]
یعنی به 22 آپدیتش کنم این مشکل حل میشه؟

**Comment by amin2plus** [comment]
من تازگی روی 22.04 پنل نصب کردم و سرور قدیمی هام هم 22.04 دارندن و مشکلی ندارم، چند تا issue دیگه هم دیدم روی 20.04 هستند و خودت هم فکر کنم سه سرور داری این مشکل رو دارن، برای همین **حدس** میزنم به نسخه سیستم عامل باشه

**Comment by Farazzzssss** [comment]
نه من رو 22هم دارم این مشکلو. ولی رو 20 خیلی بیشتره

**Comment by alirezarah** [comment]
اصلا کلا نه رو 22 و نه رو 20 چه از طریق ssh و یا با پنل آپدیت نمیشه باید فقط ریبیلد کرد

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
