### ISSUE TITLE
ارور در نصب 

### ISSUE THREAD

**Issue by ar-sam** [hiddify/Hiddify-Manager#3347]
در هنگام نصب با این خطا مواجه میشم:
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8j5hieuq/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8j5hieuq/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8j5hieuq/grpcio/pip-egg-info
         cwd: /tmp/pip-install-8j5hieuq/grpcio/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8j5hieuq/grpcio/setup.py", line 95, in <module>
        import commands
      File "/tmp/pip-install-8j5hieuq/grpcio/src/python/grpcio/commands.py", line 31, in <module>
        import support
      File "/tmp/pip-install-8j5hieuq/grpcio/src/python/grpcio/support.py", line 111, in <module>
        errors.CompileError: diagnose_compile_error,
    AttributeError: module 'setuptools.errors' has no attribute 'CompileError'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by lymanjre** [comment]
لطفا مجددا تلاش کنید مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
