### ISSUE TITLE
مشکل در نصب با docker

### ISSUE THREAD

**Issue by iebu123** [hiddify/Hiddify-Manager#3348]
موقع نصب با docker ارور زیر رو می ده: (سرور تازه نصب شده و فقط update و upgrade کردم) (سیستم عامل: ubuntu 20.04)

ERROR 2002 (HY000): Can't connect to local server through socket '/run
stty: 'standard input': Inappropriate ioctl for device
Enter current password for root (enter for none):
stty: 'standard input': Inappropriate ioctl for device

![image](https://github.com/hiddify/Hiddify-Manager/assets/43946890/7911cf98-9737-42cb-849e-b971f3567bed)

**Comment by RayWangQvQ** [comment]
same

**Comment by lymanjre** [comment]
داکر پشتیبانی نمیشه
