### ISSUE TITLE
Properly working of many modes together

### ISSUE THREAD

**Issue by alkstsgv** [hiddify/Hiddify-Manager#3349]
I have one server and two linked domains to it.
The first domain in Direct mode, the 2nd domain in CDN mode, 2nd domain also has additional mode "workers". Also I created "reality mode" with working SNI.

When I update subscription in nekoray, v2rayNG I get many configs such as:
{1st domain} CDN grpc etc, and then {2nd domain} WS VLESS etc., and then {workers} grpc VLESS. There are 32 configs from all of this. But, only 15 works, anothers don't work. 

My questions are:
I want to know why don't all received by subscription configs work?
What should I do to make all received configs work correctly?
If it really necessary what types of modes should I use to make all configs work properly?

**Comment by lymanjre** [comment]
Go to the wiki and see All tutorials page. We put a lot of articles in this regard
