### ISSUE TITLE
اشکال در اتصال به ssh

### ISSUE THREAD

**Issue by hiwasam** [hiddify/Hiddify-Manager#3350]
کانفیگ ssh داخل لینک سابسکریبشن معمولی وجود نداره، داخل لینک ساب خودکار وجود داره ولی با لینک خودکار فقط کانفیگ ssh متصل میشه و بقیه کانفیگا پینگ نمیدن. 
درضمن وقتی کانفیگ ssh رو به صورت تکی کپی میکنم داخل هیچ برنامه ای از جمله نکوباس و هایدیفای نکست اضافه نمیشه و ارور میده

**Comment by sbh96** [comment]
همین مشکل منم دارم

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
