### ISSUE TITLE
پیشنهاد: اضافه کردن آی پی به وارپ

### ISSUE THREAD

**Issue by GoldenOne1** [hiddify/Hiddify-Manager#3352]
توی نسخه آینده قراره قابلیت اضافه کردن سایت به وارپ اضافه بشه
پیشنهاد میکنم قابلیت اضافه کردن ip هم اضافه بشه که گاها واجب تر از سایت هست
بعضی اپلیکیشن ها سایت خاصی ندارن و مجبوریم آی پی اونارو به وارپ اضافه کنیم ولی راه حلی برای این کار نداریم
با تشکر

**Comment by lymanjre** [comment]
روی بتا این قابلیت اضافه شده است
