### ISSUE TITLE
آدرس سایت جعلی

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Manager#3353]
سلام و خسته نباشید 
آدرس سایت جعلی کار نمیکنه و مشکل داره و این ارور رو میده
![erorr](https://github.com/hiddify/Hiddify-Manager/assets/116164916/651baddc-8517-408b-82de-4e89781ca8b0)

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
