### ISSUE TITLE
آپدیت نشدن مشکل  Dev

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3355]
با درود و خسته نباشید

تو آخرین ورژن Dev تو مرحله کپی گیر میکنه

![update](https://github.com/hiddify/Hiddify-Manager/assets/6390536/fcdde7d4-0b3d-4fc6-b0cd-8070d324e54a)

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
