### ISSUE TITLE
چند ایده 

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3356]
با درود و خسته نباشید
 
یک درخواست دارم   محدودیت باند برای Agents/admins بذارید
این پرتکول ها رو میشه بررسی و اضافه کنید
RelayBaton
Brook
Mieru
Naive
Ping tunnel
Trojan
Trojan Go
ShadowSocks
ShadowSocksR
Wireguard

با تشکر

**Comment by lymanjre** [comment]
قبلا تیکت دیگری با این مضمون ثبت شده است
