### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by itsalivafaei** [hiddify/Hiddify-Manager#3362]
On Ubuntu 22.04 I installed panel version 8.6.10 and when I try to update it stops in the following line:

Error: Option '-v' requires an argument.
Unknown package mode: 

![image](https://github.com/hiddify/Hiddify-Manager/assets/35658253/c8d0b677-8489-4af5-9168-b336cb39b3fc)

**Comment by Graninius** [comment]
Have the same issue
The pannel vers. 8.6.11

**Comment by Amir2241** [comment]
سلام 

من هم تقریبا دو هفته هست که همین مشکل رو دارم و نمیتونم آپدیت کنم 

ubuntu 22.04
Panel V. 8.6.11

**Comment by mrvcoder** [comment]
Same

**Comment by alirezarah** [comment]
منم همین مشکل رو دارم یعنی برای آپدیت باید هر سری سرور رو پاک کنیم دوباره ورژن جدید رو بریزیم

**Comment by pjrobertson** [comment]
I was having the same problem, here's what I did:

1. SSH into the sever and exit the hiddify screen
2. Run the following commands to manually pull the latest update.sh (and relevant) scripts:
```
wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/common/utils.sh -O common/utils.sh
wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/update.sh -O update.sh
chmod +x update.sh
ln -s /opt/hiddify-config /opt/hiddify-manager
3. Run the update with  `sudo bash update.sh`

**Comment by alirezarah** [comment]
> I was having the same problem, here's what I did:
> 
> 1. SSH into the sever and exit the hiddify screen
> 2. Run the following commands to manually pull the latest update.sh (and relevant) scripts:
> 
> ```
> wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/common/utils.sh -O common/utils.sh
> wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/update.sh -O update.sh
> chmod +x update.sh
> ln -s /opt/hiddify-config /opt/hiddify-manager
> ```
> 
> 3. Run the update with  `sudo bash update.sh` - to get the latest files from the server
> 4. I had to then run `sudo bash update.sh` one more time to actually perform the update

I used these instructions of yours, the services do not come up anymore

**Comment by alirezarah** [comment]
> I was having the same problem, here's what I did:
> 
> 1. SSH into the sever and exit the hiddify screen
> 2. Run the following commands to manually pull the latest update.sh (and relevant) scripts:
> 
> ```
> wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/common/utils.sh -O common/utils.sh
> wget https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/update.sh -O update.sh
> chmod +x update.sh
> ln -s /opt/hiddify-config /opt/hiddify-manager
> ```
> 
> 3. Run the update with  `sudo bash update.sh` - to get the latest files from the server
> 4. I had to then run `sudo bash update.sh` one more time to actually perform the update

I had to delete the server and reinstall it

**Comment by Graninius** [comment]
After today's update got this message:
```
e3q8
Oops! something went wrong.

(pymysql.err.OperationalError) (1054, "Unknown column 'user.lang' in 'field list'") [SQL: SELECT user.id AS user_id, user.uuid AS user_uuid, user.name AS user_name, user.last_online AS user_last_online, user.expiry_time AS user_expiry_time, user.usage_limit AS user_usage_limit, user.package_days AS user_package_days, user.mode AS user_mode, user.monthly AS user_monthly, user.start_date AS user_start_date, user.current_usage AS user_current_usage, user.last_reset_time AS user_last_reset_time, user.comment AS user_comment, user.telegram_id AS user_telegram_id, user.added_by AS user_added_by, user.max_ips AS user_max_ips, user.enable AS user_enable, user.lang AS user_lang, user.ed25519_private_key AS user_ed25519_private_key, user.ed25519_public_key AS user_ed25519_public_key FROM user] (Background on this error at: https://sqlalche.me/e/14/e3q8)
```
After using solution from above got 
**Can't connect the server**

**Comment by h-behgam** [comment]
for solving this bug
first connect to ssh 
after that restart services from hiddify panel
then select update

**Comment by alirezarah** [comment]
> for solving this bug first connect to ssh after that restart services from hiddify panel then select update

Hello, please write the instructions
Does this solve the update problem?

**Comment by h-behgam** [comment]
> > for solving this bug first connect to ssh after that restart services from hiddify panel then select update
> 
> Hello, please write the instructions Does this solve the update problem?

first connect to ssh with putty
then hiddify menu appearance
in menu choose restart services item 
then select update item 
just it 
Enjoy the new version

**Comment by alirezarah** [comment]
> > > for solving this bug first connect to ssh after that restart services from hiddify panel then select update
> > 
> > 
> > Hello, please write the instructions Does this solve the update problem?
> 
> first connect to ssh with putty then hiddify menu appearance in menu choose restart services item wait for restarting then select update item just it Enjoy the new version

This is the same as the previous version
Could not update to the new version of the panel

**Comment by lymanjre** [comment]
pls update to the latest version. should be solved

**Comment by mrvcoder** [comment]
how to update , when the update script in old versions has issue??
