### ISSUE TITLE
مشکل اتصال بات تلگرام در ورژن 9.0.0 dev21

### ISSUE THREAD

**Issue by Bahmei** [hiddify/Hiddify-Manager#3367]
داخل ورژن 9.0.0dev21 زمانی که توکن بات تلگرام رو به پنل میدم بعد به یوزها متصلش میکنم داخل بات تلگرام فقط کلمه استارت نمایش داده میشه و یوزر و حجم و تاریخ نمایش داده نمیشه. این مشکل داخل ورژن قبلی نبود ولی داخل این ورژن اتفاق افتاده.

**Comment by amirsaam** [comment]
پیام هم کلا ارسال نمی‌کنه گویا

**Comment by Bahmei** [comment]
اره درسته پیام هم برای کاربرا ارسال نمیکنه

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
