### ISSUE TITLE
قطع ارتباط در اول اتصال در برنامه Hiddifynext

### ISSUE THREAD

**Issue by Bahmei** [hiddify/Hiddify-Manager#3368]
در بیشتر مواقع زمانی که برنامه رو برای اولین بار باز میکنیم بعد از اولین اتصال پینگ کانکشنها رو نشون میده ولی بعد از چند ثانیه ارتباط قطع و عدد پینگ نیز دیگه نشون داده نمیشه و باید ارتباط رو قطع و دوباره متصل شد تا این مشکل رفع بشه.
در برخی مواقع هم برنامه در اولین اتصال کرش میکنه و از برنامه خارج میشه، این مشکل در زمان اتصال با آیکونی که در نوتیفیکشن بار گوشی هست بشتر هم هست.

**Comment by AmirhosseinBrooklyn** [comment]
وقت بخیر، این مورد لطفاً در ریپازیتوری HiddifyNext ایشو کنید تا بهتر رسیدگی و بررسی بشه.
موفق باشید🌿

> https://github.com/hiddify/hiddify-next/issues

**Comment by lymanjre** [comment]
این ایشو مرتبط با اینجا نیست

**Comment by Ahmadmsv** [comment]
> وقت بخیر، این مورد لطفاً در ریپازیتوری HiddifyNext ایشو کنید تا بهتر رسیدگی و بررسی بشه.
> موفق باشید🌿
> 
> > https://github.com/hiddify/hiddify-next/issues
