### ISSUE TITLE
No module named hiddifypanel

### ISSUE THREAD

**Issue by zxfreedomza13** [hiddify/Hiddify-Manager#3372]
**Describe the bug**
Installing on Ubuntu 22.04 VPS server by AWS Tokyo Zone
After copying the link from the webpage, paste into the SSH console. The system install perfectly find until it says "No module named hiddifypanel" and then asked to press q to terminate.

**Comment by SajadC00p3R** [comment]
i have same issue in ubuntu 20.4
```

  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.3.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 21.3.1; however, version 23.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Created symlink /etc/systemd/system/multi-user.target.wants/hiddify-panel.service → /opt/hiddify-config/hiddify-panel/hiddify-panel.service.
bash: hiddifypanel: command not found
```

**Comment by pjrobertson** [comment]
Seems like there have been a lot of issues with updates lately. You could try following the steps here which fixed it for me:

https://github.com/hiddify/Hiddify-Manager/issues/3362#issuecomment-1805151449

**Comment by lymanjre** [comment]
pls update to the latest version and see if it exits or not. should be solved
