### ISSUE TITLE
نمایش آیکون اشتباه برای دونیت در پنل هیدیفای

### ISSUE THREAD

**Issue by HiddifyOfficial** [hiddify/Hiddify-Manager#3376]
**Describe the bug**
نمایش آیکون اشتباه برای دونیت در پنل هیدیفای - ورژن دولوپر آخرین ورژن

**Screenshots**

![Image](https://github.com/hiddify/Hiddify-Manager/assets/129010482/421a8cbe-7d6b-41f2-a804-a53ae0b158f6)

**Desktop (please complete the following information):**
 ویندوز 10
کروم آخرین ورژن

**Comment by lymanjre** [comment]
fixed
