### ISSUE TITLE
double base64 encryption in vmess link

### ISSUE THREAD

**Issue by ytpk** [hiddify/Hiddify-Manager#3380]
**Describe the bug**
the panel outputs vmess://link in double base64 encryption, in subscription and in direct copying

**To Reproduce**
1. copy vmess ws direct (any, tls, http, grpc)
2. understand that this is not a feature but a bug.
3. it's sad to sit waiting for a fix.

**Expected behavior**
the panel provides vmess links to connect in double encryption mode, which does not work in any application.

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/88273873/977ba430-5cda-4505-9b48-8109429caa1f) decode 1 step
![image](https://github.com/hiddify/Hiddify-Manager/assets/88273873/7bf1f25b-726b-4ec6-af70-4b4f025f837d) decode 2 step

.

**Comment by lymanjre** [comment]
This issue is transformed to the project to be debugged and I close it here  for now.
