### ISSUE TITLE
غیب شدن قسمت Telegram Proxy در صفحه هیدیفای

### ISSUE THREAD

**Issue by loghmanazari** [hiddify/Hiddify-Manager#3382]
با سلام
وقتی یه دامنه ای حالتش رو روی Only for Subscription Link میذاری قسمت تلگرام پروکسی در صفحه ی هیدیفای محو میشه لطفا این مورد رو رفع کنید

**Comment by lymanjre** [comment]
خب این مورد درست هست دیگه. لینک ساب برای ایجاد سالسکریپشن استفاده میشه. باید دامنه دایرکت استفاده کنید
