### ISSUE TITLE
 اضافه شدن ستون زمان ایجاد کاربر و تعداد نفرات متصل به یک کانفیگ

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/Hiddify-Manager#3384]
ستونی در پنل اضافه کنید که نشون بده کاربر در چه تاریخی ایجاد شده
و ستونی هم اضافه کنید که تعداد نفراتی که به یک اکانت متصل شده هستن رو نشون بده این خیلیمهمه و میتونه خوب باشه

**Comment by Farazzzssss** [comment]
اره تعداد کاربرای متصل به یک کانفیگو نشون بده عالی میشه

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
