### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/Hiddify-Manager#3385]
خواهشا یه تغییر و تحولی در ظاهر کاربری بدین خیلی ایرادات داره 
مثلا متون در ستون ها وسط چین نیست 
قالب در هر زمانی اتومات میره رو حالت دارک مود 
ظاهر بخش تنظیمات

**Comment by lymanjre** [comment]
در آپدیت های بعدی تغییرات زیادی خواهد داشت
