### ISSUE TITLE
مشکل در قطعی و کار نکردن ربات 

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/Hiddify-Manager#3386]
سلام خسته نباشید 
قطعی ارتبط در نسخه دولوپ وجود داره مثلا زمانی که هیستریا و تویک رو اضافه میکنی کانکشن در اپلیکیشن هیدیفای هر وقت سویچ میکنه روی یکی از این ۲ سری اتصال قطع میشه و چون همیشه پینگ پایین تری نشون میدن قطعی ها مکرر میشه و از نسخه 7.2 به بعد ریالیتی هم دچار قطعی های گاه و بی گاه میشه 

مورد بعدی اسامی هیستریا و توییک در اپ هیدیفای نکست بعد ۲۴ ساعت یهو به uuid 000000  تغییر میکنه

**Comment by lymanjre** [comment]
لطفا آپدیت کنید به آخرین ورژن مشکل باید حل شده باشه. اگر مشکل وجود داشت ایشو را باز کنید. ممنون
