### ISSUE TITLE
gfw_resist_HTTPS_proxy لطفا این ویژکی رو اضافه کنید

### ISSUE THREAD

**Issue by HassanMohammadi** [hiddify/Hiddify-Manager#3387]
یک پیشنهاد 
من از اسکریپت زیر وقتی استفاده میکنم مکمل هست مشکل قطعی ها به کل رفع میشه که یکی از دوستان در گیت هاب انتشار داده لینکش 
https://github.com/GFW-knocker/gfw_resist_HTTPS_proxy
شما هم میتونید قابلیت تقسیم پکت و تاخیر رو به هیدیفای اضافه کنید ؟ خیلی کاربردیه مشکلات قطعی به کل رفع میشه بنظرم

**Comment by lymanjre** [comment]
جهت بررسی به پروژه منتقل میشه و ایشو اینجا بسته میشه
