### ISSUE TITLE
دکمه ریست زمانی و حجمی تمام کاربران

### ISSUE THREAD

**Issue by hamedheidari** [hiddify/Hiddify-Manager#3388]
سلام و خسته نباشید به همه‌ی دوپلرهای عزیز هیدیفای

لطفاً دکمه ریست زمانی و حجمی تمام کاربران رو به پنل اضافه کنید.

این قابلیت خیلی می‌تونه کمک‌کننده باشه اگه بخوایم همه کاربرا همزمان بطور منظم ریست بشن.

**Comment by amin2plus** [comment]
+1

**Comment by lymanjre** [comment]
سلام. به بخش پروژه جهت بررسی منتقل میشه. ایشو در اینجا بسته میشود
