### ISSUE TITLE
Can‘t install hiddify-manager

### ISSUE THREAD

**Issue by hpqqph** [hiddify/Hiddify-Manager#3395]
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
bash: hiddifypanel: command not found
 * Reloading configuration files for periodic command scheduler cron
   ...done.
/usr/local/bin/yt-dlp
XXX
5

Reading Configs from Panel...
XXX
/usr/bin/python3: No module named hiddifypanel
Exception in Hiddify Panel. Please send the log to hiddify@gmail.com

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
