### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by harnid** [hiddify/Hiddify-Manager#3397]
hi I updated to develop version and have a problem
hiddify ssh library stays on activating and I cant use new protocols
 I have this error:

===run.sh common
adding rule INPUT -p udp --dport  -j ACCEPT
iptables v1.8.7 (legacy): Port "-j" does not resolve to anything.

Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p udp --dport  -j ACCEPT
ip6tables v1.8.7 (nf_tables): Port "-j" does not resolve to anything.

Try `ip6tables -h' or 'ip6tables --help' for more information.
adding rule INPUT -p udp -m udp --dport  -m conntrack --ctstate NEW -j ACCEPT
iptables v1.8.7 (legacy): Port "-m" does not resolve to anything.

Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p udp -m udp --dport  -m conntrack --ctstate NEW -j ACCEPT
ip6tables v1.8.7 (nf_tables): Port "-m" does not resolve to anything.

Try `ip6tables -h' or 'ip6tables --help' for more information.
Service is running on port 22 and path sshd:
grep
Service not found or not running
adding rule INPUT -p tcp --dport  -j ACCEPT
iptables v1.8.7 (legacy): invalid port/service `-j' specified
Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p tcp --dport  -j ACCEPT
ip6tables v1.8.7 (nf_tables): invalid port/service `-j' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
adding rule INPUT -p tcp -m tcp --dport  -m conntrack --ctstate NEW -j ACCEPT
iptables v1.8.7 (legacy): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p tcp -m tcp --dport  -m conntrack --ctstate NEW -j ACCEPT
ip6tables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
adding rule INPUT -p tcp --dport  -j ACCEPT
iptables v1.8.7 (legacy): invalid port/service `-j' specified
Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p tcp --dport  -j ACCEPT
ip6tables v1.8.7 (nf_tables): invalid port/service `-j' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
adding rule INPUT -p tcp -m tcp --dport  -m conntrack --ctstate NEW -j ACCEPT
iptables v1.8.7 (legacy): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
adding rule INPUT -p tcp -m tcp --dport  -m conntrack --ctstate NEW -j ACCEPT
ip6tables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
 * Reloading configuration files for periodic command scheduler cron
   ...done.

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
