### ISSUE TITLE
چند سرور از لوکیشن های مختلف

### ISSUE THREAD

**Issue by thejianyu** [hiddify/Hiddify-Manager#3400]
درود و خسته نباشید خدمت دولوپرهای پشت هایدیفای عزیز
میخواستم بدونم راهی هست که بشه چندین سرور از لوکیشن های مختلف رو توی کانفیگ قرار داد؟ مثلا یکی امریکا، یکی فنلاند؟

**Comment by AkramiPro** [comment]
این حالت که یک سرور مرکزی باشه و همه سرور ها رو اونجا کانفیگ کنیم اگر میشه اضافه کنید

**Comment by TiamaaShah** [comment]
این اگه اضافه بشه که عالی میشه

**Comment by lymanjre** [comment]
فعلا متنظر بمانید در نسخه های آتی اضافه خواهد شد
