### ISSUE TITLE
نمایش ندادن نام کاربری

### ISSUE THREAD

**Issue by MHP370** [hiddify/Hiddify-Manager#3402]
سلام 
برای من نام کاربری رو نشون نمیده
 باید چکار کنم ؟

**Comment by miladshaham** [comment]
آیفون هستید؟؟

**Comment by Farazzzssss** [comment]
منم یه تعداد از کاربرارو نشون نمیده کلا قطعم نمیشن اونا

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
