### ISSUE TITLE
محدودیت تعداد دیوایس های آنلاین

### ISSUE THREAD

**Issue by thejianyu** [hiddify/Hiddify-Manager#3404]
لطفا یه قابلیت اضافه کنید که بشه برای حداکثر تعداد دیوایس های آنلاین محدودیت گذاشت.
پنل زیر که داره توی چین فعالیت میکنه (از کلش استفاده میکنن) چنین قابلیتی داره:
https://bit.ly/3QW2gcc

**Comment by vadash** [comment]
This one too https://github.com/MHSanaei/3x-ui

**Comment by lymanjre** [comment]
قبلا ایشو شده و در دست بررسی است
