### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Gray1372** [hiddify/Hiddify-Manager#3405]
# Bug/Feature:
**Description**:     اگر یوزری منقضی شده باشد هم حجمی هم تاریخی وقتی زمانش ریست می کنید  دکمه ریست کردن حجم هم از کار می افتد 

## Details:
**Hiddify Version**: 11-12T20:50
**Python Version**:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
**OS**:              Linux-5.15.0-46-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by miladshaham** [comment]
سلام وقت بخیر، بنده تست کردم و صحیح هستش فرمایشتون البته زمان اتمام حجم و روز طبیعتا هر دو رو باید فعال کنید و روشن کردن یکیشون فقط منطقی نیست، به هر حال تا فیکس شدن باگ میتونید روز رو افزایش بدید یا حجم رو دوبرابر کنید تا یک ماه با حجم مشخص زیاد شه.
باگ رو بنده به ایمیل تیم ارسال میکنم تا بررسی کنند.

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
