### ISSUE TITLE
Found a Critical severity vulnerability in web application.

### ISSUE THREAD

**Issue by khetarammali9521** [hiddify/Hiddify-Manager#3407]
Hey there,
 
I want to report A Critical Security Vulnerabilities in your web application, Could you please guide me where I can report such issues?

Do you have any Bug Bounty Program ??

Thanks & Regards
Khetaram Mali

**Comment by MichaelUray** [comment]
Please report it to hiddify@gmail.com
I also found vulnerability issue and they fixed it within one day after I have sent it to this e-mail address.

**Comment by miladshaham** [comment]
contact hiddify@gmail.com asap you can.
there is no need to  bounty with such open source program imao

**Comment by khetarammali9521** [comment]
thanks for the response.
