### ISSUE TITLE
allowInsecure 

### ISSUE THREAD

**Issue by loghmanazari** [hiddify/Hiddify-Manager#3408]
در روش fake tls 
گزینه allowInsecure.  برای تعدادی از کانفیگ ها غیرفعال است و‌باید دستی فعال باشه
در کانفیگ های زیر این‌مشکل هست
Vmess tcp h2 tls

all trojans
لطفا این باگ را رفع کنید

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
