### ISSUE TITLE
Telegram (feature request): Notify users via Telegram if they have almost reached their time or data limits

### ISSUE THREAD

**Issue by MichaelUray** [hiddify/Hiddify-Manager#3411]
Right now users often do not recognize why their VPN stopped and they might think it failed.
It would be good if there would be an option to automatically send out a warning message via Telegram to a user if they are getting close to their limits.

e.g. 
3 days (configurable) before the subscription ends, you get a warning on Telegram that your VPN will stop in 3 days if you don't renew it.
If you have reached 90% (configurable) of your data volume, then you get a warning via Telegram.
Maybe also include the link to their user page in this message.

**Comment by miladshaham** [comment]
Yes, It will be great.
But take that in mind, the team trying there best to bypass all limits of countries with high censorship.
But it will be nice imo to have this future in the Telegram Bot

**Comment by lymanjre** [comment]
This issue is transformed to the project and will be closed here for now
