### ISSUE TITLE
Telegram (bug): Agents can send messages to all users on server

### ISSUE THREAD

**Issue by MichaelUray** [hiddify/Hiddify-Manager#3414]
If your are logged in as an agent, then you can access the "Send Message to User's Telegram" on the top.
I excpected that all the messages there are sent out just to the users of the agent, but it broadcasts it to all users on the server.
Agents should only be able to send out Telegram messages to their own users, but not to all on the server.

**Comment by lymanjre** [comment]
This issue is transformed to the project and will be closed here for now
