### ISSUE TITLE
Telegram (feature request): Send messages only to users marked by check boxes

### ISSUE THREAD

**Issue by MichaelUray** [hiddify/Hiddify-Manager#3415]
It would be helpfull to add a button `"Selected Users from List"` in the Telegram menu where you can send message to users which are checked in the list below:

![2023-11-18_11-34-56_Admin_Hiddify_Panel_–_Mozilla_Firefox](https://github.com/hiddify/Hiddify-Manager/assets/25169478/e2e4d16a-b46b-4558-bc9e-6d87c5a6b38f)

**Comment by lymanjre** [comment]
This issue is transformed to the project and will be closed here for now
