### ISSUE TITLE
DO NOT touch the systemd-resolved service!

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Manager#3418]
احساس می کنم به علت دستکاری در سرویس DNS ابونتو و تغییر اون، این اسکریپت باعث مشکلات بسیار زیادی شده. از جمله نمی تونم خودم دستی سرویس DNS رو کنترل، فلاش یا ... کنم و همچنین استفاده از اسکریپت هایی مثل dnsmasq و stubby و ctrl-d باعث اختلال شدید میشه.
از طرفی به خاطر همین همپوشانی و اختلال اسکریپت ها روی همدیگه (که در هر بار استارت آپ سیستم عامل توسط هیدیفای دوباره اتفاق می افته) پورت 53 و resolver روی سرور به کنترل مهاجمین در اومده که خطرات امنیتی رو به دنبال داره و آی پی سرور من رو وارد بلاک لیست کرده!

لطفا امکان کنترل این قضیه رو فورا و جدا اضافه کنید که کاربرانی که میخوان خودشون وضعیت تحلیل کننده رو به عهده داشته باشن، دچار مشکل نشن.

لازم به ذکره این مشکل روی نسخه 7 وجود نداشت و از زمان ارتقا به نسخه 8 این مشکل پیش آمده.

**Comment by vadash** [comment]
Yep it fucked my oracle server too

**Comment by hiddify-com** [comment]
fixed

**Comment by robin98** [comment]
فکر می کنم این مشکل برگشته باشه و به نوعی سیستم من آدرس های 1.1.1.1 و 8.8.8.8 رو هم به عنوان DNS Server می گیره، بعد از چند ساعت هم که سرور آپ شده یهویی 127.0.0.1 رو که من براش معرفی کردم به عنوان resolver نادیده میگیره و درخواست هارو به 1.1.1.1 و 8.8.8.8 هم پاس میده.
لازم به ذکره روی لوکال 127.0.0.1 من یه resolver پرایوت آوردم بالا برای همین میخوام تنها resolver من همین آدرس باشه.
هر کاری کردم که گوگل و کلادفلر رو حذف کنم نشد و فکر می کنم اسکریپت هیدیفای موقع اجرا شدن به یه نحوی این دوتا آدرسو دوباره به سیستم میده
مثلا فایل زیر، هر بار این مقادیر رو میگیره، آیا می تونید تایید کنید که توسط شما دستکاری میشه یا مشکل از پراسس دیگه ای هست؟
`/etc/resolvconf/resolv.conf.d/base`
