### ISSUE TITLE
خطای در زمان نصب

### ISSUE THREAD

**Issue by Sky13944** [hiddify/Hiddify-Manager#3419]
درود در زمان نصب با این خطا مواجه میشو
  note: This error originates from a subprocess,
and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> uwsgi
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
bash: line 1: hiddifypanel: command not found
 * Reloading configuration files for periodic command scheduler cron
   ...done.
Dig failed to resolve yahoo.com! Adding nameserver 8.8.8.8 to /etc/resolv.conf...
XXX
5
Reading Configs from Panel...
XXX
/usr/local/bin/yt-dlp
/usr/bin/python3: No module named hiddifypanel
Exception in Hiddify Panel. Please send the log to hiddify@gmail.com
--: line 461: less: command not found

**Comment by aslekar0** [comment]
apt install uwsgi

**Comment by Sky13944** [comment]
ممنون اما هنوز خطا داره  از خط ۴۶۱ ایراد میگیره
[info] qFKv4I-MNQc: Downloading 1 format(s): 22
[download] Destination: videos/ios-wingx.mp4
[download]   0.0% of    5.13MiB at  567.72KiB/s E[download]   0.1% of    5.13MiB at  887.68KiB/s E[download]   0.1% of    5.13MiB at    1.59MiB/s E[download]   0.3% of    5.13MiB at    2.77MiB/s E[download]   0.6% of    5.13MiB at    2.89MiB/s E[download]   1.2% of    5.13MiB at    1.14MiB/s E[download]   2.4% of    5.13MiB at    1.34MiB/s E[download]   4.9% of    5.13MiB at    1.94MiB/s E[download]   9.7% of    5.13MiB at    2.93MiB/s E[download]  19.5% of    5.13MiB at    4.68MiB/s E[download]  39.0% of    5.13MiB at    7.67MiB/s E[download]  77.9% of    5.13MiB at    9.77MiB/s E[download] 100.0% of    5.13MiB at   11.83MiB/s E[download] 100% of    5.13MiB in 00:00:00 at 6.27MiB/s
--: line 461: less: command not found
Press any key to go  to menu

**Comment by aslekar0** [comment]
log کامل رو بزارید

**Comment by Sky13944** [comment]
لینک فایل لاگ
`https://file.io/akxZKZOgqGkF`

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
