### ISSUE TITLE
مشکل کار نکردن پروکسی ها روی هسته ایکس ری در نسخه بتا

### ISSUE THREAD

**Issue by alirezasamavarchi** [hiddify/Hiddify-Manager#3424]
# Bug:
**Description**:     "روی نسخه بتا وقتی پنل روی هسته ایکس ری باشه برنامه هایی مثل v2rayng که از xray core استفاده میکنن کانفیگ ها تایم اوت میخورن ولی برنامه هایی که هسته singbox دارن مثل nekoray یا هیدیفای نکست کانفیگ رو اجرا میکنن،"

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0

**Comment by lymanjre** [comment]
این ایشو به این ریپو مرتبط نیست
