### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by mohsen136969** [hiddify/Hiddify-Manager#3426]
# Bug:
**Description**:     "Describe your problem"

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
**OS**:              Linux-5.15.0-89-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by mohsen136969** [comment]
سلام
در ورژن بتا چندین مورد هست که خواستم اطلاع دهم
مورد اول در مورد بازگرداندن فایل بکاپ هست .پس از بازگردانی یوزرها به صورت نامرتب و پراکنده وارد برنامه میشوند.یعنی ترتیب انها مثل پنل قبلی نیست.
مورد دوم لطفا برای تغییر پورت هیستریا و توییک همانند ssh باکس مربوطه اگر گذاشته شود خیلی کار را راحتتر میکند
در ضمن با هربار خاموش کردن سرور هسته از کار میفتد و باید مجدد اپلای کرد


با تشکر از زحمات شما و لطفتان

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
