### ISSUE TITLE
قطع شدن پنل و کانفیگ ها بعد از دو سه روز

### ISSUE THREAD

**Issue by smtk69** [hiddify/Hiddify-Manager#3427]
**قطع شدن پنل و کانفیگ ها بعد از دو سه روز**
بعد از دو سه روز پنل و کانفیگ ها قطع میشه و دسترسی ssh هم ندارم و مجبور میشم سرور رو ریبوت کنم تا اوکی بشه

ورژن پنل: 8.7.1
اوبونتو: 22
دیتاسنتر: هتزنر

**Comment by amin2plus** [comment]
ببین این شاید مشکلتو برطرف کنه

https://github.com/hiddify/Hiddify-Manager/issues/3371#issue-1967850553

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
