### ISSUE TITLE
ارسال ایمیل cron  /opt/hiddify-config/hiddify-panel/update_usage.sh

### ISSUE THREAD

**Issue by p19lord** [hiddify/Hiddify-Manager#3429]
سلام
بنده روی سروری که هیدیفای نصب شده ایمیل سرور هم دارم و طبیعتا کاربر root هم یک mail box داره الان مشکلی که دارم اینه که cron جاب update_usage به صورت مکرر ایمیل ارسال میکنه میخواستم ببینم این رو چطوری میتونم متوقفش بکنم؟

From: Cron Daemon <root@example.org>
To: root@example.org
Subject: Cron <root@example> /opt/hiddify-config/hiddify-panel/update_usage.sh
trying to update usage
ERROR! SingboxApi has error in get_enabled users
Xray usage da9d7a16-f587-4dca-8377-bf14fc371306 d=11668654 u=54946 sum=11723600
{<User 2>: {'usage': 11723600, 'ips': ''}, <User 3>: {'usage': 0, 'ips': ''}, <User 4>: {'usage':
0, 'ips': ''}, <User 5>: {'usage': 0, 'ips': ''}, <User 6>: {'usage': 0, 'ips': ''}, <User 7>:
{'usage': 0, 'ips': ''}}
{'status': 'success', 'comments': {'da9d7a16-f587-4dca-8377-bf14fc371306': 0.010918453335762024,
'de447098-f664-49d5-b4ca-cc9fd979862e': 'No usage', 'a0368fba-3f30-4899-ac63-058c6833bc72': 'No
usage', 'c83209a7-6722-4ed2-a1f3-aeb0fb655c69': 'No usage',
'5e2b556a-c696-4976-a499-98f8670f5865': 'No usage', 'ab2d1b45-c48d-4ca5-aef4-6a7b9d353866': 'No
usage'}}
اروری که میده مهم نیست ها فقط ایمیل ارسال نشه

**Comment by lymanjre** [comment]
در جاب های کرون باید متوقفش کنی

**Comment by mahdihk143** [comment]
سلام ببخشید آیا میشه از cdn آسیاتک استفاده کرد و کانفیگ هارو نیم بها کرد؟ من امتحان کردم دامنه ی cdn باز میشد ولی کانفیگ های cdn کار نمیکرد
