### ISSUE TITLE
اتصال به سرور از طریق ubuntu server

### ISSUE THREAD

**Issue by MohMehrnia** [hiddify/Hiddify-Manager#3433]
با سلام
بنده برای نصب برخی نرم افزارها بر روی یک نسخه از ابونتو سرور در ایران نیاز دارم که به سرور پراکسی خودم متصل شوم، این اتصال را چگونه انجام دهم

**Comment by lymanjre** [comment]
با ساخت یک تانل ssh هم میتوانید
