### ISSUE TITLE
کند لود شدن سایتا و گیر کردن کلیپا

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/Hiddify-Manager#3434]
سلام و عرض ادب
من روی اخرین نسخه هیدیفای هستم 8.8.2 لود شدن سایتا توی این نسخه خیلی پایین اومده بعضا گیر ام میکنه
توی شبکه های اجتماعی هم مثل اینستا وسط کلیپا بعضا گیر میکنه
توی نسخه 7.2.0 اصلا اینطور نبود و خیلی روون بود همه چی حتی من برای تست یه سرور روی نسخه 7.2 ران کردم یکی  8.8.2 کاملا این موضوع مشهود هست اگه دسترسی ssh خواستید برای چک کردن به این ای دی داخل تلگرام پیام بدید 
http://t.me/Mohammadxmz

**Comment by meahura** [comment]
اس اس اچ به دلیل محدودیت های که توی اپراتور ها اعمال شده کُند شده..

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
