### ISSUE TITLE
گیر کردن در آپدیت و اعمال تغییرات 

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3437]
با درود
9.0.0.dev26 

موقع آپدیت یا اعمال تغییرات گیر میکنه.
از این جلوتر دیگه نمیره و همه چیز از کار میوفته رو ورژن Betaو Dev
===run.sh other/warp
Failed to disable unit: Unit file hiddify-warp.service does not exist.
2023/12/01 18:51:19 Using config file: wgcf-account.toml
2023/12/01 18:51:19 Get "https://api.cloudflareclient.com/v0a1922/reg/1ffeeb1d-123c-4735-8616-83ab7d2c9bc8": dial tcp: lookup api.cloudflareclient.com on 127.0.0.53:53: server misbehaving
2023/12/01 18:51:19 Using config file: wgcf-account.toml
2023/12/01 18:51:19 no account detected
github.com/ViRb3/wgcf/cmd/update.updateAccount
	github.com/ViRb3/wgcf/cmd/update/update.go:39
github.com/ViRb3/wgcf/cmd/update.glob..func1
	github.com/ViRb3/wgcf/cmd/update/update.go:27
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ViRb3/wgcf/cmd.Execute
	github.com/ViRb3/wgcf/cmd/root.go:37
main.main
	github.com/ViRb3/wgcf/main.go:11
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
mv: cannot stat 'wgcf-account.toml': No such file or directory
2023/12/01 18:51:19 Using config file: wgcf-account.toml
2023/12/01 18:51:19 no account detected
github.com/ViRb3/wgcf/cmd/update.updateAccount
	github.com/ViRb3/wgcf/cmd/update/update.go:39
github.com/ViRb3/wgcf/cmd/update.glob..func1
	github.com/ViRb3/wgcf/cmd/update/update.go:27
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ViRb3/wgcf/cmd.Execute
	github.com/ViRb3/wgcf/cmd/root.go:37
main.main
	github.com/ViRb3/wgcf/main.go:11
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
2023/12/01 18:51:19 Using config file: wgcf-account.toml
2023/12/01 18:51:19 no account detected
github.com/ViRb3/wgcf/cmd/generate.generateProfile
	github.com/ViRb3/wgcf/cmd/generate/generate.go:36
github.com/ViRb3/wgcf/cmd/generate.glob..func1
	github.com/ViRb3/wgcf/cmd/generate/generate.go:24
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ViRb3/wgcf/cmd.Execute
	github.com/ViRb3/wgcf/cmd/root.go:37
main.main
	github.com/ViRb3/wgcf/main.go:11
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650

**Comment by iampouria** [comment]
منم به این مشکل بر خوردم
روی ubuntu 22
8.6=>8.8

**Comment by Farazzzssss** [comment]
منم این مشکلرو دارم فقط ربیلد کردم بکاپ زدم که اونم یکسری از کاربرارو نشون نمیده و آپدیتم نشد رو همون 8.6.1 موند

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
