### ISSUE TITLE
doh bug

### ISSUE THREAD

**Issue by newwebform** [hiddify/Hiddify-Manager#3444]
یه یک ماهی پیش من گفتم doh دیگه کار نمیکنه. ولی همچمنان مشکل وجود داره.

**Comment by newwebform** [comment]
بعد از کلی گشتن فایلاها مشکلا پیدا کردم.
 کانفیک nginx مشکل داره و پارامتر و پس را به doh گوگل ارسال نمیکنه.

با ویرایس فایل common.conf توی پوشه part nginx به شکل زیر مشکل حل میشه.
`if ($request_uri ~* "([^/]*$)" ) {
  set  $last_path_component  $1;
}
  set $upstream https://dns.google/; 
  proxy_pass $upstream$last_path_component;`

بعد با سایت https://dohjs.org میشه چک کرد که مشل حل شده.

فقط یه مورد امکان داره تو نسخه های بعد dns خود پنل هم به شکل dot یا doh کنید .
و میتونید یه راهنمایی کنید به من میخوام یه سرویس دیگه مثل تورنت تو سرور راه بندازم برای خودم. با ویرایش فایل common تونستم درستش کنم ولی میخوام یه فاسل جدا تو پوشه conf.d درست کنم که با اپدیت پنل از بین نره. 
میشه کانفیگ اونا بگید .
`location /xxx/qbit/ {
  proxy_set_header Referer "";
  proxy_set_header Origin "";
  proxy_pass          http://localhost:8080/;
}`

**Comment by newwebform** [comment]
اگه تو نسخه های بعد مدول njs nginx را هم  به nginx اضافه کتید اون خودش پردازش dns doh dot داره

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
