### ISSUE TITLE
Hiddify has connected bug all networks can't be connected ?

### ISSUE THREAD

**Issue by shyding** [hiddify/Hiddify-Manager#3447]
**Describe the bug**

**To Reproduce**
1. Go to 'just download Hiddify'
2. Click on 'import config '
3. Scroll down to 'connected'

**Expected behavior**

every things seems be ok ,but can't connecte network  in win11 .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11 ]
 - Browser [chrome ]
 - Version [Hiddify  v6.23]

**Additional context**

**Comment by lymanjre** [comment]
It seems this issue is not related to this repo
