### ISSUE TITLE
پروکسی امکان اضافه شدن در لیست را ندارد

### ISSUE THREAD

**Issue by asna220** [hiddify/Hiddify-Manager#3448]
سلام‌ 
در قسمت تنظیمات پروکسی  وقتی ویرایش را می زنیم به عنوان مثال http tcp vlessرا enable می کنیم به لیست اصلی اضافه نمی شود.
ورژن ۸.۸.۲
![Screenshot_20231204-095028_Chrome](https://github.com/hiddify/Hiddify-Manager/assets/120309510/57bddb69-4382-4d67-a9e4-d634004388df)

**Comment by meahura** [comment]
سیو کن، اعمال تغییرات بزن. درست میشه به احتمال زیاد.

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
