### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by zhoumails** [hiddify/Hiddify-Manager#3454]
# Internal Error Stacktrace:
**Error Message**:   [Errno 2] No such file or directory: '/opt/hiddify-manager//log/system/restart.log'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 75, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Actions.py", line 34, in reverselog
    with open(f'{config_dir}/log/system/{logfile}') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hiddify-manager//log/system/restart.log'

```

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-46-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
