### ISSUE TITLE
بهبود ساب

### ISSUE THREAD

**Issue by DrAmirB** [hiddify/Hiddify-Manager#3460]
سلام وقت بخیر
بنظرم یه چیز که تو پنل جاش خالیه
توانایی جدا کردن ws grpc tcp در لینک سابهای مختلفه
یعنی بشه برا یه لینک ساب reality grpc تعریف کرد و برای لینکی دیگه reality tcp
در واقع هنگام لینک ساب تعیین کنیم چ کانفیگهایی قرار داد داخلش نه اینکه چه دامنه هایی
اگه تو اپدیتای بعد اینو بتونین لحاظ کنین خیلی خوب میشه
با تشکر🙏

**Comment by lymanjre** [comment]
الانم روی ریلیتی میتونید دامنه های ریلیتی مختلف را وصل کنید به یک سال خاص
