### ISSUE TITLE
Adding VPN profile from subscription link in dev version doesn't works

### ISSUE THREAD

**Issue by lznycx** [hiddify/Hiddify-Manager#3462]
# Bug/Feature:
**Description**:     
Adding VPN profile to HiddifyNext and other apps from the subscription link isn't possible in dev version anymore. It shows just "Bad response. The request returned an invalid status code of 500."

## Details:
**Hiddify Version**: X.X.X.devX (the latest dev version at this moment)
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-6.5.0-1009-oem-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
