### ISSUE TITLE
Hiddify completely breaks after rebooting the VPS in latest dev version 

### ISSUE THREAD

**Issue by lznycx** [hiddify/Hiddify-Manager#3464]
# Bug/Feature:
**Description**:     I can't clearly tell what exactly happens, but after rebooting the VPS hiddify panel breaks (it's just completely inaccessible) and all VPN configs are refusing to connect until you SSH into the server and click "Apply Configs" from there
## Details:
**Hiddify Version**: X.X.X.devX (latest dev version at the moment)
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-6.5.0-1009-oem-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
