### ISSUE TITLE
Reality + CDN suggestion

### ISSUE THREAD

**Issue by sohate** [hiddify/Hiddify-Manager#3466]
Hi there! I know that Reality doesn't support CDN. But one guy from Russia gave a solution. I want to know if hiddify can implement it to it's panel? https://habr.com/ru/articles/761798/ - the section Websocket/gRPC вместе с XTLS-Reality. Thanks!

**Comment by sohate** [comment]
@randomguy-on-internet can you please give me a direct link to that docs in wiki?

**Comment by sohate** [comment]
@randomguy-on-internet he said that you can connect to Reality through CDN. Exactly quote: "Обратите внимание: если у вас на сервере настроен XTLS‑Reality, то через Websocket/gRPC подключаться к нему нужно только через CDN!" As I know right now you can't connect to Reality through CDN on Hiddify.

**Comment by sohate** [comment]
@randomguy-on-internet I know how Reality works, but you apparently don't know how Reality works with SNI Proxy. So, I don't see any further discussion no this topic.

**Comment by lymanjre** [comment]
This issue is transformed to the project and will be closed here for now

**Comment by Ategetemen** [comment]
I have a config made by an anonymous person. He was able to use Cloudflare on Reality.
If you check the IP of the domain in the address section, you will see that it is on Cloudflare.
How did he do it?

vless://fdf53f53-5d47-4d3e-9953-6fe9c42c40ac@freakshop6.lmxtinl.com:8443?mode=gun&security=reality&encryption=none&authority=&pbk=jSoxryMWpNraWjG3iS7_5TX-0HGrVgEpc4oPPCKN0EU&fp=chrome&spx=%2F&type=grpc&serviceName=&sni=dash.cloudflare.com&sid=be3fbd36d2637a#%F0%9F%87%A9%F0%9F%87%AA+GRPC+%F0%9F%87%A9%F0%9F%87%AA-%D8%AE%D8%B1%D8%AF%D8%A7%D8%AF%DB%B1%DB%B5-101
