### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by raminsh2001** [hiddify/Hiddify-Manager#3468]
# Bug:
**Description**:     "Describe your problem"

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-89-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

**Comment by raminsh2001** [comment]
درود بر شما و سپاس به خاطر تلاش های شما
در پنل بتا زمانی که تغییری ایجاد میکنیم ارور دامه میده و برای حل این حطا باید دامه shadowtls  و دامنه پروکسی تلگرام را تغییر دهیم و هر دو را یکی انتخاب کنیم تا تغییرات اجرایی شود

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
