### ISSUE TITLE
مشکل وارد کردن کانفیگ به نرم افزار کلاینت

### ISSUE THREAD

**Issue by error1990** [hiddify/Hiddify-Manager#3472]
در موقع نصب برای اولین بار خطا میگیره بعد از نصب دوباره کامل نصب میشه
با اینکه IP تمیزه بدون فیلتر شکن پنل باز نمیشه
وقتی هم میخوایم کانفیگ رو وارد کلاینت کنیم خطا میده فایل پیکربندی با مشکل موجه هستش
لطف میکنید راهنمایی کنید

**Comment by lymanjre** [comment]
سرتیفیکت را بررسی کنید
