### ISSUE TITLE
Please add a feature to monitor network connections

### ISSUE THREAD

**Issue by Morphorxz** [hiddify/Hiddify-Manager#3474]
I'd like to monitor my network connections to determine if a connection is direct or not, or to see their upload/download speeds to make sure everything is working properly.

Exactly what I expect is something like "connections" in Clash for Windows.

![image](https://github.com/hiddify/Hiddify-Manager/assets/52202172/782127e5-4296-430f-ac9b-7551281f88f1)

**Comment by lymanjre** [comment]
Hello. This is not related to this repo. Pls register it in Hiddify Next repo
