### ISSUE TITLE
نمایش ندادن حجم و ترافیک درست در سرور

### ISSUE THREAD

**Issue by MikeeSierrah** [hiddify/Hiddify-Manager#3476]
با سلام خدمت عزیزان هیدیفای

من پنلم نسخه 8.8.2 هست و از سرور هتزنر استفاده میکنم

پنل هر از گاهی دچار باو میشه و نمیتونه ترافیک مشتریا رو درست حساب کنه
یعنی آنلاین رو 0 نشون میده و هیچ ترافیکی ثبت نمیکنه
مجبور میشم تا ری اینستال بزنم تا دوباره مث عادی کار کنه

نصب دوباره پنل از طریق ssh ام امتحان کردم ولی متاسفانه این مشکل حل نشد
چون سرویسامون حجمیه و باید پول ترافیک سرویس ایران بدیم بخاطر این باگ هی داریم ضرر میکنیم

از دوستان هیدیفای خواهشمندم که به سرعت این مشکل رو حل کنن

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
