### ISSUE TITLE
Force Config to Use Following IPs  in CDN domain not working in Release & Beta panel.

### ISSUE THREAD

**Issue by Mfarahani1914** [hiddify/Hiddify-Manager#3479]
# Bug:
**Description**:     "Describe your problem"

## Details:
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-88-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
