### ISSUE TITLE
یک باگ که داره اینکه ادز بلاکر نداره چرا یا هست فعال نمیشه یا اینکه حذف شده از نسخه xui ؟

### ISSUE THREAD

**Issue by imaauser23** [hiddify/Hiddify-Manager#3480]
یک باگ که داره اینکه ادز بلاکر نداره چرا یا هست فعال نمیشه یا اینکه حذف شده از نسخه xui ؟ #3480

**Comment by imaauser23** [comment]
2 این گزینه در اپدیت های دیگ بیاد خیلی خوبه بتونیم از قسمت پنل ادس بلاکر  رو فعال کنیم یا غیر فعال ش کنیم بصورت دستی

**Comment by Farazzzssss** [comment]
بنظرم دی ای اس 1.1.1.2 رو بزاری از پنل بیشترشونو بلاک میکنه.

**Comment by lymanjre** [comment]
این کار باعث اختلال در یوتیوب میشه
