### ISSUE TITLE
چطوری قسمت پنل کاربر رو تغییر داد یا اختصاصیش کرد مثلا برای هر فرد یک ای پی  یا دامنه ریلیتی متفاوتی گذاشت

### ISSUE THREAD

**Issue by imaauser23** [hiddify/Hiddify-Manager#3481]
چطوری قسمت پنل کاربر رو تغییر داد یا اختصاصیش کرد مثلا برای هر فرد یک ای پی cdn یا دامنه ریلیتی متفاوتی گذاشت

**Comment by lymanjre** [comment]
با لینک ساب متفاوت
