### ISSUE TITLE
مشکل بکاپ

### ISSUE THREAD

**Issue by Farazzzssss** [hiddify/Hiddify-Manager#3482]
- Device: [هواوی میت 10 پرو]
 - OS: [ آندروید 10]
 - Browser [گوگل کروم]
 - Version [8.6.10]
 مشکل اینه که بکاپرو به هر حالتی که برمیگردونم یکسری از کاربرارو کلا نشون نمیده ولی وصل هستن و کلا قطع نمیشن انگار زمان و حجمشون نامحدوده...

**Comment by Mohammad1724** [comment]
منم همین مشکل رو دارم نمیدونم باید چکار کنم

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
