### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [hiddify/Hiddify-Manager#3483]
# Internal Error Stacktrace:
**Error Message**:   unsupported format character '?' (0x434) at index 25
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 350, in all_configs
    resp = link_maker.make_v2ray_configs(**c)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 779, in make_v2ray_configs
    name += " "+_(f'📅%(expire_days)s days', expire_days=expire_days)

```

## Details:
**Hiddify Version**: X.X.X.devX
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
