### ISSUE TITLE
تغییر owner اکانت های از قبل تعریف شده

### ISSUE THREAD

**Issue by 1razzaghi** [hiddify/Hiddify-Manager#3487]
سلام دوستان
من یک سری اکانت داشتم حالا یک ادمین جدید تعریف کردم
چطور میتونم یکسری از اکانت های موجود رو ببرم زیر مجموعه اون ادمین جدید؟

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
