### ISSUE TITLE
Ip Limit User

### ISSUE THREAD

**Issue by Parsa-n** [hiddify/Hiddify-Manager#3490]
سلام. داخل پنل هیدیفای چه موقعی تغییرات رو میدین که بشه تعداد محدودیت کاربر اعمال کرد ؟؟

**Comment by danaenayati** [comment]
گفتن هیچ وقت اینکار رو نمیکنن چون برای اهداف بیزینسی این پلتفرم رو نساختن.

**Comment by lymanjre** [comment]
این ایشو قبلا ثبت شده و در دست بررسی است. لطفا شکیبا باشید
