### ISSUE TITLE
علت کار نکردن ریلیتی grpc داخل هیدیفای نکست

### ISSUE THREAD

**Issue by bahrammm1995** [hiddify/Hiddify-Manager#3491]
وقتی جداگانه کانفیگ رو بیاری داخل برنامه کار میکنه ولی وقتی همراه همه ی کانفیگ ها باشه نه علتش رو هم داخل اسکرین شات مشخص کردم
![image](https://github.com/hiddify/Hiddify-Manager/assets/120322620/d9d0de1c-41cd-4294-a0ac-db54c392790c)
![image](https://github.com/hiddify/Hiddify-Manager/assets/120322620/d9902ed1-59dc-45b5-985f-4ce7ee9449e1)
اون قسمت transport کمه نمیاد توی لینکی که همه ی کانفیگ ها رو لود میکنه

یه مورد دیگه ام توی همین قسمت به نظر بهتر نیست برای grpc apln h2 استفاده بشه؟

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
