### ISSUE TITLE
باگ در اتو سی دی ان 

### ISSUE THREAD

**Issue by Gray1372** [hiddify/Hiddify-Manager#3500]
# Bug:
**Description**:     "باگ در اتو سی دی ان "

##ای پی تمیز کلودفلر در بخش اجبار اتو سی دی ان پاک میشه 
**Hiddify Version**: 9.0.0.dev26
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-57-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
