### ISSUE TITLE
بعد از ارتقاع به نسخه دولوپ کلا لینک پنل از کار میفته و دیگه کار نمیکنه ارور ۵۰۰ در مرورگر نمایش میده 

### ISSUE THREAD

**Issue by Gray1372** [hiddify/Hiddify-Manager#3501]
# Internal Error Stacktrace:
**Error Message**:   Error 2 connecting to unix socket: /opt/hiddify-manager/other/redis/run.sock. No such file or directory.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/common.py", line 187, in base_middleware
    hiddify.proxy_path_validator(g.proxy_path)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 240, in proxy_path_validator
    admin_proxy_path = hconfig(ConfigEnum.proxy_path_admin)

```

## Details:
**Hiddify Version**: X.X.X.devX
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-57-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
