### ISSUE TITLE
کارنکردن قسمت Following & followers اینستا

### ISSUE THREAD

**Issue by Parsa-n** [hiddify/Hiddify-Manager#3504]
سلام. از پنل هیدیفای استفاده میکنم و وقتی به کانفیگاش وصل میشم داخل اینستا همه چی خوبه ها فقط قسمت following و followers ارور میده و بالا نمیاد در حالی که یه پنل سنایی دارم و با اون اوکیه و بالا میاد.
تنظیماتش هم دی ان اس 1.1.1.1 رئ برداشتم و به جاش 8.8.8.8 گذاشتم و ای پی v4 هم روشن کردم و تست کردم بازم درست نشد. لطفا کمک کنید

**Comment by AYoonesi** [comment]
این مشکل رو روی بعضی سرورهام داشتم، از وقتی وارپ پلاس رو گذاشتم روی «همه» درست شده؛ شما هم تست کنید شاید درست شد -- حواستون باشه کلید وارپ داشته باشین
✴️ همه : همه سایت های از WARP خارج میشوند
کاش امکان این وجود داشت که یه حالت وارپ بود که بشه لیست سایتایی که می‌خوای برن پشت وارپ رو انتخاب کنی

**Comment by lymanjre** [comment]
آپدیت کنید مشکلی نباید باشه

**Comment by mrmasiha0** [comment]
من هم همین مشکل رو دارم با اینستاگرام. اگر جایی برای گرفتن وارپ خوب سراغ دارید ممنون میشم لینک بگذارید.
