### ISSUE TITLE
failed to verify certificate: x509

### ISSUE THREAD

**Issue by mahsamcse** [hiddify/Hiddify-Manager#3507]
در روش تانل با ها پروکسی و گاست
سمت کلاینت این خطا رو میگیرم
[Error] transport/internet/websocket: failed to dial to damane_relay.com:443 > tls: failed to verify certificate: x509: certificate is valid for damane_admin.com, not damane_relay.com

البته به تازگی این مورد پیش اومده و قبلا به هر دو روش ذکر شده بدون مشکل کار میکردن
با اپلای کانفیگ و نصب مجدد هم حل نشده
پنل 8.8.2
هسته xray
کانفیگ ها 
vless 443 ws tls
trojan 443 ws tls
trojan 443 tcp tls
hetzner ubuntu-22
فایروال فعال
وارپ فعال فقط سایت های ایرانی
منظور از دامنه در توضیحات و عکس همون ساب دامین هست در حقیقت

سرچ کردم اینارو پیدا کردم

این خطا می‌تواند به دلایل مختلفی رخ دهد، از جمله:
خطای پیکربندی: ممکن است گواهینامه SSL/TLS وب‌سرور به درستی نصب یا پیکربندی نشده باشد.
تغییر نام دامنه: ممکن است دامنه وب‌سرور تغییر کرده باشد و گواهینامه SSL/TLS به روز نشده باشد.
حمله MITM: ممکن است یک مهاجم در میانه مسیر ارتباط بین برنامه و وب‌سرور قرار گرفته باشد و گواهینامه جعلی ارائه کند.

توی سایت
https://www.sslchecker.com/sslchecker
وقتی چک میکنم دامنه ریلی رو 

![2024-01-07_10-48-27](https://github.com/hiddify/Hiddify-Manager/assets/114700120/9859e266-f0f1-4d8a-b62e-c9db940de1f8)

ممنون میشم بررسی کنید این مشکل رو

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.

**Comment by zeinali66** [comment]
من این مشکل هم با روش گاست دارم، هم با روش Dokodemo-door.  از اینکه تانل درست کار میکند مطمئن هستم.
آخرین ورژن نصب کردم.
اررور داخل نرم افزار : [Error] transport/internet/websocket: failed to dial to damane_relay.com:443 > tls: failed to verify certificate: x509: certificate is valid for damane_admin.com, not damane_relay.com

داخل سرور هم لاگ acme نگاه کردم، برای ساب دامین تانل نمیتونه سرتیفیکت بگیره.
