### ISSUE TITLE
Singbox client error - cache_file

### ISSUE THREAD

**Issue by infinitaa** [hiddify/Hiddify-Manager#3508]
Hi
In the latest version of the singbox (1.8.0), the core unable to create the service due this error:
Create service: create clash api server: cache_file an related dield in Clash API is deprecated in sing-box 1.8.0, use experimental_cache_file instead.
I'm using 9.0.0.dev26 version.
Thanks
In addition please consider some of application use old version of sing-box and take care of them too. Many thanks

**Comment by lymanjre** [comment]
Pls update to the latest version. The issue should be solved. If it exists pls open this issue.
