### ISSUE TITLE
حذف کاربر با استفاده از api

### ISSUE THREAD

**Issue by rezahajrahimi** [hiddify/Hiddify-Manager#3510]
درود
هنگام حذف کاربر و با استفاده از api، کاربر از لیست کاربران حذف می گردد اما کاربر همچنان می تواند از کانفیگ ها استفاده کند و همچنین می تواند از url که دارد به کانفیگ ها و اطلاعات کاربر دسترسی داشته باشد (خطای 404 ارسال نمی شود).
نسخه مورد استفاده : 8.8.2

**Comment by kianoushqorbani** [comment]
سلام برای من هم همچین مشکلی پیش اومده، من از کانفیگ های Reality استفاده میکنم. مشکل به این صورته که کاربر ها فقط در صورتی که لینک subscription رو توی اپلیکیشن بزنن محدودیت حجم و زمان براشون اعمال میشه. اگه به صورت مستقیم کانفیگ Reality رو از پنل کاربریشون کپی کنن و توی اپلیکیشن بزنن ختی بعد از اتمام حجم و زمان و حتی حذف کاربر از طرف ادمین هم دسترسیشون رو قطع نمیکنه.

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه

**Comment by lymanjre** [comment]
ایشو قبلا ثبت شده
