### ISSUE TITLE
فیلتر شدن  دامنه

### ISSUE THREAD

**Issue by TiamaaShah** [hiddify/Hiddify-Manager#3511]
سلام 
طی چند روز گذشته به طور مداوم  دامنه‌های من فیلتر می‌شود این در صورتیه که من 6 تا ۷ ماه گذشته از همین شیوه با همین نام دامنه ها استفاده می‌کردم و هیچ مشکلی برای من پیش نیامده بود حتی یک دفعه هم نام دامنه‌های من فیلتر نشده بود !
من از سی دی ان‌های کلادفلر با آی پی تمیز استفاده می‌کنم.
می‌خواستم بدونم کسی همچین مشکلی داره و به نظرتون مشکل از کجاست؟

**Comment by kianoushqorbani** [comment]
سلام این مشکل برای من هم پیش اومده و الان کاربرها به لینک پنل خودشون دسترسی ندارن و حجم استفاده شده و زمان اشتراکشون براشون آپدیت نمیشه. با تغییر دامنه هم مشکل دسترسی به پنل کاربرها حل نشد.

**Comment by TiamaaShah** [comment]
> سلام این مشکل برای من هم پیش اومده و الان کاربرها به لینک پنل خودشون دسترسی ندارن و حجم استفاده شده و زمان اشتراکشون براشون آپدیت نمیشه. با تغییر دامنه هم مشکل دسترسی به پنل کاربرها حل نشد.

این مشکلی که شما می‌گین یه مشکل دیگه‌هست این مشکل رو هم من دارم و اینطوریه که کاربرها  بدون وی پی ان به پنلشون دسترسی پیدا نمی‌کنن همچنین لینک‌های سابسکریپشنشون آپدیت نمی‌شه ولی این تاپیکی که من الان گذاشتم اینطوریه که دیگه کاربرا کلاً از وی پی ان شون نمی‌تونن استفاده کنن چون که لینک دامنه‌ای که استفاده می‌کنم به طور کامل فیلتر شده.

**Comment by TiamaaShah** [comment]
البته الان طبق تحقیقاتی که کردم فهمیدم که دولت تمام یو آر ال‌های جدیدی که ثبت می‌شه رو بعد از چند دقیقه ازاستفاده  فیلتر می‌کنه و یو آر ال‌های قدیمی بهتر الان کار می‌کنند ولی پیدا کردن یو آر ال قدیمی خوب غیرممکنه.
 میخواستم بدونم کسی راه چاره بهتری برای این مشکل پیدا کرده؟

**Comment by TiamaaShah** [comment]
> سلام این مشکل برای من هم پیش اومده و الان کاربرها به لینک پنل خودشون دسترسی ندارن و حجم استفاده شده و زمان اشتراکشون براشون آپدیت نمیشه. با تغییر دامنه هم مشکل دسترسی به پنل کاربرها حل نشد.

البته اگه خود شما یا کس دیگه ای راه چاره ای برای این یکی مشکلم پیدا کرده خوشحال میشم بفهمم که چه جوری میشه کاری کرد که لینک‌های سابسکریپشن یوزرها به راحتی آپدیت شه

**Comment by brightening-eyes** [comment]
سلام.
به جای دامنه یه بار با آیپی سرور بزنید ببینید میشه؟
احتمالا نشه که در اون صورت آیپی سرور فیلتر شده (از کلادفلر استفاده کنید) با همون دامنه به صورت cdn و همینطور یه worker هم بسازید و با اون بزنید.
