### ISSUE TITLE
Cloudflare workers

### ISSUE THREAD

**Issue by AliZf1d** [hiddify/Hiddify-Manager#3513]
سلام
ورکرز کلود فلیر هم تا حالا کامل فیلتر کردن؟
چون با فیلتر کردن دامنه ها راه حلی نزاشتن و cdn جی کور هم استفاده کردم برای دامین فرانتینگ ولی خوب خیلی اختلال داره روی نت مخابرات.

**Comment by lymanjre** [comment]
از روشهای فیک یا دایرکت استفاده کنید
