### ISSUE TITLE
از کار افتادن سرویس های  hiddify-haproxy && hiddify-xray

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3514]
با درود و خسته نباشید
سرویس های ddify-haproxy && hiddify-xray در آخرین آپدیت dev & beta از کار افتادن و پنل و پروکسی ها از کار افتادن
![Services](https://github.com/hiddify/Hiddify-Manager/assets/6390536/0712c386-a567-4edf-b929-b4681ef3fc50)
![update](https://github.com/hiddify/Hiddify-Manager/assets/6390536/d3f8c23d-57c9-4e82-ac4f-bf13b33c3bf9)

**Comment by zhoumails** [comment]
the same problem！

**Comment by typerhack** [comment]
Check the steps in this issue it may help. make sure port 443 is open and not used by anythingelse other than hiddify components.

https://github.com/hiddify/Hiddify-Manager/issues/3470

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
