### ISSUE TITLE
لود نشدن کانفیگ ها در ورژن 8.8.8.8

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3515]
با درود
تو ورژن 8.

8.8.8 فقط یک کانفیگ لود میشه 
![proxy](https://github.com/hiddify/Hiddify-Manager/assets/6390536/6483952d-9962-4e16-b356-5557d3002ba5)

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
