### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Manager#3516]
سلام و وقت بخیر
من سرورم رو به اوبنتو 22 آپدیت کردم و وقتی هیدیفای رو نصب میکنم ورژن 8.6.10 نصب میشه و وقتی هم که میخوام به روزرسانی کنم پیغام زیر رو میده : 
Creating a backup ...
XXX
5
Checking for Update...
Hiddify Panel
XXX
{'key': 'package_mode', 'value': 'release'}
hiddify panel version current=8.6.10 latest=latest
XXX
10
Updating...
Hiddify Panel from 8.6.10 to latest
XXX
panel is outdated! updating....
ERROR: Could not find a version that satisfies the requirement hiddifypanel==latest (from versions: 0.0.1, 0.0.2, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.5, 0.8.6, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.17, 0.9.18, 0.9.19, 0.9.20, 0.9.21, 0.9.22, 0.9.24, 0.9.25, 0.9.26, 0.9.27, 0.9.28, 0.9.29, 0.9.30, 0.9.31, 0.9.33, 0.9.34, 0.9.35, 0.9.37, 0.9.38, 0.9.39, 0.9.40, 0.9.41, 0.9.42, 0.9.43, 0.9.44, 0.9.45, 0.9.46, 0.9.47, 0.9.49, 0.9.50, 0.9.51, 0.9.52, 0.9.53, 0.9.54, 0.9.55, 0.9.56, 0.9.57, 0.9.58, 0.9.59, 0.9.60, 0.9.61, 0.9.62, 0.9.63, 0.9.64, 0.9.65, 0.9.66, 0.9.70, 0.9.71, 0.9.72, 0.9.73, 0.9.74, 0.9.75, 0.9.76, 0.9.77, 0.9.78, 0.9.79, 0.9.80, 0.9.81, 0.9.82, 0.9.83, 0.9.84, 0.9.85, 0.9.86, 0.9.87, 0.9.88, 0.9.89, 0.9.90, 0.9.91, 0.9.92, 0.9.93, 0.9.94, 0.9.95, 0.9.96, 0.9.98, 0.9.99, 0.9.100, 0.9.101, 0.9.103, 0.9.104, 0.9.105, 0.9.106, 0.9.107, 0.9.108, 0.9.110, 0.9.111, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.2, 1.5.3, 1.6.0, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 2.9.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.9, 3.1.10, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.1.0, 4.1.1, 4.1.2, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.7, 4.2.8, 4.2.9, 4.3.0, 4.3.1, 4.5.0, 4.5.1, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 6.0.0, 6.0.1, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.5, 6.1.6, 6.1.7, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.4.1, 6.4.2, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.0.6, 7.0.7, 7.0.8, 7.0.9, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 7.1.9, 7.2.0, 8.0.0.dev56, 8.0.0.dev57, 8.0.0.dev58, 8.0.0.dev59, 8.0.0.dev60, 8.0.0.dev61, 8.0.0.dev62, 8.0.0.dev64, 8.0.0.dev65, 8.0.0.dev66, 8.0.0.dev67, 8.0.0.dev68, 8.0.0.dev69, 8.0.0.dev70, 8.0.0.dev71, 8.0.0.dev72, 8.0.0.dev73, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5.dev1, 8.1.5.dev2, 8.1.5.dev3, 8.1.5.dev5, 8.1.6, 8.1.7, 8.1.8, 8.1.9, 8.1.10.dev0, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.3.0.dev0, 8.3.0.dev1, 8.3.0.dev2, 8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.5, 8.3.6, 8.3.7, 8.3.8, 8.3.9, 8.4.0, 8.4.1, 8.4.2, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.6.0, 8.6.1, 8.6.2, 8.6.3, 8.6.4, 8.6.6, 8.6.7, 8.6.8, 8.6.9, 8.6.10, 8.6.11, 8.7.1, 8.8.0, 8.8.1, 8.8.2, 8.8.3, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 9.0.0.dev0, 9.0.0.dev1, 9.0.0.dev2, 9.0.0.dev3, 9.0.0.dev4, 9.0.0.dev5, 9.0.0.dev6, 9.0.0.dev7, 9.0.0.dev8, 9.0.0.dev9, 9.0.0.dev10, 9.0.0.dev11, 9.0.0.dev12, 9.0.0.dev13, 9.0.0.dev14, 9.0.0.dev15, 9.0.0.dev16, 9.0.0.dev17, 9.0.0.dev18, 9.0.0.dev19, 9.0.0.dev20, 9.0.0.dev21, 9.0.0.dev22, 9.0.0.dev23, 9.0.0.dev24, 9.0.0.dev25, 9.0.0.dev26, 9.0.0.dev30, 9.0.0.dev31, 9.0.0.dev32, 9.0.0.dev33, 9.0.0.dev34, 9.0.0.dev35, 9.0.0.dev36, 9.0.0.dev37, 9.0.0.dev38, 9.0.0.dev39, 9.0.0.dev40, 9.0.0.dev41, 9.0.0.dev42, 9.0.0.dev43, 9.0.0.dev44)
ERROR: No matching distribution found for hiddifypanel==latest
XXX
50
Updated...
Hiddify Panel to latest
XXX
XXX
55
Checking for Update...
Hiddify Config
XXX
RELEASE: Current Config Version=10.5.50 -- Latest=10.5.50
---------------------Finished!------------------------

**Comment by lymanjre** [comment]
لطفا آخرین آپدیت را امتحان کنید. مشکل حل شده
