### ISSUE TITLE
خطای ۵۲۰ قسمت دامنه ها

### ISSUE THREAD

**Issue by amirpaul** [hiddify/Hiddify-Manager#3520]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amirpaul** [comment]
دوستان وقتی میرم توی تنظیمات قسمت دامنه ها خطای ۵۲۰ برام میاد کسی میدون مشکل چیه؟

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
