### ISSUE TITLE
لود نشدن کانفیگ ها در اپلیکشین هیدفای نکست ورژن 013.6 ورژن پنل 8.8.9

### ISSUE THREAD

**Issue by ClassicDarkPack** [hiddify/Hiddify-Manager#3521]
![Screenshot_2024-01-13-16-22-16-178_app hiddify com](https://github.com/hiddify/Hiddify-Manager/assets/123335722/7cfc6654-e35a-46c8-a38a-100b78d31c56)
لینک اتوماتیک کانفیگ هاش لود نمیشه نسخه هیدفای نکست هم آخرین نسخه هست

**Comment by zarvan9** [comment]
منم این مشکل رو دارم
ابونتو 22 
با rebuild سرور هم مشکل رفع نشد
