### ISSUE TITLE
ERROR!!!! There is an error in the installation of python panel. Exit....

### ISSUE THREAD

**Issue by GoldenOne1** [hiddify/Hiddify-Manager#3522]
این باگ چندین ماهه بارها گزارش شده
کی بررسی میشه پس؟
ERROR!!!! There is an error in the installation of python panel. Exit....

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
