### ISSUE TITLE
لینک ورود 

### ISSUE THREAD

**Issue by alendark1361** [hiddify/Hiddify-Manager#3527]
سلام در پایین نصب لینک ورود داده نمیشه

**Comment by alendark1361** [comment]
این اخر نصب هست
[download] 100% of    8.09MiB in 00:00:00 at 9.84MiB/s
[youtube] Extracting URL: https://youtu.be/01m7w-I4JXE
[youtube] 01m7w-I4JXE: Downloading webpage
[youtube] 01m7w-I4JXE: Downloading ios player API JSON
[youtube] 01m7w-I4JXE: Downloading android player API JSON
[youtube] 01m7w-I4JXE: Downloading m3u8 information
[info] 01m7w-I4JXE: Downloading 1 format(s): 22
[download] Destination: videos/ios-fair.mp4
[download] 100% of   10.33MiB in 00:00:00 at 14.13MiB/s
[youtube] Extracting URL: https://youtu.be/qFKv4I-MNQc
[youtube] qFKv4I-MNQc: Downloading webpage
[youtube] qFKv4I-MNQc: Downloading ios player API JSON
[youtube] qFKv4I-MNQc: Downloading android player API JSON
[youtube] qFKv4I-MNQc: Downloading player 80b90bfd
[youtube] qFKv4I-MNQc: Downloading m3u8 information
[info] qFKv4I-MNQc: Downloading 1 format(s): 22
[download] Destination: videos/ios-wingx.mp4
[download] 100% of    5.13MiB in 00:00:00 at 8.60MiB/s
--: line 461: less: command not found

**Comment by lymanjre** [comment]
لطفا آپدیت کنید حل شده مشکل
