### ISSUE TITLE
Proxies Not Loading After Automatic Upgrade

### ISSUE THREAD

**Issue by thejianyu** [hiddify/Hiddify-Manager#3529]
**Describe the bug**
After updating Hiddify Manager to version 8.8.92, I encountered an issue where no proxies are loading on Hiddify Next 0.13.6. It seems that this problem is specific to Hiddify Manager, as other sub-links from different panels are functioning correctly on Hiddify Next.

**To Reproduce**

1. Update Hiddify Manager to version 8.8.92.
2. Open Hiddify Next 0.13.6.
3. Click on the "Connect" button.
4. Attempt to load proxies list.
5. No proxies are loaded.

**Expected behavior**
Proxies should load successfully on Hiddify Next 0.13.6 after updating Hiddify Manager to version 8.8.92 and clicking on the "Connect" button.

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/109133022/853ec451-90a6-487f-92dd-919d535a0f5f)
![image](https://github.com/hiddify/Hiddify-Manager/assets/109133022/ad2aefa0-638d-41ce-8b56-9b1ecfcc1c8b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chromium 120
 - Version [Hiddify Manager v8.8.92]

**Additional context**
No proxies are loading specifically on Hiddify Next 0.13.6 after the automatic update to Hiddify Manager version 8.8.92. Other panels' sub-links are functioning as expected on Hiddify Next. Hence there's no connection with a stable version of Hiddify Manager!

**Comment by lymanjre** [comment]
Pls update to the latest version
