### ISSUE TITLE
مشکل درssl گرفتن برای دامنه

### ISSUE THREAD

**Issue by Mohammad1724** [hiddify/Hiddify-Manager#3530]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mohammad1724** [comment]
وقتی میخام با فایل بکاپ دامنه هامو برگردونم ssl برا دامنه هام نمیگیره
ساب دامین جدید که بهش میدم ssl میگیره ولی برای دامنه های قبلیم نمیگیره

**Comment by lymanjre** [comment]
ایشو قبلا ثبت شده و در دست بررسی است
