### ISSUE TITLE
اشکال در اتصال توکن کلادفلر

### ISSUE THREAD

**Issue by BachBahmani** [hiddify/Hiddify-Manager#3534]
**Describe the bug**
در بخش تنظیمات وقتی توی قسمت very advance setting  میایم و توکن api مخصوصی که از کلادفلر گرفتیم رو وارد میکنیم، با توجه به دسترسی که به اکانت کلادفلر میدیم میاد و مرتب تنظیمات dnsهای دامنه رو تغییر میده، IP نسخه ۶ جای  IP نسخه 4 تعریف میکنه و این موضوع باعث بروز خطا، از جمله خارج شدن دسترسی لینک ساب کاربرها، ssl دامنه‌ها و از کار افتادن کانفیگها میشه.

**Expected behavior**
ایده بسیار خوبه ولی بهتره که خود پنل هیدیفای ساب دامنه رندوم توی کلافلر ایجاد و یا حذف کنه و توی پنل جای‌گذاری کنه، منتها یه سری ساب دامنه مثل سابسکریپشن‌ها و یا دامنه‌های پنل و... رو مستثنی بذاره تا باعث بروز مشکل برای کاربران و ادمین‌ها نشه.

**Additional context**
عرض ارادت و دمتون گرم ✌🏻♥️

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
