### ISSUE TITLE
کار نکردن دکمه ثبت در قسمت تنظیمات پنل

### ISSUE THREAD

**Issue by payam999** [hiddify/Hiddify-Manager#3536]
پنل در آپدیت آخر یعنی 8.8.94 هست اما تغییراتی که در تنظیمات پنل انجام میشود ثبت نمیشود. دکمه ثبت کار نمیکند
مثلا من میخاستم فایروال رو خاموش کنم و نمیتونم این تغییر رو انجام بدم

**Comment by lymanjre** [comment]
لطفا به آخرین نسخه آپدیت کنید. مشکل باید رفع شده باشه. در صورت وجود مشکل ایشو را باز نمایید.
