### ISSUE TITLE
کارنکردن reverse tunnel

### ISSUE THREAD

**Issue by Amirwixa** [hiddify/Hiddify-Manager#3538]
سلام
در تمامی نسخه های هیدیفای باگی دیدم که باید بگم اگر رفع بشه میتونه خیلی کمک بکنه به تمام کاربران
الان همه ی تیم تمرکزش رو گذاشته روی مولتی سرور یا همون سرور پنل اصلی که ریلیز نشده و ...
اما به مشکلی که برخوردیم در  این پنل و واقعا یکی از باگ های بزرگش به حساب میاد اینه که نمیتونه اکثر تانل ها رو ساپورت کنه 
بهترین جوابدهی رو  روی ریلیتی داره اونم دایرکت
اما اگر زمانی خواستی تانل کنی سرورت رو به همین روش های جدیدی که اومده چیسل یا هر نوع 6to4 پنل باگ میزنه و نمیگذاره این اتفاق بیفته و فوروارد انجام بشه به خاطر مشغول بودن پورت هاست 
اگر برای این چاره ای باشه میتونه واقعا حرف بیشتری داشته باشه برای گفتن

**Comment by lymanjre** [comment]
هم اکنون تانلهای پر استفاده بدون مشکل هستند

**Comment by Amirwixa** [comment]
داداش دمتون گرم ولی خدایی راست میگه ریورس تانل نمیشه واسه سرورایی که فیلتره حداقل این ریورس خیلی کمک میکنه
فقط هم وقتی میشه ریورس تانل رو فعال کرد قبل از نصب پنل اصلی هست
