### ISSUE TITLE
Idea: Fragment feature enabled by the sub link

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Manager#3541]
I was thinking about implementation of SNI fragmentation (json parameters) directly via subscription link.

As the filtering of the FQDN domains still in progress by the GFW, it is the time to invest on the fragment feature, more than ever.

You can start this by adding a separate sub link in the user’s page that enabled the SNI fragment on the user side automatically.

I know not all the xray-based clients supporting this feature right now, so we need some push to make this more serious (at least until we can find a solution for this heavy domain blocking).

**Comment by lymanjre** [comment]
It s done in next release
