### ISSUE TITLE
Invalid Character 'o' in literal true (expecting 'u'): row 1, column4

### ISSUE THREAD

**Issue by infinitaa** [hiddify/Hiddify-Manager#3542]
MacOS Singbox 1.8.3 core, with auto url (/sub/) brings error but "Full sing box" is OK.
![image](https://github.com/hiddify/Hiddify-Manager/assets/121110779/a6353a9e-40fa-42b5-88fb-ba5b366d0e27)

**Comment by lymanjre** [comment]
It seems there is a problem in sub link

**Comment by lymanjre** [comment]
This issue is transformed to the project and will be closed here for now
