### ISSUE TITLE
اشتباه در صفحه تغییر دی‌ان‌اس ویکی

### ISSUE THREAD

**Issue by khodedawsh** [hiddify/Hiddify-Manager#3544]
سلام توی این [صفحه](https://github.com/hiddify/Hiddify-Manager/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%AA%D9%86%D8%B8%DB%8C%D9%85-DNS-%D8%B3%D8%B1%D9%88%D8%B1#%D8%AA%D9%86%D8%B8%DB%8C%D9%85-dns-%D8%A7%D8%B2-%D8%B7%D8%B1%DB%8C%D9%82-ssh ) برای دستور chattr اتریبیوت I استفاده شده که برای ایندکس کردن دیرکتوری استفاده میشه. منظور نویسنده حتما اتریبیوت i بوده که برای ریدآنلی کردن فایل استفاده میشه.
 همچنین بهتره آپشن -f حذف بشه تا کاربری که اجرا میکنه بتونه خطا رو در صورت بروز ببینه. سپاس.

**Comment by lymanjre** [comment]
سپاس از شما
