### ISSUE TITLE
مشکل آپدیت نشدن پنل 8.8.94

### ISSUE THREAD

**Issue by dora310** [hiddify/Hiddify-Manager#3547]
سلام من هم از طریق پنل سعی کردم هم از طرف SSH. 

Hiddify: Command update
=========================
update.sh: line 9: log_file: command not found update.sh: line 76: show_progress: command not found update.sh: line 80: msg_with hiddify: command not found
Press any key to return to menu

این را هم انجام دادم باز نشد.

sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
sudo pip3 install pyopenssl
sudo pip3 install pyopenssl --upgrade
echo "nameserver 1.1.1.1" >/etc/resolv.conf &&sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&/opt/hiddify-config/update.sh release

لطفا راهنمایی کنید ممنون.

**Comment by MHMALEK** [comment]
من اینطوری فیکس کردم:

-به جای استفاده از یو آی پنل برای آپدیت، از طریق SSH وصل شید به سروری که روش پنل بالا آوردید.
- اونجا به صورت خودکار دستور hiddify ران میشه و شما گزینه‌های مربوط به هیدیفای رو در ابتدا میبینید (اگر ندیدی فقط یکبار بنویس hiddify و اینتر کنید تا CLI پنل ران بشه رو سرور)
- گزینه Update رو انتخاب کنید. احتمال زیاد ارور مشابهی می‌گیرید.
- برگردید به صفحه قبل تو ترمینا و از ادمین Hiddify خارج بشید.
- مطابق توضیحات [اینجا](https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check) سعی کنید pyopenssl رو ریمو و از نو نصب کنید. (من شخصا کلا pip رو پاک کردم و همه چی رو از نو نصب کردم تا کار کرد)
- دوباره دستور hiddify رو بزنید و بعد گزینه Update رو بزنید. اینبار ایشالله باز میشه.

**Comment by dora310** [comment]
سلام ممنون از راهنمایی. 
پنل به روز رسانی شد ولی لینک های مستقیم کار بر ها کار نمیکنه برای دانلود اپلیکشن. ![image](https://github.com/hiddify/Hiddify-Manager/assets/685224/524e14d3-1f7c-4e51-8fb6-5c4db087bd50)

**Comment by MHMALEK** [comment]
خوشحالم که مشکل اول حل شد. راستش من خیلی به پنل آشنا نیستم و به همین خاطر توصیه میکنم برای این مشکل یه ایشو جدید باز کنید و مشکل رو ریپورت کنید. به هر حال فکر نمیکنم ولی هیچ ربطی به این مشکل فعلی داشته باشه.

**Comment by bepehr** [comment]
من بکاپ گرفتم از تنظیمات هایدفیفای و از طریق ssh  از خود منوی Hiddify کل Hiddify رو پاک کردم و بعد دوباره نصب کردم ، بکاپ رو برگردوندم و مشکل حل شد
