### ISSUE TITLE
bug add domain with langouge china

### ISSUE THREAD

**Issue by rezaparsad** [hiddify/Hiddify-Manager#3549]
bug in add domain with other langouge

من دامنه با نام چینی خرید ولی توی پنل ادد نمیشه متاسفانه

![Screenshot from 2024-01-24 15-23-36](https://github.com/hiddify/Hiddify-Manager/assets/70529677/9810fc9b-073c-47f1-8847-3098492df6fd)

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
