### ISSUE TITLE
php subscription bug

### ISSUE THREAD

**Issue by itz-mawni** [hiddify/Hiddify-Manager#3550]
ساب پی اچ پی مشکل داره و نمیشه باهاش کاربر ساخت اپدیت کرد یا حتی تغییرات اعمال کرد!
فقط باهاش میشه داخل پنل رو دید
یعنی من باید با لینک دایرکت یه کاربر بسازم و با لینک ساب وارد پنل بشم و برم لینک ساب اون کاربر رو بردارم
برای منی که با api کار میکنم خیلی مشکل بزرگیه که نمیشه با یک لینک هم کاربر ساخت هم ساب گرفت!

**Comment by lymanjre** [comment]
ساب php برای سابسکریپشن هست
