### ISSUE TITLE
relay domain bug

### ISSUE THREAD

**Issue by itz-mawni** [hiddify/Hiddify-Manager#3551]
بعد اپدیت یا اعمال تغییرات اس اس ال سرور میانی میپره و باید یبار پاک کرد لینک رو اعمال کرد و دوباره اضافه کرد و اعمال کرد!

تانلمم دکو هست با اسکریپت هیدیفای

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
