### ISSUE TITLE
ipv6 bug

### ISSUE THREAD

**Issue by newwebform** [hiddify/Hiddify-Manager#3553]
اگر در استفاده ازریالیتی یا هر پروتکل دیگری اجبار به استفاده از ipv6 انجام بشه کانفیک به صورت مثلا 0000:0000:0000:0000 ارسال میشه که اشتباهه و باید در لینک یابسکریبشن و همینطور خود برنامه ipv6 داخل کروشه [0000:0000:0000:0000] باشه

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
