### ISSUE TITLE
گیر کردن وسط کلیپا شورت

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/Hiddify-Manager#3554]
سلام و خسته نباشید به تیم هیدیفای
با شروع ورژن 8 پنل و تغییر هسته xray از 1.8.1 به 1.8.4 در هیدیفای ، این مشکل گیر کردن وسط کلیپا شورت ، چه اینستاگرام چه یوتیوب هم شروع شد و تا به الان که ورژن 8.8.95 هست همچنان ادامه داره
اگه ممکنه لطفاً بررسی کنید ممنون

**Comment by lymanjre** [comment]
وارپ را روی همه بگذارید
