### ISSUE TITLE
نیومدن بک اپ در بات

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#3557]
ارور در بات تلگرام

ورژن اخر 
سلام من توکن رباتم رو تغیر دادم
با اینکه توکن جدید رو جایگزین کردم  
و UUID رو دوباره وارد کردم
اما بک اپ ها برام نمیار و از داخل پنل میزنم استارت ارور میده

**Comment by lymanjre** [comment]
ایشو به پروژه منتقل شد تا بررسی بشه. فعلا اینجا بسته میشه
