### ISSUE TITLE
apply configs و ...

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#3560]
از داخل پنل تنظیمات رو اپلی کانفیگس میزنیم همش ارور میده بعد از پایان تایم

از داخل ssh اپلی نمیشه و میپره صفحه ی اول

پنل اپدیت نمیشه و ارور میده

 ln: failed to create symbolic link '/opt/hiddify-config/hiddify-manager': File exists    │ ▒▒│ ln: failed to create symbolic link '/opt/hiddify-server/hiddify-manager': File exists    │ ▒▒│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current          │ ▒▒│                                  Dload  Upload   Total   Spent    Left  Speed        
 
 ربات به تلگرام برای دریافت بک اپ وصل نمیشه

**Comment by lymanjre** [comment]
این مشکل فیکس شده به زودی آپدیت میدیم
