### ISSUE TITLE
Relay Config wont shown if I disable direct configs

### ISSUE THREAD

**Issue by ali-masoudi** [hiddify/Hiddify-Manager#3568]
**Describe the bug**
Hi
I have installed and configured hiddify and relay server, problem is if i disable direct config in proxy menu, relay config wont be shown for cdn configs and i must change them manually when giving to client.

Hidddify Panel 8.8.95

**Comment by lymanjre** [comment]
In next release I ll be solved

**Comment by ali-masoudi** [comment]
> In next release it ll be solved

Still wont shown
