### ISSUE TITLE
beta version

### ISSUE THREAD

**Issue by it-saeed** [hiddify/Hiddify-Manager#3574]
سلام .پنل روی ubuntu 22 نصب شد . بعد نصب به نسخه beta و develop آپدید شد . اما به مشکل خورد . داخل هر منو خطایی مربوط به db_version     مشاهده میشه
این مشکل ۳.۴ روزی هست که ایجاد شده . چندین بار سرور  rebuild شد و مجدد نصب شد . اما مشکل همچنان وجود داره

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.

**Comment by it-saeed** [comment]
@lymanjre 
تسک توسط automation از todo به done منتقل شده
