### ISSUE TITLE
خطا هنگام افزودن کانفیگ ssh در تمام کلاینت ها

### ISSUE THREAD

**Issue by aliresonance** [hiddify/Hiddify-Manager#3575]
هنگام افزودن پروکسی ssh به برنامه هیدیفای نکست یا کلاینت sing-box، ارور
create clash api server: cache_file and related fields in Clash API is deprecated in sing-box 1.8.0, use experimental.cache_file instead.
نشان داده می شود.
hiddify manager ver 8.8.95
sing-box ver 1.8.4
hiddify next ver 0.15.4

**Comment by lymanjre** [comment]
کتنفیگ فول سینگ باکس را تست میکنید؟

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.

**Comment by aliresonance** [comment]
> کانفیگ فول سینگ باکس را تست میکنید؟

تست شد. کانفیگ ها در هیدیفای نکست بدون مشکل بودند.

**Comment by mehranshabanpooral** [comment]
ارور 
starr clash api : external controller listen error : listen tcp 127.0.0.1:6756:
bind : An Attempt wass made to access asocket in a way forbidden by its access permissions 
چیست ؟
