### ISSUE TITLE
مشکل کانفیگ های grpc پنل هیدیفای

### ISSUE THREAD

**Issue by AntiGFW614** [hiddify/Hiddify-Manager#3576]
در کانفیگ هایی که با ترنسپورتر grpc هستند و توسط خود پنل هیدیفای تولید می شوند مشکلی وجود داره که باعث میشه تا در برنامه نکست اجرا نشه ولی در سایر کلاینت ها قابل اجرا باشه. همچنین همین کانفیگ های grpc که توسط سایر پنل ها مانند سنایی تولید می شوند به خوبی قابل اجرا در هیدیفای نکست هستند. این مشکل مدت زیادی هست که در تمام نسخه های پنل ها وجود داره. با تشکر از تیم پشتیبانی هیدیفای.

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
