### ISSUE TITLE
وارپ پنل هیدیفای

### ISSUE THREAD

**Issue by AntiGFW614** [hiddify/Hiddify-Manager#3577]
شکل دیگری که نسخه جدید پنل هیدیفای یعنی 8.8.95 با آن درگیر است مشکل وارپ می باشد. زمانی که وارپ را از داخل پنل هیدیفای فعال می کنیم و حتی لاینسس هم اضافه می شود در تست های مربوط به آیپی همچنان آیپی اصلی سرور نمایش داده می شود که نشان از عدم فعال سازی وارپ روی سرور می باشد.

**Comment by lymanjre** [comment]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.
