### ISSUE TITLE
عدم نصب 

### ISSUE THREAD

**Issue by alendark1361** [hiddify/Hiddify-Manager#3578]
15.46MiB/s
[youtube] Extracting URL: https://youtu.be/F2bC_mtbYmQ
[youtube] F2bC_mtbYmQ: Downloading webpage
[youtube] F2bC_mtbYmQ: Downloading ios player API JSON
[youtube] F2bC_mtbYmQ: Downloading android player API JSON
[youtube] F2bC_mtbYmQ: Downloading m3u8 information
[info] F2bC_mtbYmQ: Downloading 1 format(s): 22
[download] Destination: videos/ios-shadowrocket.mp4
[download] 100% of   14.27MiB in 00:00:01 at 10.92MiB/s
[youtube] Extracting URL: https://youtu.be/8P887E-KMls
[youtube] 8P887E-KMls: Downloading webpage
[youtube] 8P887E-KMls: Downloading ios player API JSON
[youtube] 8P887E-KMls: Downloading android player API JSON
[youtube] 8P887E-KMls: Downloading m3u8 information
[info] 8P887E-KMls: Downloading 1 format(s): 22
[download] Destination: videos/android-hiddifyclash.mp4
[download] 100% of    7.33MiB in 00:00:00 at 14.72MiB/s
[youtube] Extracting URL: https://youtu.be/6HncctDHXVs
[youtube] 6HncctDHXVs: Downloading webpage
[youtube] 6HncctDHXVs: Downloading ios player API JSON
[youtube] 6HncctDHXVs: Downloading android player API JSON
[youtube] 6HncctDHXVs: Downloading m3u8 information
[info] 6HncctDHXVs: Downloading 1 format(s): 22
[download] Destination: videos/android-v2rayng.mp4
[download] 100% of    8.09MiB in 00:00:00 at 14.57MiB/s
[youtube] Extracting URL: https://youtu.be/01m7w-I4JXE
[youtube] 01m7w-I4JXE: Downloading webpage
[youtube] 01m7w-I4JXE: Downloading ios player API JSON
[youtube] 01m7w-I4JXE: Downloading android player API JSON
[youtube] 01m7w-I4JXE: Downloading m3u8 information
[info] 01m7w-I4JXE: Downloading 1 format(s): 22
[download] Destination: videos/ios-fair.mp4
[download] 100% of   10.33MiB in 00:00:00 at 15.45MiB/s
[youtube] Extracting URL: https://youtu.be/qFKv4I-MNQc
[youtube] qFKv4I-MNQc: Downloading webpage
[youtube] qFKv4I-MNQc: Downloading ios player API JSON
[youtube] qFKv4I-MNQc: Downloading android player API JSON
[youtube] qFKv4I-MNQc: Downloading player cb886c6c
[youtube] qFKv4I-MNQc: Downloading m3u8 information
[info] qFKv4I-MNQc: Downloading 1 format(s): 22
[download] Destination: videos/ios-wingx.mp4
[download] 100% of    5.13MiB in 00:00:00 at 10.67MiB/s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hiddifypanel'
cat: /VERSION: No such file or directory
root@server-fkj6fn:~#

**Comment by lymanjre** [comment]
This issue will be transformed to the project and I will close it here.
