### ISSUE TITLE
github project automation

### ISSUE THREAD

**Issue by it-saeed** [hiddify/Hiddify-Manager#3585]
این ایشو به پروژه منتقل خواهد شد و در اینجا بسته می‌شود.

_Originally posted by @lymanjre in https://github.com/hiddify/Hiddify-Manager/issues/3574#issuecomment-1915993811_
            

سلام . آیا این اکشن درست  کار میکنه ؟ به عنوان مثال این ایشو به برد منتقل شد و بدون هیچ تغییری به done منتقل شد

**Comment by Iam54r1n4** [comment]
بله
