### ISSUE TITLE
عدم استفاده از دامنه ساخته شده از روی آی پی

### ISSUE THREAD

**Issue by MihanDeveloper** [hiddify/Hiddify-Manager#3590]
اگر قرار است که از دامنه ای که هنگام نصب از روی آی پی ساخته میشود ، یعنی:
xxx.xxx.xxx.xxx.sslip.io
استفاده نشود و من هم با این تصمیم موافقم.
ولی چون سیستم برای ساخت کانکشنهای ریالیتی اولین دامنه مستقیم در لیست را استفاده میکند به اصل بالا توجه نکرده و اگر دامنه sslip.io اولین دامنه مستقیم در لیست باشد . همان را در سابسکریپش جایگذاری میکند.

**Comment by Iam54r1n4** [comment]
خیر اینطور نیست دامنه ی reality مستقل از این دامنه است.
