### ISSUE TITLE
Internal server error: Bad Request

### ISSUE THREAD

**Issue by amaleky** [hiddify/Hiddify-Manager#3593]
# Internal Error Stacktrace:
**Error Message**:   400 Bad Request: The referrer does not match the host.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 117, in check_csrf
    csrf.protect()

```

## Details:
**Hiddify Version**: 9.0.0.dev61
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-92-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Please update your panel. Fixed.
