### ISSUE TITLE
هسته ی xray

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#3602]
سلام
پنل من ورژن اخر استیبل هست 8.8.95
Xray کار نمیکنه
تنظیمات رو اپلی کردم تا اخرم رفت اوکی داد
ولی یهو قطع شد!

اپدیت کردم
رینستال
اپلی کانفیگ
ولی روی xray کار نمیکنه
گذشتم سینگ باکس کار میکنه!
ولی به xray اصلا
راه حل چیه؟
پنل میاد بالا
کانفیگ ها پینگ میدن اما فقط xray از کار افتاد
![photo_2024-02-05_00-36-32](https://github.com/hiddify/Hiddify-Manager/assets/82303769/eff41e5c-9891-4c4e-8ee0-00fc96b85f2b)

اپدیت:
سینگ باکس هم از کار افتاد!

اپدیت:
مشکل رو فهمیدم ولی این یک باگه
دامین طولانی ساخته بودم و اپلی کردم مشکل خورد
الان حذفش کردم حل شد!

**Comment by Iam54r1n4** [comment]
خودتون فیکس کردید. ایشو بسته میشه.
