### ISSUE TITLE
Improve decoy site management

### ISSUE THREAD

**Issue by fakoor** [hiddify/Hiddify-Manager#3612]
**Is your feature request related to a problem? Please describe.**
By default, decoy sites are accessible by IP address as well (in addition to domain names)

**Describe the solution you'd like**
The server should refrain from serving any content by IP address in case of invalid or missing UUID path. Actually it may respond with empty content (ERR_EMPTY_RESPONSE),  or close the connection (ERR_CONNECTION_CLOSED),  or anything else equivalent when directly accessed by IP address. This behavior is expected and normal; for example it happens  when you access a site that is behind a CDN  (if you type in the IP‌ only nothing is served). So it improves privacy of the IP‌ address by not associating it with a specific content since mimicing a balancer/CDN Address.
 

**Describe alternatives you've considered**
The decoy mechanism could be improved by enabling to install and side-host a local blog or wiki instance (for example a DokuWiki that is statically managed  [no-DB] ) and serving that instead. In this case the decoy site has the advantage of being functionally used as well for some reasonable purpose as a bonus.

**Additional context**
N/A

**Comment by 4deployAPP** [comment]
+1 for this always doing this blockage on new servers. I have managed to fix this by using publicly available cloudflare only script with firewall rules.
