### ISSUE TITLE
Error in import

### ISSUE THREAD

**Issue by mohsen9april** [hiddify/Hiddify-Manager#3620]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 9.0.0.dev61
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-60-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

<img width="391" alt="Screenshot 2024-02-10 at 7 40 33 PM" src="https://github.com/hiddify/Hiddify-Manager/assets/37551348/4ca3caf4-0488-4a7a-896f-f4e176274465">

**Comment by Iam54r1n4** [comment]
Fixed
