### ISSUE TITLE
This version of Hiddify Manager is outdated

### ISSUE THREAD

**Issue by AytoMaximo** [hiddify/Hiddify-Manager#3621]
**Describe the bug**
Just installed Hiddify and got “This version of Hiddify Manager is outdated” popup error

**To Reproduce**
Steps to reproduce the behavior: install Hiddify by `curl https://install.hiddify.com/release |bash`, open dashboard the first time using the admin link. 

**Expected behavior**
Just installed app has the latest version. 

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/14392087/645c616b-aad3-45da-b443-4c44df7f3d88)

**Comment by xPROMSx** [comment]
I get the same thing today when installing on a clean server

**Comment by Iam54r1n4** [comment]
Please update your panel to latest. this issue fixed.
