### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by hojatsajadinia** [hiddify/Hiddify-Manager#3623]
#12 [5/8] RUN bash install.sh install-docker
#0 0.141 
#0 0.141 
#0 0.141 
#12 0.143 (B./common/utils.sh: line 112: pip: command not found
#12 0.152 Package cli_progress==1.7.0 is not installed.
#12 0.153 ./common/utils.sh: line 123: pip: command not found
#12 0.154 ./common/utils.sh: line 348: cli_progress: command not found
'utf-8' codec can't decode byte 0xe2 in position 803: invalid continuation byte

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
