### ISSUE TITLE
Old version warning

### ISSUE THREAD

**Issue by Daariush** [hiddify/Hiddify-Manager#3629]
I have installed the hiddify manager on my ubuntu with the single command line. after installation is complete, a warning message is shown that my panel version is old and can update through the admin panel. (for clarification the installed version is 8.8.95)
after clicking update and wait for completion and error! message appears and it wont update.

 - OS: Ubuntu
 - Version 22.04

How can I update or install the newest version?

**Comment by xPROMSx** [comment]
https://github.com/hiddify/Hiddify-Manager/issues/3621
No answer unfortunately. i've only been able to install the dev version of the panel, but it all seems very unreliable and unstable. Even the stable version is impossible to install the latest version.
