### ISSUE TITLE
عدم امکان انتخاب پورت برای دامنه و کانفیگ ها 

### ISSUE THREAD

**Issue by denundern** [hiddify/Hiddify-Manager#3632]
**Is your feature request related to a problem? Please describe.**
امکان اضافه کردن یه پورت خاص برای یک دامنه وجود نداره و اگه یه پورت برای http یا https باز بشه برای همه دامنه ها بصورت اتوماتیک اون کانفیگ با لینک سابسکرایب ساخته میشه که باعث میشه یه سری کانفیگا اضافه باشن و کار نکنن 

**Describe the solution you'd like**
برای دامنه ی سابسکرایب بشه انتخاب کرد کدوم دامنه با کدوم پورت ها نمایش داده بشه یا موقع اضافه کردن دامنه های اصلی و یا CDN بشه انتخاب کرد با چه پورتی میخواییم کارکنه

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
