### ISSUE TITLE
هنگ کردن و بیرون پریدن از برنامه ،همینطور گزارش خطا هنگام‌اضافه کردن لینک ساب

### ISSUE THREAD

**Issue by Mahanam2** [hiddify/Hiddify-Manager#3634]
سلام گوشی من اندروید ۱۳ هست و پنج شش ماه مشکل کرش و بیرون پریدن از برنامه رو دارم،در بروز رسانی های جدید هم در  این یکماه آخر، موقع اضافه کردن لینک های سابسکرایب با خطا مواجه میشم و مشکل دیگه در بخش اضافه شده وارپ هست و این‌که‌ در هیچ جا توضیحاتی جامع در یک ویدئو سا آموزش در مورد کاربران عام کلاینت هیدیفای نکست از ابتدا تنظیمات تا بخش های مختلف ،خطا ها و راه های رفع اون وجود نداره ،متاسفانه در تلگرام هم پاسخگو نیستن

**Comment by ReturnFI** [comment]
سلام.
در ریپازیتوری هیدیفای نکست ایشو ثبت بفرمایید

**Comment by Mahanam2** [comment]
Мне жаль, что в начале 2025 года истинный смысл жизни все еще неясен.
Сегодня вы говорите об этике и праве, лучше потратить годы, которые ваши
отцы создали страну Иран и свою колонию, в обмен на несправедливую кровь,
которую ваши отцы пролили во время Второй мировой войны и декларации
нейтралитета Ирана. думая о компенсации, люди подвергаются экономическим
санкциям и оказываются в ловушке диктаторского правительства. вместо
управленческих функций капитализма; Иногда ты думал о человечности

در تاریخ شنبه ۶ ژوئیه ۲۰۲۴، ۲۰:۵۹ Whispering Wind ***@***.***>
نوشت:
