### ISSUE TITLE
چیدمان دامین ها

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#3635]
یکی از مشکلات ما در قسمت دامین این هستش که 
وقتی یک سری دامین اضافه میکنیم نمیتونیم ترتیبشون رو دستکاری کنیم

خوب وقتی بشه جابجا کرد میتونیم  وقتی ساب رو اپدیت میکنیم همون چیدمانی که میخواییم رو داشته باشیم

الان باید حذف کنید و دوباره اضافه کنیم بر اساس چیدمانی که میخواییم😐

**Comment by aref199** [comment]
درسته خیلی کاربردی میشه اگر بشه ترتیب دامین ها رو تغییر داد بدون نیاز به حذفشون
