### ISSUE TITLE
Allow certbot to request wild-card certificates (DNS-01 verification via cloudflare API)

### ISSUE THREAD

**Issue by fakoor** [hiddify/Hiddify-Manager#3637]
**Is your feature request related to a problem? Please describe.**
When we organize multiple sub-only links to force specific/manual clean IPs based on provider (e.g.: sub-mtn.example.com, sub-mci.example.com,..., sub-xxx.example.com), It is necessary for the manager to obtain SSL certificate individually for each of such subdomains. 

**Describe the solution you'd like**
Improve the process by using a variant of  acme/certbot  that support DNS verification method (Like what is done for example by CertifyTheWeb). This enables to once get a certificate for both the root domain and all its subdomains in a single request (by supplying cloudflare API key and using DNS-01 challenge type instead of .acme http-01 files ). This speeds up addition of subdomains to the deployment and keep the quota of Lets Encrypt reissuance policy under more control.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
