### ISSUE TITLE
Please add multi-server load-balancing  feature to Hiddify

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3640]
Hi;
Please add multi-server load-balancing  feature to Hiddify
A Master Server that handle multi-server load-balancing configurations. The traffic is split up and sent to multiple servers, rather than let the client selecting the best server based on ping or speed and sending all traffic through the single server. 
Thanks

**Comment by Iam54r1n4** [comment]
we're working on it. thanks for your report. the issue will be close.

**Comment by marab2** [comment]
Any update on this please?
