### ISSUE TITLE
اضافه کردن سرور مرکزی و مدیریت چند سرور

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#3641]
با درود

لطفا قابلیت مدیریت چند سرور که بتونیم چندین سرور و ترافیک رو مدیریت کنیم رو به پروژه اضافه کنید.

با تشکر

**Comment by mohammadrezaordooni** [comment]
سلام بله واقعا پنل به این کاملی فقط همینو کم داره و اگه امکان تعریف سرور مرکزی فراهم بشه عالی میشه
خیلی ممنون از زحماتتون.
