### ISSUE TITLE
قطع شدن کانفیگ ها در صورت اد کردن دامنه با تعداد کارکتر بالا 

### ISSUE THREAD

**Issue by persian-michael-scott** [hiddify/Hiddify-Manager#3648]
#باگ 
نسخه هیدیفای 8.8.95 
من یک دامنه تهیه کردم با تعداد 63 کارکتر . 
مثلا به این صورت : 
cdn.2pf3izqqouazbb6c2nuba0nw9rnsxctyse78hz05t02rrjz4w389rhil13rfrv.top 
وقتی ادش میکنم به عنوان دامنه cdn در پنل ، بخش xray کرش میکنه و کل کانفیگ ها قطع میشه اما خود پنل باز میشه.

**Comment by kiavash599** [comment]
درسته دقیقا من هم 4 روزه با این مشکل روبرو هستم حتی با 60 کاراکتر هم چک کردم به مشکل خورد

**Comment by akonil** [comment]
مشکل از هسته x-ray هست و ربطی به هیدیفای نداره

**Comment by Rasoul-Khajavi** [comment]
در سمت کلاینت وقتی ادیت میکنی کانفیگ رو و این مدل ساب دامین رو میذاری کار میکنه ! فقط ما میخوایم که در قسمت اجبار توی یه کانفیگ بتونیم این دامنه با تعداد کاراکتر بالا بذاریم ربطی هسته نباید داشته باشه و فقط تو سابسکریپشن لینکمون اینجور کانفیگی باشه 


> مشکل از هسته x-ray هست و ربطی به هیدیفای نداره

**Comment by ReturnFI** [comment]
سلام.
به آخرین نسخه ریلیز آپدیت کنید مورد بررسی و رفع شده.
