### ISSUE TITLE
Install Hiddify-Manager using docker failed

### ISSUE THREAD

**Issue by jun9** [hiddify/Hiddify-Manager#3651]
**Describe the bug**
An attempt to install Hiddify-Manager using docker failed

**To Reproduce**
1. Following instruction at https://github.com/hiddify/Hiddify-Manager/wiki/Install-Hiddify-using-Docker
git clone https://github.com/hiddify/hiddify-config
cd hiddify-config
touch hiddify-panel/hiddifypanel.db
docker-compose up -d

5. See error
 => ERROR [hiddify 5/6] RUN bash install.sh install-docker                                                                                          0.1s 
------                                                                                                                                                   
 > [hiddify 5/6] RUN bash install.sh install-docker:                                                                                                     
0.090                                                                                                                                                    
0.090 
0.090 
0.090 ./common/utils.sh: line 112: pip: command not found
0.092 Package cli_progress==1.7.0 is not installed.
0.092 ./common/utils.sh: line 123: pip: command not found
0.092 ./common/utils.sh: line 348: cli_progress: command not found
**Expected behavior**

**Desktop (please complete the following information):**
Docker on MacOS 14.2.1 

Same error on ubuntu 22.04

**Comment by dogrocker** [comment]
as I know docker doesn't work now

**Comment by tangpop2000** [comment]
Yes, Error as below

Building hiddify
Step 1/13 : FROM ubuntu:22.04
 ---> 3db8720ecbf5
Step 2/13 : EXPOSE 80
 ---> Using cache
 ---> 24befb809170
Step 3/13 : EXPOSE 443
 ---> Using cache
 ---> 73459936e037
Step 4/13 : RUN apt-get update && apt-get install -y whiptail apt-utils curl sudo systemd python2 xxd lsof
 ---> Using cache
 ---> f7325768e3e1
Step 5/13 : ENV TERM xterm
 ---> Using cache
 ---> e333fb8e6945
Step 6/13 : ENV TZ Etc/UTC
 ---> Using cache
 ---> c05a2f08576a
Step 7/13 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 6f74e13665f4
Step 8/13 : USER root
 ---> Using cache
 ---> 46371be149dc
Step 9/13 : WORKDIR /opt/hiddify-manager/
 ---> Running in 926f2ff689eb
 ---> Removed intermediate container 926f2ff689eb
 ---> 8fbb81742589
Step 10/13 : COPY . .
 ---> 3f99720fc46b
Step 11/13 : RUN bash install.sh install-docker
 ---> Running in c41ce8228a79



./common/utils.sh: line 112: pip: command not found
Package cli_progress==1.7.0 is not installed.



./common/utils.sh: line 123: pip: command not found
./common/utils.sh: line 348: cli_progress: command not found
Failed to open terminal.


ERROR: Service 'hiddify' failed to build: The command '/bin/sh -c bash install.sh install-docker' returned a non-zero code: 127

**Comment by q2333gh** [comment]
Almost same issue 

```
btwl@btwl-virtual-machine ~/a/h/hiddify-config (main) [SIGINT]> docker compose up -d
[+] Running 0/1                                                                                                                    
 ⠿ hiddify Error                                                                                                              3.4s 
[+] Building 84.2s (8/10)                                                                                                          
 => [internal] load .dockerignore                                                                                             0.0s 
 => => transferring context: 59B                                                                                              0.0s
 => [internal] load build definition from Dockerfile                                                                          0.0s
 => => transferring dockerfile: 635B                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                               0.0s
 => [1/6] FROM docker.io/library/ubuntu:22.04                                                                                 0.0s
 => [internal] load build context                                                                                             0.1s
 => => transferring context: 35.23kB                                                                                          0.1s
 => CACHED [2/6] RUN apt-get update && apt-get install -y whiptail apt-utils curl sudo systemd python2 xxd lsof               0.0s
 => CACHED [3/6] WORKDIR /opt/hiddify-manager/                                                                                0.0s
 => [4/6] COPY . .                                                                                                            1.3s
 => [5/6] RUN bash install.sh install-docker                                                                                 82.8s
 => => # Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)                                                                  
 => => # Installing collected packages: wcwidth, asyncio, argparse, typing-extensions, urwid, cli_progress                        
 => => # Successfully installed argparse-1.4.0 asyncio-3.4.3 cli_progress-2.0.0 typing-extensions-4.11.0 urwid-2.6.10 wcwidth-0.2.
 => => # 13                                                                                                                       
 => => # WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system packag
 => => # e manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv 
```

**Comment by PCbIX** [comment]
UP the same issue trying to start in docker. If I add pre-isntall python it's stuck at venv. If original dockerfile ./common/utils.sh: line 112: pip: command not found
Pls. If you didn't support docker install remove it from documentation.

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
