### ISSUE TITLE
اختلال در ایرانسل

### ISSUE THREAD

**Issue by 1razzaghi** [hiddify/Hiddify-Manager#3652]
سلام دوستان
حدود یک هفته ای میشه که کانفیگ ها روی ایرانسل اختلال دارن
آی پی سرورم هم فیلتر نیست
همراه اول و اینترنت خونگی اکی هستن ولی ایرانسل تایم اوت زیاد داره
شما به چنین مشکلی بر نخوردید؟

**Comment by Iam54r1n4** [comment]
به دلیل عدم پاسخگویی "دوستان" فعلا ایشو بسته میشه :)
