### ISSUE TITLE
مشکلی در نشون دادن کاربرای آنلاین وجود داره

### ISSUE THREAD

**Issue by ojooubeh** [hiddify/Hiddify-Manager#3654]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 9.0.0.dev74
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-94-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by miladj3** [comment]
"I updated from version 8.8.95 to 8.8.96 and encountered an issue."

**Comment by Iam54r1n4** [comment]
Please update your panel to latest version. it's been fixed.

**Comment by miladj3** [comment]
mine fixed
