### ISSUE TITLE
اضافه کردن سایت شخصی به سرور

### ISSUE THREAD

**Issue by bepehr** [hiddify/Hiddify-Manager#3656]
سلام و تشکر بابت پروژه ی خوبی که پیاده کردید

من یه سرور شخصی دارم با چند تا کاربر محدود ، امکانش هست از nginx روی سرور که مربوط به پروژه ی شماست برای بالا آوردن یه سایت شخصی هم استفاده کنم ؟ 

متشکرم

**Comment by ReturnFI** [comment]
سلام و ممنون از لطف شما
خیر با دستکاری کانفیگ nginx اختلال در پنل ایجاد میشود.
موفق باشید.
