### ISSUE TITLE
Request to act as Bridge/Proxy for WARP configs [or literally any config!] ...

### ISSUE THREAD

**Issue by A5DkjGQUZx** [hiddify/Hiddify-Manager#3660]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
I would like to be able to relay or bridge third party config URL from the manager into the subscription link of users.
e.g. I add a domain on the Manager and force it to read "https://raw.githubusercontent.com/ippscan/ippscanTEAM/main/Montervpn" and include the domain in my sub-link settings.
When the user updates the subscription, they will get most recent version of the relay domains I added for them as well.

**Comment by litoosh13** [comment]
we will look into it
