### ISSUE TITLE
Not named

### ISSUE THREAD

**Issue by waseemcn** [hiddify/Hiddify-Manager#3662]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 9.0.0.dev75
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-83-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

( English is not named, Chinese is not named )

![image](https://github.com/hiddify/Hiddify-Manager/assets/44390023/3ad3e7a8-f838-4f5e-9d56-f7f974bcdfb2)

**Comment by Iam54r1n4** [comment]
Please update your panel. it fixed.
BTW, thanks for your report.
