### ISSUE TITLE
مشکل در صفحه کاربران

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3680]
سلام در صفحه کاربران هنگام کلیک بر روی دکمه بروزرسانی حجم مصرفی در انتهای صفحه، کل صفحه سفید میشه و گزینه ها ناپدید میشن.
 - Device: [Note 11]
 - OS: [14.0.5]
 - Browser [chrome 122]
 - Version [8.8.97]

**Comment by Iam54r1n4** [comment]
لطفا پنل رو اپدیت کنید و دوباره تست کنید. اگر مشکلی نبود issue رو ببندید.

**Comment by Alirezamoradi20** [comment]
![Screenshot_۲۰۲۴-۰۳-۰۶-۰۹-۵۴-۰۷-۵۹۸_com.android.chrome.jpg](https://github.com/hiddify/Hiddify-Manager/assets/161325792/d1573e7c-c2d4-4ff0-8b73-f98b97fb8ef4)

مشکل هنوز وجود داره.
