### ISSUE TITLE
امکان ترتیب بندی دامنه ها

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3681]
سلام 
لطفا قابلیت تغییر ترتیب دامنه ها رو اضافه کنید. در نسخه فعلی (۸.۸.۹۷) فقط با حذف و افزودن مجدد دامنه میشه ترتیب رو تغییر داد.

**Comment by akonil** [comment]
@lymanjre @hiddify-com 
این فیچر واقعا کاربردی میتونه باشه

**Comment by Iam54r1n4** [comment]
پیشنهادتون برای بررسی بیشتر به پروژه منتقل میشه.
(فعلا ایشو بسته میشه)
