### ISSUE TITLE
مشکل در ذخیره تنظیمات

### ISSUE THREAD

**Issue by hamedm94** [hiddify/Hiddify-Manager#3683]
در قسمت تنظیمات هیچ گزینه ای قابل تغییر نیست حتی تغییر زبان. در واقع فیلد Telegram Fake Domain که یک دامنه پیش فرض است را قبول نمی کند و هیچ دامنه ای را اجازه نمی دهد که جایگزین شود تا این خطا را ندهد. پنل انگلیسی است و زبان هم غیر قابل تغییر است. ورژن تست شده 8.8.97
حتی اگر تغییری هم انجام ندهم فقط روی دکمه submit این صفحه کلیک کنم باز هم این خطا دریافت می شود.

Error:
There is an error in one of the fields.

![Uploading ee.jpg…]()

**Comment by Iam54r1n4** [comment]
مشکل حل شد. لطفا اپدیت کنید.
