### ISSUE TITLE
Generate duplicate UUID in create user

### ISSUE THREAD

**Issue by realattila** [hiddify/Hiddify-Manager#3686]
**Describe the bug**
when you want to create user, after close to 500 times try, i received duplicated UUID and return error this UUID used before

**To Reproduce**
go to hiddify panel create user, and try to create one.

**Expected behavior**
never returns an UUID used before

**Additional context**
[[HiddifyPanel](https://github.com/hiddify/HiddifyPanel/tree/main)/[hiddifypanel](https://github.com/hiddify/HiddifyPanel/tree/main/hiddifypanel)/[panel](https://github.com/hiddify/HiddifyPanel/tree/main/hiddifypanel/panel)/[admin](https://github.com/hiddify/HiddifyPanel/tree/main/hiddifypanel/panel/admin)
/UserAdmin.py](https://github.com/hiddify/HiddifyPanel/blob/main/hiddifypanel/panel/admin/UserAdmin.py) in line 250

it is better to use UUID v7 instead of UUID v4 for generate userId, it`s faster and better

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
