### ISSUE TITLE
چند پیشنهاد جهت اجرا

### ISSUE THREAD

**Issue by smblue07** [hiddify/Hiddify-Manager#3697]
سلام وقت بخیر
چند پیشنهاد دارم امیدوارم با اجرای اون تجربه ی بهتری داشته باشیم توی پنل هیدیفای منیجر
۱. اضافه کردن فیلد شماره ی اکانت برای مرتب سازی و اولویت بندی نمایش در صفحه کاربران
۲. امکان انتقال کاربر توسط ادمین اصلی بین ادمینا یا تخصیص دادن کاربر به خود ادمین اصلی ( فیلد اضافه شده توسط کدوم ادمین بوسیله ی ادمین اصلی قابل تغییر باشد)
۳. امکان تغییر ترتیب دامین ها در صفحه دامین ها
۴. امکان تغییر  مسیر خروجی (اوتباندها) یه سری از سایتهارو بشه از وارپ عبور داد یه سری از سایتهارو دایرکت و ....
۵.امکان استفاده از فرگمنت و ماکس در اوتباند
۶. امکان تخصیص کانفیگ به هر کاربر با توجه به دامنه ها و کانفیگ های موجود
۷. امکان لاگین با یوزرنیم و پسورد 
۸. ساخت اکاانت ssh معمولی برای هر کاربر  بدون هسته سینگ باکس

با تشکر از تیم توسعه

**Comment by Iam54r1n4** [comment]
درود، ممنون بابت پیشنهادتون پیشنهادتون برای بررسی بیشتر به بورد پروژه منتقل شد.
(ایشو فعلا بسته میشه)
