### ISSUE TITLE
درخواست افزوده شدن اتصال از آی‌پی کدام کشورها به سرور

### ISSUE THREAD

**Issue by HadiTak** [hiddify/Hiddify-Manager#3701]
سلام، درخواست داشتم جهت افزایش امنیت، این امکان در تنظیمات پنل هیدیفای اضافه شود که کاربر انتخاب کند دسترسی به سرور از ip کدام کشورها مجاز است. سپاس

**Comment by A5DkjGQUZx** [comment]
This can be done via and integration with Cloudflare's API and WAF configs (of course if the domain is hosted there and if the transport later is CDN-compatible)
https://developers.cloudflare.com/waf/tools/ip-access-rules/

**Comment by Iam54r1n4** [comment]
نیاز به توضیحات بیشتری در این مورد هست.
- دلایل تون برای اضافه کردن چنین قابلیتی چی هست؟
- در چه شرایطی میتونه مفید باشه براتون؟

**Comment by HadiTak** [comment]
ضمن تشکر:
برای افرادی که به هر دلیلی از cdn استفاده نمیکنن و از طرفی نمیخوان سرور رو با ابزارهای جانبی یا iptables درگیر کنن، جهت جلوگیری از حملات برنامه ریزی شده به سرورها و علاوه بر اون، مصرف نشدن بیخود پهنای باند سرورها، وجود یک گزینه در تنظیمات هیدیفای که ارتباط رو مثلا فقط با سرورهای آپدیت یا مثلا یک سرور دیگه برقرار کنه میتونه مفید باشه.
