### ISSUE TITLE
Conflict between server's firewall and WARP

### ISSUE THREAD

**Issue by A5DkjGQUZx** [hiddify/Hiddify-Manager#3702]
The title is very self-descriptive!
When firewall is on (using the webUI), then WARP and Wireguard do not work on the server...
Tested and confirmed by disabling the firewall on the server using version 9.0.0.dev75

**Comment by akonil** [comment]
@lymanjre @hiddify-com

**Comment by nullname79** [comment]
@lymanjre ⁉

**Comment by Iam54r1n4** [comment]
We are working on it.

**Comment by Iam54r1n4** [comment]
Please update your panel to latest version, Fixed.
