### ISSUE TITLE
مشکل در نصب پنل ریلیز

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3704]
سلام خسته نباشید
بعد از نصب پنل روی سروری با 1GB رم 20GB هارد و 1Core سی پی یو تقریبا بیشتر سرویس ها failed هستن.با دانگرید و آپدیت مجدد به ریلیز تقریبا همگی بجز موردی که در عکس مشخص است active شدند.
حالا این یه مورد رو چطوری باید active کنم؟![IMG_20240302_114547_020.jpg](https://github.com/hiddify/Hiddify-Manager/assets/161325792/edea1639-ea86-4477-a0cc-b5b5e631eb05)

**Comment by Iam54r1n4** [comment]
دستور زیر رو تست کنید:
```bash
cd /opt/; ln -s /opt/hiddify-manager/ hiddify-config
```
