### ISSUE TITLE
Oracle Cloud Installation doesn't show config link

### ISSUE THREAD

**Issue by bithack3r** [hiddify/Hiddify-Manager#3707]
As the title suggests, I get the IP from the OCI after the successful run of the stack. I wait for 10 minutes and when I open the IP, it goes to the decoy website and I don't see any configuration link. I've tried it three times now on new stacks but the problem persists. Am I missing something or is this a bug?

**Comment by auxiliary** [comment]
Yup, same issue here.

**Comment by bithack3r** [comment]
Login to your VPS with SSH, then do sudo su​
This should automatically show you the admin panel where you can select to show the admin link​
________________________________
