### ISSUE TITLE
Problem with downloading configs

### ISSUE THREAD

**Issue by AmirmahdiAlimadadi** [hiddify/Hiddify-Manager#3710]
### Discussed in https://github.com/hiddify/Hiddify-Manager/discussions/3709

<div type='discussions-op-text'>

<sup>Originally posted by **AmirmahdiAlimadadi** March  2, 2024</sup>
با سلام و عرض خسته نباشید خدمت تیم هیدیفای، بنده نزدیک به یک سالی هست از این پلتفرم استفاده می کنم ولی چند روزه نمی تونم کانفیگ هارو در سیستم کلاینت اضافه کنم، یعنی یوزر می سازم ولی نمی تونم به کلش یا هیدیفای نکست اضافه کنم.

توضیحات در مورد توپولوژی سرور های من:

سرور های اصلی و میانی با گوست تانل شدن و سرور های ایران با سایر تانل ها به سرور های میانی وصل هستن و از سی دی ان آروان استفاده می کنم، البته باید بگم کانکشن HTTP رو بستم</div>

![image](https://github.com/hiddify/Hiddify-Manager/assets/83460761/95c99950-62c6-43d3-896a-99a5e8d712b8)

**Comment by AmirmahdiAlimadadi** [comment]
لطفا کسی کمک کنه، من وقت نکردم رپو شما رو مطالعه کنم الانم بدجایی گیر کردم

**Comment by Iam54r1n4** [comment]
(در عکس دامینت مشخص هست)
امکانش هست دامین تون فیلتر شده باشه.
