### ISSUE TITLE
Hiddify Panel Arrow keys don't work for selection of items

### ISSUE THREAD

**Issue by bithack3r** [hiddify/Hiddify-Manager#3711]
**Describe the bug**
Hiddify Panel (Config=v10.5.73 Panel=v8.8.99) Arrow keys don't work for selection of items. I wanted to get the Admin link but I'm stuck on the first line.

**To Reproduce**
1. After SSH into the server and  the installation scripts are complete in Ubuntu Installation, the Hiddify Panel is shown
2. Try to move the selection down with arrow keys and instead of moving the selection it starts putting the characters ^[[B^[[B^[[B^[[B    (for down arrow)

**Expected behavior**
Moving up and down with arrow keys should move the selection to desired item but it doesn't. For testing purpose, I logged into my raspberry pi and started _raspi-config_ because it's a similar selection box. In RPI, on same terminals, the selection moves without any problem with arrow keys. 

**Screenshots**
Added screenshot.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Terminal, MobaXterm, Powershell all have same error

**Additional context**
I've tried to change the terminal to Xterm256, tried ssh into server with -t as well but the problem persists. 

![image](https://github.com/hiddify/Hiddify-Manager/assets/16251467/a603c437-5ff8-4590-b250-e8bf22fbf20d)

**Comment by soroshzzz26** [comment]
Same issue

**Comment by AmirmahdiAlimadadi** [comment]
Same issue

**Comment by Iam54r1n4** [comment]
Thanks for your report. Update your panel.
