### ISSUE TITLE
مشکل در nginx

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3712]
سلام خسته نباشید
به تازگی روی دو سرور  nginx میره روی حالت failed و پنل بالا نمیاد.حتی با ریستارت سرویس هم اوکی نمیشه.

نسخه سیستم عامل 22.04
نسخه پنل 8.8.99
سی پی یو 1 هسته
رم 1 گیگ
هارد 20 گیگ

**Comment by alirezarah** [comment]
در فایل resolv.conf dns ها رو به به dns گوگل تغییر بده ngnix run میشه

**Comment by Iam54r1n4** [comment]
سلام، پنل رو اپدیت کنید.
