### ISSUE TITLE
مشکل دسترسی به پنل از سیستم دیگر

### ISSUE THREAD

**Issue by aydinfarro** [hiddify/Hiddify-Manager#3713]
خسته نباشید. من میخوام از طریق لبتاب به پنل وصل شم ولی با این گزینه مواجه میشم که ازم پسورد میخواد!؟ چیکار باید بکنم؟![IMG_20240303_031943.jpg](https://github.com/hiddify/Hiddify-Manager/assets/9675771/79700efb-29ce-496e-83df-3f0168b4e335)

**Comment by akonil** [comment]
سلام٬‌ نسخه بتا نصب کردید؟

**Comment by Iam54r1n4** [comment]
به سرور ssh کنید و لینک رو دریافت کنید.
شما فقط لینک رو بدون uuid کپی کردید.

**Comment by aydinfarro** [comment]
بله نسخه بتا بوده فکر کنم

> سلام٬‌ نسخه بتا نصب کردید؟

**Comment by aydinfarro** [comment]
> به سرور ssh کنید و لینک رو دریافت کنید. شما فقط لینک رو بدون uuid کپی کردید.

تشکر. بعد از آپدیت رسمی نسخه 10 رفع شد مشکل.
