### ISSUE TITLE
Worker GRPC Config Problem

### ISSUE THREAD

**Issue by nzrmohammad** [hiddify/Hiddify-Manager#3714]
سلام وقتی طبق آموزش ورکر به پنل اضافه کردم الان چندین نوع کانفیگ داره می سازه که شامل GRPC و WS هستش ولی ورکر خالی که از GRPC پشتیبانی نمیکنه و این کانفیگ ها کار نمیکنن و فقط کانفیگ های ورکر ws دارن کار میکنن امیدوارم تونسته باشم منظورمو برسونم و این مشکل حل کنید

**Comment by akonil** [comment]
درصورتی که دامنه ورکر خودتون رو از نوع `ورکر` انتخاب کنید٬ فقط کانفیگ هایی که توسط ورکر پشتیبانی میشند ساخته میشه

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
