### ISSUE TITLE
如何卸载Hiddify-Manager呢？

### ISSUE THREAD

**Issue by beyondth** [hiddify/Hiddify-Manager#3715]
我是debian11，arm64的，安装了宝塔。
用【bash <(curl i.hiddify.com/release)】这个命令安装了之后，打不开网页，估计是跟宝塔自带的nginx冲突了吧。
现在想要卸载后安装docker版本试试。不知道怎么卸载，每次远程连接时显示的hiddify菜单中选择卸载，好像没成功，每次连接还是显示hiddify菜单

**Comment by akonil** [comment]
You can turn off showing the Hiddify menu in the startup in the `Advanced > Disable`
Suggestion:
After installing the Hiddify, in the Hiddify menu, select `Install or reInstall` again.

**Comment by beyondth** [comment]
> You can turn off showing the Hiddify menu in the startup in the `Advanced > Disable`您可以关闭显示隐藏菜单在启动中的 `Advanced > Disable` Suggestion:  建议： After installing the Hiddify, in the Hiddify menu, select `Install or reInstall` again. 安装Hiddify后，在Hiddify菜单中，再次选择 `Install or reInstall` 。

试过了不行的，应该是在安装时有很多一同安装的组件跟宝塔里边自带的有冲突

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
