### ISSUE TITLE
"domainStrategy": "UseIPv4"

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/Hiddify-Manager#3717]
hi there , pls add a use ipv4 option , so our server can have ipv6 and dont get 403 error in google and some other sites
even when warp is off

```
  "outbounds": [
    {
      "tag": "freedom",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    },

```
i didnt checked beta/dev version of hiddify but in release dont exist

**Comment by akonil** [comment]
you can set ` UseIPv4` in hiddify-manager settings.
![CleanShot 2024-03-05 at 14 56 19@2x](https://github.com/hiddify/Hiddify-Manager/assets/128259098/98e1a77b-fbd9-404f-b441-437f95c02c6f)

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
