### ISSUE TITLE
فعال نشدن hiddify-xray

### ISSUE THREAD

**Issue by ma-rahmati** [hiddify/Hiddify-Manager#3719]
سلام
ورژن ۸.۸.۹۹ hiddify-xray روی حالت activating  میمونه و با ریستارت سرور هم درست نمیشه و هیچکدام از کانفیگها دیگه کار نمیکنن

**Comment by Iam54r1n4** [comment]
سوالتون رو در گروه هیدیفای مطرح کنید:
https://t.me/hiddify_board
