### ISSUE TITLE
مشکل در ایجاد با داکر کامپوز

### ISSUE THREAD

**Issue by fazelit** [hiddify/Hiddify-Manager#3723]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

 => [internal] load .dockerignore                                                              0.0s
 => => transferring context: 59B                                                               0.0s
 => [internal] load build definition from Dockerfile                                           0.0s
 => => transferring dockerfile: 635B                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                1.5s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                  0.0s
 => [1/6] FROM docker.io/library/ubuntu:22.04@sha256:77906da86b60585ce12215807090eb327e7386c8  2.6s
 => => resolve docker.io/library/ubuntu:22.04@sha256:77906da86b60585ce12215807090eb327e7386c8  0.0s
 => => sha256:77906da86b60585ce12215807090eb327e7386c8fafb5402369e421f44eff17 1.13kB / 1.13kB  0.0s
 => => sha256:aa772c98400ef833586d1d517d3e8de670f7e712bf581ce6053165081773259d 424B / 424B     0.0s
 => => sha256:ca2b0f26964cf2e80ba3e084d5983dab293fdb87485dc6445f3f7bbfc89d745 2.30kB / 2.30kB  0.0s
 => => sha256:bccd10f490ab0f3fba61b193d1b80af91b17ca9bdca9768a16ed05ce16552 29.54MB / 29.54MB  1.2s
 => => extracting sha256:bccd10f490ab0f3fba61b193d1b80af91b17ca9bdca9768a16ed05ce16552fcb      1.0s
 => [internal] load build context                                                              0.2s
 => => transferring context: 6.23MB                                                            0.2s
 => [2/6] RUN apt-get update && apt-get install -y whiptail apt-utils curl sudo systemd pyth  26.9s
 => [3/6] WORKDIR /opt/hiddify-manager/                                                        0.1s
 => [4/6] COPY . .                                                                             0.2s
 => ERROR [5/6] RUN bash install.sh install-docker                                             0.6s
------
 > [5/6] RUN bash install.sh install-docker:
#0 0.560
#0 0.560
#0 0.560
#0 0.561 ./common/utils.sh: line 112: pip: command not found
#0 0.575 Package cli_progress==1.7.0 is not installed.
#0 0.576 ./common/utils.sh: line 123: pip: command not found
#0 0.576 ./common/utils.sh: line 348: cli_progress: command not found
#0 0.577
#0 0.577
#0 0.577
root@ubuntu:~/docker/hiddify/Hiddify-Manager# ll.sh install-docker" did not complete success

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
