### ISSUE TITLE
sorry for briefings! / just ERR

### ISSUE THREAD

**Issue by MajidRB** [hiddify/Hiddify-Manager#3727]
▒
▒│ NEEDRESTART-VER: 3.5                                                      │ ▒
▒│ NEEDRESTART-KCUR: 5.15.0-91-generic                                       │ ▒
▒│ NEEDRESTART-KEXP: 5.15.0-97-generic                                       │ ▒
▒│ NEEDRESTART-KSTA: 3                                                       │ ▒
▒│ NEEDRESTART-SVC: dbus.service                                             │ ▒
▒│ NEEDRESTART-SVC: getty@tty1.service                                       │ ▒
▒│ NEEDRESTART-SVC: networkd-dispatcher.service                              │ ▒
▒│ NEEDRESTART-SVC: systemd-logind.service                                   │ ▒
▒│ NEEDRESTART-SVC: unattended-upgrades.service                              │ ▒
▒│ Traceback (most recent call last):                                        │ ▒
▒│   File "<string>", line 1, in <module>                                    │ ▒
▒│ ModuleNotFoundError: No module named 'hiddifypanel'                       │ ▒
▒│ cat: /VERSION: No such file or directory                                  │ ▒
▒│ you can not install release version 8 using this script

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
