### ISSUE TITLE
when i want to use panel, asks me for a Secret code

### ISSUE THREAD

**Issue by danyalfa79** [hiddify/Hiddify-Manager#3729]
Hello

i upgraded panel from 8.8.94 to 10.10.12 & when i want to use panel it asks me for some "Secret Code"
how do i find that?? i couldn't see such thing anywhere in panel nor in linux

**Comment by Iam54r1n4** [comment]
The secret code is admin's uuid. you can find it by looking at the admin link:
https://domain.com/PROXY_PATH/UUID/
You can copy that UUID and enter in the field box to login.

Easy way:
Do ssh to your server get your admin link.
