### ISSUE TITLE
no add button in modifying proxies v10.10.12

### ISSUE THREAD

**Issue by Ariannetflix** [hiddify/Hiddify-Manager#3730]
**Describe the bug**
there is no way to add a new proxy configuration in modifying proxies and i just deleted all of them to add my own :)
**To Reproduce**
1. Go to 'setting/proxies/modifying proxies '

<img width="1344" alt="Screenshot 2024-03-07 at 6 46 03 PM" src="https://github.com/hiddify/Hiddify-Manager/assets/158844334/fb5a6528-e5aa-4f6e-b772-14f347c9cf64">

**Comment by Iam54r1n4** [comment]
Update
