### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by shahinfard93** [hiddify/Hiddify-Manager#3731]
**Describe the bug**
While I try to update the panel, I get the error down in the picture.

I use Ubuntu 22.

![IMG_20240307_184946](https://github.com/hiddify/Hiddify-Manager/assets/41050901/11309d6a-0042-4828-ad7f-0ea10c0fd44f)

**Comment by Iam54r1n4** [comment]
Hi,
Get a backup and reinstall release version.
