### ISSUE TITLE
امکان دسترسی غیر مجاز

### ISSUE THREAD

**Issue by travian1** [hiddify/Hiddify-Manager#3733]
اگر بعضی نرم افزارها امکان دسترسی به تاریخچه‌ی مرورگر ادمین رو داشته باشن، امکان دسترسی غیرمجاز به پنل ممکن نمیشه؟

**Comment by hiddify-com** [comment]
توی ورژن 10 این تاریخچه لاگ نمیشه

ولی جهت بالا بردن امنیت میتونید secret کد را دستی وارد کنید  و فقط آدرس 
domain.com/admin-path
را وارد کنید
