### ISSUE TITLE
BUG: Warp is not working! ❗️❗️

### ISSUE THREAD

**Issue by amir-rz** [hiddify/Hiddify-Manager#3734]
# Bug/Feature: BUG: WARP is not working!
**Description**:    تو آپدیت جدید وارپ دیگه برام کار نمیکنه!
**Error:**
```
===install.sh other/warp
===run.sh other/warp
Checking WARP ...
Generating WARP config...
Removing IPV6 from WARP...
Starting WARP.... checking real connectivitiy
WARP is not working!
Checking real connectivitiy again!
WARP is not working!
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
Generating WARP config...
Removing IPV6 from WARP...
Starting WARP.... checking real connectivitiy
WARP is not working!
Checking real connectivitiy again!
WARP is not working!
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
Generating WARP config...
Removing IPV6 from WARP...
Starting WARP.... checking real connectivitiy
WARP is not working!
Checking real connectivitiy again!
WARP is not working!
!!!!!!!!!!!!!!! WARP ERROR
```

- [x] وارپ معمولی امتحان شد
- [x] وارپ پلاس امتحان شد.
- [x] وارپ پلاس با کلید های مختلف امتحان شد.

## Details:
**Hiddify Version**: 10.10.13
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by amir-rz** [comment]
> # Bug/Feature: BUG: WARP is not working!
> **Description**: تو آپدیت جدید وارپ دیگه برام کار نمیکنه! **Error:**
> 
> ```
> ===install.sh other/warp
> ===run.sh other/warp
> Checking WARP ...
> Generating WARP config...
> Removing IPV6 from WARP...
> Starting WARP.... checking real connectivitiy
> WARP is not working!
> Checking real connectivitiy again!
> WARP is not working!
> Checking WARP ...
> mv: cannot stat 'wgcf-account.toml': No such file or directory
> Generating WARP config...
> Removing IPV6 from WARP...
> Starting WARP.... checking real connectivitiy
> WARP is not working!
> Checking real connectivitiy again!
> WARP is not working!
> Checking WARP ...
> mv: cannot stat 'wgcf-account.toml': No such file or directory
> Generating WARP config...
> Removing IPV6 from WARP...
> Starting WARP.... checking real connectivitiy
> WARP is not working!
> Checking real connectivitiy again!
> WARP is not working!
> !!!!!!!!!!!!!!! WARP ERROR
> ```
> 
> * [x]  وارپ معمولی امتحان شد
> * [x]  وارپ پلاس امتحان شد.
> * [x]  وارپ پلاس با کلید های مختلف امتحان شد.
> 
> ## Details:
> **Hiddify Version**: 10.10.13 **Python Version**: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] **OS**: Linux-5.15.0-97-generic-x86_64-with-glibc2.35 **User Agent**: Unknown

Actions made:
- [ ] Server restarted
- [ ] Panel reinstalled

**Comment by amir-rz** [comment]
yes, I checked the project and tried to activate and start warp+ on the server manually, it seems to be working after you restart the server but after a few minutes, it automatically crashes.

I couldn't find the reason why but as far as I could understand it has to do something with the configurations and the apply_config part of Hiddify

**Comment by nullname79** [comment]
فایروال رو خاموش کن دوباره امتحان کن!

**Comment by amir-rz** [comment]
بازم نمیشه

**Comment by amir-rz** [comment]
Before I restored my backup I tried Warp and it worked, but yeah, when you restore your backups it won't work anymore.

But if you restore your backup with **users** and **domains** checked, then it won't be a problem, right?
Or do I still need to give them new sub links?

**Comment by amir-rz** [comment]
Yes its 

> I finally fixed this problem through these steps (client's links will be changed and all of them should get the new subscription links):
> 
> 1. Take a backup.
> 2. Rebuild the ubuntu 22.
> 3. Reinstall the Hiddify Manager via bash command
> 
> ```
> bash <(curl i.hiddify.com/release)
> ```
> 
> 4. Restore your backup but only check the users and domains.
> 5. Set the settings you had manually.
> 6. Warp should work fine now!

Yes, now it works, the only downside is that all the subscription links are now changed and that's the worse thing that could happen.

**Comment by amir-rz** [comment]
> I finally fixed this problem through these steps (client's links will be changed and all of them should get the new subscription links):
> 
> 1. Take a backup.
> 2. Rebuild the ubuntu 22.
> 3. Reinstall the Hiddify Manager via bash command
> 
> ```
> bash <(curl i.hiddify.com/release)
> ```
> 
> 4. Restore your backup but only have the **users** and **domains** checked.
> 5. Set the settings you had manually.
> 6. Warp should work fine now!

Temporary solution thanks to @mrgeex
