### ISSUE TITLE
چند باگ کوچک

### ISSUE THREAD

**Issue by ojooubeh** [hiddify/Hiddify-Manager#3735]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.12
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

مثل نسخه های قبلی نیست و امکان ایجاد کانفیگ شخصی و یا ویرایش کانفیگ های موجود وجود نداره  فقط اسمشون ویرایش میشه و موضوع دووم این که کانفیگی که در نسخه قبلب کار میکرد تو این نسخه به هیچ وجه پینگ نمیده مثل tls ws cdn

**Comment by Iam54r1n4** [comment]
لطفا پنل رو اپدیت و دوباره تست کنید.
(فعلا ایشو بسته میشه)
