### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by ojooubeh** [hiddify/Hiddify-Manager#3738]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.14
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

با فعال کردن HTTPUpgrade بعد از مدتی تمام کانفیگ ها بجز ssh از کار می افته

**Comment by Iam54r1n4** [comment]
Thanks for your report. update your panel and test again.
