### ISSUE TITLE
باگ پنل هیدیفای

### ISSUE THREAD

**Issue by peter1982710** [hiddify/Hiddify-Manager#3739]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

نشان ندادن گیگهای مصرفی روزانه و ماهانه و کل

**Comment by Hamedb91** [comment]
منم همین مشکلو دارم

**Comment by peter1982710** [comment]
در ورژن ۱۰.۱۰.۲۰ عدم برگرداندن فایل پشتیبان قبول نمیکنه

**Comment by Iam54r1n4** [comment]
لطفا به اخرین ورژن اپدیت کنید. مشکل حل شده.
