### ISSUE TITLE
there is something error while using trojan

### ISSUE THREAD

**Issue by Dzulqarnaenzulfa** [hiddify/Hiddify-Manager#3740]
# Bug/Feature:
**Description**:     when i using new update i use trojan ws but there is something error like when i open tiktok is disconnect

## Details:
**Hiddify Version**: 10.10.16
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
