### ISSUE TITLE
قطعی

### ISSUE THREAD

**Issue by themilan1** [hiddify/Hiddify-Manager#3743]
# Bug/Feature:
**Description**:     دامنه ها سرتیفیکیت نمیگیرن

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-94-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
به اخرین ورژن اپدیت کنید. اگر مشکل وجود داشت ایشو رو باز کنید.
