### ISSUE TITLE
Domain Fronting

### ISSUE THREAD

**Issue by bahrammm1995** [hiddify/Hiddify-Manager#3745]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

وقتی چنتا دامنه میزارم توی کادر Domain Fronting توی کانفیگ همه رو میاره، یعنی اینکه جدا نمیکنه هر دفه یکی رو خودش جای گذاری کنه التبه با همون کاما جدا هم میکنم ها ولی بازم نمیشه

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
