### ISSUE TITLE
It is not possible to add a new domain

### ISSUE THREAD

**Issue by miladshakerdn** [hiddify/Hiddify-Manager#3747]
# Bug:
**Description**:     It is not possible to add a new domain on Cloudflare

Error message:
نمی توان به Cloudflare متصل شد. DNS name is invalid.

## Details:
**Hiddify Version**: 10.10.16
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-60-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by iStifix** [comment]
Turn off firewall in settings, its helps

**Comment by miladshakerdn** [comment]
> Turn off firewall in settings, it helps

It's already turn off

**Comment by moli1369** [comment]
api ورکر رو از توی پنل هیدی  حذف کن مشکل اینه که پنل نمیتونه با ورکر ارتباط برقرار کنه

**Comment by drupalshift** [comment]
> api ورکر رو از توی پنل هیدی حذف کن مشکل اینه که پنل نمیتونه با ورکر ارتباط برقرار کنه

میشه بفرمایید چطور اینکار رو باید کرد چون منم درگیر این مشکل شدم

**Comment by moli1369** [comment]
> > api ورکر رو از توی پنل هیدی حذف کن مشکل اینه که پنل نمیتونه با ورکر ارتباط برقرار کنه
> 
> میشه بفرمایید چطور اینکار رو باید کرد چون منم درگیر این مشکل شدم 
> 
> @miladshakerdn @moli1369 

حتما دوتا موضوع رو انجام بده یکی اینکه تو کلود فلر اومدی ورکر ساختی و api رو به پنل هیدی فای دادی توی پنل هیدی فای توی قسمت تنظیمات تنظیمات خیلی پیشرفته کلید کلود فلر اگر داره پاکش کن اپدیت کن و بعد از اپدیت یکبار سرور رو ریبوت کن تمومه  اگه توی کلودفلر هم پاک نکردی نکردی مهم نیست ولی توی پنل هیدیفای حتما پاک کن.

**Comment by miladshakerdn** [comment]
> > > api ورکر رو از توی پنل هیدی حذف کن مشکل اینه که پنل نمیتونه با ورکر ارتباط برقرار کنه
> > 
> > 
> > میشه بفرمایید چطور اینکار رو باید کرد چون منم درگیر این مشکل شدم
> > @miladshakerdn @moli1369
> 
> حتما دوتا موضوع رو انجام بده یکی اینکه تو کلود فلر اومدی ورکر ساختی و api رو به پنل هیدی فای دادی توی پنل هیدی فای توی قسمت تنظیمات تنظیمات خیلی پیشرفته کلید کلود فلر اگر داره پاکش کن اپدیت کن و بعد از اپدیت یکبار سرور رو ریبوت کن تمومه اگه توی کلودفلر هم پاک نکردی نکردی مهم نیست ولی توی پنل هیدیفای حتما پاک کن.

![image](https://github.com/hiddify/Hiddify-Manager/assets/30466140/8766396a-7ff3-4c48-a828-0c174f528c40)
برای من با حذف کلید توسعه کلودفلر مشکلش حل شد

**Comment by moli1369** [comment]
> > > > api ورکر رو از توی پنل هیدی حذف کن مشکل اینه که پنل نمیتونه با ورکر ارتباط برقرار کنه
> > > 
> > > 
> > > میشه بفرمایید چطور اینکار رو باید کرد چون منم درگیر این مشکل شدم
> > > @miladshakerdn @moli1369
> > 
> > حتما دوتا موضوع رو انجام بده یکی اینکه تو کلود فلر اومدی ورکر ساختی و api رو به پنل هیدی فای دادی توی پنل هیدی فای توی قسمت تنظیمات تنظیمات خیلی پیشرفته کلید کلود فلر اگر داره پاکش کن اپدیت کن و بعد از اپدیت یکبار سرور رو ریبوت کن تمومه اگه توی کلودفلر هم پاک نکردی نکردی مهم نیست ولی توی پنل هیدیفای حتما پاک کن.
> 
> ![image](https://github.com/hiddify/Hiddify-Manager/assets/30466140/8766396a-7ff3-4c48-a828-0c174f528c40)
> برای من با حذف کلید توسعه کلودفلر مشکلش حل شد

دقیقا مشکل همینه که نمیتونه ارتباط بگیره و حذفش کنی درست میشه
