### ISSUE TITLE
عدم ساخت پروتکل جدید

### ISSUE THREAD

**Issue by roboticman2007** [hiddify/Hiddify-Manager#3748]
درود به شما . 
در قسمت پروکسی نمیتوان پروتکل جدید وارد کرد .
![photo_2024-03-08_13-33-32](https://github.com/hiddify/Hiddify-Manager/assets/159495742/b34748fe-59a9-4843-92c3-30f00d328866)

**Comment by moli1369** [comment]
نمیتونی پروکسی جدید اضافه کنی فقط میتونی حذف فعال یا غیر فعال کنی
