### ISSUE TITLE
Bug in API

### ISSUE THREAD

**Issue by hermavpn** [hiddify/Hiddify-Manager#3749]
# Bug:
**Description**:    in Delete API show me error 403
![image](https://github.com/hiddify/Hiddify-Manager/assets/141176675/11450fda-a0c0-4387-b1d3-fa78c94961b1)

also in API docs requests not working after i test some request i understand you need to set session until request send.

also in PUT method of user cant update user information

## Details:
**Hiddify Version**: 10.10.16
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
شما با ادمینی در حال کار با API ها هستید که اون ادمین به اون کاربر خاص دسترسی نداره.
برای مثال ادمین B که روی حالت admin هست به کاربر ادمین A که سوپر ادمین هست دسترسی نداره.
