### ISSUE TITLE
Config names are truncated

### ISSUE THREAD

**Issue by someonemax** [hiddify/Hiddify-Manager#3752]
**Describe the bug**
Config names are truncated. Making it difficult to know which config is which.

**To Reproduce**
1. Open user link
2. Go to "All Configs page"

**Expected behavior**
Config names should be shown in full, even if that means having a horizontal scroll bar on smaller displays.

**Screenshots**
![Untitled](https://github.com/hiddify/Hiddify-Manager/assets/76533230/05bd6bb1-8ce3-47c1-a1db-a0ad06e9126a)

**Additional context**
For example in the link above the last 4 config names are truncated and not shown in full.
The two configs that say "Subscripti..." are basically indistinguishable. 
(I removed the domains and IP addresses from the screenshot above myself, for obvious reasons)

**Comment by Iam54r1n4** [comment]
Thanks for your report. We will check it.

**Comment by hiddify-com** [comment]
fixed
