### ISSUE TITLE
Reality doesn't work on singbox core after update to version 10, but works on xray core

### ISSUE THREAD

**Issue by someonemax** [hiddify/Hiddify-Manager#3753]
**Describe the bug**
My reality configs (GRPC) worked just fine on singbox core before updating to version 10.
Now they do not work on singbox core, but if I change the core from singbox to xray core in the panel, they work just fine.

**To Reproduce**
1. Make a GRPC reality config with forced IP.
2. Set the core to singbox in the panel settings.
3. Apply config
4. Try to connect to the reality config (won't work)
5. Set the core to xray in the panel settings.
6. Apply config
7. Try to connect to the reality config (it will work)

**Expected behavior**
Reality should work on singbox. 

**Screenshots**

**Additional context**

**Comment by Iam54r1n4** [comment]
Fixed in latest version.
Thanks for your report.
