### ISSUE TITLE
Captcha Error on Installation

### ISSUE THREAD

**Issue by Moamethic** [hiddify/Hiddify-Manager#3754]
Hi
I installed the latest version and everything was fine, except when I open my IP address in the browser to do initial setup I get this:
![FireShot Capture 003 - Visitor anti-robot validation - 91 107 133 105](https://github.com/hiddify/Hiddify-Manager/assets/16816836/a6a7fea3-f404-449a-807e-102b01a9b49f)

At this point also everything is just fine except there is no any captcha to solve, I don't have any idea if this page made by you or Hetzner itself made it for all web applications running on its servers?

**Comment by Iam54r1n4** [comment]
It's probably your decoy website. the panel installed incomplete. please rebuild your server and install latest version of Hiddify.
(The issue will be close)
