### ISSUE TITLE
Bug: After automatic Upgrade to the latest (10.10.17)

### ISSUE THREAD

**Issue by Sooshka-X** [hiddify/Hiddify-Manager#3755]
# Bug/Feature:
**Description**:     Bug: Upgrade to the latest (10.10.17)
After the automatic Upgrade to the latest (10.10.17), all my configs won't work.
I Rebuilt the server installed it again and restored backup. the result is the same.
Please help.
Thank you.
## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Ask these type of questions in The hiddify Telegram group.
Regards.
