### ISSUE TITLE
مشکل در ریلیتی grpc

### ISSUE THREAD

**Issue by bahrammm1995** [hiddify/Hiddify-Manager#3757]
# Bug/Feature: Bug
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

وقتی لینک ساب میدی به اپ هیدیفای ریلیتی های grpc کار نمیکنن، در صورتی که توی برنامه های دیگه مشکلی نیست

**Comment by Iam54r1n4** [comment]
مشکل در تنها در صورتی وجود داشت که core روی singbox میبود.
در اخرین ورژن مشکل حل شده.
