### ISSUE TITLE
سایت سابسکریپشن توسط سایت PHP بعد از آپدیت به ورژن ۱۰ کلا از کار افتاده.

### ISSUE THREAD

**Issue by dora310** [hiddify/Hiddify-Manager#3758]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
سلام 
بعد از به روزرسانی به ورژن ۱۰ سایت سابسکریپشن که با سایت PHP ساخته شده بود از کار افتاد.

**Comment by alirahimi818** [comment]
میتونید از توضیحات زیر استفاده کنید بصورت موقت:

[https://github.com/hiddify/Hiddify-Manager/discussions/689#discussioncomment-8711390](https://github.com/hiddify/Hiddify-Manager/discussions/689#discussioncomment-8711390)

**Comment by dora310** [comment]
ممنون از پاسخ شما متاسفانه کد کار نکرد و صفحه کاربر بصورت صحفه پر از کد نشون میده. 
نمیدونم کد جاییش نقص داره من تمام مراحل را که ذکر شده بود انجام دادم و تعقییرات را انجام دادم چندین بار ولی بازم کار نکرد.

**Comment by alirahimi818** [comment]
> ممنون از پاسخ شما متاسفانه کد کار نکرد و صفحه کاربر بصورت صفحه پر از کد نشون داده میشه. نمیدونم کد جاییش نقص داره، من تمام مراحل را که ذکر شده بود انجام دادم و تغییرات را هم انجام دادم چندین بار ولی بازم کار نکرد.

اون کد ها یی که مشاهده کردید همه ی کانفیگ ها هستش و برای استفاده کافیه لینک اون صفحه رو به عنوان لینک ساب به کاربر بدید
من این روش رو بصورت موقت نوشتم تا خود هیدیفای اون بخش رو درست کنه. توی این روش صفحه جدید کاربری که میتونید qr کد بگیرید و... نمایش داده نمیشه، مستقیم همه ی کانفیگ هارو برمیگردونه

**Comment by dora310** [comment]
ممنونم از پاسخ شما وقتی که گذاشتید. من مجدد امتحان کردم وی باز هم اررور میده.

هم برای آپدیت کانفیگ قبلی و هم برای اضافه کردن به اپ. 

باز هم ممنونم از شما. 
اگه بتونید کمک کنید خیلی لطف میکنید. 
من چند تا عکس هم اضافه کردم. 
ممنون. 

 ![image](https://github.com/hiddify/Hiddify-Manager/assets/685224/5aedfa77-7a20-4b0a-a47b-25e76fca6e3a)

![image](https://github.com/hiddify/Hiddify-Manager/assets/685224/bbb63393-4724-43d2-a8b5-1d1000bd8359)

**Comment by alirahimi818** [comment]
احتمالا مشکل شما در کانفیگ خود پنل هستش

![2024-03-10_14-25-57](https://github.com/hiddify/Hiddify-Manager/assets/20303078/60eea0e1-915b-41b4-b209-41ec5b34cb51)

شما آدرس ساب اصلی رو باید در کد php قرار بدید تا اطلاعات کانفیگ ها رو از لینک ساب اصلی دریافت کنه
همونطور که گفتم این یه روش موقت برای این کاره و ممکنه مشکلاتی داشته باشه و نیاز باشه که تغییراتی اعمال کنید.

**Comment by dora310** [comment]
سلام علی عزیز 
ممنونم از شما 
من عکس پنل و کد را گذاشتم لطف میکنید یه نگاه کنید و راهنمایی بفرمایید که اشتباه من کجاست. 

![image](https://github.com/hiddify/Hiddify-Manager/assets/685224/7c03d1ee-d8e9-40d3-a9bc-6c452b86278c)

![image](https://github.com/hiddify/Hiddify-Manager/assets/685224/4874c47f-3155-4ba0-81d4-fd298dbeb7bc)

**Comment by alirahimi818** [comment]
شما باید آدرس سرور رو بصورت کامل در کد php وارد کنید (https://)
```
$server_domain="https://XXXXXX";
```

مشکل دیگه ای نمیبینم
حالا وقتی برای هر کاربر روی دکمه sub_php در بخش کاربرها کلیک کنید، لینک ساب با همه ی کانفیگ های Subscription بهتون نمایش میده. قبلی ها هم اتوماتیک باید تبدیل بشن

**Comment by dora310** [comment]
علی جان 
خیلی ممنون که وقت گذاشتی. 
لطف کردی. 
متاسفانه https را هم اضافه کردم به اسم سرور ولی باز کار نکرد. 
فکر کنم باید منتظر هیدیفای باشم تا این مشکل را حل کنه. 
همه ی یوزرهام قطع شدن. 😞

**Comment by dora310** [comment]
با این کد کار کرد. 


<?php

// Define the server domain
$serverDomain = "https://YOUR_SUBSCRIPTION_DOMAIN";

// Modify the URI
$uri = $_SERVER['REQUEST_URI'];
$uri = str_replace('OLD_PATH', 'NEW_PATH', $uri); 
$uri = str_replace('all.txt', 'sub/', $uri); 
if (strpos($uri, '/sub') === false) {
    $uri .= 'sub/';
}
$url = $serverDomain . $uri;

// Initialize cURL session
$ch = curl_init();

// Set cURL options
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true); // Enable SSL verification
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2); // Enable SSL verification

// Execute the cURL request
$response = curl_exec($ch);

// Check for cURL errors
if (curl_errno($ch)) {
    $error_message = curl_error($ch);
    error_log("Curl error: $error_message");
    http_response_code(500); // Internal Server Error
    echo "Failed to fetch content: $error_message";
    exit;
}

// Close cURL session
curl_close($ch);

// Set headers
foreach ($http_response_header as $header) {
    header($header);
}

// Output the response
echo $response;

?>

**Comment by Iam54r1n4** [comment]
فعلا این ایشو بسته میشه.

**Comment by cycyfyyf** [comment]
سلام من چجوری کانفینگ درست کنم میشه یکی راهنمایی کنه ممنون
