### ISSUE TITLE
باگ در نمایش لینک پنل و آپدیت ساب ها

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3764]
💠طریقه نصب: نصب مستقیم

💠 وضعیت وارپ:غیرفعال
💠وضعیت فایروال:غیرفعال
💠ورژن منیجر: 10.10.17
💠نوع کانفیگ:vmess tcp http مستقیم و ریلی هردو با ipv6 و cdn
💠 ورژن اوبونتو :22.04
💠نوع CPU سرور:  ×86_64 amd ryzen 3900x

بعد از تغییرات در پنل و اپلای کانفیگ و حتی ریستارت پنل باز نمیشه و موقع گرفتن لینک پنل از منوی ssh هیچ لینکی نمیده. بعلاوه امکان آپدیت سابسکریپشن ها هم نیست با ریبوت سرور مشکل حل میشه و موقتا لینک پنل رو میده ولی باز با اپلای کانفیگ مشکل تکرار میشه و نیاز به ریبوت هست

**Comment by Iam54r1n4** [comment]
درود، بنظر پنل رو ناقص نصب کردید. لطفا سرور رو ری بیلد کنید و اخرین ورژن هیدیفای رو نصب کنید.
(ایشو فعلا بسته میشه)
