### ISSUE TITLE
مشکل در ثبت دامنه در نسخه ۱۰.۱۰.۱۷

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#3770]
مشکل در ثبت دامنه جدید در نسخه ۱۰.۱۰.۱۷ 
نمیتوان به Cloudflare متصل شد. DNS name is invalid

**Comment by A5DkjGQUZx** [comment]
Same here:
https://github.com/hiddify/Hiddify-Manager/issues/3791
