### ISSUE TITLE
#2 : After automatic Upgrade to the latest (10.10.17)

### ISSUE THREAD

**Issue by Sooshka-X** [hiddify/Hiddify-Manager#3771]
Second Bug:
After automatic Upgrade to the latest (10.10.17):
one workers and one reallity works but, it shows my real ip.

Regards,

**Comment by Eisahastam** [comment]
> Second Bug:
> After automatic Upgrade to the latest (10.10.17):
> one workers and one reallity works but, it shows my real ip.
> 
> Regards,

**Comment by Iam54r1n4** [comment]
Please describe the problem completely
