### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by aminsn95** [hiddify/Hiddify-Manager#3775]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by aminsn95** [comment]
سلام
زمانی فایروال روشن باشه کانفیگ های ip v6 cdn CF کلا از کار می‌افتن.

**Comment by Iam54r1n4** [comment]
در حال بررسی هست. فعلا این issue بسته میشه.
