### ISSUE TITLE
Update problems 

### ISSUE THREAD

**Issue by amir-ardalanuk** [hiddify/Hiddify-Manager#3783]
**Describe the bug**
I'm trying to update my panel from admin dialog on server side

**To Reproduce**
N/A

**Expected behavior**
Update the panel when trying to upgrade 

**Screenshots**
<img width="641" alt="image" src="https://github.com/hiddify/Hiddify-Manager/assets/12419118/baef952d-a8ed-4e0b-bec9-9a1bb5c0e715">
<img width="291" alt="image" src="https://github.com/hiddify/Hiddify-Manager/assets/12419118/87db1033-33f5-4be3-980f-006676abdcb6">
<img width="530" alt="image" src="https://github.com/hiddify/Hiddify-Manager/assets/12419118/a01e2756-4e86-4bbe-9aa6-984503a64cee">

**Desktop (please complete the following information):**
 - OS: Linux 20
 - Browser Chrome
 - Version 8.8.94

**Smartphone (please complete the following information):**
N/A

**Comment by Asofwar** [comment]
use downgrade function , after use upgrade
