### ISSUE TITLE
کیل سویچ

### ISSUE THREAD

**Issue by parsasariri** [hiddify/Hiddify-Manager#3784]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
سلام خسته نباشید میخواستم بدونم امکانش هست گزینه ی کیل سویچ هم به هدیفای اضافه کنید؟؟

**Comment by litoosh13** [comment]
هیدیفای نکست این قابلیت رو داره:
hiddify.com/app
hiddify.com/fa/app
