### ISSUE TITLE
stash , shadowrocket وارد نشدن کد به صورت اتوماتیک در برنامه 

### ISSUE THREAD

**Issue by Afx110** [hiddify/Hiddify-Manager#3785]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

در این نسخه جدید کدها به برنامه وارد نمی‌شه لطفاً بررسی کنید

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
