### ISSUE TITLE
حجم مصرفی اصلا کم نمیشه و آخرین اتصال کار نمیکنه

### ISSUE THREAD

**Issue by Hamedb91** [hiddify/Hiddify-Manager#3788]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.17
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.2.0-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Hamedb91** [comment]
دوستان کسی میتونه این فایل ورژن 8 رو بهم بده ؟
    /opt/hiddify-manager/hiddify-panel/hiddify_usages.json
فکر میکنم مشکل همینه

**Comment by Iam54r1n4** [comment]
لطفا به اخرین ورژن اپدیت کنید، این مشکل برطرف شده.
