### ISSUE TITLE
ipv6 setting

### ISSUE THREAD

**Issue by ghost** [hiddify/Hiddify-Manager#3790]
در بخش تنظیمات گزینه فقط ipv4 فعال شده . اما بعد restart یا apply config  
ipv6 همچنان فعال هست 

version 10.10.17

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
