### ISSUE TITLE
غیر فعال شدن hiddify-haproxy, hiddify-panel, hiddify-xray

### ISSUE THREAD

**Issue by saeedhadinejad** [hiddify/Hiddify-Manager#3796]
سلام دوستان مشکل جدید پیش آمده روی آخرین آپدیت
![hiddify](https://github.com/hiddify/Hiddify-Manager/assets/145412836/0ee54f75-87ff-4474-a480-d967594cf74b)
کسی میتونه راهنمایی کنه
سیستم ری استارت شده
مجددا آپدیت شده
ولی تغییری ایجاد نشده

**Comment by Iam54r1n4** [comment]
سلام این مساله در حال بررسی هست.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
