### ISSUE TITLE
reality ipv6

### ISSUE THREAD

**Issue by rezakeshavarza** [hiddify/Hiddify-Manager#3797]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.19
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown
سلام چرا تو ورژن ۱۰ ایپی ورژن ۶ کار نمیکنه برای ریالیتی؟

**Comment by ReturnFI** [comment]
سلام.
به آخرین نسخه ریلیز آپدیت کنید.
برای جوابگوی بهتر سوالات خودتون در گروه [تلگرامی هیدیفای](https://t.me/hiddify) مطرح بفرمایید.
