### ISSUE TITLE
عدم پشتیبان گیری از طریق ربات تلگرام

### ISSUE THREAD

**Issue by matinsajadii** [hiddify/Hiddify-Manager#3800]
# Bug/Feature:
**Description**: 
پنل از ورژن 8 به ورژن 10.10.17 اپدیت شد و مشکلی که داره پشتیبان گیری نمیتونه از طریق ربات انجام بده و  توکن api ربات تلگرام رو هم درست وارد کردم و حتی توکن رو هم عوض کردم گفتم شاید مشکل از توکن باشه ولی الان پنل به نسخه 10.10.19 ارتقا یافته بازم این مشکل همچنان وجود داره و بیان اینن مشکل صرفا برای اطلاع رسانی و رفع مشکل هست ممنون زحماتی که میکشید 
سپاسگزارم

## Details:
**Hiddify Version**: 10.10.19
**Python Version**:  3.10.12
**OS**:              ubuntu 22.04
**User Agent**:      admin

**Comment by Iam54r1n4** [comment]
ممنون بابت گزارش. مشکل حل شده لطفا پنل رو اپدیت کنید.
