### ISSUE TITLE
Bug with not accepting valid internationalized domain name (IDN) or its'  ASCII strings using Punycode transcription

### ISSUE THREAD

**Issue by A5DkjGQUZx** [hiddify/Hiddify-Manager#3802]
the subject line is pretty self explanatory...
https://en.wikipedia.org/wiki/Internationalized_domain_name

![image](https://github.com/hiddify/Hiddify-Manager/assets/25065763/0835d30a-b0ac-45a5-bfab-08718b9f7658)

![image](https://github.com/hiddify/Hiddify-Manager/assets/25065763/cea8d228-0966-4e54-81de-1d0e50f4c074)

**Comment by litoosh13** [comment]
we are on it
