### ISSUE TITLE
بروز نشدن زمان و حجم باقیمانده 

### ISSUE THREAD

**Issue by mehdi-kiyani** [hiddify/Hiddify-Manager#3804]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.20
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-43-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Morteza1615** [comment]
کسی جواب نمیده

**Comment by Iam54r1n4** [comment]
Please Update your panel to latest version. it's been fixed.
