### ISSUE TITLE
Cloudflare DNS name is invalid.

### ISSUE THREAD

**Issue by presolve0** [hiddify/Hiddify-Manager#3807]
#Bug:
**Description**: Cloudflare DNS name is invalid.

## Details:
**Hiddify Version**: 10.10.20
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35

فرقی نمیکنه فایروال خاموش باشه یا روشن، دامنه فیلتر باشه یا فیلتر نباشه یا پروکسی مود باشه یا direct،همه جور دامنه ای این ارورو میده حتی وقتی میخوای نام مستعار دامنرو عوض کنی این ارورو میده؟ نمیخواید این مشکل رو حل کنید؟؟؟؟

**Comment by freehorn3000** [comment]
سلام وقت بخیر 
با تشکر فراوان 
ایراد برطرف شد برای من
