### ISSUE TITLE
Sing-Box application error!

### ISSUE THREAD

**Issue by momalekiii** [hiddify/Hiddify-Manager#3808]
Sing-Box Application Can't detect the sublink which generates from Hiddify manager or Users Panel!

Desktop:
 - Device: [MacBook Air M1]
 - OS: [MacOs 14.3.1]
 - Browser [safari]
 - Version [-]

SmartPhone:
 - Device: [iPhone 12Pro]
 - OS: [iOS 17.4]
 - Browser [safari]
 - Version [-]

Panel Version : [Release, V10.10.20]

**Comment by Iam54r1n4** [comment]
This issue will be close due insufficient information.
