### ISSUE TITLE
ShadowsocksR

### ISSUE THREAD

**Issue by vagabund89** [hiddify/Hiddify-Manager#3810]
Hello.
Is it possible to add 443 on one port so that users have different passwords?

**Comment by hiddify-com** [comment]
SSR support SNI ?

**Comment by vagabund89** [comment]
https://armazopu.github.io/install-shadowsocksr-teddysun-script.html

**Comment by vagabund89** [comment]
so that users have different passwords on the same port

**Comment by ReturnFI** [comment]
Hi,
Yes it's possible.
