### ISSUE TITLE
نشون ندادن حجم مصرفی و کاربران انلاین

### ISSUE THREAD

**Issue by Morteza1615** [hiddify/Hiddify-Manager#3811]
نشون ندادن حجم مصرفی و کاربران انلاین

**Comment by Hamedb91** [comment]
مشکل منم هست از وقتی ورژن 10 اومده حجم کاربرا حساب نمیشه همشون نامحدود شدن کسی هم جواب نمیده :(

**Comment by Iam54r1n4** [comment]
لطفا پنل تون رو به اخرین ورژن هیدیفای اپدیت کنید. حل شده.
