### ISSUE TITLE
سایت php و عدم وجود کانفیگ

### ISSUE THREAD

**Issue by alirezaturkoglan** [hiddify/Hiddify-Manager#3814]
لینک سابسکرایب php کار نمیکنه(ارور 500 دیتابیس)
کانفیگ tls WS CDN vless نیست
Hiddify 10.10.20
OS : Ubuntu 22.04.2 LTS
 Arch  : x86_64 (64 Bit)
 Kernel : 5.15.0-60-generic

**Comment by ReturnFI** [comment]
سلام.
از کد جدید در آموزش ساب PHP استفاده بفرمایید.
همچنین پنل رو به آخرین نسخه ریلیز آپدیت کنید.

صمیمانه پیشنهاد میکنم مشکل خودتون را با ذکر جزییات در گروه تلگرام هیدیفای و تاپیک مربوط به منیجر مطرح کنید تا همکارانم برای رفع مشکل شما را راهنمایی کنند.

[گروه تلگرام هیدیفای
](https://t.me/hiddify_board)
