### ISSUE TITLE
صفحه مدیریت کاربران

### ISSUE THREAD

**Issue by rezakeshavarza** [hiddify/Hiddify-Manager#3817]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.20
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

سلام 
ممنون از زحمات زیاد شما.
یه پیشنهاد داشتم اونم اینکه صفحه کاربرا یکم شیکتر بشه و دکمه تمدید اضافه بشه و اینکه باید یدونه یدونه کاربر بسازیم 
یه کاری کنید بشه تعداد هم ساخت مثلا یهو ۱۰ تا باهم

**Comment by rezakeshavarza** [comment]
مثل x-ui

**Comment by rezakeshavarza** [comment]
اموزش رو من جایی ندیدم از طریق بات
با خوده پنل چرا نشه؟
صفحه مدیریت کاربران به نظرم جالب نیست
میشه برای کاربر دکمه تمدید اضافه کنید

**Comment by Iam54r1n4** [comment]
ممنون بابت پیشنهاد.
برای ساخت کاربر با تعداد بالا میتونید از API های مربوط بهش استفاده کنید.
فعلا ایشو بسته میشه.
