### ISSUE TITLE
Auto connect after auto boot

### ISSUE THREAD

**Issue by HuaWang135608** [hiddify/Hiddify-Manager#3821]
I'm using Hiddify Next, the version is 0.14.20 on Windows11.

I set it auto boot when the pc open, and I have two configuration files of proxy. I have to click 'connect' to use proxy after it is running.

How I can set it auto connect and use proxy after it is running?

Thanks!!!

**Comment by Iam54r1n4** [comment]
Please open an issue in Hididfy-next (Hiddify App).
