### ISSUE TITLE
نمایش اطلاعات دسترسی به دیتابیس mysql

### ISSUE THREAD

**Issue by esg3006** [hiddify/Hiddify-Manager#3822]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.20
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

سلام.
بنظرم اطلاعات دسترسی به دیتابیس mysql رو توی پنل ادمین قرار بدید. شاید بخواد صفحه ساب خودش رو بسازه

**Comment by Iam54r1n4** [comment]
شما می تونید با کاربر root به دیتابیس دسترسی داشته باشید.
همچنین کاربر دیگه ای با نام hiddifypanel نیز وجود داره که پنل از طریق این کاربر query میزنه که پسوردش توی 
/opt/hiddify-manager/hiddify-panel/app.cfg
وجود داره.

**Comment by AliM1988** [comment]
> شما می تونید با کاربر root به دیتابیس دسترسی داشته باشید. همچنین کاربر دیگه ای با نام hiddifypanel نیز وجود داره که پنل از طریق این کاربر query میزنه که پسوردش توی /opt/hiddify-manager/hiddify-panel/app.cfg وجود داره.

مسير ديتابيس كجاست؟

**Comment by Iam54r1n4** [comment]
mariadb

**Comment by AliM1988** [comment]
بهتر راهنمايي ميكنيد؟ چطور ميتونم محتواي ديتابيس رو ببينم يا ويرايش كنم

**Comment by Iam54r1n4** [comment]
```bash
mysql
```
```bash
-> use hiddifypanel;
-> <use whatever sql command you want>
```
