### ISSUE TITLE
وارپ برای سایت‌های داخلی و بلاک شده، کار نمی‌کند

### ISSUE THREAD

**Issue by KSMM-INFINITY** [hiddify/Hiddify-Manager#3825]
مشکل:
در نسخه 8 اگر وارپ را بر روی گزینه "سایت‌های بلاک شده و داخلی" قرار می‌دادیم، می‌توانستیم سایت‌های بلاک شده داخلی را نیز به کمک وارپ باز نماییم. اما در نسخه 10.10.20 هیدیفای، با انتخاب این گزینه، نمی‌توان سایت‌های ایرانی و بلاک شده داخلی را باز کرد. در واقع وارپ تنها به تعداد محدودی از سایت‌های خارجی از جمله گوگل و اسپاتیفای اعمال می‌شود و نمی‌توان از وارپ برای سایت‌های ایرانی استفاده کرد.
این در حالی است که با انتخاب گزینه "همه سایت‌ها" در تنظیمات وارپ، می‌توان سایت‌های ایرانی را نیز با وارپ باز کرد.

نسخه هیدیفای:
Hiddify-Manager 10.10.20

**Comment by Alirezamoradi20** [comment]
مشکل مشابهی با همان نسخه 10.10.20 و اوبونتو 22.04 دارم.

**Comment by rezakeshavarza** [comment]
سلام از داخل پنل قسمت تنظیمات فایروال رو خاموش کنید

**Comment by Alirezamoradi20** [comment]
> سلام از داخل پنل قسمت تنظیمات فایروال رو خاموش کنید

حتی با فایروال خاموش هم این مشکل وجود داره

**Comment by KSMM-INFINITY** [comment]
سلام
من فایروال رو اصلا فعال نکردم و غیرفعاله اما همچنان وارپ نمیتونه سایتایی که ایرانی هستند رو نمایش بده. من لاگ xray.out.log رو بررسی کردم و دیدم که outbound سایتای ایرانی به جای اینکه مثل سایت گوگل WARP باشه، forbidden-sites هستش. این یعنی سیستم با وجود اینکه سایت رو به کمک geosite.dat به عنوان سایت ایرانی شناسایی کرده، اما نیومده از WARP به عنوان outbound براش استفاده کنه و همون forbidden-sites رو براش استفاده کرده.

**Comment by fkia87** [comment]
> سلام از داخل پنل قسمت تنظیمات فایروال رو خاموش کنید

من این کارو کردم و درست شد.
