### ISSUE TITLE
گزینه ذخیره و ایجاد جدید و کاربر عمده

### ISSUE THREAD

**Issue by mdseven** [hiddify/Hiddify-Manager#3826]
سلام
ادمین های عزیز خسته نباشید
ی سری پیشنهاد میخواستم بدم هم نظر خودمو هم چندین نفر از دوستانم که از هیدیفای استفاده میکنن
۱-توی آپدیت جدید گزینه ذخیره و ایجاد جدید توی قسمت ایجاد کاربر حذف شده که سرعت ساخت کاربر رو خیلی کم میکنه.

۲-اضافه کردن ویژگی ساخت کاربر عمده که من این پیشنهاد رو حدودا شش ماه پیش چندین بار به ادمین ها گفتم،خیلی کاربردی هست,برای نمونه این گزینه توی پنل xpanel که برای ssh هست میتونین ببینید

۳-گزینه reinstall هم مجدد به پنل توی حالت اتصال با ssh برگرده

البته مورد های ۱ و ۲ بنظرم خیلی مهم ترن،یه سری از کاربرا بخاطره همین مسئله آپدیت نمیکنند.

بازم ممنون از زحمات شما

**Comment by mdseven** [comment]
البته ساخت چندین کاربر با ربات امکانش هست،فقط بدیش اسم کاربریه که میسازه هست،اگر بشه اسم اکانت هایی ک عمده میسازه ربات رو از داخل همون ربات تغییر داد عالی میشه
برای مثال یک اسم بدیم 
1testS1
بعد ربات بسازه
1testS1
2testS1
3testS1
و....

**Comment by Iam54r1n4** [comment]
امکان ساخت کاربر بصورت گروهی همونطور که اشاره در ربات وجود داره.
اما اگر نیاز دارید با برنامه نویسی چنین کاری رو انجام بدید میتونید از API های مربوط بهش استفاده کنید.
فعلا این ایشو بسته میشهَ.
ممنون بابت پیشنهاد.

**Comment by mdseven** [comment]
بله درسته امکانش وجود داره فقط مشکلش اینه که اسم دلخواه نمیشه انتخاب کرد
برای مثال یک پنل برای ssh بود که برای ساخت کاربر عمده شما یک اسم مثلا admin با یک عدد جلوش میدادی
مثال admin1

بعد بر اساس تعداد اون برات با همون اسم میساخت

مثال:

admin1
admin2
admin3
admin4
......

اون پنل خیلی چیز ساده ای بود و این آپشنو داشت،حیفه هیدیفای چنین چیزی نداشته باشه
