### ISSUE TITLE
از کار افتادن singbox،xray, hiddify-panel

### ISSUE THREAD

**Issue by umidomm** [hiddify/Hiddify-Manager#3827]
بعد از آپدیت به 10.10.20بعد از هر بار اپلای کانفینگ یک یا چند سرویس از کار میوفته،باید چندین بار آپدیت زد تا شاید یکی از این دفعات سرویس ها به درستی کار کنه،از سمتی یکی از سرور ها هیچ جوره هسته ی sing-box روش اجرا نمیشه

**Comment by KSMM-INFINITY** [comment]
من هم همین مشکل رو داشتم. تنها راهش فعلا اینه که سرور رو ریبیلد کنید و مجددا از اول هیدیفای رو روش نصب کنید. البته قبلش از تنظیمات و کاربرها فایل پشتیبان تهیه کنید.
