### ISSUE TITLE
پورت hysteria 

### ISSUE THREAD

**Issue by umidomm** [hiddify/Hiddify-Manager#3828]
روی برخی از سرویس دهنده ها udp فقط روی پورت های متداول https و http کار میکنه،از اونجا که پنل برای هر دامنه پورت hysteria مجزا تخصیص میده میدونم سخته،شما زحمت کشیدید این پروتکل رو اضافه کردید،لطفا قابل استفاده اش هم بکنید

**Comment by Iam54r1n4** [comment]
بررسی میشه.
