### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Mehrdad14** [hiddify/Hiddify-Manager#3829]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.10.20
**Python Version**:  3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
**OS**:              Linux-5.4.0-x86_64-with-glibc2.31
**User Agent**:      Unknown

**Comment by Mehrdad14** [comment]
i upgraded to ver10 and the volume and online users dont work. then i rebuild and installed again and it dont work again.

**Comment by Iam54r1n4** [comment]
Fixed.
