### ISSUE TITLE
پیشنهاد بهبود 

### ISSUE THREAD

**Issue by ghost** [hiddify/Hiddify-Manager#3830]
درود وقت بخیر
ما خیلی دوست داریم مهاجرت کنیم به پروژه شما اما به دلیل داشتن کاربر زیاد نمیشه تک تک یوزر ها رو منتقل کرد 
لطفا کاری کنید بشه کاربر های سایر پنل ها مثل x-ui هدیفایی منتقل کنیم 
باتشکر

**Comment by Iam54r1n4** [comment]
درود
ممنون بابت پیشنهادتون، در حال حاضر امکان وارد کردن کاربران از پنل X-UI به هیدیفای وجود داره، میتونید در لینک زیر در موردش بخونید.
https://hiddify.com/fa/manager/configuration-and-advanced-settings/how-to-import-xui-to-hiddifymanager/

(اگه نیاز بود ایشو رو reopen کنید)
