### ISSUE TITLE
بازشدن سایت های ایرانی با فیلترشکن فعال ولی با آی پی ایرانی

### ISSUE THREAD

**Issue by Aknuun** [hiddify/Hiddify-Manager#3831]
پنل سنایی این قابلیت رو اضافه کردن و به نظرم میتونه جلوی شناسایی رو توسط فیلترینگ بگیره
مثلا من الان میرم سایت باما
با ورودم به سایت چون درخواست ورود میدم و وارد نمیشه احتمالا سامانه هوشمند فیلترینگ نیفهمه که من دارم از فیلترشکن استفاده میکنم و میتونه رد فیلترشکن و سرور رو بزنه

**Comment by Iam54r1n4** [comment]
وارپ کاملا فعال کنید یا میتونید بذارید روی گزینه ی only blocked and local site. مشکل حل میشه.
