### ISSUE TITLE
چی به چیه؟!

### ISSUE THREAD

**Issue by A5DkjGQUZx** [hiddify/Hiddify-Manager#3833]
چطور باید متوجه شد در هر نسچه چی درست شده؟ چی تغییر کرده؟ چی اضافه شده؟ کدوم Issue حل شده؟ کدوما Address شده؟ تغییرات چیه و "چی به چیه"؟!

**Comment by rezakeshavarza** [comment]
راس میگه نامویا سوال منم هست این

**Comment by A5DkjGQUZx** [comment]
توی تلگرام دوستان سوال پرسیدن که آیا مشکلاتی که گزارش دادیم حل شده یا نه؟ بلاکش کردن!!!

**Comment by A5DkjGQUZx** [comment]
البته که میشه [اینطوری ](https://github.com/hiddify/Hiddify-Manager/compare/v10.10.20...v10.11.0)دنبال کرد موضوع رو، ولی انتظار میره شفاف تر باشه پروژه...

**Comment by lymanjre** [comment]
دوستان عزیز
همبشه چنج لاگها در [اینجا](https://github.com/hiddify/Hiddify-Panel/blob/main/HISTORY.md) و [اینجا](https://github.com/hiddify/Hiddify-manager/blob/main/HISTORY.md) موجوده. میتونید تغییرات را مشاهده کنید. 

همچنین در [کانال تلگرام](https://t.me/hiddify) و [گروه پشتیبانی و رفع مشکل](https://t.me/hiddify_board) نیز تغییرات را اطلاع میدیم. با سپاس از همراهی شما

**Comment by lymanjre** [comment]
دوستان عزیز
همبشه چنج لاگها در [اینجا](https://github.com/hiddify/Hiddify-Panel/blob/main/HISTORY.md) و [اینجا](https://github.com/hiddify/Hiddify-manager/blob/main/HISTORY.md) موجوده. میتونید تغییرات را مشاهده کنید. 

همچنین در [کانال تلگرام](https://t.me/hiddify) و [گروه پشتیبانی و رفع مشکل](https://t.me/hiddify_board) نیز تغییرات را اطلاع میدیم. با سپاس از همراهی شما
