### ISSUE TITLE
Internal server error: ASN REALITY

### ISSUE THREAD

**Issue by Afx110** [hiddify/Hiddify-Manager#3839]
# Internal Error Stacktrace:
local variable 'server_asn' referenced before assignment

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 237, in on_model_change
    msg = _("selected domain for REALITY is not in the same ASN. To better use of the protocol, it is better to find a domain in the same ASN.")+(f"<br> Server ASN={server_asn}<br>{d}_ASN={domain_asn}" if server_asn or domain_asn else "")
درود زمانی که سایت‌های ریالیتی که تطابق داره با سرور (ای اس ان ) اصلی برای اضافه کردن این خطا رو میده ولی زمانی که � سایت رو در ریالیتی می‌خواین اضافه کنید که مربوط  نیست به سرور ما دیگه خطا نمیده ولی خوب اون هم کارایی نداره

**Hiddify Version**: 10.11.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Thanks, Fixed.
