### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Daniamir125** [hiddify/Hiddify-Manager#3844]
# Bug/Feature:
**Description**:     Describe bug or needed feature
درود و خسته نیاشید
به یاد یوسف و سگارو و با نام خدا
بسیار ممنون از زحمات شما
خواستم چند تا پیشنهاد بدم که مفید واقع شده باشم
امکان تنظیم کردن و کم وزیاد کردن 6 ساعت بکاپ
ارسال خودکار بکاپ توسط بات به ادمین
x-uiامکان ایجاد کانفیگ دستی مثل  
نرم افزار اندروید مدیریت مثل سافت اتر
امکان انتقال دیتا در قالب icmp,dns
به امید خدا با اجرای این ها هیدیفای بسیار قدرتمند تر از قبل میشه
به امید زمین زدن فیلترچی و دسترسی ازاد به اطلاعات
## Details:
**Hiddify Version**: 10.11.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-25-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
ممنون بابت پیشنهاد، بررسی میشه.
