### ISSUE TITLE
وارپ برای سایت‌های داخلی کار نمی‌کند

### ISSUE THREAD

**Issue by KSMM-INFINITY** [hiddify/Hiddify-Manager#3847]
در نسخه ۸ هیدیفای، سایت‌های داخلی از آی پی‌های وارپ استفاده می‌کردند اما در نسخه ۱۰، نمی‌توان با وارپ وارد سایت‌های داخلی شد. در واقع در این نسخه، به جای اینکه برای اتصال به سایت‌های داخلی از وارپ استفاده شود، اتصال را مسدود می‌نماید.

ورژن هیدیفای: 10.11.1

**Comment by amir-rz** [comment]
#3734

**Comment by KSMM-INFINITY** [comment]
> #3734

وارپ برای سایتایی مثل گوگل کار میکنه و مشکلی نداره، اما وقتی که روی حالت "سایتهای داخلی و مسدود شده" تنظیم شده باشه، سایتای ایرانی رو باز نمیکنه و یعنی به جای اینکه از وارپ برای اونا استفاده کنه، بلامشون میکنه. این در حالیه که اگر گزینه وارپ رو روی "همه سایتها" بذاریم، سایتای ایرانی رو هم از وارپ عبور میده و مشکل حل میشه. این مشکل تو نسخه قبلی یعنی نسخه 8 هیدیفای منیجر وحود نداشت.
