### ISSUE TITLE
کافنیگ trojan+tcp+tls کار نمیکند

### ISSUE THREAD

**Issue by rezconf** [hiddify/Hiddify-Manager#3848]
سلام 
یک مسئله ای که هست اینه که رو هسته سینگ باکس کافنیگ trojan+tcp+tls کار نمیکند مشکل هم اینجاست که این کانفیگ رو هسته به trojan+http+tls تبدیل میشه .و کلا کانفیگ دیگه کار نمیده

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
