### ISSUE TITLE
چطور میشه سایتهای ایرانی رو از روی نرم افزار بای پس کرد که اصلا وارد فیلترشکن نشن؟

### ISSUE THREAD

**Issue by dreamboxone** [hiddify/Hiddify-Manager#3849]
چطور میشه سایتهای ایرانی رو از روی نرم افزار بای پس کرد که اصلا وارد فیلترشکن نشن؟
مثل iran.dat

**Comment by mojtabashahosseinii** [comment]
باید توی برنامه Role تعریف بشه که این امکان رو خود برنامه حل کرده

**Comment by eArash** [comment]
چطور به صورت دستی میتونیم برخی سایت هارو اضافه کنیم (مستقیم کنیم) یا حتی برخی سایتا بلاک بشن؟ درواقع راهی هست قوانین روتینگ رول رو خودمون تعریف کنیم؟
