### ISSUE TITLE
مشکل در هر اپدیت برنامه

### ISSUE THREAD

**Issue by mojtabashahosseinii** [hiddify/Hiddify-Manager#3851]
با سلام خدمت شما
اگر امکانش هست در اپدیت یک گزینه اضافه کنین که بعد از اپدیت کامل دسترسی hiddify_usages.json رو به دسترسی 777 برسونه که مشکل آنلاین و حجم مصرفی در هر اپدیت حل بشه
و بعد دستور apply config هم اجرا بشه
و مشکل حل میشه
در چند اپدیت اخیر این مشکل همیشه هست و باید به صورت دستی این مشکل حل بشه
ممنونم

**Comment by Iam54r1n4** [comment]
بررسی خواهد شد.
