### ISSUE TITLE
عدم برقراری ارتباط در https

### ISSUE THREAD

**Issue by DISRUPT-NET** [hiddify/Hiddify-Manager#3852]
بنده یک سرو ایران دارم که از سرور اصلی بهش تانل کردم منتها مشکل اینه که آنتی ویروس سی دی ان و... به سرتفیکت ایراد می گیرن می گن قابل اعتماد نیست، حتی سی دی ان در حالت اتو و یا HTTPS هم کار نمی کنه

@HiddifyOfficial

**Comment by ReturnFI** [comment]
سلام.
برای دریافت درست سرتیفیکت باید پورت 80 رو تانل کنید.
موفق باشید
