### ISSUE TITLE
Can't use TUN 

### ISSUE THREAD

**Issue by DarkBlud** [hiddify/Hiddify-Manager#3855]
I'm trying to use TUN But when I try to 
![image_2024-03-18_200853551](https://github.com/hiddify/Hiddify-Manager/assets/73785215/88571bbe-0da1-48be-a34a-10af86917fbc)
connect I get the error in the picture ( app is run by administrator )

**Comment by Iam54r1n4** [comment]
Please open issue in Hiddify-Next(Hiddify App) repository. **not** in the Manager.
