### ISSUE TITLE
Online Users Problem

### ISSUE THREAD

**Issue by momalekiii** [hiddify/Hiddify-Manager#3859]
After Updating to V10.12.0 Online Users Are not showing up on the Admin Panel, They all are offline and Network still Counts the bytes! 

please check it, it cannot refresh users Status and usage!

Ubuntu 22.04 
Panel V10.12.0

**Comment by V2RVPNShop** [comment]
من همین مشکل را دارم.

**Comment by Iam54r1n4** [comment]
Thanks for your report. It's fixed.
