### ISSUE TITLE
تنظیمات پروکسی مختص به هر دامین متفاوت 

### ISSUE THREAD

**Issue by w0l4i** [hiddify/Hiddify-Manager#386]
تنظیمات پروکسی برای هر دامین متفاوت باشد 
مثلا اگر از 4 دامین استفاده کنیم و در هر دامین از سی دی ان استفاده کنیم ، بتونیم تعین کنیم کدام دامین ها فقط vmess کدام دامین فقط tls و کدام دامین فقط trojan باشد 
و فقط مختص به سی دی ان نباشد ، در دایرکت ها و ریلای ها هم اعمال شود
![image](https://user-images.githubusercontent.com/52799129/224029188-a287d9e8-fad9-4044-a37c-a4850eba2886.png)

با تشکر از زحماتی که کشیدید این پنل پتانسیل خوبی دارد ، ممنون

**Comment by conall1995** [comment]
به جای اینکه فعال و غیر فعال کردن پروکسی به صورت کلی رو تمام دامین ها اعمال بشه این تنظیمات زیر مجموعه دامین بشه و برای هر دامین لیست پروکسی های فعال وجود داشته باشه 
مثلا دامین ۱ >> پروکسی reality_grpc_vless و reality_xtls_vless فعال باشه
دامین ۲ >> پروکسی tls_ws_direct_trojan 

این مورد اگه float ip تمیز استفاده کنی به کار میاد 
یا در مواردی که مثلا تونل کردی و تونلت فقط از همه چی پشتیبانی نمیکنه
یا از بعضی کانتینر ها استفاده میکنی 
و در نهایت باعث دقیقتر بودن و خلوت تر شدن لیست کانفیگ های کاربر میشه
