### ISSUE TITLE
Problem  configuration fie  "Invalid link"

### ISSUE THREAD

**Issue by CLONER-hub** [hiddify/Hiddify-Manager#3861]
Dear friend, I am a Linux programmer myself, because of your busy schedule, I can't go back to find the bug
The problem is that the new version of Hidify has a bug.
My problem: I tried to add the configs again, whether I tried to give the source to the program or as a link, the answer is the same, "invalid link".
I have Samsung Android 13 core 5 program version 0.14.20
How did you update it? When the program is completely full, this release doesn't work because of the bug. The previous version was better

**Comment by Iam54r1n4** [comment]
Hi Cloner-hub,
We need more information about the problem you encounter with. my suggestion is to use newer versions.
