### ISSUE TITLE
سوال در مورد نصب

### ISSUE THREAD

**Issue by cr4zyfish** [hiddify/Hiddify-Manager#3863]
سوال اول اینکه در چه نسخه‌هایی از ubuntu کار می‌کنه؟ من روی 16 18 20 و 22 تست کردم و فقط روی 22 کار می‌کرد.

سوال دوم اینکه در این صفحه گفته:
https://github.com/hiddify/Hiddify-Manager/wiki/Quick-Installation-On-Ubuntu

After installation At the end, a link will be generated which is the link to setup your proxy. Now we need to set the domain. Click on [this link](https://github.com/hiddify/hiddify-config/wiki/Guide-for-setting-up-the-domain-and-finalizing-the-installation) to complete the installation.

اما لینکی برای من بعد از نصب نمایش داده نشد و وقتی خودم دستور hiddify رو وارد کردم لینک نمایش داده شد. آیا نباید این توضیح به صفحه اضافه بشه؟

سوال سوم اینکه من دامنه فیک رو از washingtontimes.com تغییر دادم به example.com ولی وقتی ip رو مستقیم باز می کنیم چرا دوباره همون washingtontimes.com نمایش داده میشه.

**Comment by Iam54r1n4** [comment]
یک: لطفا ویکی رو بخونید
دو: بررسی میشه
سه: احتمالا شما بعد از تغییر فیک دامین، apply config نکردید
