### ISSUE TITLE
Unexpected Error (listen tcp... error)

### ISSUE THREAD

**Issue by SamParklcf** [hiddify/Hiddify-Manager#3869]
![UnexpectedError](https://github.com/hiddify/Hiddify-Manager/assets/75083627/95d696e5-9b88-4151-b560-b9b1f52bd8c2)

When trying to connect to the profile it will show from time to time, I'm running the app as admin to use VPN.
and after one more try, the app crashes.

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
