### ISSUE TITLE
از ورژن 0.13.6 تا 0.14.20  فرگمنت کارمیکنه

### ISSUE THREAD

**Issue by mekowl** [hiddify/Hiddify-Manager#3870]
سلام سال نو مبارک 
از ورژن 0.13.6 تا 0.14.20  فرگمنت کارمیکنه
باقی ورژن ها به هیچ وجه فرگمنت کار نمیکنه و بجای پینگ ضربدر میزنه

حالت cdn ورژن 
پنل هم ریلیز

**Comment by Iam54r1n4** [comment]
لطفا پنل رو اپدیت کنید و تست کنید.
