### ISSUE TITLE
نمایش دقیق مانده روز کاربران

### ISSUE THREAD

**Issue by mahmood1993hub** [hiddify/Hiddify-Manager#3871]
بجای نمایش 3 ماه مانده یا 2 ماه مانده بشه 90 روز مانده چون تا زیر 60 روز نرسه دقیق نمیشه فهمید چند روز دیگه کاربر زمان داره

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
