### ISSUE TITLE
Hysteria Obfuscation (Salamander) Bug

### ISSUE THREAD

**Issue by mhmd-hb** [hiddify/Hiddify-Manager#3874]
when the **Hysteria Obfuscation** option is enabled on the server, the related configs times out and user have to disable this option to make them work again.

i don't know if it's a bug, limited system resources for **salamander** encryption or any conflict with tls fragment settings.

**HiddifyManager 10.12.1**
**HiddifyPanel 10.12.1**

**Server info:**
Vultr
OS: Ubuntu 22.04 x64
vCPU/s: 1 vCPU
RAM: 1024.00 MB
Storage: 25 GB NVMe

**Comment by Iam54r1n4** [comment]
Thanks for your report, we'll work on it.

**Comment by Iam54r1n4** [comment]
The issue moved to feature in the project table.
