### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by z8nyar** [hiddify/Hiddify-Manager#3875]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.12.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
