### ISSUE TITLE
High resource usage

### ISSUE THREAD

**Issue by trytopassgfw** [hiddify/Hiddify-Manager#3876]
پنل من روی ورژن 10.11.1 یهو مصرف همه سخت افزارش زیاد میشه. کل کاربرهام زیر 50تا هست.
ubuntu 22.04 هستم.

![cpu](https://github.com/hiddify/Hiddify-Manager/assets/125186696/11671675-a3de-4fbc-8624-b9ed95e0a99a)
![htop](https://github.com/hiddify/Hiddify-Manager/assets/125186696/a4d2ec26-3938-4242-aac8-f1ce8ad7abbd)

**Comment by Iam54r1n4** [comment]
از ورژن های جدید استفاده کنید.
