### ISSUE TITLE
فرگمنت

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#3879]
در ورژن ۱۰.۱۲.۱
فرگمنت انگار کار نمیکنه
تنظیمات فرگمنت رو زدم داخل پنل اما اپلود نمیده
همون تنظیمات رو با ircf میزنم رو همون کانفیگ عین بنز کار میکنه

**Comment by Iam54r1n4** [comment]
در اخرین ورژن تست کنید اگه مشکل وجود داشت ایشو رو باز کنید.
