### ISSUE TITLE
grpc configs are down

### ISSUE THREAD

**Issue by zekerya** [hiddify/Hiddify-Manager#3880]
بعد از اپدیت به اخرین ورژن 10.12.1 تمام کانفیگهای grpc از کار افتادن. ری اینستال و اپلای هم جواب نداد.

**Comment by zekerya** [comment]
لینک  موقت کاربر هم باز نمیشه

**Comment by zekerya** [comment]
ظاهرا با عوض کردن هسته از سینگ باکس به اکس ری مشکل حل شد.

**Comment by Iam54r1n4** [comment]
> ظاهرا با عوض کردن هسته از سینگ باکس به اکس ری مشکل حل شد.

در اخرین ورژن مشکل حل شد.
