### ISSUE TITLE
برگرداندن نمایش "زمان صفر شدن حجم کاربر" 

### ISSUE THREAD

**Issue by trytopassgfw** [hiddify/Hiddify-Manager#3884]
داخل ورژن 8 یک ویژگی بود که زمان صفر شدن حجم کاربر رو نشون میداد. برای امثال من که به خانواده و دوستان کانفیگ میدیم، این ویژگی خیلی خوب بود. ما اصولا اکانت کوتاه مدت نمیدیم و همه با پیش فرض 900 روز ساخته میشن. ریست ماهانه برای این هست که مصرفشون رو کنترل کنن و مصرف زیادی نداشته باشن. در نسخه 8 میتونستن ببینن چند روز دیگه حجمشون ریست میشه و بالطبع مصرف رو کنترل میکردن. داخل نسخه 10 این مورد وجود نداره.
![photo_2024-03-22_19-31-34](https://github.com/hiddify/Hiddify-Manager/assets/125186696/86d07a2d-a641-4f1f-9c02-5f84852fcc7e)

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
