### ISSUE TITLE
عدم کارکرد هیستریا ریلی و تویک ریلی در آپدیت ۱۰.۱۲.۱

### ISSUE THREAD

**Issue by HadiTak** [hiddify/Hiddify-Manager#3888]
سلام
در ورژن ۱۰.۱۲.۱ دو پروتکل مهم ریلی hysteria2 relay و tuic relay و احتمالا wiregard relay و ssh relay کار نمیکنند و پروتکل‌های نامبرده صرفا فقط بصورت دایرکت جواب میدهند.

**Comment by HadiTak** [comment]
این مشکل در ورژن جدید هم پابرجاست

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
