### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by nilofari700** [hiddify/Hiddify-Manager#3889]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.12.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

سرور شما به دلیل فعال بودن احراز هویت رمز عبور در SSH، در معرض سوء استفاده قرار دارد. برای امنیت بخشیدن به سرور خود، لطفاً به مکانیزم احراز هویت مبتنی بر کلید سوئیچ کنید و احراز هویت رمز عبور را غیرفعال نمایید. [بیشتر بخوانید...](https://github.com/hiddify/Hiddify-Manager/wiki/%D8%BA%DB%8C%D8%B1%D9%81%D8%B9%D8%A7%D9%84-%DA%A9%D8%B1%D8%AF%D9%86-%D8%AF%D8%B3%D8%AA%D8%B1%D8%B3%DB%8C-%D8%A8%D8%A7-%D9%BE%D8%B3%D9%88%D8%B1%D8%AF)

سللام میشه برای نمایش یا عدم نمایش این کلید یا تیک روشن خاموش بزارید بعد از اولین لود ادم بتونه خاموش کنه؟

**Comment by Iam54r1n4** [comment]
ممنون بابت پیشنهاد. پیشنهادتون بررسی میشه.
