### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Fardinmilani** [hiddify/Hiddify-Manager#3892]
# Bug/Feature:
**Description**:     سلام وقتتون بخیر بابت نسخه ای که ریلیز کردید فقط یه پیشنهادی داشتم و اونم این بود که کاش تنظیمات فرگمنت و موکس رو طوری تو پنل قرار میدادید که میتونستیم برای هر دامنه دلخواه این تنظیمات رو اعمال کنیم اینطوری نباشه که وقتی فرگمنت رو طبق یه تنظیماتی اعمال کنیم تغییرات روی همه دامنه هامون اتفاق بیافته. خیلی ممنون
## Details:
**Hiddify Version**: 10.12.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
بررسی می‌شود
