### ISSUE TITLE
اضافه کردن یک امکان برای ادمین ها

### ISSUE THREAD

**Issue by fazelit** [hiddify/Hiddify-Manager#3894]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.12.1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

با سلام
لطفا برای بخش ادمین ها علاوه بر محدودیت تعداد کاربر محدودیت حجم هم قرار بدید مثلا برای یک ادمین بتواند 100 کاربر با محدودیت حجم ماهانه 500 گیگ برای مجموعه تمام کاربر ها قرار دهد.

**Comment by Iam54r1n4** [comment]
ممنون بابت پیشنهاد بررسی خواهد شد.
