### ISSUE TITLE
پیشنهاد - جابه جایی کاربران در صفحه

### ISSUE THREAD

**Issue by TheMarwin** [hiddify/Hiddify-Manager#3896]
«امکانی برای جا به جا کردن کاربران»
اگر بشه گزینه یا دکمه ای رو اضافه کرد که بشه جای کاربران رو توی صفحه کاربران از پنل ادمین عوض کرد، خیلی بهتر میشه. اینجوری میشه کاربرایی که به هم مربوطن رو کنار هم آورد تا از پراکندگیشون و گشتن دنبالشون بشه جلوگیری کرد و بهتر مدیریتشون کرد. 
ممنون از تیم حرفه ای هیدیفای

**Comment by litoosh13** [comment]
بررسی میشود
