### ISSUE TITLE
403 forbidden error on spotify and many other websites, ipv6 is disabled.

### ISSUE THREAD

**Issue by Hadi-1624** [hiddify/Hiddify-Manager#3897]
I have an issue with Hiddify. I have had this issue for three servers. iPV6 is disabled, but many websites will not open. I get error 403 forbidden.
noone in telegram helps meAlso.

Hiddify manager version 10.12.1

**Comment by litoosh13** [comment]
use warp and
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager

**Comment by Mammad3861** [comment]
> use warp and 1.Make a backup 2. rebuild server to ubuntu 22.04 3. install latest version of the panel 4.restore backup you can follow all learning's material about the panel here: hiddify.com/manager hiddify.com/fa/manager

This is many users problem, if you put in all sites route or in other panels route 4070 port to warp can solve the problem
according to this conversation [route](https://github.com/alireza0/x-ui/issues/1019#issuecomment-2101610832)
It's good if we can config this route manually!
