### ISSUE TITLE
Please fill the title properly با این آپدیت حجم مصرفی و آنلاینی از کارافتادن V10.14.0 hiddify panel

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#3902]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
 در نسخه جدید وضعیت کاربرا نمایش نمیده و در حالی که متصل هستند و استفاده میکنند وضعیت رو آنلاین نمایش نمیده همچنین میزان مصرف رو نیز تغییر نمیده با اینکه دارند دانلود و اپلود میکنند.

**Comment by moli1369** [comment]
جالبه در برنامه اندروید مشکلی نداره و میزان مصرف را نمایش میده.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
