### ISSUE TITLE
خطای 500

### ISSUE THREAD

**Issue by Ali7268** [hiddify/Hiddify-Manager#3903]
سلام وقتتون بخیر کابر جدید که می خوایم اضافه کنم خطای ۵۰۰بهم میده عکسش هم برات میفرستم
![Screenshot_20240326_094436_Chrome](https://github.com/hiddify/Hiddify-Manager/assets/118038793/c24b4f8d-3e23-49c1-8ed7-f054ddac8869)
ممنون میشم راهنماییم کنید

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.

لطفا چنین مباحثی رو در گروه تلگرام هیدیفای مطرح کنید.
