### ISSUE TITLE
مشکل ریست حجم در مود های daily

### ISSUE THREAD

**Issue by Amirrkmh** [hiddify/Hiddify-Manager#3913]
نسخه پنل ۱۰.۱۴.۰
حجم کاربر هایی که با مود daily ساختم همیشه ساعت ۱۲ شب ریست میشد الان نمیشه ، این مشکل بزرگیه برام.
وارپ فعال
ابونتو ۲۲.۰۴
لطفا این مشکل رو بررسی کنید
نسخه قبل مشکل قطع نشدن کانفیگ ها بعد از تموم شدن حجم و زمان وجود داشت که خوشبختانه در نسخه ۱۰.۱۴ رفع شد و اکنون این مشکل جدید پیش آمده.

**Comment by moli1369** [comment]
تنها راه حلش اینکه که یک ساعتی قطعی بدی و اینکه قبل از تمامی این روش حتما این کار رو انجام بده 
به پشتیبان گیری برو و یه نسخه پشتیبان گیری واسه خودت بگیرد به جایی که سرور خریدی برو سرور رو ریست فکتوری کن خام شه تمامی اپدیت ها رو انجام بده مجدد پنل رو نصب کن وقتی که بالا اومد هیچکاری نکن مستقیم برو به پشتیبان گیری فایل پشتیبان رو بهش بده و ریکاوری رو بزن سرور اپدیت میشه کاریش نداشته باش تموم شد تمامی اطلاعات واست لیست میشه و مشکل اپدیت حجم برات برطرف میشه حتی آنلاین و آفلاین بودن کاربرا هم واست درست میشه کلا تمامی مشکلات حل میشه سعی کن این کار رو اخر شب انجام بدی که ترافیک سمت سرورت کمه بازم تاکید میکنم حتما پشتیبان گیری رو انجام بده.نگران حجم استفاده شده دوستان نباش بلافاصله اپدیت کنی اطلاعات پنل به روز میشه و حجم کسایی که استفاده کردن برات اپدیت میشه.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
