### ISSUE TITLE
حذف شدن پروکسی tls ws cdn vless

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3915]
سلام. بعد از آپدیت از نسخه 10.12.1 به نسخه 10.14 پروکسی tls ws cdn vless از لیست حذف شده.
آپدیت مجدد و اپلای کانفیگ و چند بار روشن و خاموش کردن گزینه وبسوکت هم جواب نداد.
از قسمت ویرایش پروکسی ها هم جستجو کردم و پروکسی مذکور کلا وجود نداشت.
من برای این مورد به جای نام چند عدد فاصله قرار داده بودم.

نسخه پنل 10.14
اوبونتو 22.04
نصب مستقیم نسخه 10

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
