### ISSUE TITLE
عدم ارسال بکاپ توسط ربات

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#3917]
بعد از آپدیت به نسخه 10.14 بکاپ توسط ربات ارسال نمیشود. ربات مجددا استارت شد ولی فرقی نکرد.

**Comment by moli1369** [comment]
تا  هفته دیگر مشکل حل میشه

**Comment by Iam54r1n4** [comment]
Fixed
