### ISSUE TITLE
Qr code not working true 

### ISSUE THREAD

**Issue by freehorn3000** [hiddify/Hiddify-Manager#3918]
# Bug/Feature:
**Description**:     
Hi 
Qr code not working true 
I'm can't scan my qr code 

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by moli1369** [comment]
موقتا برای برطرف کردنش زبان پنلتو انگلیسی کن تا چند روز دیگه این مشکل حل میشه.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
