### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by age4u** [hiddify/Hiddify-Manager#3919]
# Bug/Feature:
**Description**:     Describe bug or needed feature
age.mining1@gmail.com
## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
با سلام تو ورژن جدید نه تاریخ نه حجم کاربران تغیری نمیکنه
ینی حجم مصرفیشون کم نمیشه

**Comment by Iam54r1n4** [comment]
Fixed. wait for update.
