### ISSUE TITLE
متاسفانه کاربران آنلاین و ترافیک مصرفی نمایش داده نمیشه

### ISSUE THREAD

**Issue by pishtaz13** [hiddify/Hiddify-Manager#3922]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by misagh72** [comment]
fixed in next release be patience

https://github.com/hiddify/hiddify-user-front/commit/5dc87f743f233b8fd0ff0c40b9a3ddbbe7c2812a

**Comment by 1351438** [comment]
when the update will release?

**Comment by Iam54r1n4** [comment]
Fixed.
