### ISSUE TITLE
Internal server error: Method Not Allowed

### ISSUE THREAD

**Issue by skydarklord** [hiddify/Hiddify-Manager#3926]
# Internal Error Stacktrace:
**Error Message**:   405 Method Not Allowed: The method is not allowed for the requested URL.
```
Traceback (most recent call last):

```

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
**OS**:              Linux-5.15.0-76-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
سلام دوستان 
این ارور تو بخش لاگ وجود داره :

405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1499, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1481, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/flask/ctx.py", line 397, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/routing.py", line 2044, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

لاگ سیستم : 
 Services Status:
    hiddify-cli                   inactive
    hiddify-redis                 active
    hiddify-ssh-liberty-bridge    active
    hiddify-haproxy               active
    hiddify-panel                 active
    hiddify-nginx                 active
    hiddify-singbox               active
    hiddify-xray                  active
    wg-quick@warp                 active
    mtproto-proxy                 active

هنگام فعال سازی وارپ این ارور در پایان بروز رسانی نمایش داده میشه
من کلید توسعه کلودفلر و warp+ رو تغییرد ادم اما بار مشکل وجود داره . ممنون میشم راهنمایی کنید . 

####75####Applying...####Warp####
Error: Key not found: warp_enable
===========================================================
===run.sh other/warp
Checking WARP ...
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
Generating WARP config...
Removing IPV6 from WARP...
Starting WARP.... checking real connectivitiy
WARP is not working!
Checking real connectivitiy again!
WARP is not working!
!!!!!!!!!!!!!!! WARP ERROR
===========================================================
####85####Applying...####Wireguard####
===========================================================
===disable.sh other/wireguard
===========================================================
####90####Applying...####HiddifyCli####
Error: Key not found: hiddifycli_enable
===========================================================
===run.sh other/hiddify-cli
rm: cannot remove 'clash.db': No such file or directory
Running HiddifyCli...
===========================================================
####95####Applying...####Singbox####
===========================================================
===run.sh singbox
ignoring singbox test
===========================================================
####98####Applying...####Almost Finished####
---------------------Finished!------------------------

**Comment by hiddify-com** [comment]
بررسی میشه

**Comment by skydarklord** [comment]
سلام دوستان 
. سه هفته گذشت اما مشکل رفع نشد . به نسخه 10.20.2 آپدیت کردم اما همچنان وارپ غیر فعال هست و ارور عدم فعال شدن میده . به نظر شما تو نسخه بعدی این مشکل رفع میشه ؟

با تشکر

**Comment by Iam54r1n4** [comment]
درود
قبل از همه چیز، ما هیچ وظیفه ای در قبال حل کردن مشکل به محض گزارش شما نداریم که زمان میدید.

در حال حاضر اخرین نسخه 10.20.4 هست و نه 10.20.2. اپدیت کنید. چنین مشکلی وجود نداره.
