### ISSUE TITLE
مشکل در نصب روی ابونتو

### ISSUE THREAD

**Issue by itsmmrd** [hiddify/Hiddify-Manager#3929]
سلام 
من چندین بار اقدام به نصب کردم با کد زیر 
bash <(curl i.hiddify.com/release)

اول اینکه هیج کدی در اخر نمی دهد
دوم اینکه با اجرای Hiddify پنجره مدیریت می اید و لینک های قابل مشاهده است ولی وقتی لینک را وارد میکنم اررور 502 می اید. بار های سرویس رو ریستارت کردم، سرور رو ریستارت کردم، اقدام به اپدیت و یا دانگرید کردم ولی اصلا و ابدا جواب نمیدهد 
لطفا کمک کنید

**Comment by Iam54r1n4** [comment]
لطفا چنین سوالاتی رو در گروه تلگرام هیدیفای بپرسید.
ایشو های گیتهاب برای بحث و گفتگو در مورد اشکالات در سطح کد هست.
