### ISSUE TITLE
گزارش چند مشکل در پنل

### ISSUE THREAD

**Issue by poava** [hiddify/Hiddify-Manager#3931]
توضیح مشکلات:
- برای دامنه ای که تانل هست به درستی Certificate گرفته نمیشه (تانلی که در نسخه 8 ساخته شده بدون مشکل کار میکنه، اما تانل جدید کانفیگ ها کار نمیکنند). این مشکل در نسخه 8 وجود نداشت. برای CDN هم با اینکه میدونه پشت کلادفلر هست و نمیتونه به IP اصلی دسترسی داشته باشه که بتونه Issue کنه اما 30 بار تلاش میکنه که Certificate بگیره و در نهایت Ignore میکنه و بجز اینکه عملیات دریافت Certificate به درستی انجام نمیشه، یه تایم طولانی ای زمان میبره تا "اعمال تغییرات" صورت بگیره.
- اگر برای VLESS بیام و Path رو از چیزی که دیفالت هست تغییر بدم، به طور کامل کانفیگ ها از کار میفتن (بعدش اعمال تغییراتم میزنم و کامل میشه).
- اگر کلیدهای Reality رو تغییر بدم، کلا دیگه هیچ کانفیگی حتی WS یا TCP و غیره هم کار نمیکنن (اعمال تغییرات انجام شد، کانفیگ سمت کلاینت هم بروز شد اما همچنان کار نمیکنه و اگر کلیدهای قبلی رو به صورت دستی برگردونم، بازم مشکل داره و مجبورم کلا بکاپ رو Restore کنم).

نسخه مورد استفاده: 10.14.0
سیستم عامل: Ubuntu Server 22.04

**Comment by Ariannetflix** [comment]
امشکل عدم دریافت certificate برای من هم وجود داره  با ip  های relay این مشکل داره. در version 10.20.4  هم این مشکل پابرجاست. در این ورژن برای cdn  gcore هم این مشکل اضافه شده علاوه بر  relay ها. در ورژن 10.14 relay اصلا کا نمیکرد به خاطر همین مشکل و  فقط با  allow insecure کار میکرد. احتمالا  به دلیل  نبود یا مشکل certificate اما زمانی که  certificate  رو  با certificate که از سرور relay با certbot گرفتم و جاگزین  کردم درست شد. نمیدونم با چه  پروسه ای cert رو  میگیره اما قاعدتا وقتی نمیتونه ip سرور  رو authenticate کنه نمیتونه cert رو  بگیره.  شایدم مشکل از فوروارد کردن پورت در سرور relay هست چون من فقط پورت ۴۴۳ رو فوروارد کردم   و شاید با  پورت دیگه این مثل ۸۰  cert رو میگیره 
<img width="912" alt="Screenshot 2024-04-13 at 9 46 58 PM" src="https://github.com/hiddify/Hiddify-Manager/assets/158844334/20e71ca5-2776-4588-92dd-4969436d42be">

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
