### ISSUE TITLE
مشکل با IPV6 در هنگام نصب و راه اندازی

### ISSUE THREAD

**Issue by poava** [hiddify/Hiddify-Manager#3933]
- اگر در هنگام نصب و راه اندازی اولیه، سرور فقط IPV6 داشته باشه به مشکل در نصب میخوریم، کلا با کامندی که برای ubuntu قرار دادیت نمیشه نصب رو انجام داد. اگر با اینستالر که در گیت هاب هست نصب کنی، یکسری پکیح ها نصب نمیشه.
- در زمان راه اندازی اولیه فقط باید IPV4 رو روی دامنه ست کرد و اگر IPV6 رو روی دامنه ست کنیم، کلا ارور میده و کار نمیکنه. برای سرورهایی که IPV6 Only هستند کلا استفاده از هیدیفای در اونها غیر ممکنه.

- در پنل، منوی "تنظیمات" زیر منوی "وضعیت پروکسی ها" ارور 502 میده.

این مورد از قبل (نسخه 8) تا نسخه کنونی وجود داشته و داره.
سرور: Ubuntu server 22.04

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
