### ISSUE TITLE
10.14.0 version have problem

### ISSUE THREAD

**Issue by mashtiali2023** [hiddify/Hiddify-Manager#3938]
hi

my hddify manager panel updated automatically to 10.14.0

after that i found that this version have problem for users that expired but have volume. so system shows that because of that expire time arrived it is disable, but user could connect.

second problem that is started from 8 hours ago and very critical is:

i found in dashboard my online users is zero. but users could connect.

when i checked more , i found that my server doesnt count gigabytes that users use. and my daily traffic usage is stoped in fixed number.

i checked and found users uses service but the counter of volume usage of user doesnt increase and all of my users last online is for 8 hours ago. but my users are online and use but system doesnt count their usage.

it is very important and critical, please help me about that

Regards

**Comment by Sensetize** [comment]
Yes there is such a problem in the latest version
In general:
1. For some users, the daily traffic package (gbs) is not reset and you have to manually restore their access after they fill up the daily GB traffic
2. After the used days, the user can still connect even if the disconnect box is checked
3. The user can still connect even if you delete it
4. If you change the user's uuid to another to stop from using, the user will still be able to connect using the old uuid and it will be impossible to control him (neither traffic nor days will be valid for him).
5. Also very often it gives an error 500 internal, you have to reboot the panel many times until it opens

**Comment by mashtiali2023** [comment]
I remember one thing

You know that from last year in Iran we didn't change clock for summer tune. But other countries changed they time 1 hour sooner from 30th March. And I saw in my dashboard in Iran my clock is 23:00 but hiddify time went to 24:00

Is there any relation to this ??

Regards

**Comment by mashtiali2023** [comment]
Does panel update automatically ?
Or it needs that update manually ?
