### ISSUE TITLE
Resource Usage on X version

### ISSUE THREAD

**Issue by infinitaa** [hiddify/Hiddify-Manager#3940]
Hi, and Thank You for your awsome project.
I've been using this panel for 1 year almost and it was OK even in 9 Dev version. But in the X version of software I have faced resource usage problem that causes services stop randomly. For example haproxy service, cli service or panel service.
I'm planning to revert to developer version, It was more stable that X version.
Thanks for your efforts

**Comment by Iam54r1n4** [comment]
We're working on it, the issue will be close for now, if you find any new clue reopen it.
