### ISSUE TITLE
Add ability to specify geoip/geosite block/warp proxy

### ISSUE THREAD

**Issue by kzvdar42** [hiddify/Hiddify-Manager#3945]
# Feature:
**Description**:     Please, add ability to specify geoip/geosite blocks or geoip/geosite warp proxy to block/proxy domestic sites in other regions

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
