### ISSUE TITLE
Telegram bot didn't send backup, everything work fine now it's been few days just bot didn't send backup I do apply config, update, restart, new token everything, I work with this panel for near one year so not noob and know how panel work and how config it but can't fix this problem, maybe it's from your side to fix or check thanks for help everyone ❤️🙏🏻

### ISSUE THREAD

**Issue by H3ein** [hiddify/Hiddify-Manager#3947]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Iam54r1n4** [comment]
Thanks for your report. it's fixed, please wait for newer version or use beta version.
