### ISSUE TITLE
Internal server error: Internal Server Error

### ISSUE THREAD

**Issue by RustemAnn** [hiddify/Hiddify-Manager#3948]
# Internal Error Stacktrace:
**Error Message**:   500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Traceback (most recent call last):

```

## Details:
**Hiddify Version**: 10.15.0.dev1
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
