### ISSUE TITLE
Importing the user link to Hiddify Next (Auto sub) causes TLS-H2 WS CDN Trojan and Vless not to work

### ISSUE THREAD

**Issue by mktwix** [hiddify/Hiddify-Manager#3949]
# Bug/Feature:
**Description**:     Importing the user link to Hiddify Next (Auto sub link) causes TLS-H2 WS CDN Trojan and Vless not to work while they work if other subscription links add to the app. Other protocols work okay though.

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
