### ISSUE TITLE
The button "Record" does not work in the setting.

### ISSUE THREAD

**Issue by Azhinn** [hiddify/Hiddify-Manager#3950]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Need more information, please put a screenshot or something in here

**Comment by Iam54r1n4** [comment]
This issue will be close due to insufficient information.
