### ISSUE TITLE
Warp is not working for domestic sites

### ISSUE THREAD

**Issue by KSMM-INFINITY** [hiddify/Hiddify-Manager#3952]
### **Bug description**
In the previous version of hiddify-manager, one could use warp to visit iranian sites without the requests being blocked by the hiddify-manager. But after upgrading to the hiddify-manager 10, this ability is not working. The options are the same as they were in the version 8 but it's not working. When the warp is set to work for domestic and blocked sites, it blocks iranian domestic sites. So it means we can't surf Iranain websites when the VPN is turned on, even when the Warp is enabled in the panel.

### **Bug Reproduction**
1. Go to the hiddify-manager setting.
2. From the Warp+ section, enter your warp key and set it to be used just for blocked and domestic sites.
3. Click on the submit button to save the changes.
4. To apply changes to the system, click on apply configs button.
5. Now on every client you have, connect to your VPN and try to open an Iranian website, like (https://soft98.ir).

### **Expected Behavior**
If everything was working fine, you could be able to visit this Iranian website with warp enabled but in reality you can't.

**Hiddify-Manager**
 - Version: 10.14.0
 

**Used Client apps**
- V2RayNG 1.8.19 on Android
- Hiddify 1.1.1 on Android
- Nekoray 3.26 on Windows

**Comment by Iam54r1n4** [comment]
Fixed in v10.20.1

**Comment by KSMM-INFINITY** [comment]
Thank you so much. Yes that's fixed in 10.20.1.
