### ISSUE TITLE
بات تلگرام

### ISSUE THREAD

**Issue by FreeBestApps** [hiddify/Hiddify-Manager#3956]
Feature:
**Description**:     در صورت امکان رباتی مشابه ربات هیدی بات به پنل اضافه بشه فکر میکنم فوق العاده میتونه باشه. هیچ ربات فروشگاهی برای هیدیفای به جز هیدی بات نیست

## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
در حال کار بر روی ربات تلگرام هیدیفای هستیم.
ممنون بابت پیشنهاد.
