### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by salardosti** [hiddify/Hiddify-Manager#3957]
# Bug/Feature:
**Description**:     Describe bug or needed feature
بات تلگرام کار نمیکنه و همچنین هر چند ساعت کاربران انلاین و محاسبه ترافیک قط میشه
## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
ممنون بابت گزارش تون. در اپدیت بعدی مشکل حل خواهد شد
