### ISSUE TITLE
پیشنهاد برنامه در پنل کاربری کاربر و  برای تمامی دوستان  ios با اتصال هوشمند

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#3958]
سلام همگی مدتی بود که برای دوستان ایفونی مشکل داشتم برای کانفیگ و اینکه خودش بتونه بهترین کانفیگ رو پیدا کنه حتی بتونن برای اینکه ترافیک ایران رو از خارج استفاده کنند نبود 
واقعیتش برنامه karing رو پیدا کردم که برای تمامی پلتفرم ها وجود دارد میخواستم درخواست بدم این برنامه رو در پیشنهاد برنامه ها در صفحه کاربر برای افراد ios پیشنهاد بده چون تند به تند دارند اپدیت میدن و مشکلات رو حل میکنند و اینکه اگر کانفیگی برای کاربر سریعتر باشه اون رو انتخاب میکنه لینک گیت هابشو میذارم اگر مورد تایید شما بود در اپدیت بعدی در صفحه مشتری یا خریدار برای افراد ios  پیشنهاد بده تمامی پروتکل ها رو هم حدودا ساپورت میکنه
> 
https://github.com/KaringX/karing/tree/main

**Comment by Iam54r1n4** [comment]
ممنون بابت پیشنهاد، بررسی میشه.

**Comment by moli1369** [comment]
ممنونم با اپدیتی که الان دادن کاملش کردن و ترافیک داخلی رو از خارجی جدا کردن بی نظیره حتما قرارش بدین معرکس جدی میگم تست کنید متوجه میشید.
![new app karing](https://github.com/hiddify/Hiddify-Manager/assets/31498696/d981a1c6-774a-4ed2-93fb-d34cd0972d2d)

**Comment by moli1369** [comment]
تا به روز رسانی چقدر ممکن هست اضافه بشه یا راهی هست که بتونم خودم اضافه کنم؟

**Comment by Iam54r1n4** [comment]
فعلا برنامه ای جهت اضافه کردن این اپ در لیست پیشنهادات نداریم.
