### ISSUE TITLE
ریست ربات گروه تلگرامی

### ISSUE THREAD

**Issue by Gold-IP** [hiddify/Hiddify-Manager#3959]
لطفا ربات گروه تلگرامی رو ریست کنید آیپی من بدون دلیل بلاک شده نمیتونم با ادمین ها در ارتباط باشم.آیدی جدیدهم که میسازم بازم از پیش مسدود شده هست

**Comment by Iam54r1n4** [comment]
لطفا چنین مشکلاتی رو در گروه تلگرام مطرح کنید. در ضمن اگر مسدود شدید حتما دلیلی داشته.
ایشو های گیتهاب برای بحث در مورد کد و پیشنهادات/مشکلات پنل هست.

**Comment by Gold-IP** [comment]
مهندس جان عرض کردم که آیپی بنده رو مسدود کردن نمیتونم پیام بدم توی گروه الان اکانت جدیدهم که بسازم نم بازم نمیتونم پیام بدم.حدود ۳۰ تا سرور هیدیفای دارم آنلاین از قبل عیدکه آپدیت اومد api از کار افتاد دیگه نه تونستم با ادمین هادر ارتباط باشم که api رو ویرایش کنم که بتونم کاربر جدید بگیرم. کاملا هم بدون دلیل مسدود شدم
