### ISSUE TITLE
  پیشنهاد برای تکمیل کرده ربات تلگرام

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#3961]
سلام این بات یه جورایی اوکی هست برای تلگرام فقط اینکه باید تکمیلش کنید ممنون میشم برسی کنید اگر اوکی بود توی اپدیت بعدی قرارش بدین 
این بات تعرفه همه چی رو میسازه و روی سرور پیاده میشه فقط نمیشه بهش لینک داد در حال حاضر امکان پرداخت از طریق کارت به کارت رو داره اما توی نسخه vip میتونیم درگاه پرداخت بهش وصل کنیم ممنون میتونیم یه جورایی کاملش کنیم. ازش بهره ببریم چون روی نسخه 10.14.0 جواب میده
https://github.com/B3H1Z/Hiddify-Telegram-Bot

**Comment by lymanjre** [comment]
دوست عزیز 
بات هیدیفای در حال توسعه است و در نسخه های بعدی ارائه می‌گردد. بات‌های متفرقه که توسط تیم ما توسعه داده نشده‌اند مورد تایید نمی‌باشند.
