### ISSUE TITLE
مشکل باقیمانده پس از بروزسانی ۱۰.۱۴‌.۰ که چند روز پیش ارائه شد

### ISSUE THREAD

**Issue by mashtiali2023** [hiddify/Hiddify-Manager#3966]
پس از مشکلات ایجاد شده در نسخه ۱۰.۱۴.۰ که لطف نمودید و حل شد هنوز یک مشکل حل نشده. استفاده کننده اگر مدت استقاده روزهایش به پایان رسیده باشد ولی هنوز حجم تعیین شده را به اتمام نرسانده باشد ، کماکان می‌تواند آنلاین شود. یعنی استفاده کننده زمانی توسط سیستم قطع می‌شود که حجم تمام کرده باشد و سیستم توجهی به انقضا زمان کاربر ندارد

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
