### ISSUE TITLE
Unable to install Hiddify manager on the server

### ISSUE THREAD

**Issue by mfathi91** [hiddify/Hiddify-Manager#3973]
**Describe the bug**
`bash <(curl i.hiddify.com/release)` throws unexpected error!

**To Reproduce**
1. SSH into your server.
2. Run the official command `bash <(curl i.hiddify.com/release)` to install Hiddify.
3. It shows an error `curl: (23) Failed writing body`

**Expected behavior**
The official installation command should install Hiddify without any error.

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/29010410/bbecd45b-5947-4ab4-83ae-6b87d86f4582)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Comment by FourOFour** [comment]
same problem

**Comment by emadtoranji** [comment]
Try This:

 `bash <(curl https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/common/download.sh)`

**Comment by omimoz** [comment]
just run sudo su then write your command

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
