### ISSUE TITLE
امکان تغییر پورت هیدیفای 

### ISSUE THREAD

**Issue by amir-rz** [hiddify/Hiddify-Manager#3975]
**Is your feature request related to a problem? Please describe.**
امکان تغییر پورت هیدیفای با استفاده از Docker یا HAProxy

مشکلی که هست اینکه با نصب هیدیفای, پورت ۴۴۳ کاملا اشغال میشه و تو خیلی از موارد نیازه که این پورت برای کارهای دیگه مثل ران کردن یک سایت روی سرور استفاده بشه. اگه گزینه یا گزینه هایی تهییه بشه تا تونست پورت هیدیفای رو عوض کرد خیلی عالی میشه.

**Describe the solution you'd like**
- پیشنهاد من استفاده از داکر بود که تا حدودی میدونم با قابلیت Port Forwarding خودش کارو خیلی راحت میکنه. 
- اگر هم برای HAProxy توضیحاتی آماده کنید که بشه کانفیگی که برای خود هیدیفای آماده شده رو تغییر و یا گسترش داد تا بشه پورت های دیگه هم به کانفیگ اضافه کرد هم خیلی عالیه. 

@Iam54r1n4
این مورد الان برام خیلی اظطراریه, امکانش هست جهت  راهنمایی با شما در تماس باشم؟

**Comment by Iam54r1n4** [comment]
شما میتونید سایت خودتون رو در هر پورتی که نیاز دارید بالا بیارید و در haproxy درخواست هایی که میاد رو کنترل کنید. برای اگر ssl.sni روی دامین سایت شما بود، درخواست فرستاده بشه به پورتی که سایت روش هندل میشه.

**Comment by amir-rz** [comment]
سوال اینجاست که اگه من الان تنظیمات لازمم رو داخل فایل /etc/haproxy/haproxy.cfg رو تغییر با هیدیفای تداخل نمیکنه؟ 
و اگر اینکه لازمه تنظیمات لازممو داخل فایل های HAProxy داخل هیدیفای اضافه کنم, دقیقا باید به کدوم فایل و کجا اضافه کنم تا اختلالی برای هیدیفای روی سرورم رخ نده؟

**Comment by amir-rz** [comment]
> شما میتونید سایت خودتون رو در هر پورتی که نیاز دارید بالا بیارید و در haproxy درخواست هایی که میاد رو کنترل کنید. برای اگر ssl.sni روی دامین سایت شما بود، درخواست فرستاده بشه به پورتی که سایت روش هندل میشه. برای فهمیدن اینکه چطور باید چنین کاری انجام بشه باید به داکیومنت های haproxy مراجعه کنید.

سوال اینجاست که اگه من الان تنظیمات لازمم رو داخل فایل /etc/haproxy/haproxy.cfg رو تغییر با هیدیفای تداخل نمیکنه؟ 
و اگر اینکه لازمه تنظیمات لازممو داخل فایل های HAProxy داخل هیدیفای اضافه کنم, دقیقا باید به کدوم فایل و کجا اضافه کنم تا اختلالی برای هیدیفای روی سرورم رخ نده؟

**Comment by amir-rz** [comment]
دوستانی که میخوان درکنار سرویس های هیدیفای, سرویس دیگه ای مثل سایت, پنل دیگه و غیره روی پورت ۴۴۳ ران کنند میتونن داخل فایل مراحل زیرو انجام بدن:

- اطمینان از نصب HAProxy
- وارد فایل **/etc/haproxy/haproxy.cfg** شید و کد زیرو به انتهای فایل اضافه کنید

```
frontend ptcs
    mode http
    bind *:443 ssl crt PATH/TO/SSL/DIRECTORY alpn h2,http/1.1
    # Wait for SSL handshake completion before inspecting
    tcp-request inspect-delay 5s

    # Accept SSL requests only
    tcp-request content accept if { req.ssl_hello_type 1 }
    acl ptcs_domain req.ssl_sni -i YOUR_DOMAIN.COM
    use_backend ptcs_backend if ptcs_domain
    default_backend ptcs_backend



backend ptcs_backend
    mode http
    server nginx_http 127.0.0.1:8800
```

- YOUR_DOMAIN.COM با دامنه ای که میخواید استفاده کنید عوض شه
- PATH/TO/SSL/DIRECTORY با پوشه ای که داخلش فایل های سرتیفیکت دامنه قرار داره عوض شه
- 127.0.0.1:8800 پورتی که سرور روش درحال اجرا هستش رو با 8800 عوض کنید.
- اگر نیاز داشتید سرویس های بیشتری رو روی پورت 443 بیارید باید backend های بیشتر بسازید و داخل frontend مشخص کنید که هر backend با چه دامنه ای استفاده بشه. برای مثال:
    acl ptcs_domain req.ssl_sni -i YOUR_DOMAIN.COM
    use_backend ptcs_backend if ptcs_domain
    اینجا گفته شده که اگر درخواست کاربر از دامنه فلان بود, ptcs_backend استفاده بشه, همونی که پورت 8800 هستش.

**Comment by amir-rz** [comment]
مثلکه این روش باعث تداخل با هیدیفای میشه و راه مناسبی نیست.
ازونجایی که خود هیدیفای تنظیمات مختص به خودشو برای HAProxy داره و پورت ۴۴۳ هم اشغال کرده, داشتن دوتا frontend که هردو روی یک پورت (۴۴۳) باشن باعث تداخل تو ارتباط با سرور شد. برای مثال سایت و پنل بعد از هربار رفرش بعضی اوقات بالا میان و بعضی اوقات ارور ۵۰۳ میدن.

اینطور که هیدیفای کلا روی پورت ۴۴۳ هست و امکان تغیرش بجز دست بردن توی کد پروژه ( که اونم بعد هر بار آپدیت دوباره برمیگرده به حالت اول ) اصلا ممکن نیست خیلی واقعا اذیت کنندست, انگار با نصب هیدیفای کلا باید قید پورت ۴۴۳ رو بزنی و استفاده از سرور خیلی محدود میشه.

ممنون میشم رسیدگی کنید یا بشه پورت هیدیفای رو عوض کرد و یا راه حل بهتری که خودتون فکر میکنید ارايه بدید

**Comment by Iam54r1n4** [comment]
> 

نیازی به اضافه کردن یک fronend اضافه نبود شما میتونید از همون frontend های موجود استفاده کنید.
اما بله بعد از هر اپدیت این مساله رو باید تکرار کنید. فعلا برنامه ای برای انجام چنین قابلیتی نداریم.

**Comment by amir-rz** [comment]
داخل کانفیگ های haproxy هیدیفای frontend ۴۴۳ با mode tcp تعریف شده.
سروری که سعی داشتم بالا بیارم با http هستش و با mode tcp بالا نیومد, امکان دور زدنش هست؟
