### ISSUE TITLE
عدم نمایش آنلاین و افلاین بودن کاربران در پنل نسخه 10.20.3

### ISSUE THREAD

**Issue by akbarzadehkamran** [hiddify/Hiddify-Manager#3976]
با سلام 
بعد از آپدیت به نسخه جدید 10.20.3 آنلاین و آفلاین بودن کاربران را نمایش نمی دهد .

**Comment by Iam54r1n4** [comment]
ونل رو به آخرین ورژن ارائه شده اپدیت کنید.
