### ISSUE TITLE
امکان دریافت سرویس حتی بعد از منقضی شدن زمان اکانت

### ISSUE THREAD

**Issue by rezahajrahimi** [hiddify/Hiddify-Manager#3979]
بعد از منقضی شدن تعداد روز یک اکانت و درصورتی که اکانت دارای حجم باشد، کاربر امکان اتصال را دارد.
## Details:
**Hiddify Version**: 10.14.0
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
