### ISSUE TITLE
Internal server error: configs_as_json

### ISSUE THREAD

**Issue by parsatavafi** [hiddify/Hiddify-Manager#3981]
سلام وقت بخیر. در هنگام باز کردن لینک سابسکریپشن با خطا مواجه میشم و فکر می کنم در نسخه 10.20.3 مشکلی برای باز کردن لینک های سابسکریپشن وجود داره. جزئیات این خطا به این شکله :

# Internal Error Stacktrace:
**Error Message**:   module 'hiddifypanel.hutils.proxy.xray' has no attribute 'configs_as_json'
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/auth.py", line 114, in decorated_view
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 66, in xray
    configs = hutils.proxy.xray.configs_as_json(c['domains'], c['profile_title'])

```

## Details:
**Hiddify Version**: 10.20.3
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-102-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
اروری که فرستاد شامل کدی هست که در ورژن 10.20.3 وجود نداره. لطفا بکاپ بگیرید و سرور رو ریبیلد کنید و در نهایت بکاپ رو restore  کنید.
