### ISSUE TITLE
> Second Bug:

### ISSUE THREAD

**Issue by Eisahastam** [hiddify/Hiddify-Manager#3982]
> Second Bug:
> After automatic Upgrade to the latest (10.10.17):
> one workers and one reallity works but, it shows my real ip.
> 
> Regards,

_Originally posted by @Eisahastam in https://github.com/hiddify/Hiddify-Manager/issues/3771#issuecomment-1987634413_

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
