### ISSUE TITLE
اپدیدت کردم فایل بک اپ بالا نمیاد 

### ISSUE THREAD

**Issue by alborz2103** [hiddify/Hiddify-Manager#3985]
سلام ممنون از زحماتتون 
من سرور رو اپدیت کردم بعد بالا نیومد مجبور شدم دباره نصب کنم نسخه که بودم  v10.12.1بودم 
فایل بک اپ رو بعد از نصب ورژن جدید  نمیشه وارد کرد لطفا کمک کنید یا راهنمایی

**Comment by The-Mj-01** [comment]
این مشکل برای من هم وجود داره من از ورژن ۸ پنل به ورژن ۱۰.۲۰.۴ آپدیت کردم.

**Comment by ReturnFI** [comment]
سلام.
مشکل در آخرین ریلیز برطرف شده ، آپدیت کنید به آخرین نسخه ریلیز.
صمیمانه پیشنهاد میکنم مشکل خودتون را با ذکر جزییات در گروه تلگرام هیدیفای و تاپیک مربوط به منیجر مطرح کنید تا همکارانم برای رفع مشکل شما را راهنمایی کنند.

[آدرس گروه تلگرام هیدیفای](https://t.me/hiddify_board)
