### ISSUE TITLE
عدم نمایش حجم و انلاینی کاربران

### ISSUE THREAD

**Issue by ojooubeh** [hiddify/Hiddify-Manager#3987]
نسخه 10.20.4
Os:  Ubuntu 22

پس از مدتی نمایش حجم و آنلاینی کاربران از کار میوفته و حتما باید ریست سیستم بزنیم که برای مدتی دیگه ، حداکثر چند ساعت مشکل برطرف بشه

**Comment by ReturnFI** [comment]
سلام.
به آخرین نسخه ریلیز آپدیت بفرمایید مشکل اکانتینگ برطرف شده.
موفق باشید.
