### ISSUE TITLE
اضافه شدن راهنمای احراز هویت مبتنی با کلید در گیتهاب هیدیفای

### ISSUE THREAD

**Issue by Mohammad9964** [hiddify/Hiddify-Manager#3989]
سلام 
تو راهنمایی که تو گیتهاب هست برای احراز هویت مبتنی بر کلید ، یک مشکلی هست
در اجرای دستور
ssh-copy-id username@your_server_ip
اگر پورت عوض شده باشه حتما باید دستور
ssh-copy-id -p YOURPORT root@your_server_ip
استفاده بشه
و اگر دستور بالا رو انجام دادید و در اخر باز هم از شما پسورد خواست و نتونستین وارد مرحله بعد بشید باید از دستور زیر به جای دستور بالا استفاده کنید

cat ~/.ssh/id_rsa.pub | ssh -p YOURPOT root@ your_server_ip 'cat >> ~/.ssh/authorized_keys'

دستوری که نوشتم بنظرم باید تو گیتهاب قرار بگیره
با زدن دستور بالا مشکلتون حل میشه و میتونید وارد مرحله بعدی یعنی 
خاموش کردن 
PasswordAuthentication
بشید

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
