### ISSUE TITLE
محدود کردن کاربر به یک دستگاه

### ISSUE THREAD

**Issue by BloodhoundAllfather** [hiddify/Hiddify-Manager#3991]
سلام

میخواستم بپرسم که آیا میشه یک کاربر رو محدود به یک دستگاه در آن واحد کرد؟ یعنی کاربر در هر لحظه فقط از یک دستگاه قابل استفاده از سرور رو داشته باشه. ممکنه همچین چیزی؟

با تشکر

**Comment by litoosh13** [comment]
سلام 
خیر امکانش نیست
