### ISSUE TITLE
CPU 100% Usage

### ISSUE THREAD

**Issue by Mehdisharbaf** [hiddify/Hiddify-Manager#3992]
# Bug:
با یک کاربر cpu 100 شده !

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-25-generic-x86_64-with-glibc2.35
**User Agent**:      AWS

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager

**Comment by xiaobai01111** [comment]
hiddify 2.1.1 CPU占用100%  系统代理，VPN一样。
