### ISSUE TITLE
امکان تعیین حجم مصرفی برای ادمین Agent و عدم دسترسی ادمین Agent به حذف کاربر

### ISSUE THREAD

**Issue by jamali-amirhossein** [hiddify/Hiddify-Manager#3994]
با سلام و احترام خدمت دولوپر عزیز هیدیفای
لطفا امکان تعیین حجم مصرفی و محدودیت حجم مصرفی برای نقش های ادمین زیر مجموعه خصوصا نقش ادمین Agent اضافه کنید.
و یک نقش ادمین اضافه شود که فقط بتواند کاربر اضافه کند و نتواند کاربر ایجاد کرده را حذف کند و یا این قابلیت را به نقش Agent اضافه کنید.
سپاس و درود فراوان

**Comment by litoosh13** [comment]
فعلا امکانش نیس
