### ISSUE TITLE
Database upgrade v78 is broken

### ISSUE THREAD

**Issue by atomic-dz** [hiddify/Hiddify-Manager#3995]
The main trouble is in non-starting hiddify-panel.
Because of this - not generating configs for all other modules.
Give those commands

`cd /opt/hiddify-manager/hiddify-panel`
`/opt/hiddify-manager/hiddify-panel/app.py`

It will give you the error:

> (MySQLdb.OperationalError) (1091, "Can't DROP INDEX 'name'; check that it exists")
> [SQL: ALTER TABLE child DROP INDEX 'name';]
> (Background on this error at: https://sqlalche.me/e/20/e3q8)
> Updating db from version 77 for node 0
> Traceback (most recent call last):
>   File "/opt/hiddify-manager/hiddify-panel/app.py", line 6, in <module>
>     bjoern.run(wsgi_app=hiddifypanel.create_app(), host="127.0.0.1", port=9000)
>   File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 76, in create_app
>     init_db()
>   File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/init_db.py", line 692, in init_db
>     db_action(child.id)
>   File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/init_db.py", line 51, in _v78
>     root_child_unique_id = Child.query.filter(Child.name == "Root").first().unique_id
> AttributeError: 'NoneType' object has no attribute 'unique_id'

Don't look at MySQL error, it's not a problem.
Main trouble is here:

>   File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/init_db.py", line 51, in _v78
>     root_child_unique_id = Child.query.filter(Child.name == "Root").first().unique_id
> AttributeError: 'NoneType' object has no attribute 'unique_id'

If you look at mysql table "child" you will see that "name" has NULL value.

`select name from child;`

> +------+
> | name |
> +------+
> | NULL |
> +------+
> 1 row in set (0.000 sec)
> 

Just need to update it to "Root";
<img width="374" alt="Screenshot_10" src="https://github.com/hiddify/Hiddify-Manager/assets/11003/a222d14c-75d1-4414-a027-9ed7f7e76f5e">

After this you can "Apply configs"
And "Upgrade".

The panel will make all configs and will start.

Somebody, need to fix it in the update script.

_Originally posted by @atomic-dz in https://github.com/hiddify/Hiddify-Manager/issues/3895#issuecomment-2057727526_

**Comment by meokey** [comment]
I encounter the same issue too

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
