### ISSUE TITLE
Hysteria Obscured Configuration Error

### ISSUE THREAD

**Issue by YZFTM** [hiddify/Hiddify-Manager#3996]
When the configuration option for enabling hysteria obfuscation (config.hysteria_obfs_enable.label) is turned off, the obfuscation feature is not properly disabled upon importing the subscription into alternative proxy applications.
![20240416](https://github.com/hiddify/Hiddify-Manager/assets/47804325/fa7914fe-d11b-45dc-bfc6-d5f992be5ccc)

**Comment by Iam54r1n4** [comment]
Please describe your problem completely.
