### ISSUE TITLE
نسخه ۱۰.۲۰.۴ بشدت مصرف سی پی یو را بالا برده است

### ISSUE THREAD

**Issue by mashtiali2023** [hiddify/Hiddify-Manager#3999]
سلام

این نسخه بشدت مصرف cpu را بالا برده است تقریبا با تعداد کاربر مشابه و حجم مصرف که تغییری نکرده بیش از ۲ برابر زیاد شده است.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
