### ISSUE TITLE
قطعی بعد از ریست کاربر

### ISSUE THREAD

**Issue by harnid** [hiddify/Hiddify-Manager#4000]
سلام خسته نباشین
ی باگ که نسخه آخر ریلیز داره اینه که بعد از ریست حجم و زمان کاربر همون شب کانفیگش دیسیبل میشه
و باید بری یبار تیک انیبل رو غیرفعال و دوبار فعال کنی
فقط یکبار برای هر کاربر ک ریست میکنی این اتفاق میافته
سرور رو ریبیلد هم کردم بازم باگش هست.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
