### ISSUE TITLE
مشکل v2rayng  با فرگمنت

### ISSUE THREAD

**Issue by erfanye96** [hiddify/Hiddify-Manager#4002]
سلام وقت بخیر
میخواستم بدونم چه زمانی با لینک سابسکریپشن معمولی (نه برنامه خود هیدیفای و نه لینک های اتو و جیسون و ...) میتونیم به صورت فرگمنت در v2rayng استفاده کنیم؟
به عبارت دیگه تو برنامتون هست ک ایا فرگمنت پنل (لینک سابسکریپشن) رو با فرگمنت v2rayng  سازگار کنید یا خیر؟ که با لینک سابسکریپشن معمولی و فرگمنت روشن پنل ، فرگمنت v2rayng  هم روشن بشه
ممنون از تمام زحماتتون

**Comment by Iam54r1n4** [comment]
درود، در حال حاضر این امکان پیاده سازی شده.
شما میتونید لینک سابسکریپشن Full Xray رو به کلاینت V2rayng بدید تا fragmentation سمت کلاینت به طور خودکار با توجه به مقادیری که داخل پنل تنظیم کردید اعمال بشه.

همچنین این امکان وجود داره، شما لینک Auto بدید.
در این صورت اگر درخواستی که به سرور میاد، مقدار User Agent اش با V2rayng شروع بشه. و همچنین ورژن V2rayng از [Xray sub](https://github.com/2dust/v2rayNG/pull/2827#issue-2127534078) پشتیبانی کنه، کانفیگی که به کلاینت داده میشه دارای مقادیر فرگمنتیشن های پنل هست.
(تمام اینها در صورتی اتفاق میوفته که شما فرگمنت رو در پنل فعال کرده باشید)

کلاینت V2rayng از [این ورژن](https://github.com/2dust/v2rayNG/pull/2827) از چنین کانفیگ هایی پشتیبانی میکنه (با تشکر از @vfarid)

**Comment by erfanye96** [comment]
ممنون از پاسخگوییتون
بله از دو لینک مذکور با خبر بودم
ولی چون لینک سابسکریپشن معمولی داده بودم به یوزرام و نمیتونم عوض کنم میخواستم بدونم تو برنامتون هست که لینک ساب معمولی رو هم با v2rayng هماهنگ کنید ک فرگمنت رو از سمت کلاینت روشن کنه یا خیر؟ اگر بله چه زمانی میشه حدودا؟

**Comment by erfanye96** [comment]
من معذرت میخوام بابت سوال نامفهومم
بنده لینکی که الان ضمیمه این پیام کردم رو فقط به یوزرام دادم و امکان تغییر اون به انواع دیگر (اتو و xray و ... ) رو ندارم
زمانیکه از پنل فرگمنت رو روشن میکنم در نرم افزار استریسند شناسایی میشه و فرگمنت کلاینت هم روشن میشه ولی فعلا این لینک مذکور در v2rayng کار نمیکنه چون نمیتونه اتومات فرگمنت رو شناسایی و روشن کنه
سوالم این هست ایا امکان این هست در آپدیت های اینده این لینک به همراه فرگمنت روشن پنل با نرم افزار مشخصا v2rayng سازگار بشه؟
یعنی لینک رو وارد v2rayng کنن و نرم افزار فرگمنت رو شناسایی کنه و اتومات برای لینک ما روشنش کنه؟
جسارتا من فقط در مورد لینک عکس ضمیمه شده صحبت میکنم
ممنون بابت زحماتتون

**Comment by erfanye96** [comment]
ببخشید این فایل ضمیمه پیام قبلی
![Capture](https://github.com/hiddify/Hiddify-Manager/assets/123875669/dbf0ddf8-dd5d-46e6-b706-a1c3b6a959a0)
