### ISSUE TITLE
خطای ایجاد کاربر در هنگام استفاده با api

### ISSUE THREAD

**Issue by rezahajrahimi** [hiddify/Hiddify-Manager#4009]
# Bug/Feature:
موقع ایجاد کاربر با استفاده از api استاتوس کد 500 همراه با پیام     "msg": "'NoneType' object has no attribute 'name'" برگشت داده می شود و کاربر جدیدی با نام unknown افزوده می شود در صورتیکه در نسخه قبلی چنین خطایی وجود نداشت.
## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
این مشکل به ظور خاص در اپدیت بعدی حل میشه.

**Comment by soroshzzz26** [comment]
سلام. وقت بخیر
ما هم این مشکل رو داریم
کی حل میشه؟

**Comment by rbsdotnet** [comment]
> این مشکل به ظور خاص در اپدیت بعدی حل میشه.

این مشکل کی حل میشه؟

**Comment by Iam54r1n4** [comment]
به زودی D:
