### ISSUE TITLE
Warp error

### ISSUE THREAD

**Issue by MrLlnux** [hiddify/Hiddify-Manager#4013]
####75####Applying...####Warp####
===========================================================
===run.sh other/warp
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
mv: cannot stat 'wgcf-account.toml': No such file or directory
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
mv: cannot stat 'wgcf-account.toml': No such file or directory
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
!!!!!!!!!!!!!!! WARP ERROR

**Comment by nimbold** [comment]
I have the same problem.

**Comment by Alijm05** [comment]
same issue

**Comment by papampi** [comment]
Same as #4047

**Comment by Alijm05** [comment]
i'm late ik ), i hope this helps...

it depends on your provider, some of the companies will add some network configurations while initializing & setup the server, you may investigate and check the following:

if system-resolved == enabled - (check by this "resolvectl status")
then check these files : 
/etc/systemd/resolved.conf
/etc/systemd/resolved.conf.d/

else if netplan in use :
/etc/netplan/

please for further information about dealing with and applying modifications on all previous mentions, check the internet or get assistance with chatGpt.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
