### ISSUE TITLE
Status active, admin link not working. Error: Gateway time out

### ISSUE THREAD

**Issue by pandaaxi** [hiddify/Hiddify-Manager#4018]
**Describe the bug**
Install on ubuntu 22.04. with one script install. after finished it's respawned with status active and admin link. Yet when i try to access the link on browser it's showing Gateway time out.
**To Reproduce**

**Expected behavior**
it's should show 'Hiddify Panal'

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/127378505/e0eaf992-0b68-4205-8e25-b104519d345a)
![image](https://github.com/hiddify/Hiddify-Manager/assets/127378505/c4f3d472-d02c-4f63-8d69-2fe609a7dfb2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Recoba86** [comment]
I Have the Same Problem!

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
