### ISSUE TITLE
cant install for docker

### ISSUE THREAD

**Issue by Viknopx** [hiddify/Hiddify-Manager#4020]
**Describe the bug**

When installing using Docker mode, the build failed and kept getting stuck with the following error message:

 => CACHED [4/6] COPY . .                                                             0.0s 
 => [5/6] RUN bash install.sh install-docker                                        471.4s 
 => => # s                                                                                 
 => => # Successfully installed argparse-1.4.0 asyncio-3.4.3 cli_progress-2.0.0 typing-exte
 => => # urwid-2.6.10 wcwidth-0.2.13                                                       
 => => # WARNING: Running pip as the 'root' user can result in broken permissions and confl
 => => # ur with the system package manager. It is recommended to use a virtual environment
 => => # s://pip.pypa.io/warnings/venv                                                     

**To Reproduce**
1. According to the document“ https://hiddify.com/manager/installation-and-setup/Install-Hiddify-using-Docker/ “

**Expected behavior**
finsh installation.

**Screenshots**
<img width="746" alt="image" src="https://github.com/hiddify/Hiddify-Manager/assets/27153268/676d3bd9-8ac6-48bb-961c-f58ed14669ae">

**Desktop (please complete the following information):**
 - OS: [ubuntu 22]
 - Docker [Version: 24.0.2]

**Comment by q2333gh** [comment]
Same issue as above. seems stuck at warning process ?

**Comment by zx900930** [comment]
if you edit the Dockerfile, you can see what the detail error is:
```
Step 11/13 : RUN sh -x ./install.sh install-docker
 ---> Running in 84703d1dac6c
+ dirname -- ./install.sh
+ cd .
+ source ./common/utils.sh
./install.sh: 3: source: not found
+ NAME=0-install
+ log_file 0-install
./install.sh: 5: log_file: not found
+ LOG_FILE=
+ [ ! -d /opt/hiddify-manager/ ]
+ [ ! -d /opt/hiddify-manager/ ]
+ export DEBIAN_FRONTEND=noninteractive
+ id -u
+ [ 0 -ne 0 ]
./install.sh: 22: Syntax error: "(" unexpected
The command '/bin/sh -c sh -x ./install.sh install-docker' returned a non-zero code: 2
```

**Comment by zx900930** [comment]
After debug, the error was:
```
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)  
stty: 'standard input': Inappropriate ioctl for device
Enter current password for root (enter for none):
```
Apparently, if you run this script using root user, you'll need to pass the root password to MariaDB setup

**Comment by UdoChudo** [comment]
> After debug, the error was:
> 
> ```
> ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)  
> stty: 'standard input': Inappropriate ioctl for device
> Enter current password for root (enter for none):
> ```
> 
> Apparently, if you run this script using root user, you'll need to pass the root password to MariaDB setup

Is you find solution ? would you explain what we need to change or doing step by step?

**Comment by vincent1890** [comment]
up

**Comment by litoosh13** [comment]
we notice this problem...we will look into it
