### ISSUE TITLE
عدم نمایش آخرین اتصال کاربران

### ISSUE THREAD

**Issue by Gold-IP** [hiddify/Hiddify-Manager#4022]
آخرین اتصال کاربران نمایش داده نمیشه همه رو زده آخرین اتصال یک هفته پیش. هرچی هم آپدیت زدم و هیدیفای رو حذف و مجدد نصب کردم مشکل رفع نشد

**Comment by ghostmcf** [comment]
راه حلش پیدا شد؟

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
