### ISSUE TITLE
خطای نصب در کلود کانفیگ

### ISSUE THREAD

**Issue by sspoormosavi** [hiddify/Hiddify-Manager#4023]
پس از نصب در کلود کانفیگ با خطای زیر مواجه میشوم: 

500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file connect-failed or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
