### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by mohamad2583247** [hiddify/Hiddify-Manager#4024]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-100-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by mohamad2583247** [comment]
ببخشید قسمت کابران وقتی زمان کاربر تمام میشه در برنامه هیدیفای نکست روی ‍‍‍پروفایل کاربرمیزنه منقضی ولی باز می تونه اتصال داشته باشه وتا داخل پنل تیک فعال بودن برنداری پیغام اتمام مهلت نمایش داده نمیشه بعد باید بریم داخل پنل و تیک فعال بودن برداریم این بار  دیگه درست میشه و می خواستم بدونم نمیشه در قسمت زمان کاربر تقویم داشته باشیم مثلا تقویم شمسی مثلا مثل پنل ثنایی یا علیرضا

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
