### ISSUE TITLE
Using both Arvancloud and cloudflare.com 

### ISSUE THREAD

**Issue by Sadegh-Kalami** [hiddify/Hiddify-Manager#4028]
سلام 
با تشکر از زحمات ارزشمند شما.
من یک دامنه مخصوص cloudflare گرقتم و از cdn استفاده کردم.
یک دامنه دیگر گرفتم و از arvancloud خواستم استفاده کنم اما کانفیگ‌ها کار نمیکنه. درحالی که صفحه ادمین رو به خوبی میاره.
ممنون بشم راهنمایی کنید

**Comment by litoosh13** [comment]
arvancloud 
توسط ما ساپورت نمیشود
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
