### ISSUE TITLE
Version 10.20.4 - Subscription Error

### ISSUE THREAD

**Issue by Sooshka-X** [hiddify/Hiddify-Manager#4032]
Hello,
Version 10.20.4 has a problem with Subscription, especially with TD-LTE Irancell and none of the configurations works.
Regards,

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
