### ISSUE TITLE
عدم امکان انتخاب یک نوع پروتوکل مجزا برای یک دامنه

### ISSUE THREAD

**Issue by alisadeghi1997** [hiddify/Hiddify-Manager#4037]
سلام 
مشکل رو داخل گروه تلگرام بیان کردم متاسفانه تا سه روز محدودم کردن و این از تیم هیدیفای بعیده که بجای گرفتن باگ ها و مشکلات میاد سه روزم محدود میکنه بگذریم
مشکلی که هست اینه
وقتی دو دامنه ثبت میکنیم یکی یرای تانل که بصورت ریلی ثبت شده و یکی بصورت مستقیم با ای پی سرور ثبت شده ،
نمیتونیم انتخاب کنیم که دامنه مستقیم داخل لینک ساب فقط بصورت ویمس tcp باشه یا دامنه ریلی  فقط بصورت ویمس ws داخل لینک ساب اد بشه 
زمانی که دو دامنه ثبت میشه و دو گزینه ویمس tcp ، ws فعال میشه ،داخل لینک ساب ۴ عدد کانفیگ اضافه میشه که دوتا ws هست دو تا tcp  و این باعث میشه اولا کانفیگا زیاد بشن که کاربرارو گیج میکنه دوما کانفیگ ویمس tcp که ناخواسته برای دامنه ریلی ساخته شده و داخل لینک ساب اد شده باعث فیلتر شدن دامنه یا ای پی میشه و کانفیگ ویمس ws که برای دامنه مستقیم ناخواسته داخل لینک ساب اد میشه باعث فیلتر سدن دامنه یا ای پی مستقیم میشه.
لطفا این قابلیت رو اضافه کنید که بتونیم دامنه با پروتکلی که مد نظرمونه اضافه کنیم مثلا دامنه یکفقط  ویمس tcp براش فعال بشه و دامنه دو فقط ویمس ws فعال بشه 
اینجور نباشه با فعال شدن گزینه ویمس ws,tcp  برای هر دامنه یه ws یه tcp  بسازه

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
