### ISSUE TITLE
fragment

### ISSUE THREAD

**Issue by erfanye96** [hiddify/Hiddify-Manager#4039]
سلام وقتتون بخیر
ممنون بابت تمام زحماتتون

بنده لینکی که الان ضمیمه این پیام کردم رو فقط به یوزرام دادم و امکان تغییر اون به انواع دیگر )اتو و xray و ... ) رو ندارم.
زمانیکه از پنل فرگمنت رو روشن میکنم در نرم افزار استریسند برای ios شناسایی میشه و فرگمنت کلاینت هم روشن میشه ولی فعلا این لینک مذکور در v2rayng کار نمیکنه چون نمیتونه اتومات فرگمنت رو شناسایی و روشن کنه.
خواهشم اینه لطفا در آپدیت اینده کاری کنید این لینک به همراه فرگمنت روشن پنل با نرم افزار مشخصا v2rayng سازگار بشه؟
یعنی لینک رو وارد v2rayng کنن و نرم افزار، فرگمنت رو شناسایی کنه و اتومات برای لینک ما روشنش کنه؟
جسارتا من فقط در مورد لینک عکس ضمیمه شده صحبت میکنم
![324600081-dbf0ddf8-dd5d-46e6-b706-a1c3b6a959a0](https://github.com/hiddify/Hiddify-Manager/assets/123875669/45f66f6b-1d56-46f1-8e06-969828092c4f)

**Comment by Iam54r1n4** [comment]
شما سابسکریپشنی رو به کاربرهاتون دادید که به طور مشخص نوع خاصی از کانفیگ رو در جواب میده. و امکان این وجود نداره که فقط چون شما چنین مشکلی رو دارید, چنین تغییری رو بدیم.
سابسکریپشن auto دقیقا برای چنین مواردی ایجاد شده که بر اساس درخواست هر کلاینت بهترین کانفیگ ممکن رو در جواب بده.
این ایشو بسته میشه.
