### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Clonner07** [hiddify/Hiddify-Manager#4042]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-25-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Clonner07** [comment]
سلام پنل هدیفای من اصلا مصرف حجم رو نشون نمیده ممنون میشم راهنمایی کنین

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
