### ISSUE TITLE
an important service hiddify-haproxy is not working again Installation Failed!

### ISSUE THREAD

**Issue by hesanf** [hiddify/Hiddify-Manager#4044]
installation failed
reinstalling not worked either

also logs of haproxy doesnt have any useful info

**Comment by Abdipour** [comment]
I had the same problem. The problem was the port settings. Tuic port port should be number only. In the hint, multiple ports should be separated with a comma, but you can enter only one number. Finally I had to change the port into the database manually.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
