### ISSUE TITLE
هیستریا

### ISSUE THREAD

**Issue by Mahdi7b** [hiddify/Hiddify-Manager#4046]
مثل ریالتی، دامنه های هیستریا رو هم از بقیه دامنه ها مستقل کنید، من الان میخوام یه دامنه مستقیم برای تانل اضاف کنم ولی هیستریا هم روی اون دامنه فعال میشه و این مشکل سازه. و همیچنین دامنه ای که برای هیستریا معرفی شده هم همراه با کانفیگ تانل که مستقیم هست میاد و باعث لو رفتن ip سرور میشه که این دیگه خیلی خیلی مشکل سازه

راستی یه مشکل دیگه که با هیستریا دارم اینکه هیستریا روی ip شناور کار نمیکنه

**Comment by Mahdi7b** [comment]
راستی یه مشکل دیگه که با هیستریا دارم اینکه هیستریا روی ip شناور کار نمیکنه

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
