### ISSUE TITLE
Warp Status

### ISSUE THREAD

**Issue by Sooshka-X** [hiddify/Hiddify-Manager#4047]
Hello,
I enable warp with the key. When I checked the status  of the system in the server's terminal it showed me this message:
"- Warp Status:
  - Profile:
        status.sh: line 9: wgcf: command not found "
## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:"Ubuntu 22.04.4 LTS"    Linux-5.15.0-105-generic-x86_64-with-glibc2.35

**Comment by Mahdar62** [comment]
Hello
I have this problem too

**Comment by FaRaZ-M** [comment]
same here

**Comment by rezabagh** [comment]
same issue

**Comment by zekerya** [comment]
same here

**Comment by mr-mamali** [comment]
**same here**

**Comment by Alijm05** [comment]
same issue

**Comment by alireza-brz** [comment]
Same problem and I solve it with reinstalling the hiddify
reinstall the hiddify from the actions menu. the reinstall process will not remove your data, it  reinstall the packages only.

**Comment by Alijm05** [comment]
> Same problem and I solve it with reinstalling the hiddify reinstall the hiddify from the actions menu. the reinstall process will not remove your data, it reinstall the packages only.

this didn't work for me, but I came up with another solution, and all work now
i was thinking about posting the whole solution procedure(i don't have that much time tho '] ), but if only the 'reinstallation' doesn't work for some of you >>>then i guess i can provide mine

**Comment by sadidshop** [comment]
> Same problem and I solve it with reinstalling the hiddify reinstall the hiddify from the actions menu. the reinstall process will not remove your data, it reinstall the packages only.

ممنون بابت پیشنهادت، مشکل من رو حل کرد
جالبه ری اینستال از طریق ترمینال مشکل رو حل نکرد ولی از قسمت اکشن/نصب مجدد اوکی شد
ممنون رفیق

**Comment by papampi** [comment]
> > Same problem and I solve it with reinstalling the hiddify reinstall the hiddify from the actions menu. the reinstall process will not remove your data, it reinstall the packages only.
> 
> this didn't work for me, but I came up with another solution, and all work now i was thinking about posting the whole solution procedure a few days ago(i don't have that much time tho '] ), but if only the 'reinstallation' doesn't work for some of you >>>then i guess i can provide mine

Reinstall didn't work for me, can you explain how to solve this issue?

**Comment by papampi** [comment]
Reinstall shows wgcf-accoint.toml missing, anyway I can create and add it manually?

```
===run.sh other/warp
Checking WARP ...
mv: cannot stat 'wgcf-account.toml': No such file or directory
Generating WARP config...
Removing IPV6 from WARP...
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@warp.service → /lib/systemd/system/wg-quick@.service.
Job for wg-quick@warp.service failed because the control process exited with error code.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
Starting WARP.... checking real connectivitiy
WARP is not working!
Checking real connectivitiy again!
WARP is not working!
```

**Comment by Alijm05** [comment]
> > > Same problem and I solve it with reinstalling the hiddify reinstall the hiddify from the actions menu. the reinstall process will not remove your data, it reinstall the packages only.
> > 
> > 
> > this didn't work for me, but I came up with another solution, and all work now i was thinking about posting the whole solution procedure a few days ago(i don't have that much time tho '] ), but if only the 'reinstallation' doesn't work for some of you >>>then i guess i can provide mine
> 
> Reinstall didn't work for me, can you explain how to solve this issue?

i'm late ik ), i hope this helps...

it depends on your provider, some of the companies will add some network configurations while initializing & setup the server, you may investigate and check the following:

if system-resolved == enabled - (check by this "resolvectl status")
then check these files : 
/etc/systemd/resolved.conf
/etc/systemd/resolved.conf.d/

else if netplan in use :
/etc/netplan/

please for further information about dealing with and applying modifications on all previous mentions, check the internet or get assistance with chatGpt.

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
