### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Javadwebs** [hiddify/Hiddify-Manager#4050]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-94-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

بخش اتصال به ای پی های کلود فلر اوکی نیست ، خودکار ای پی عوض نمیشه و قرارش نمیده ای پی ها رو

**Comment by litoosh13** [comment]
به آخرین نسخه آپدیت نمایید
آموزش نصب و کانفیگ صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
