### ISSUE TITLE
help me,my website can't open wen I setup this services on my vps

### ISSUE THREAD

**Issue by xkdopod** [hiddify/Hiddify-Manager#4053]
"After I installed this software on my VPS, my website couldn't open at all and kept showing 404 errors. Then, when I logged into the server, I saw this prompt. How can I resolve this issue so that my website can open normally again?" hao solve it???
![4000](https://github.com/hiddify/Hiddify-Manager/assets/35407030/d109920f-9dca-4aa2-9c68-59fa52646992)

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning material about the  panel here:
hiddify.com/manager
hiddify.com/fa/manager
