### ISSUE TITLE
error warp

### ISSUE THREAD

**Issue by alishmaste** [hiddify/Hiddify-Manager#4055]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-105-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
درود  بر شما خسته نباشید
شرمنده ما وقتی میخوایم توی وارپ گوگل رو پاک کنیم نمیشه و دوباره خودش اتومات اد میکنه مشکلش چیه؟

**Comment by Iam54r1n4** [comment]
اگه منظورتون این هست که فایل
```bash
/opt/hiddify-manager/xray/configs/03_routing.json
 ```
 رو تغییر میدید. اما با اپلای کانفیگ کردن، باز مقادیر قبلی جایگزین میشد. شما باید فایل:
 ```bash
 /opt/hiddify-manager/xray/configs/03_routing.json.j2
 ```
 رو تغیر بدید.
