### ISSUE TITLE
WARP

### ISSUE THREAD

**Issue by zekerya** [hiddify/Hiddify-Manager#4057]
با فعال کردن وارپ برای سایتهای داخلی کل کانفیگها از کار میفتن. با تعویض ای پی سرور و کلید وارپ مشکل حل نشد.
ورژن آخر پنل 10.20.04 
با دستور تعویض ای پی وارپ این ارور میاد:
Your current WARP IP is 
new IP  is the same as the previous one  
new IP  is the same as the previous one  
new IP  is the same as the previous one  
new IP  is the same as the previous one  
new IP  is the same as the previous one  
Job for wg-quick@warp.service failed.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.
new IP  is the same as the previous one  
Job for wg-quick@warp.service failed.
See "systemctl status wg-quick@warp.service" and "journalctl -xeu wg-quick@warp.service" for details.

**Comment by litoosh13** [comment]
به اخرین نسخه آپدیت نمایید
نحوه صحیح نصب و کانفیگ پنل:
hiddify.com/manager
hiddify.com/fa/manager
