### ISSUE TITLE
اضافه کردن

### ISSUE THREAD

**Issue by asghar61** [hiddify/Hiddify-Manager#4059]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-105-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
سلام . اول اینکه یکم پنل کلا کنده و سرعت خوبی تو تعویض منو ها نداره . دوم مثل پنل سنایی کاری کنین که بشه با pihole اونو تو میکروتیک نصب کرد و یه قابلیت هم اضافه کنید که بشه با پورت خاصی محدودید ایجاد کنیم . مثلا اگر کاربر با فلان پورت متصل بشه نتونه محتوی بزرگسال رو ببینه .

**Comment by litoosh13** [comment]
به اخرین نسخه اپدیت کنید لطفا
