### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by hbagheri** [hiddify/Hiddify-Manager#4061]
# Bug/Feature:
**Description**:     افزودن shortlink  در بخش ربات برای شروع ساخت کانفیگ جدید
## Details:
از آنجا که هر ۶ ساعت یک لینک جدید داونلود کانفیگ ارسال میشه، دسترسی به منوی ساخت کانفیگ گم میشه.
لطفا یک لیک مثلا /new_config به منوهای پیشفرض ربات اضافه کنید.
با سپاس از اجرای عالی پروژه

**Comment by litoosh13** [comment]
به اخرین نسخه اپدیت کنید و مجدد ایشو بزنید
