### ISSUE TITLE
an important service hiddify-xray is not working again Installation Failed!

### ISSUE THREAD

**Issue by javadlive** [hiddify/Hiddify-Manager#4065]
an important service hiddify-xray is not working again Installation Failed!
![Screenshot 2024-05-05 095631](https://github.com/hiddify/Hiddify-Manager/assets/117009351/f16e060d-8bc4-4c4b-b18b-46e2d6226b11)

**Comment by ghl528** [comment]
me too

**Comment by 1razzaghi** [comment]
i have the same error
reinstall the script on fresh server solved mine
