### ISSUE TITLE
Unfortunately, you did not provide the new eternity for Android, HiFi is having problems connecting to sites, try a little more and thank you.

### ISSUE THREAD

**Issue by Nato9024** [hiddify/Hiddify-Manager#4073]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Yousef22ka** [comment]
_****_

**Comment by Yousef22ka** [comment]
0
