### ISSUE TITLE
What is structure of a subscription link provided by hiddify manager to limit time and traffic usage in client?

### ISSUE THREAD

**Issue by mmahdium** [hiddify/Hiddify-Manager#4074]
Hi, I hope you are doing well.
What is the structure of the subscription link provided by the Hiddify manager to limit time and traffic usage by clients?
Is it in a JSON structure?
Unfortunately, I don't have access to any Hiddify manager instance to find it by myself.

**Comment by litoosh13** [comment]
hi
you could look through the code, the out project is open source
