### ISSUE TITLE
Uninstall  Hiddify-Manager will cause existing  python(like user already install python3 before install Hiddify-Manager) be uninstalled.

### ISSUE THREAD

**Issue by q2333gh** [hiddify/Hiddify-Manager#4075]

**Comment by easymoney322** [comment]
I believe same goes for NginX

**Comment by easymoney322** [comment]
I re-checked with container, and the installed version of python doesn't rather doesn't get deleted by purge, so even if you had no `python-3.10` prior to intstallation and only had 3.12, you are left with both versions. But the nginx, however, gets deleted by the purge operation, even if it was installed manually before the hiddify.


I would send bash output, but hiddify clears console like 3 times during purge, so I wont bother.
