### ISSUE TITLE
Can I test `Hiddify-Manager` installation command in a docker container ? :  `bash <(curl i.hiddify.com/release)`

### ISSUE THREAD

**Issue by q2333gh** [hiddify/Hiddify-Manager#4076]
container version ubuntu2204

But got err report:

```
...
▒│ sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) 
(2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)") 
...
```

**Comment by q2333gh** [comment]
Also worth to mention that .  During installation procedure:
If got any err cause. should the rest of code abort ?
While current script is still all continuing.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
