### ISSUE TITLE
Wrong notification about updating....

### ISSUE THREAD

**Issue by SamParklcf** [hiddify/Hiddify-Manager#4085]
# Bug:
**Description**:     When you are in dashboard, it shows you a prompt to update the outdated Hiddify Manager version, but when we are going to update it, the manager said that you have already the latest version.

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-105-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
![01](https://github.com/hiddify/Hiddify-Manager/assets/75083627/288f4855-90ab-4f37-ba61-95a5af585d7d)
![02](https://github.com/hiddify/Hiddify-Manager/assets/75083627/41e3743b-8f45-41c8-a733-8aa73a0d4e8d)

**Comment by partzan** [comment]
This is happening on my Hiddify panel too

**Comment by Iam54r1n4** [comment]
Thanks a lot for reporting. It will be fixed in the next update.
