### ISSUE TITLE
حذف اکانت تلگرام کاربر

### ISSUE THREAD

**Issue by hbagheri** [hiddify/Hiddify-Manager#4089]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-106-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

گاهی با حذف و تغییر اکانت تلگرام از سوی کاربر، امکان ارسال پیام به کاربر از بین میرود. وجود این امکان که با دیدن نوتیفیکیشن عدم موفقیت ارسال پیام به کاربر، ادمین بتواند telegram id کار بر را حذف کند تا او بتواند دوباره با idجدبد ارتباط خود را درست کند مفید بنظر میرسد

**Comment by litoosh13** [comment]
بررسی می‌شود
