### ISSUE TITLE
Bug: "Can't connect to MySQL server on '127.0.0.1:3306' (111)"" on Amazon Lightsail (AWS)'s Ubuntu

### ISSUE THREAD

**Issue by userisuserisuser** [hiddify/Hiddify-Manager#4091]
1. Go to AWS's Lightsail
2. Create an Ubuntu 22.04 instance
3. Install Hiddify with `bash <(curl i.hiddify.com/release)`
5. After a while it says:

`sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1:3306' (111)")(Background on this error at: https://sqlalche.me/e/20/e3q8)`

**Comment by EdwardTan666** [comment]
i have also encountered this problem. How can i solve it

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
