### ISSUE TITLE
نوتیف دائمی به روز رسانی 

### ISSUE THREAD

**Issue by Toranj1** [hiddify/Hiddify-Manager#4099]
# Bug/Feature:
**Description**:     با اینکه هیدیفای منیجر رو آپدیت کردم ولی بازهم نوتیفیکیش میده : این نسخه هیدیفای قدیمی شده است. لطفا از پنل ادمین آن را به روزرسانی کنید

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-105-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
#4085
