### ISSUE TITLE
مشکل در اکانتینگ 

### ISSUE THREAD

**Issue by Ariannetflix** [hiddify/Hiddify-Manager#4101]
سلام. یه باگ در سیستم اکانتینگ هیدیفای نسخه 10.20.4 هست که با اینکه یوزر هم حجم دارد و هم زمان تمام کانکشن ها از سمت یوزر time out میده و این باگ با ریست کردن تنها زمان یوزر یا حتی تغییر زمان یوزر درست میشه اما مشکل چند روز بعد برای برخی اکانت ها برمیگرده. من نتونستم لاگی برای قسمت اکانتینگ پیدا کنم که مشکل رو نشون بده لاگ redis رو پایین میزارم. این لاگ بعد از ریستارت کردن هیدیفای هستش. 
![IMG_0569](https://github.com/hiddify/Hiddify-Manager/assets/158844334/ae28d2fb-e16a-41d6-b11c-4c8e7cbe5715)

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
