### ISSUE TITLE
تانل از سرور ایران به خارج

### ISSUE THREAD

**Issue by firemassod** [hiddify/Hiddify-Manager#4107]
با سلام
با نصب پنل روی سرور ایران و ساخت یوزر 
چجوری میتونم ترافیک رو به سرور خارج انتقال بدم؟
در واقع میخام یوزرها روی سرور ایران باشن

سوال دوم اینکه ایا امکان تغییر outbound در پنل هدیفای مثل پنل سنایی وجود دارد؟

**Comment by firemassod** [comment]
up

**Comment by firemassod** [comment]
یعنی هیچکس نیست اینو جواب بده

**Comment by litoosh13** [comment]
پیشنهاد نمیشه روی سرور ایران پنل رو نصب کنید
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
