### ISSUE TITLE
Opening the "copy link" modal is only for subscribe and config links

### ISSUE THREAD

**Issue by savyjs** [hiddify/Hiddify-Manager#4110]
# Problem:
**Description**:     

It's confusing for users when they click on a link and a modal appears. Many users get confused and end up copying the panel link instead of the intended link to their V2Ray Subscribe links. We need to simplify the UX and make it more straightforward for users to reach the point where they can easily copy the subscribe link. About 50% of my friends have copied either their panel link or incorrect links into their V2RayNG subscribe group.

## Details:
**Hiddify Version**: 10.20.4

**Suggestion:**

The previous versions of Hiddify, specifically versions before 8, had a better UI/UX for copying config links. I believe the new version has become too complex and intimidating for older and less experienced users. Please simplify it again to make it more accessible.
 
Open the 'Copy Link' modal only for subscribe/config links, not for users/admins/panel links.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
