### ISSUE TITLE
اشکال در اسکریپت نصب پنل

### ISSUE THREAD

**Issue by Armin-kho** [hiddify/Hiddify-Manager#4118]
**Describe the bug**

پس از پایان نصب پنل، لینک داده نمیشه و هنگام چک کردن وضعیت پنل بسیاری از سرویس ها در حالت Activating میمانند.
روش نصب سریع و اسان روی Hetzner و نصب اصلی روی ubuntu رو تست کردم خروجی یکسان بود.

**Screenshots**

![photo_2024-05-18_23-25-13](https://github.com/hiddify/Hiddify-Manager/assets/19794365/78cf05a3-ef29-4d3c-ab05-985849722ef0)

**Comment by Armin-kho** [comment]
ظاهرا با ابونتو نسخه 24 مشکل داره
روی ابونتو نسخه 22 نصب شد فقط وارپ درست نصب نمیشه

**Comment by Iam54r1n4** [comment]
در داکیومنت پروژه صراحتا نوشته شده که روی 22.04 تست شده.
لطفا از همین ورژن استفاده کنید.
وارپ هم مشکلی نداره، اما شما باید در تنظیمات اول واپ رو فعال کنید تا سرویس اکتیو بشه.
