### ISSUE TITLE
Singbox cpu usage is always at 100%

### ISSUE THREAD

**Issue by desprdo** [hiddify/Hiddify-Manager#4119]
**Describe the bug**
Singbox درحال استفاده از ۱۰۰ درصد سی پی یو

**To Reproduce**
چند ساعت بعد از ریبوت سیستم استفاده سینگ باکس از سی پی یو میچسبه به سقف, کلا هم کمتر از ۱۰ تا کاربر استفاده میکنن از سرویس. مشکلش چیه؟
**Screenshots**
![Screenshot_2024-05-19-14-08-03-628_com server auditor ssh client](https://github.com/hiddify/Hiddify-Manager/assets/80700894/89ed410c-d0f4-4220-a7b5-edfbd856e345)
این لاگو با journalctl -u hiddify-singbox گرفتم

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
