### ISSUE TITLE
سلام .حتما امکان تک کاربره و چند کاربره به پنل اضافه بشه 

### ISSUE THREAD

**Issue by hojjatrad** [hiddify/Hiddify-Manager#4124]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by TheMarwin** [comment]
هیدیفای با هسته Xray و Sing-Box کار می‌کنه 
و این قابلیت درابتدا نیازمند اضافه شدنش به هسته Xray هستش. سازندگان xray باید قابلیت چند کاربره کردن رو بهش اضافه کنم که ظاهراً احتمالش خیلی کمه
