### ISSUE TITLE
خطا در نصب

### ISSUE THREAD

**Issue by rbsdotnet** [hiddify/Hiddify-Manager#4125]
**Describe the bug**
اوبونتو 22.4 هست موقع نصب خطا در بخش MariaDB میده

**Additional context**
Thanks for using MariaDB!
MariaDB setup complete.
bind-address set to 127.0.0.1 in /etc/mysql/mariadb.conf.d/50-server.cnf
MariaDB service restarted
===========================================================
===========================================================
===install.sh hiddify-panel
Created symlink /etc/systemd/system/multi-user.target.wants/hiddify-panel.service → /opt/hiddify-manager/hiddify-panel/hiddify-panel.service.
str db_version not found
(MySQLdb.OperationalError) (1091, "Can't DROP INDEX `name`; check that it exists")
[SQL: ALTER TABLE child DROP INDEX `name`;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(MySQLdb.OperationalError) (1091, "Can't DROP COLUMN `connected_ips`; check that it exists")
[SQL: ALTER TABLE user_detail DROP COLUMN connected_ips;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(MySQLdb.OperationalError) (1091, "Can't DROP INDEX `name`; check that it exists")
[SQL: ALTER TABLE proxy DROP INDEX `name`;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(MySQLdb.OperationalError) (1054, "Unknown column 'monthly_usage_limit_GB' in 'user'")
[SQL: ALTER TABLE user RENAME COLUMN monthly_usage_limit_GB TO usage_limit_GB]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(MySQLdb.ProgrammingError) (1146, "Table 'hiddifypanel.dailyusage' doesn't exist")
[SQL: update dailyusage set child_id=0 where child_id is NULL]
(Background on this error at: https://sqlalche.me/e/20/f405)
(MySQLdb.ProgrammingError) (1146, "Table 'hiddifypanel.dailyusage' doesn't exist")
[SQL: update dailyusage set admin_id=1 where admin_id is NULL]
(Background on this error at: https://sqlalche.me/e/20/f405)
(MySQLdb.ProgrammingError) (1146, "Table 'hiddifypanel.dailyusage' doesn't exist")
[SQL: update dailyusage set admin_id=1 where admin_id = 0]
(Background on this error at: https://sqlalche.me/e/20/f405)
no backup found...
str db_version not found
Updating db from version 0 for node 0

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
