### ISSUE TITLE
یک مشکل امنیتی در api 

### ISSUE THREAD

**Issue by Alireza271** [hiddify/Hiddify-Manager#4128]
**Describe the bug**
یک مشکل امنیتی در api 

**To Reproduce**
در پاسخ api/v2/admin/me/

{
  "can_add_admin": false,
  "comment": "",
  "lang": "fa",
  "mode": "agent",
  "name": "Mojtaba",
  "parent_admin_uuid": "xxxxxxxxxxxxxxxxxx",
  "telegram_id": 0,
  "uuid": "xxxx"
}

parent_admin_uuid دارای مقدار میباشد که میتواند مشکل ساز شود

**Comment by Iam54r1n4** [comment]
Thanks, it'll be fixed in the next update.
