### ISSUE TITLE
مشکل دریافت گواهی ssl

### ISSUE THREAD

**Issue by RezaNaghideh** [hiddify/Hiddify-Manager#4131]
سلام خسته نباشید بعد از نصب پنل و دامین وقتی میخوام یه سرور میانی ایرانی رو با تانل متصل کنم به سرور اصلی همه کارها بدون خطا انجام میشه ولی در آخر دامین مربوط به سرور میانی گواهی ssl رو درایفت نمیکنه و پنل مدیریت در حالت http باز میشه و همین باعث میشه کانفینگ های تانل کار نکنن.
ممنون میشم اگر راهنمایی کنین

**Comment by Ariannetflix** [comment]
برای حلش باید توی سرور ایران با acme یا certbot برای همون دامنه یه cert بگیری و بعد اون فایلایی که نیازه توی سرور خارج توی فولدر ssl جایگزین کنی. ولی هردفعه که apply configs میزنی دوباره باید تعویض کنی من با chatgpt یه bash script نوشتم که خودش هرموقع دید سرتیفیکت تغییر کرده عوضش کنه.

**Comment by RezaNaghideh** [comment]
میشه لطفاً اسکریپت رو به اشتراک بزارین با نحوه کار کردنش؟
