### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by hojjatrad** [hiddify/Hiddify-Manager#4135]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
سلام 
متاسفانه کانفیگ های من اصلا در نرم افزار اضافه نمیشه و اعلام میکنه خطا رخ داد 
همه چی هم درسته 
ipهم مشکل نداره و
راهنمایی میفرمائید چیکارش کنم 
ممنونم

**Comment by Iam54r1n4** [comment]
امکان این هست که دامینی که استفاده میکنید فیلتر باشه.
در هر صورت ایشو های گیتهاب جای مناسبی برای این موضوع نیست. اینجا به مشکلات و باگ هایی که در سطح کد وجود داره رسیدگی میکنیم.
لطفا مشکل رو در کانال تلگرامی هیدیفای بازگو کنید.
