### ISSUE TITLE
Internal server error: Unknown

### ISSUE THREAD

**Issue by RustemAnn** [hiddify/Hiddify-Manager#4148]
# Internal Error Stacktrace:
**Error Message**:   'sub_full_singbox_enable' is not among the defined enum values. Enum name: configenum. Possible values: dbvalues, create_easy.., wireguard_e.., ..., path_grpc
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 150, in on_model_change
    configs = get_hconfigs()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/config.py", line 145, in get_hconfigs
    return {**{f'{u.key}' if json else u.key: u.value for u in BoolConfig.query.filter(BoolConfig.child_id == child_id).all() if u.key.type == bool},

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-75-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
Please rebuild your server and install the panel again.
