### ISSUE TITLE
Add new domain with special characters 

### ISSUE THREAD

**Issue by alix1383** [hiddify/Hiddify-Manager#4149]
I trying to add a new domain with special characters (ichikava.推の子.store) but it says the format of domain is wrong

**Comment by mahdipooryazdan** [comment]
درود مشکل برای اینه که باید کارکتر های دامین از استاندارد Ascii پشتیبانی کند
برای حل مشکل میتونید با کتابخونه idna فرمت دامنه رو به Punycode  تغییر دهید
