### ISSUE TITLE
2024新人，有vps怎样搭建一个安全的 网络环境？

### ISSUE THREAD

**Issue by GITHUBTONYFANG** [hiddify/Hiddify-Manager#4150]
习惯用v2ray

**Comment by cyberxsboy** [comment]
可以用梯子面板相关的一键脚本去搭建，好了之后，自己再去手动配置节点给自己用。

**Comment by Iam54r1n4** [comment]
In this repository, the main language is English. Do NOT speak in any language that the repository moderators or the majority of users cannot understand.
Thanks.

**Comment by GITHUBTONYFANG** [comment]
> In this repository, the main language is English. Do NOT speak in any language that the repository moderators or the majority of users cannot understand. Thanks.

我喜欢用中文，怎么啦，显示你英文很好呗
