### ISSUE TITLE
API Cloudflare

### ISSUE THREAD

**Issue by nima110** [hiddify/Hiddify-Manager#4154]
# Bug/Feature: set cloudflare api token in hidify manager problem
**Description**:     setting cloudflare api token on hidify manager setting  no work properly 

status 
hiddify_panel.err.log: changing cloudflare from ( token keys )

issues make :
in domain setting trying create  cdn adress but its shows : Can not connect to Cloudflare. DNS Validation Error
status log shows:
hiddify_panel.err.log: changing cloudflare from ( token keys )

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-107-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

status:
hiddify_panel.err.log: changing cloudflare from ( token keys )

issues make :
trying create  cdn adress but its shows : Can not connect to Cloudflare. DNS Validation Error

**Comment by Iam54r1n4** [comment]
Done
