### ISSUE TITLE
Subject: Request for API Documentation |نیاز به مستندات API

### ISSUE THREAD

**Issue by amanjmoezi** [hiddify/Hiddify-Manager#4166]
### **سلام hiddify**

**مشکل اینجاست که برای API مستندسازی دقیقی موجود نیست،در پنل هم به خوبی کار نمیکنه، و اینکه درک کامل از قابلیت‌ها، پارامترها، و نحوه استفاده ازش یکم دشوار بوده. این عدم وضوح باعث کند شدن فرآیند کارم شده و کار رو کمی غیر بهینه کرده.**

آیا میشه یه مستندات جامعی ارائه بدید که همه جنبه‌های API رو شامل شه؟ چیزایی مثل:

هدف و عملکرد API و نحوه کارش
توضیحات دقیق از نقاط پایانی، متدها و پارامترها
نمونه‌های درخواست و پاسخ
چطوری احراز هویت انجام میشه
چیکار باید بکنیم اگر خطا پیش بیاد
هرگونه محدودیت یا سیاست‌های استفاده
سعی کردم خودم سعی کنم با تحلیل ترافیک شبکه و مهندسی معکوس نقاط پایانی، چیزی رو درست کنم، ولی خب کمی سخت بود. داشتن مستندات معتبر و کامل واقعاً به سرعت فرآیند کارم رو بالا میبره و مطمئن میشم که API رو به درستی استفاده می‌کنم.

میشه با این موضوع کمکم کنید؟ دسترسی به مستندات جامع واقعاً کمک زیادی به من میکنه. اگه نیاز به اطلاعات بیشتری یا هرگونه کمک دیگه‌ای از سمت من دارید، فقط کافیه بهم بگید.

ممنون از بررسی این درخواست!

**با احترام،
امانج معزی
برنامه‌نویس وب**

**Comment by Iam54r1n4** [comment]
این یک خلاصه ای درباره ی API های هیدیفای هست:
[API document on website](https://hiddify.com/manager/contribution/How-to-use-API-in-HiddifyManager-project/?h=api)

اما برای اینکه درک بهتری از API ها پیدا کنید، همراه با ورودی/خروجی هر کدوم باید از چنین مسیری رو طی کنید:
پنل ادمین -> تنظیمات -> API

**Comment by amanjmoezi** [comment]
بله هست اما هر کاری میکنم درخواست ها نامفهومه یا اینکه درست در نمیاد یا اینکه ۴۰۱ در میاد
