### ISSUE TITLE
Installation on VPS NAT

### ISSUE THREAD

**Issue by alirohmat** [hiddify/Hiddify-Manager#4171]
# Bug/Feature:
**Description**:   I have 2 servers a regular VPS KVM server and a VPS NAT ipv4 shared/ipv6.

Hiddify runs normally on the KVM VPS, but on the NAT VPS the user is online and the bandwidth usage is not detected.

I use direct domain mode on the IPv6 that I have. And that doesn't change anything.

Is it true that hiddify can only run on IPv4?

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.2.0-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
