### ISSUE TITLE
اضافه کردن fragment packets

### ISSUE THREAD

**Issue by mashkouk** [hiddify/Hiddify-Manager#4172]
اگه امکان داره یه اپدیت سریع و اورژانسی برای انتخاب حالت tlshello و 1-1 و 2-1 رو تو پنل اضافه کنید
تا محدودیت همراه اول و مخابرات رو فرگمنت رفع کنیم

**Comment by Iam54r1n4** [comment]
همراه اول و مخابرات چه محدودیتی دارند، توضیح بدید.

**Comment by mashkouk** [comment]
در حالت عادی cdn کلودفلر با فرگمنت tlshello روی همراه اول و مخابرات حدود یک ماه هست جواب نمیده ولی مقادیر fragment packets رو 1-1  کنید عالی کار میده
