### ISSUE TITLE
مشکل با اینترنت همراه اول

### ISSUE THREAD

**Issue by PouyaShahmandi** [hiddify/Hiddify-Manager#4174]
سلام وقت بخیر
دامنه من روی کلودفلر هستش و پروکسی روشن و داخل هیدیفای روی auto cdn گذاشته بودم که خودش نسبت به اپراتور آی پی بده توسط سایت ircf.space
 چند وقت خوب کار کرد اما الان روی اینترنت همراه اول مشکل پیدا کرده باید برم آی پی تمیز اسکن کنم بزار که اونم یک روز خوبه و بعد دوباره بهم میریزه 
چ راه حلی پیشنهاد میکنید که من این موضوع را حل کنم؟؟

**Comment by misagh72** [comment]
ircf.space 
دیگه اپدیت نمیشه خودتون با اسکن کنید

**Comment by ReturnFI** [comment]
سلام.
لطفا سوالت مربوط را در گروه تلگرامی بپرسید.
آدرس گروه تلگرام هیدیفای:
https://t.me/hiddify_board
