### ISSUE TITLE
PUT, PATCH and GET methods are not working  for endpoint " /{proxy_path}/api/v2/admin/user/"

### ISSUE THREAD

**Issue by Elahirad** [hiddify/Hiddify-Manager#4180]
# Bug/Feature:
**Description**:     PUT, PATCH and GET methods are not working in endpoint " /{proxy_path}/api/v2/admin/user/" in api v2. Please fix this in the next update.

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-97-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Iam54r1n4** [comment]
We will do fix it.
