### ISSUE TITLE
سلام دم تیم هیدیفای گرم با این نرم افزارش ولی مشکل اصلی دامنه س بدجوری زود فیلتر میشه خواهشا راهی واسه دامنه پیدا کنید ....

### ISSUE THREAD

**Issue by meh732** [hiddify/Hiddify-Manager#4181]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by misagh72** [comment]
باشه انجام میشه
