### ISSUE TITLE
سرور مرکزی

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#4182]
با درود و خسته نباشید.
از سرور مرکزی هیچ خبری نشد؟
چند پیشنهاد هم داشتم.
اضافه کردن سرچ باکس در بخش پروکسی ها
اضافه کردن چند پرتکول جدید 
Juicity
Mieru 
Naive 
Quantumult
Tor

با تشکر

**Comment by ReturnFI** [comment]
منتقل شد.
