### ISSUE TITLE
subscription link 

### ISSUE THREAD

**Issue by amin502** [hiddify/Hiddify-Manager#4183]
hi,
doesn't 1.4.0 version support subsciption link ?
what should do to solve this problem

**Comment by Iam54r1n4** [comment]
I do not understand, version 1.4.0 of what? we're on 10.20.4 currently.

**Comment by ReturnFI** [comment]
This issue is not related to this repository.
Please create a new issue in this [repository ](https://github.com/hiddify/hiddify-next/issues)for this problem.
