### ISSUE TITLE
ارسال بک آپ اتومات به ربات تلگرام

### ISSUE THREAD

**Issue by javadlive** [hiddify/Hiddify-Manager#4184]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-92-generic-x86_64-with-glibc2.35
با سلام خدمت شما عزیزان و زحمت کشان در این عرصه
میخواستم بدونم چطوری میشه بک آپ اطلاعات داخل ربات تلگرام ارسال بشه - قبلاً اتومات هر 6 ساعت میفرستاد ولی الان دیگه نمی فرسته .
با تشکر از شما

**Comment by arashshrf** [comment]
منم سرور رو بک اپ ریستور کردم اینجوری شد
حالا نمیدونم باید چی کار کنم

**Comment by soshiantmahdavi** [comment]
یدونه بک آپ بگیر از پنل بعد فایل بک آپ رو باز کن توی خط اول بگرد دنبال telegram id احتمالا مقدارش برای شما null باشه شما باید null رو با آی دی تلگرامتون که به صورت عدد هست (گوگل کنید چطور telegram id رو پیدا کنیم) جایگزین اون مقدار null کنید
بعد از اینکار فایل بک آپ رو ذخیره کنید 
و سپس بک آپ رو روی پنل بالا بیارید (البته فقط تیک اعمال تنظیمات رو بزنید)

**Comment by javadlive** [comment]
ممنون از راهنمایی تون
فقط موقع بازیابی کدوم گزینه ها رو تیک بذارم و بعدش بازیابی کنم
عکس رو پیوست گذاشتم

**Comment by soshiantmahdavi** [comment]
زنده باد
فقط تیک تنظیمات رو بزنین

**Comment by ReturnFI** [comment]
سلام در نسخه آخر ریلیز رفع شده.
ممنون از ثبت ایشو.
