### ISSUE TITLE
مشگل نصب نشدن hiddify روی سرور ایران 

### ISSUE THREAD

**Issue by pouyaza** [hiddify/Hiddify-Manager#4187]
سلام من رو دو تا سرور ایران تست کردم جفتشون همچین مشگلی داشتن با فیلتر شکن تست کردم بار نشد 
![Uploading Screenshot 2024-06-11 120019.png…]()

**Comment by pouyaza** [comment]
روی دو تا سرور تست کردم همین مشگل عکسو دارم

**Comment by ReturnFI** [comment]
سلام وقتتون بخیر نصب هیدیفای در سرور های ایران امکان پذیر نیست.
