### ISSUE TITLE
an important service hiddify-nginx is not working again Installation Failed!

### ISSUE THREAD

**Issue by rirh** [hiddify/Hiddify-Manager#4191]
**Describe the bug**
Two machines execute `bash <(curl i.hiddify.com/release)`

**To Reproduce**
1. run bash <(curl i.hiddify.com/release)

**Expected behavior**

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/21093108/3298ecd4-1a63-4f1e-8357-b575d12167d1)

**Comment by Iam54r1n4** [comment]
Thanks for the report you provided. If I were you, I would first check the version of my operating system to see if it's 22.04. After that, I would look for logs of inactive services. By the way the installation log could help a lot, you can find it in this path:
```bash
/opt/hiddify-manager/log/system/0-install.log
```

**Comment by Iam54r1n4** [comment]
As I mentioned earlier, to troubleshoot the issue, it would be helpful to look for inactive services log. For now you can ignore the "hiddify-cli" and "hiddify-ssh-liberty-bridge", but your main concern appears to be the "hiddify-nginx". You can check its logs by running this command:
```bash
journalctl -exu hiddify-nginx
```

**Comment by Iam54r1n4** [comment]
The provided log is incomplete. Scroll up a little to provide more context, it's necessary to understand why the Nginx failed.

**Comment by Iam54r1n4** [comment]
Use the PG-UP button on your keyboard; the full log is 6571 lines, just scroll up a little or give the whole latest logs.

**Comment by reinethernal** [comment]
add system user nginx to fix this

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager

**Comment by mrAntonD** [comment]
Hi!

Ubuntu 22.04
During clean installation I get the ERROR:
"
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the followi>│
│ hiddifypanel 10.70.9 requires PyYAML==6.0.1, but you have pyyaml 6.0.2 which is incompatible. │
│ sysctl: setting key "net.ipv4.conf.all.accept_source_route": Invalid argument │
│ sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument

**Comment by Iam54r1n4** [comment]
> Hi!
> 
> Ubuntu 22.04 During clean installation I get the ERROR: " ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the followi>│ │ hiddifypanel 10.70.9 requires PyYAML==6.0.1, but you have pyyaml 6.0.2 which is incompatible. │ │ sysctl: setting key "net.ipv4.conf.all.accept_source_route": Invalid argument │ │ sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument

Hi
I received a notification about your message. I'm not exactly sure what your issue is, but as far as I remember, this project had a Telegram group dedicated to resolving such problems. You can resend your message there.
