### ISSUE TITLE
مشکل لینک داخل ربات تلگرام

### ISSUE THREAD

**Issue by mehdisamurai** [hiddify/Hiddify-Manager#4192]
هیدیفای منیجر ۱۰.۲۰.۴

لینکی که ربات برای دسترسی به پیج اختصاصی به کاربر ارائه میده، متناسب با لینکی که از طریقش عضو شده نیست.

فرض کنید دو تا لینک ساب وجود داره که به یوزر لینک دوم (با محدودیت نوع کانفیگ‌ها) ارائه شده. اما ربات لینک اول که تمام کانفیگ‌ها برای ادمین یا یوزرهای دیگه تعریف شده رو بر میگردونه.

ضمنا با توجه به راهنمایی‌های ادمین‌ها در گروه، بگم که یوزر از طریق لینک ساب دو عضو تلگرام میشه و این مشکل وجود داره.

**Comment by litoosh13** [comment]
به اخرین نسخه اپدیت نمایید
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
