### ISSUE TITLE
قسمت apply_configs یا "اعمال تغییرات" کار نمیکنه

### ISSUE THREAD

**Issue by daBigJay** [hiddify/Hiddify-Manager#4195]
درود به شما
قسمت apply_configs یا "اعمال تغییرات" کار نمیکنه
سپاس

**Comment by Iam54r1n4** [comment]
این ایشو به دلیل اطلاعات ناکافی بسته میشه.
[HOW TO WRITE A PROPER ISSUE](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f)
