### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by darkzed-dev** [hiddify/Hiddify-Manager#4200]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

The entire service is interrupted and restarted about three times a day for three to four minutes and this issue is not from the data center.

**Comment by Iam54r1n4** [comment]
Please provide a more detailed description of the issue. I'm having trouble understanding your message.

**Comment by darkzed-dev** [comment]
Operating system: Ubuntu 22
During the day, the server works fully, but every few hours, the goal service is interrupted. At this time, it is possible to ssh the server.
But neither the panel nor the configurations work, and after 5 minutes everything is automatically fixed

The server log panel is also below
[New Text Document (2).txt](https://github.com/user-attachments/files/15891700/New.Text.Document.2.txt)

**Comment by ReturnFI** [comment]
update to latest release version
