### ISSUE TITLE
latest ver. update loop.

### ISSUE THREAD

**Issue by reza-esmaeel-zade** [hiddify/Hiddify-Manager#4211]
# Bug: ask to update to the latest version as it's already the latest version

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-112-generic-x86_64-with-glibc2.35
**User Agent**:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0

**Comment by Iam54r1n4** [comment]
Fixed
