### ISSUE TITLE
Internal server error: Method Not Allowed

### ISSUE THREAD

**Issue by ThihaWin177** [hiddify/Hiddify-Manager#4215]
<img width="625" alt="Screenshot 2024-06-20 110805" src="https://github.com/hiddify/Hiddify-Manager/assets/159916323/ebe03b9e-b721-4700-bc9b-b2b38efd466b">
# Internal Error Stacktrace:
**Error Message**:   405 Method Not Allowed: The method is not allowed for the requested URL.
```
Traceback (most recent call last):

```

## Details:
**Hiddify Version**: 10.20.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-1030-aws-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by ReturnFI** [comment]
Get a backup and rebuild to Ubuntu 22.04 and install latest release version
Or update to latest release version
