### ISSUE TITLE
Error installing by docker

### ISSUE THREAD

**Issue by valjusha** [hiddify/Hiddify-Manager#4219]
**Describe the bug**

1. Created an Ubuntu 24.04 server
2. Installed docker
3. Followed the [instruction](https://hiddify.com/manager/installation-and-setup/Install-Hiddify-using-Docker/)

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/40063546/43992a41-806c-4c19-aa2b-7789394c258b)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 24.04
 - Version Latest
 - Docker: Docker version 26.1.4, build 5650f9b

**Comment by valjusha** [comment]
Im reinstall to Ubuntu 22.04, but the error remains the same

**Comment by litoosh13** [comment]
we will look into it
