### ISSUE TITLE
راه اندازی هیدیفای در سروری کنار سایت های دیگر

### ISSUE THREAD

**Issue by mohrezkhorasani** [hiddify/Hiddify-Manager#4224]
با سلام.
سروری دارم که چندین سایت مختلف روی آن بالا آمده است. nginx رو هرطور کانفیگ میکنم نمیتوانم وارد سایت های دیگری شوم و هر بار صفحه Decoy Site هیدیفای مربوط به stonewall نمایش داده میشود. با سابدامین های مختلف این عمل را انجام داده ام. فایروال نیز باز است روی پورت های مربوطه.

**Comment by ReturnFI** [comment]
سلام.
امکان پذیر نیست و باعث اختلال در سرویس های میشه.
