### ISSUE TITLE
typo error for one of the JS file

### ISSUE THREAD

**Issue by heinnge** [hiddify/Hiddify-Manager#4228]
there is a 'space' typo error for (https://xxx.com/xxx/static/%20plugins/select2/select2.min.js)

**To Reproduce**
go to admin panel.

**Expected behavior**
should return correct js file

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
