### ISSUE TITLE
ImportError: No module named apt_pkg

### ISSUE THREAD

**Issue by mrjavadseydi** [hiddify/Hiddify-Manager#4237]
After installing on Ubuntu 22.04 (which could happen in another version, too), I get this error whenever I put every apt command in the terminal(apt update, apt install, or type a command that does not exist).
 
This issue could be fixed by adding a symlink for `/usr/lib/python3/dist-packages/apt_pkg.cpython-{your-version-number}-x86_64-linux-gnu.so`  as apt_pkg.

Exact solution :
[https://stackoverflow.com/questions/13708180/python-dev-installation-error-importerror-no-module-named-apt-pkg](https://stackoverflow.com/questions/13708180/python-dev-installation-error-importerror-no-module-named-apt-pkg)

**Exbehaviourehavior**
every command using apt gives you this error : 
Traceback (most recent call last):       
  File "/usr/bin/apt-listchanges", line 28, in <module>
    import apt_pkg
ImportError: No module named apt_pkg

 - OS: ubuntu 22.04 lts

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
