### ISSUE TITLE
بعد از اپدیت v10.30.4 پنل مشکل پیدا کرده

### ISSUE THREAD

**Issue by 3mehdi** [hiddify/Hiddify-Manager#4242]
سلام دوستان عزیز بعد از اپدیت خودکار همه چیز از کار افتاده v10.30.4  آپدیت شد و همه چی خراب شد.

**Comment by 3mehdi** [comment]
Error: Key not found: hidd- Global IP:
Error: Key not found: core_type
----------------------------------------------------------------
- Services Status:
    hiddify-cli                   activating
    hiddify-redis                 active
    hiddify-ssh-liberty-bridge    active
    hiddify-haproxy               activating
    hiddify-panel                 failed
    hiddify-nginx                 active
    hiddify-singbox               activating
Error: Key not found: warp_mode
    wg-quick@warp                 active
    mtproxy                       activeifycli_enable

**Comment by ReturnFI** [comment]
سلام.
آخرین بکاپ بر مبنی تاریخ از داخل سرور  و مسیر داخل [آموزش](https://hiddify.com/fa/manager/configuration-and-advanced-settings/How-to-backup-and-restore-panel-on-Hiddify/#_3) بردارید و ریبیلد کنید.
برای راهنمایی های بیشتر داخل گروه تلگرام هیدیفای و در تایپک مرتبط سوال بفرمایید
آدرس گروه تلگرام هیدیفای:
https://t.me/hiddify_board
