### ISSUE TITLE
hiddify-cli does not start after update

### ISSUE THREAD

**Issue by win64exe** [hiddify/Hiddify-Manager#4243]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.30.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-60-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

Services Status:
    hiddify-cli                   activating
     
HiddifyCli[74422]: Error making GET request: Get "url": remote error: tls: internal >
HiddifyCli[74422]: Error in read and build config Get
systemd[1]: hiddify-cli.service: Deactivated successfully.

**Comment by ReturnFI** [comment]
Issue has been fixed in the latest release.
Please update to the latest release
