### ISSUE TITLE
Configs are not displayed in the all configs section

### ISSUE THREAD

**Issue by g-unix** [hiddify/Hiddify-Manager#4244]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.30.4
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-69-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

Configs are not displayed in the all configs section
![image](https://github.com/hiddify/Hiddify-Manager/assets/5406320/1cd2dece-5407-4e7e-b9d3-e6815fcf866a)

I can't import them either

**Comment by miladj3** [comment]
I have same issue too
