### ISSUE TITLE
اد شدن وارپ جدید

### ISSUE THREAD

**Issue by Danial-Rahimi1381** [hiddify/Hiddify-Manager#4245]
سلام عرض ادب  زمانی که روی دکمه add warp کلیک میکنم  اد میشه ولی زماین که میخوام ازش استفاده کنم 
new configuration file: +Add Warp Hiddify WARP
error patching outbound[National § 0][custom]: netip,ParsePrefix("/24"):ParseAddr(""): unable to parse lP

این پیغام رو بهم نمایش میده چک کردم که وی پی ان دیگه ای نصب نباشه  ویا  DNS روی جایی تنظیم نشده باشه   
ممنون میشم کمکم کنین

**Comment by arianfar62** [comment]
درود بر شما
از طریف + در بالا وارپ اضافه کنید. سپس وارپ را فعال کنید. بعد از فعالسازی وارپ، از طریق تنظیمات پیکربندی، ایجاد پیکربندی وارپ را بزنید تاپیکربندی ایجاد و مشکل حل شود.
درصورتی که باز هم مشکل داشتید از طریق سه کلید ALT+CTRL+DEL فقط وارپ کلاینت را End Task کنید و دوباره افزودن پروفایل وارپ را بزنید.
سلامتی شما و همه ام آرزوست
