### ISSUE TITLE
سلام ببخشید من یوزرای هیدیفایم دو دقه ی‌بار‌قط میشن پینگ نمیده بهشون برنامه یهو دودقه پینگ میده بعد دوباره قط میشه

### ISSUE THREAD

**Issue by mmrzahydri** [hiddify/Hiddify-Manager#4252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here. با هر کانفیگیم بگین تست کردم همیش همینه

**Comment by ReturnFI** [comment]
لطفا اگر سوال داشتید یا نیاز به راهنمایی بود داخل گروه تلگرام ما پیام بفرستید و مشکلتون رو با ذکر جزییات بیان کنید تا دوستان شما رو راهنمایی کنند.

لینک گروه تلگرام هیدیفای:
https://t.me/hiddify_board
