### ISSUE TITLE
not work sub link create from telegram bot

### ISSUE THREAD

**Issue by noxyacc1** [hiddify/Hiddify-Manager#4253]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.30.5
**Python Version**:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-58-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by ReturnFI** [comment]
Thank you for reporting this bug.
We are currently developing a new feature for the telegram bot that will be included in the next release
