### ISSUE TITLE
Error in the api parser and endpoint /api/v2/admin/user/

### ISSUE THREAD

**Issue by hermavpn** [hiddify/Hiddify-Manager#4259]
**Describe the bug**
At the endpoint /api/v2/admin/user/, the following request is made along with the cookie session, but the api gives me the following message in response.

{"msg":"{'last_reset_time': ['Not a valid date.']}"}

According to the method of sending the request which is GET, it doesn't seem that I should set a parameter named last_reset_time, as a result the API gives me the wrong answer.

**To Reproduce**
curl --request GET --url https://xxx.xxxxxx.com/JF7lNUTJZtYjw0upsizA02aU1/api/v2/admin/user/ --header 'Accept: application/json' --header 'Cookie: session=5gIlW5B5RmJz5_g9vsCz0t69Dn8k45iSVl7p3ine1TY'
{"msg":"{'last_reset_time': ['Not a valid date.']}"}

**Screenshots**
<img width="1009" alt="Screenshot 2024-07-07 at 11-18-21 Hiddify API 2 0 0 - Elements" src="https://github.com/hiddify/Hiddify-Manager/assets/141176675/dc35e2c1-f322-4921-9d15-bc6ba3db7c66">

![photo_2024-07-07_11-03-34](https://github.com/hiddify/Hiddify-Manager/assets/141176675/e7ec6193-7371-45b3-80c3-0c550b014fbb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 127
 - Version Hiddify Manager 10.30.6

**Comment by ReturnFI** [comment]
Thank you for reporting this bug.
#4264
