### ISSUE TITLE
عدم نمایش تنظیمات در صفحه همه تنظیمات

### ISSUE THREAD

**Issue by miladj3** [hiddify/Hiddify-Manager#4262]
من بعد از نسخه 10.30.4، به مشکلی که خوردم این هستش که دیگه لیست همه تنظیمات را در این صفحه نمایش نمیده. 
![Screenshot from 2024-07-08 12-45-18](https://github.com/hiddify/Hiddify-Manager/assets/16199445/26a914e6-70cf-4bda-a37f-cc36f1a7e84d)

**Comment by mehrdad1985** [comment]
the error is :


&#39;fakedomain&#39;
Traceback (most recent call last):
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py&#34;, line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/app.py&#34;, line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py&#34;, line 303, in proxy
    response = view(**request.view_args)
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask_classful.py&#34;, line 271, in inner
    return fn(*args, **kwargs)
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py&#34;, line 22, in index
    return self.auto_sub()
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py&#34;, line 27, in auto_sub
    return self.get_proper_config() or self.links_imp(base64=True)
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/auth.py&#34;, line 114, in decorated_view
    return fn(*args, **kwargs)
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/user/user.py&#34;, line 253, in links_imp
    resp = hutils.proxy.xray.make_v2ray_configs(c[&#39;domains&#39;], c[&#39;user&#39;], c[&#39;expire_days&#39;], c[&#39;ip_debug&#39;])
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/proxy/xray.py&#34;, line 191, in make_v2ray_configs
    link = to_link(pinfo)
  File &#34;/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/proxy/xray.py&#34;, line 85, in to_link
    return f&#39;{baseurl}?plugin=v2ray-plugin&amp;mode=websocket&amp;path={proxy[&#34;proxy_path&#34;]}&amp;host={proxy[&#34;fakedomain&#34;]}&amp;tls&amp;udp-over-tcp=true#{name_link}&#39;
KeyError: &#39;fakedomain&#39;

                    </pre>

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
