### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by hamidreza-ygh** [hiddify/Hiddify-Manager#4264]
**Describe the bug**
There appears to be a bug in API V2 with the **Get Users API** and **Get User API**. Instead of retrieving the users list or the configuration information for a specific user, it returns the following message:

> {
>     "msg": "{'last_reset_time': ['Not a valid date.']}"
> } 

**Expected behavior**
I expect to get users list

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Manager/assets/79920955/310dd0ee-4628-4683-87bb-112363f7aeb9)

**Comment by ReturnFI** [comment]
Thank you for reporting this bug.
We are aware of this issue and it will be fixed in the next release.
