### ISSUE TITLE
Haproxy is not being installed

### ISSUE THREAD

**Issue by sazary** [hiddify/Hiddify-Manager#4265]
**Describe the bug**
i did a clean setup and the `haproxy` service didn't start. after investigation i found out that haproxy wasn't installed during the setup.

**To Reproduce**
1. get a fresh ubutnu 24.04
2. run `bash <(curl i.hiddify.com/release)`

**Expected behavior**
to have `hiddify-haproxy.service` running

**Desktop (please complete the following information):**
 - OS:  Ubuntu 24.04
 - hiddify manager version: 10.30.6

**Additional context**
i did run this command to get the log of haproxy:

`journalctl -f -u hiddify-haproxy.service`

and these lines were repeating, as it was retrying to run it:

```
Jul 08 21:06:50 ******* systemd[1]: hiddify-haproxy.service: Scheduled restart job, restart counter is at 267.
Jul 08 21:06:50 ******* systemd[1]: Starting hiddify-haproxy.service - HAProxy Load Balancer...
Jul 08 21:06:50 ******* systemd[1]: hiddify-haproxy.service: Control process exited, code=exited, status=203/EXEC
Jul 08 21:06:50 ******* systemd[1]: hiddify-haproxy.service: Failed with result 'exit-code'.
Jul 08 21:06:50 ******* systemd[1]: Failed to start hiddify-haproxy.service - HAProxy Load Balancer.
```

i checked the `/etc/systemd/system/hiddify-haproxy.service` file and found out that this line starts the service:

```
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
```

and using this command i found out that haproxy isn't installed:

```
$ /usr/sbin/haproxy -Ws -f /opt/hiddify-manager/haproxy/
-bash: /usr/sbin/haproxy: No such file or directory
```

after doing this the problem was solved:

```
 apt install haproxy
```

and this is the relevant part of `installer.log` (before and after this is only my addresses):

```
----------------------------------------------------------------
- Services Status:
    hiddify-cli                   active
    hiddify-redis                 active
    hiddify-ssh-liberty-bridge    active
    hiddify-haproxy               failed
    hiddify-panel                 failed
    hiddify-nginx                 active
    hiddify-singbox               active
    hiddify-xray                  active
----------------------------------------------------------------
```

and this is `0-install.log`:

```
####0####Please wait...####We are going to install Hiddify...####
####5####HiddifyPanel####Reading Configs from Panel...####
####8####Applying Configs####...####
```

**Comment by hamidreza-ygh** [comment]
Use **ubutnu 22.04** instead of ubutnu 24.04

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
