### ISSUE TITLE
امکان مشاهده حجم مصرفی ادمین ها

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#4266]
سلام خسته نباشید 
لطفا اگر امکان دارد قابلیت مشاهده حجم مصرفی ادمین ها در صفحه owner و همچنین قابلیت ایجاد محدودیت حجم به این قسمت اضافه نمایید.
با تشکر از زحمات شما

**Comment by litoosh13** [comment]
بررسی می‌شود
