### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4271]
درود تو پنل دامین اول که هیچی مستقیم متصل میشه و ssl رو میگیره ولی برای لینک ساب و cdn که در حالت proxy  روشن حتما باید باشه نمیتونه ssl رو بگیره و تا 30 باز هم try میکنه ولی نمیتونه proxy هم که خاموش میکنم پنل اجازه نمیده ممنون میشم راهنمایی کنید 

از ubuntu 20.04 استفاده میکنم و ویدو های آموزشتون هم دیدم

**Comment by ReturnFI** [comment]
سلام.
1. ورژن ابونتو شما باید 22.04 باشه.
2. رول های کلادفلر بررسی کنید.
3. تنظیمات dns سرور هم حتما انجام بدید.

**Comment by dahraf** [comment]
درود باید خاموش کنم تا بتونم سرت رو بگیرم و مجدد روشن کن یعنی روسن باشه که هیدیفای بزنه پشت پروکسیه بعد تو کلادفلر خاموش کنم و بیام هیدیفای اعمال کنم تا بتونم سرت بگیرم بعد که گرفت باز روشن کنم تو حالت روشن هیچ جوره نمیگیره
