### ISSUE TITLE
fragment Subs

### ISSUE THREAD

**Issue by Gj4meZ** [hiddify/Hiddify-Manager#4273]
سلام من اخیرا به مشکلی خوردم که اونم اینکه 
چون دارم از دامنه فیلتر استفاده میکنم داخل پنل 
و کاملا کانفیگ هارو با فرگمنت اوکی میکنم 
و بیشتر یوزر ها از برنامه هایی مثل V2raNg , V2rayn , nekoray
استفاده میکنن میخواستم ببینم آیا امکان این هست داخل بخش یوزر ها ساب لینک فرگمنت هم قرار بگیره 
برای برنامه های مختلف

**Comment by ReturnFI** [comment]
سلام از ساب لینک full xray استفاده کنید.

لطفا اگر سوال بیشتری داشتید یا نیاز به راهنمایی بیشتری بود داخل گروه تلگرام ما پیام بفرستید و مشکلتون رو با ذکر جزییات بیان کنید تا دوستان شما رو راهنمایی کنند.

لینک گروه تلگرام هیدیفای:
https://t.me/hiddify_board
