### ISSUE TITLE
کلید ثبت در تنظیمات کار نمیکنه :))))

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4274]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.30.6
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-113-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

از اول نصب کردم به روز رسانی کردم کار نمیکنه ثبت

**Comment by ReturnFI** [comment]
سلام.
بکاپ از پنل تهیه کنید و سرور ریبیلد کنید به اوبنتو 22.04
نصب مجدد انجام بدید
اسکریپ جانی هم نصب نداشته باشید.

لطفا اگر سوال بیشتری داشتید یا نیاز به راهنمایی بیشتری بود داخل گروه تلگرام ما پیام بفرستید و مشکلتون رو با ذکر جزییات بیان کنید تا دوستان شما رو راهنمایی کنند.

لینک گروه تلگرام هیدیفای:
https://t.me/hiddify_board
