### ISSUE TITLE
Domain IP=127.0.0.1 is not matched with your ip=xxx.xxxx.xxxx.xxx which is required in direct mode

### ISSUE THREAD

**Issue by crowlink** [hiddify/Hiddify-Manager#4278]
Hello;
When I try adding my domain in direct mode I got this error.
Domain IP is matched with my ip.
I rebuild server from sratch.
Domain IP=127.0.0.1 is not matched with your ip=xxx.xxxx.xxxx.xxx which is required in direct mode.
Ip is the .
How to resolve this issue?
Thanks

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager

**Comment by ramdroid2015** [comment]
> Hello; When I try adding my domain in direct mode I got this error. Domain IP is matched with my ip. I rebuild server from sratch. Domain IP=127.0.0.1 is not matched with your ip=xxx.xxxx.xxxx.xxx which is required in direct mode. Ip is the . How to resolve this issue? Thanks

I have the same problem. I had been installed Hiddify Manager and used it properly until this new installation but this time this strange problem occurred. 
I have rebuilt and installed several times but there were no vain.

ver. 10.70.7
ubuntu 22.04

**Comment by litoosh13** [comment]
please open a new issue this one is closed
