### ISSUE TITLE
باگ در کانفیگ وایرگارد

### ISSUE THREAD

**Issue by persian-michael-scott** [hiddify/Hiddify-Manager#4288]
نسخه پنل : 10.20.4
حقیقت با توجه به حجم باگ های جدید جرئت نکردم به 10.30 آپدیت کنم ولی فکر نکنم مشکلش رفع شده باشه پرسیدم.
شما وقتی وایرگارد رو فعال میکنی توی پنل و یه دامنه دایرکت داشته باشی میاد برات یه کانفیگ میسازه به این شکل : 
```
wg://direct.example.com:13779?publicKey=Opgl3z5brMo25XznraK1tC5HQ4oNF5mQYU9K0zJlBhs=&privateKey=uHHBrnPKeAQGdaLrGfM6gbe0qRNNgOdEexEIO6uXjHA==&presharedKey=CZ1JbhKq8HvPP9DQ2GVFBQ3AROkcMOvn7WeGmLPuNqo=&ip=10.0.0.1&mtu=1380&keepalive=30&udp=1&reserved=0,0,0&ifp=5-10#%F0%9F%93%B6%20Irancell%28IPV6%29%20WireGuard
```

مشکل اینجاست که این تولید پرایوت کی مشکل داره و ارور میده هم در اپ اصلی wireguard و هم در هیدیفای : ( انگار یه = بیشتر داره)

```
privateKey=uHHBrnPKeAQGdaLrGfM6gbe0qRNNgOdEexEIO6uXjHA==
```

ارور در اپ وایرگارد  : 
```
illegal base64 data at input byte 44
```

ارور در لاگ اپ هیدیفای :

```
outbound/wireguard[ Irancell(IPV6) WireGuard § 2]: Irancell(IPV6) WireGuard § 2decode private key:
44 byte input at data base64illegal
```
اگه = اضافه رو هم پا کنی وصل نمیشه

**Comment by farzaaaan** [comment]
were you able to resolve this issue? currently dealing with the same error, and unfortunately parents aren't savvy enough to help me troubleshoot from here.

panel is 10.7, and it seems like that the issue began after the panel upgrade

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
