### ISSUE TITLE
Import IPv6 Branch in Detailed Configs

### ISSUE THREAD

**Issue by OXiD360** [hiddify/Hiddify-Manager#4289]
# Bug/Feature:
**Description**:
عرض ادب و خسته نباشید
چند تا پیشنهاد داشتم که اگه به پنل اضافه بشه خالی از لطف نیست و پنل رو کامل تر میکنه

اولیش اضافه کردن شاخه IPv6 به بخش کانفیگ ها هست چون خیلی از کانفیگ ها بصورت دایرکت فقط با IPv6 وصل میشن و با IPv4 یا اصلا کار نمیکنن یا فقط اوایل اتصال پینگ خوبی میدن و بعد تقریبا قطع میشن، که باعث میشه تو حالت اتو مشکل ساز شه! پس اگه داخل پنل بشه حالت دایرکت رو جداگونه بین IPv4 و IPv6 انتخاب کرد عالی میشه

دومیش هم راجع به پروکسی SSH هست که تو برنامه هیدیفای دو مدل داره یکی SSH و یکی دیگه هم Socks که فقط حالت ساکس با بیشتر سرویس ها و برنامه ها مثل گوگل پلی سازگار هست و حالت SSH روشون کار نمیکنه! اگه بشه توی پنل بین این دو تا حالت انتخاب کرد یعنی فعال یا غیر فعالشون کرد عالی میشه مثلا فقط بشه از حالت Socks استفاده کرد

سومین مورد هم اگه بشه برای Agentها تعیین کرد که به چه ساب لینکی دسترسی داشته باشن خیلی بهتر میشه

چهارمین مورد هم اگه بشه پروکسی وارپ WOW رو داخل پنل ایجاد کرد عالی میشه

پنجمین مورد هم مربوط میشه به اپ هیدیفای که وقتی کاربر نوتیفیکیشن برنامه رو از تنظیمات خاموش میکنه، دیگه نمیشه کانکت شد!

ممنون از زحمات و تلاش تیم خفن هیدیفای 3>

## Details:
**Hiddify Version**: 10.50.3
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-113-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
میتونید به صورت ریلی ساب ای پی ۶ سرور رو اضافه کنید
باقی موارد هم در اینجا:
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
