### ISSUE TITLE
عدم محاسبه حجم مصرفی کاربران و پنل

### ISSUE THREAD

**Issue by rahmatzadmohammad** [hiddify/Hiddify-Manager#4290]
سلام دوستان
در نسخه 10.50.3 حجم مصرفی پنل و کاربران بعد از گذشتن از ساعت 12 شب محاسبه نمیشه.
برای حل مشکل باید نصب مجدد کنم و دوباره ساعت 12 شب این اتفاق تکرار میشه

این مشکل برای هر 5 پنلی که دارم هست

**Comment by rahmatzadmohammad** [comment]
در نسخه 10.50.3 هم این مشکل هست

**Comment by Ariannetflix** [comment]
برای من با اپلای کانفیگ درست میشه و نیاز به نصب مجدد نداره. ولی هر شب باید بزنم.

**Comment by rahmatzadmohammad** [comment]
تو نسخه 10.70.2 هم این مشکل هست متاسفانه داره اذیت کننده میشه
![Untitled](https://github.com/user-attachments/assets/78c07aca-87a1-48e0-a563-5a5ae9327dc4)
