### ISSUE TITLE
ارسال بکاپ به ربات تلگرام

### ISSUE THREAD

**Issue by immrit** [hiddify/Hiddify-Manager#4296]
#پیشنهاد

بنظرم واسه بکاپ گرفتن روزانه یا ساعتی از کل پنل یه قسمتی رو بزارید بشه ربات تلگرام تعریف کرد و طبق زمانبندی که تعریف میشه بکاپ به ربات ارسال شه که خدایی نکرده اطلاعات از بین نره

**Comment by litoosh13** [comment]
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
