### ISSUE TITLE
ریستارت شدن مداوم سرویس hiddify-cli

### ISSUE THREAD

**Issue by miladj3** [hiddify/Hiddify-Manager#4303]
![Screenshot from 2024-07-19 13-26-27](https://github.com/user-attachments/assets/1c9e45e7-e1ec-4082-9094-2b5167e81e88)

version: 10.50.4
OS: ubuntu 22

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
