### ISSUE TITLE
مدیریت فروش ادمین ها

### ISSUE THREAD

**Issue by Alighaemi9731** [hiddify/Hiddify-Manager#4305]
سلام. لطفا فیچر هایی برای مدیریت فروش ادمین ها در نظر بگیرید و به پنل اضافه کنید. مثلا هر ادمین کیف پول داشته باشد و وقتی کاربر جدیدی میسازد یا تمدید میکند یا کاربری را ادیت میکند متناسب با ضریب هر گیگ برای آن ادمین از کیف پولش کم شود.

**Comment by litoosh13** [comment]
فعلا برنامه ای براش در نظر گرفته نشده
