### ISSUE TITLE
عدم محاسبه ترافیک آپلود کاربران در پنل

### ISSUE THREAD

**Issue by AshkanGalaxy** [hiddify/Hiddify-Manager#4311]
ترافیک مصرفی گویا فقط دانلود کاربران محاسبه میشه و نه آپلود ! من این مسئله رو از مغایرت مصرف ترافیک در دیتاسنتر و پنل متوجه شدم

**Comment by litoosh13** [comment]
مصرف وی پی ان به صورت کلی دانلود دو برابر اپلود هست
