### ISSUE TITLE
specfic paths don't work including ? or =

### ISSUE THREAD

**Issue by infinitaa** [hiddify/Hiddify-Manager#4317]
Hi There
I was trying to use ? or = in the path but it didn't work and I know it's because of the locations in the nginx. Is there anyway to do this?
Also I tried same paths for vmess and vless and it ended with error in nginx.
Thanks a lot.

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
