### ISSUE TITLE
لینک سابسکرایب

### ISSUE THREAD

**Issue by ojooubeh** [hiddify/Hiddify-Manager#4319]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.50.4
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-116-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

درود و وقت بخیر 
موردی که وجود داره اینه که لینک سابی که از قسمت یوزر ها برمیدارم تو هیدیفای نسخه ویندوز اد نمیشه و همون تو نسخه موبایلی ادد میشه و حتی رو نسخه های قبلی ویندوزی هیدیفای نکست هم اد نمیشه ولی وقتی میرم تو صفحه کاربر و لینک اتوماتیک رو از اونجا کپی میکنم و میزنم ساب کار میکنه

**Comment by litoosh13** [comment]
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
