### ISSUE TITLE
Question about WARP

### ISSUE THREAD

**Issue by Sajjad-Arjmand** [hiddify/Hiddify-Manager#4322]
Hi!
I want to use WARP for local and banned sites, but it connects to **Hong Kong** after enabling WARP from settings in hiddify manager.
![Screenshot 2024-07-22 130126](https://github.com/user-attachments/assets/3171abb1-cca2-4a57-96be-73138899a600)

Although my VPS location is Finland.

If I use another package like yonggekkk/warp-yg it connects to **Finland** properly. but it's routing all outbound traffic through WARP and doesn't support split tunneling or include exclude domains.

please help me. is anybody facing similar issues here?!

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
