### ISSUE TITLE
Hiddify proxy url opens vpn website

### ISSUE THREAD

**Issue by Yarav153** [hiddify/Hiddify-Manager#4327]
I'm following [this guide](https://hiddify.com/manager/installation-and-setup/Guide-for-setting-up-the-domain-and-finalizing-the-installation/#2-reaching-the-admin-page-after-installing-the-script) for the ocl. I've waited 20 minutes, but proxy url link opens vpn websites. Tried twice, first time it lead to TOR and the second time it leads to Proton. I don't know what I'm doing wrong and what I should fix. Just in case if this is important I'm using VM.Standard.E2.1.Micro on OCl always free resources, everything else is the same as in the tutorial.

here's the log for the job that made the link i suppose:

[log](https://github.com/user-attachments/files/16335460/ocid1_ormjob_oc1_eu_zurich_1_amaaaaaaugdsumiaise66pkhwymahjeidy.log)

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
