### ISSUE TITLE
Firewall and udp ports ?

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4334]
درود چرا وقتی سمت سرور فایروال رو فعال میکنم و پورت های کلاد فلر رو فقط اجازه میدم دیگه از کار میافته و متصل نمیشه حتما باید پوت 53 رو به صورت udp تو فایروال قرار بدم و اینکه چرا انکپسولیت نمیکنه خودش که من این پورت رو فعال نکنم تو فایروال ؟

برای اینکه فقط از cdn استفاده بشه و فایروالی روشن باشه چه پورت هایی رو باید دسترسی داد ؟

روی پنل های دیگه نیاز به دسترسی پورت 53 udp نیست ولی اینجا حتما باید دسترسی بدم و این جالب نیست اصلا نمیشه کاری کرد که انکپسوله بشه روی cdn ?

هسته xray استفاده میکنم singbox که از udp استفاده میکنه ولی روی xray  عجیبه که حتما udp  باید باز باشه

**Comment by litoosh13** [comment]
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
