### ISSUE TITLE
Unespected Error

### ISSUE THREAD

**Issue by nayminthu94** [hiddify/Hiddify-Manager#4341]
Post-start outbound/xxxxx.xxx.com WireGuard 28056 3: resolve endpoint domain: exchange4: context cancled | exchange6: context canceled

please help me

**Comment by nayminthu94** [comment]
![Uploading asdf.jpg…]()

**Comment by grabakin** [comment]
Is it fixed for you? Have the same problem

**Comment by grabakin** [comment]
turning off the wireguard on the server helped me

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
