### ISSUE TITLE
Message: You have already used this Domain

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Manager#4349]
من دامینی دارم که اون رو به شکل wildcard و به صورت زیر اضافه می کنم و این دامنه از نوع سی‌دی‌ان هستش:
`*.mydomain.com
`
در نسخه های قبل میتونستم همین دامین رو چندین مرتبه با Alias های متفاوت دیگری هم ثبت کنم.
علت اینکار این بود که میخواستم در subscription چندین کانفیگ مجزا داشته باشم و روی هر کدام رنج های آی پی مختلفی از CDN رو ست کرده بودم.
هر چند ممکن هست بگید آپشن auto cdn ip همین امکان رو تا حدی فراهم می کنه، اما اگه بشه دامین `*.mydomain.com` رو به جای یکمرتبه، چندین بار ثبت کرد و تعداد کانفیگ های مجزا بیشتر بشه، مزایای خودش رو داره از جمعه کاهش نیاز کاربران به آپدیت های متوالی برای بدست آوردن یک working CDN IP.
امیدوارم مورد توجه قرار بگیره.

**Comment by litoosh13** [comment]
برای آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
