### ISSUE TITLE
مشکل فرگمنت در ورژن 10.70.2

### ISSUE THREAD

**Issue by MH-128** [hiddify/Hiddify-Manager#4359]
سلام

 فرگمنت در ورژن 10.70.2 کار نمی کنه مخصوصا در نرم افزار Streisand در ios

![photo_2024-07-30_22-55-35](https://github.com/user-attachments/assets/7ae0a2c1-3760-4580-9fc8-2297218e1e44)

ذر برنامه Streisand در قسمت فرگمنت جای مثدار های فرگمنت اشتباه است

**Comment by MH-128** [comment]
این مشکل در ورژه 10.70.7 هم همچنان در پروفایل هایی به از لینک کامل پیکربندی xray استفاده نمی کنند وجود دارد

فقط وقتی درست مقادیر جایگزاری میشن که از جالت json وارد برنامه شوند

**Comment by litoosh13** [comment]
از ساب لینک auto استفاده کنید
برای مشاهده آموزش نصب و کانفیگ صحیح پنل به لینک های زیر مراجعه نمایید:
hiddify.com/manager
hiddify.com/fa/manager
