### ISSUE TITLE
Interference with some sysctl modules

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Manager#4361]
من از سرور ابونتوی 22 استفاده می کنم و در فایل /etc/sysctl.conf یک سری ماژول هایی برای کرنل و امنیت سرورم اضافه کردم. از جمله اونها غیرفعالسازی IPv6 با این 3 خط:
```
# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1

# Disable IPv6 by default
net.ipv6.conf.default.disable_ipv6 = 1

# Disable IPv6 on the loopback interface (lo)
net.ipv6.conf.lo.disable_ipv6 = 1
```

متوجه شدم هرباری که هیدیفای برای اپلای شدن تغییرات اقدام می کنه، دستوراتی رو اجرا می کنه که حداقل بعضی از ماژول های فایل sysctl.conf روخنثی/غیرفعال می کنه؛ در موقع ریستارت شدن سیستم هم اتفاق مشابهی می افته.

از بابت اینکه دستورات هیدیفای باعث بی اثر شدن دستورات بالا برای غیرفعالسازی IPv6 میشه مطمئن هستم، و هیدیفای باعث میشه IPv6 سرور من دوباره فعال بشه، علیرغم اینکه در کانفیگ محیط گرافیکی هیدیفای تیک فقط استفاده از IPv4 رو هم فعال کردم.

احتمالا مشکل فقط به خنثی شدن دستورات غیرفعالسازی IPv6 محدود نمیشه و هیدیفای روی بقیه محتویات این فایل هم تاثیر میذاره؛
من از اسکریپت [hawshemi/Linux-Optimizer](https://github.com/hawshemi/Linux-Optimizer) استفاده کردم که ماژول هایی رو برای افزایش امنیت به sysctl.conf اضافه میکنه

راه حلی که به نظر خودم رسیده، هیدیفای بعد از هردفعه که تغییراتی عمده توی سیستم ایجاد میکنه، در آخرش یکبار دستور `sysctl -p` هم اجرا کنه تا از override شدن تنظیمات ترجیحی ادمین سیستم تا حدی جلوگیری بشه.

**Comment by robin98** [comment]
نکته جدیدی که متوجه شدم:
با اجرای `sysctl -p`، قابلیت اندازه گیری حجم مصرفی کاربران در هیدیفای از کار می افته.
از طرفی برای اعمال ماژول های تعریف شده داخل فایل sysctl.conf و بازگردانی تغییراتی که هیدیفای در اونها دستکاری می کنه، چاره ای بجز این نیست.

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
