### ISSUE TITLE
xray & singbox

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4363]
درود پنل با هسته Xray روی grpc پینگ داره ولی در اینستا فالوور فالووینگ ها و ریلزهای افراد نمایش داده نمیشه اما وقتی هسته رو تغییر میدم به singbox مشکل حل میشه اما فقط ws کار میکنه و سایر کانفیگ ها پینگ ندارن هیچ کدام بنده از cdn استفاده میکنم .

نسخه پنل 10.70.2 روی نسخه های قبل هم این مشکل رو داشتم ممنون میشم بررسی کنید چون grpc سرعت به نسبت بهتری داره .

**Comment by litoosh13** [comment]
به اخرین نسخه اپدیت نمایید
