### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by HtNetIR** [hiddify/Hiddify-Manager#4366]
چطوري ميشه اين ؟؟؟؟
كل يوزر من 34 تاست و 1827 تا آنلاين ؟؟؟
کاربران آنلاین: 1827 / 34

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
