### ISSUE TITLE
telegram backup not working

### ISSUE THREAD

**Issue by AmirhoseinKhanlari** [hiddify/Hiddify-Manager#4367]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.50.4
**Python Version**:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
**OS**:              Linux-5.15.0-113-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
