### ISSUE TITLE
آدرس IP Local و Port هیدیفای

### ISSUE THREAD

**Issue by Shabahang7** [hiddify/Hiddify-Manager#4368]
با درود و احترام
به نظر میاد آدرس IP Local و Port هیدیفای از 127.0.0.1 و پورت 2334 تغییر کرده.
چطور میتوانم بفهمم که هیدیفای در حال حاضر از چه آدرس IP Local و Port استفاده میکنه؟

**Comment by Shabahang7** [comment]
خودم پیداش کردم
Local IP: 127.0.0.1
Port: 12334

**Comment by mehrdad2200** [comment]
2334
