### ISSUE TITLE
روشی برای انتخاب فعال بودن فرگمنت فقط برای دامنه دلخواه 

### ISSUE THREAD

**Issue by mmkprog** [hiddify/Hiddify-Manager#4370]
سلام و خسته نباشید خدمت ادمین عزیز

اگر در نسخه های جدید تر امکانی فراهم شود تا بتوان فرگمنت را فقط برای یک دامنه خاص فعال و غیرفعال کرد خیلی خوب می شود.
همچنین اگر بتوان مقادیر را هم برای هر دامنه مشخص نمود که واقعا دیگه خیلی بهتر میشه😅

با تشکر از زحمات شما 🙏

**Comment by litoosh13** [comment]
بررسی می‌شود
