### ISSUE TITLE
عدم اتصال vmess http tcp 10.70.4

### ISSUE THREAD

**Issue by Alighaemi9731** [hiddify/Hiddify-Manager#4374]
با سلام
در اخرین نسخه هیدیفای منیجر 10.70.4 کانفیگ های vmess http tcp از کار افتاده و کار نمیکنند. ایپی سالم است و با ریلیتی کار میکند. مشخصا باگ پنل برای این نوع کانفیگ میباشد.

**Comment by litoosh13** [comment]
به اخرین نسخه اپدیت فرمایید
