### ISSUE TITLE
فرگمنت

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#4375]
سلام 
 شما مقدار packets رو از حالت  tlshello خارج کنی
و بزارین ما بتونیم مقادیر دلخواهمون رو بزاریم
دوباره میتونیم فرگمنت رو روی cdn بدون دامین سالم و بدون ای پی سالم
دوباره زندش کنیم روی همراه اول
الان ما به packets با مقدار tlshello محدود شدیم و هیچکاری نمیتونیم بکنیم!

و ممنون میشم اگر بگین از کجا میشه دستی تغیرش داد ❤️

**Comment by litoosh13** [comment]
در دست بررسی می‌باشد
