### ISSUE TITLE
جابجایی دامین ها

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Manager#4376]
سلام
من این پیشنهاد رو بارها اعلام کردم !

یکی از مشکلات ما در قسمت دامین ها این هستش که ما وقتی در این قسمت دامینی اضافه میکنیم قابل جابجایی نیست
و باید اون دامین هارو حذف کنیم تا به ترتیبی که میخوایم کانفیک هامون روی اپ های کلاینت نشون بده برسیم
و این خیلی ازاردهنده هستش

مثلا من ۵ تا دامین اضافه کردم
ترتیب 
۱
۲
۳
۴
۵

الان بخوام بعد از دامین ۲ دامینی اضافه کنم باید از دامین ۵ تا ۳ حذف کنم یا تغیر بدم تا بتونم یک دامین بعد از ۲ اضافه کنم

حالا شما فرض کن من ۱۰ تا ۲۰ تا دامین دارم
این کار خیلی ازاردهنده هست

ممنون میشم برسی کنید ❤️🙏

**Comment by litoosh13** [comment]
در دست بررسی می‌باشد
