### ISSUE TITLE
Modifying Hysteria2 & TUIC

### ISSUE THREAD

**Issue by setarehirani** [hiddify/Hiddify-Manager#4380]
Hello, how can I modify the hysteria2 and TUIC configs?
for example changing the ports, removing obfuscation, allow insecure by default, 
congestion controller for TUIC, SNI, ... How can I edit these?

Thanks.

**Comment by mhmd-hb** [comment]
there is an option called config editor on the Hiddify App. i opened an [issue (FR)](https://github.com/hiddify/Hiddify-Manager/issues/4364#issue-2440345871) so maybe devs add this to Panel too.

**Comment by litoosh13** [comment]
> Hello, how can I modify the hysteria2 and TUIC configs? for example changing the ports, removing obfuscation, allow insecure by default, congestion controller for TUIC, SNI, ... How can I edit these?
> 
> Thanks.

ports and other stuff you could change in settings in panel

you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
