### ISSUE TITLE
[bug] Major Clash Issues in Hiddify Manager

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [hiddify/Hiddify-Manager#4383]
Greetings to the esteemed Hiddify developers,

Unfortunately, in the latest versions of Hiddify Manager, using Sub Link Clash has encountered issues and does not support the new links of the Hiddify panel, showing an error as depicted in the image below.
![Screenshot 2024-08-05 134649](https://github.com/user-attachments/assets/b5e5eaee-5e1f-46d9-ab73-58b6478a19ab)

Additionally, I kindly request that you reintroduce the option to select `all link` and `lite link` for internal Iranian sites, as was possible before. Also, please add the download links for the latest versions of Clash for Windows and Clash Meta for Android, similar to the Hiddify App, for users.

> https://domain.com/KdleXqBNndSVHvyRpOtMuT/f841b00e-6e35-4f3b-90e1-ae8838629f79/clash/lite.yml?mode=new&asn=unknown&name=unknown_lite_domain.com-new
> https://domain.com/KdleXqBNndSVHvyRpOtMuT/f841b00e-6e35-4f3b-90e1-ae8838629f79/clash/all.yml?mode=new&asn=unknown&name=unknown_lite_domain.com-new

Lastly, there is another issue where the beginning of the Clash link is prefixed with `clash://install-config?url=` which is not suitable. Users copy the link instead of it being automatically entered into Clash (like in the Hiddify app). This results in the need to edit the link after copying and remove `clash://install-config?url=` .

Thank you and I kindly request that these issues be addressed in future versions of the Hiddify panel.

**Comment by litoosh13** [comment]
we suggest using hiddify next
hiddify.com/app
hiddify.com/fa/app
