### ISSUE TITLE
کانفیگ مختص hiddify 

### ISSUE THREAD

**Issue by andyplop9** [hiddify/Hiddify-Manager#4387]
درود
چگونه می شود یک کانفیگ مختص خود هیدیفای ساخت که در نرم‌افزار های دیگر نظیر v2rayng و ... نتوان کپی کرد
و مانند vmess اطلاعات کانفیگ نامشخص باشد 

Hey 
How to make a config only for hiddify and can't add it into v2rayng and ..... 
And it can't be readable like vmess

**Comment by litoosh13** [comment]
فعلا امکان پذیر نیست
