### ISSUE TITLE
Add protocol brook & amneziaWG

### ISSUE THREAD

**Issue by Ho3einz44** [hiddify/Hiddify-Manager#4397]
سلام و خدا قوت
این دو پروکسی کاملا اکی هستن روی همه نت ها و من پابلیک کردم الان چند وقته و هنوز فیلتر نشده،واقعا جاشون تو هیدیفای که طیف گسترده ای از پروکسی هارو ساپورت میکنه خالیه.
Hello 
These two proxies are completely the same on all nets, and I have published it for some time now and it has not been filtered yet, in fact, it is empty in Hidify, which supports a wide range of proxies.

**Brook**
**AmneziaWG**

**Comment by litoosh13** [comment]
با سلام بررسی میشود
