### ISSUE TITLE
bug :  TLS Mixed SNI Case

### ISSUE THREAD

**Issue by rnj79** [hiddify/Hiddify-Manager#4398]
با فعال کردن TLS Mixed SNI Case فقط دامنه و sni تغییر میکنند .  و host هیچ تغییری نمی کند

اگر این مشکل رفع شود . کانفیگ http httpupgrade CDN vless به خوبی روی همراه اول با دامنه محدود کار میکند
همچنین مشکل اضاف شدن نقطه به پایان هاست هم اگر رفع شود . دامنه های فیلتر امکان حیات پیدا میکنند .

**Comment by litoosh13** [comment]
به اخرین ورژن اپدیت نمایید
