### ISSUE TITLE
تعیین پروتکل خاص برای هر یک ساب دامنه

### ISSUE THREAD

**Issue by shzdiushju** [hiddify/Hiddify-Manager#4400]
درود

خواهش میکنم که امکان تعیین پروتکل خاص برای هر سابدامنه را اضافه کنید تا در Subscription بتوان تعیین کرد که برای مثال ساب دامنه A فقط از CDN WS tls http1 استفاده کنه و برای کاربر به نمیاش گذارد و ساب دامنه B برای مثال CDN gRPC QUIC بهمراه CDN WS Http2  را به نمایش دهد بجای اینکه تمام پروتکل های فعال برای تمام سابدامنه های فعال برای کاربر به نمایش گذاشته شود.

این کار هم از شلوغی بی اندازه جلو گیری میکنه هم امکان شخصی و بهینه سازی بیشتر را برای هر اوپراتور را فراهم میکنم.

ممنونم از تیم هدیفای

**Comment by litoosh13** [comment]
در دست بررسی هست این مورد
