### ISSUE TITLE
Ipv6 وارپ 

### ISSUE THREAD

**Issue by EMMeiS** [hiddify/Hiddify-Manager#4401]
سلام وقت بخیر و خسته نباشید
در سایر پنل ها وقتی از وارپ استفاده میکینم به صورت دیفالت وارپ به غیر از ipv4 از ipv6 هم ساپورت میکنه
اما تو هیدیفای به صورت پیشفرض فکر کنم ipv6 وارپ غیر فعاله
پیشنهادم این بود که گزینه ای اضافه بشه تا بتونیم ipv6 رو در وارپ فعال کنیم چون در خیلی از مواقع میتونه مفید باشه و همچنین مشکل موزیک اینستگرام رو حل میکنه

**Comment by litoosh13** [comment]
بررسی میشود
