### ISSUE TITLE
قطع شدن یوزر های جدید 

### ISSUE THREAD

**Issue by alisadeghi1997** [hiddify/Hiddify-Manager#4402]
# Bug/Feature:
**Description**:     زمانی که کاربر جدید تو پنل ساخته میشه کاربر ها فعال میشن ولی بایه ریستارت کردن پنل کاربر های جدیدی که ساخته شدن همگی قطع میشن باید هر کاربر که ساخته میشه یه بار اعمال تغییرات زده بشه که یا ریستارت شدن پنل کاربر ها قطع نشن 

کلی بگم داستان اینه که بعد از عمال تغیییرات هر چند تا کاربرم ساخته شده باشن با یه ریستارت همه قطع میشن و تا اعمال تغییرات زده نشه نمیتونن متصل بشن 

## Details:
**Hiddify Version**: 10.7.4
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-117-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
لطفا آخرین نسخه پنل را نصب نمایید
برای مشاهده آموزش نصب و کانفیگ صحیح پنل به آدرس های زیر مراجعه فرمایید:
hiddify.com/manager
hiddify.com/fa/manager
