### ISSUE TITLE
Can't acess admin panel 502 Bad Gateway

### ISSUE THREAD

**Issue by AlexanderKhudoev** [hiddify/Hiddify-Manager#4404]
**Describe the bug**
After clean install Hiddify Manager on clean Ubuntu - 502 error in access admin panel 
**To Reproduce**
1. Fresh install Hiddify manager 10.70.4
2. After installation get admin links
3. Follow on any of the generated links to access the admin panel
4. See error 502 Bad Gateway

**Expected behavior**
Access to admin panel without 502 error

**Screenshots**
![image](https://github.com/user-attachments/assets/8aa77b7b-dfbb-43b6-9185-dbe17224001e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser Chrome

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
