### ISSUE TITLE
کار نکردن مسدود شدن سایت های داخلی

### ISSUE THREAD

**Issue by mohammadfbi** [hiddify/Hiddify-Manager#4406]
سلام خسته نباشید
ورژن پنل: 10.70.4
آپشن مسدود شدن سایت های داخلی که در قسمت تنظیمات پروکسی هست رو فعال و اپلای کانفیگ میکنم ولی بعد اتصال سایت های ایرانی باز میشن و کارساز نیست.
و اینکه دو مورد دیگه هم میخواستم تو همین تیکت گزارش بدم که تعداد تیکت ها بیشتر نشه:
یکی اینکه موقع ساخت یوزر گزینه ذخیره و ایجاد جدید که خیلی برامون کاربرد داشت رو تو ورژن ۱۰ حذف کردید اگر امکانش باشه اون گزینه رو‌برگردونید.
و مورد بعدی اینکه تو پنل سمت یوزر حجم باقیمانده رو‌نشون میده ولی کل حجم معلوم نیست چند بوده همینطور برای روزهای باقی مانده هم همین مشکل هست

و یه پیشنهاد کوچولو هم میخواستم اضافه کنم پنل سمت کاربر تو نسخه ویندوز خیلی خوبه که بارکد بصورت پیشفرض نشون میده. کاش تو نسخه گوشی ها هم همینطور بود مثلا بجای آیکون on/off بارکد بود خیلی بهتر میشد یا هر دو رو تو همون صفحه نشون میداد

**Comment by ramdroid2015** [comment]
در مورد مسدود شدن سایتهای ایرانی:

این امکان برای "مسدود شدن" نیست و بد نوشته شده. وقتی این گزینه فعال بشه سایتهای ایرانی از VPN عبور نمی‌کنن و مستقیما به سرور سایت وصل میشن. چون خیلی از سایتهای دولتی روی اینترانت هستند و با vpn کاربر دسترسی نداره اینطوری بدون خاموش کردن vpn میتونه به سایتهای داخلی هم دسترسی داشته باشه.

**Comment by litoosh13** [comment]
لطفا آخرین نسخه پنل را نصب نمایید
برای مشاهده آموزش نصب و کانفیگ صحیح پنل به آدرس های زیر مراجعه فرمایید:
hiddify.com/manager
hiddify.com/fa/manager
