### ISSUE TITLE
مطرح کردن چنتا باگ

### ISSUE THREAD

**Issue by bahrammm1995** [hiddify/Hiddify-Manager#4408]
![1BD23A19-5709-46FC-AFAE-DFCFB10924A1](https://github.com/user-attachments/assets/b25ab530-e9f6-4f34-b305-8f531f92e489)
# Bug/Feature:
یکی از مشکلات پنل اینه که اگه پورت وایرگارد رو تغییر بدی از کار میافته
۲. داخل عکس همونطور که معلومه سی پی رو درگیر میکنه هسته سینگ باکس و رم پر میشه و ارور out of memory میده و سرور کلاً داون میشه و دیگه حتی نمیشه بهش اس اس اچ زد
۳. الان داخل پنل من کانفیگ اس اس اچ ریلی از طریق لینک سابسکریپشن برای کاربر میره ولی اس اس اچ مستقیم توی کانفیگا نمیاد
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.4
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-117-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
لطفا به آخرین ورژن پنل آپدیت کنید 
برای مشاهده آموزش نصب صحیح پنل و کانفیگ آن :
hiddify.com/manager
hiddify.com/fa/manager
