### ISSUE TITLE
build time long

### ISSUE THREAD

**Issue by hyh1750522171** [hiddify/Hiddify-Manager#4414]
**Describe the bug**
![image](https://github.com/user-attachments/assets/e08c46ea-7768-4bb5-955d-35e38ce3b0ed)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by low-skill-dev** [comment]
+1
Tried both single-threaded VPS and my R9 5900X home PC, always stuck on `Successfully installed argparse` message.

**Comment by TheLastFlame** [comment]
same problem

**Comment by litoosh13** [comment]
please use the latest version of the panel if error persisted open new issue
