### ISSUE TITLE
adding profile is not working without vpn

### ISSUE THREAD

**Issue by AmirArsalanTaqavi** [hiddify/Hiddify-Manager#4417]
**Description**:     I don't know where is the problem exactly. is it the app is it the server is it a bug? i can open the profile link with domain and ip and the page opens up. so it shouldn't be restricted i think but adding the profile in app is not working
it says adding profile for a while and it gives connection time out and i have to use a VPN to add the profile

## Details:
**Hiddify Version**: 10.70.4
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-118-generic-x86_64-with-glibc2.35

here is the app log:

17:09:12.693925 - [W] ProfileRepositoryImpl: error adding profile by url
DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server.
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _FutureListener.handleError (dart:async/future_impl.dart:181)
#2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:859)
#3      Future._propagateToListeners (dart:async/future_impl.dart:880)
#4      Future._completeError (dart:async/future_impl.dart:660)
#5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#6      _Completer.completeError (dart:async/future_impl.dart:27)
#7      Future.any.onError (dart:async/future.dart:623)
#8      _RootZone.runBinary (dart:async/zone.dart:1666)
#9      _FutureListener.handleError (dart:async/future_impl.dart:178)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:859)
#11     Future._propagateToListeners (dart:async/future_impl.dart:880)
#12     Future._completeError (dart:async/future_impl.dart:660)
#13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:564)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

17:09:12.693925 - [W] AddProfile: failed to add profile
ProfileFailure.unexpected(error: DioException [connection timeout]: The request connection took longer than 0:00:15.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 0:00:15.000000 or improve the response time of the server., stackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _FutureListener.handleError (dart:async/future_impl.dart:181)
#2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:859)
#3      Future._propagateToListeners (dart:async/future_impl.dart:880)
#4      Future._completeError (dart:async/future_impl.dart:660)
#5      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#6      _Completer.completeError (dart:async/future_impl.dart:27)
#7      Future.any.onError (dart:async/future.dart:623)
#8      _RootZone.runBinary (dart:async/zone.dart:1666)
#9      _FutureListener.handleError (dart:async/future_impl.dart:178)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:859)
#11     Future._propagateToListeners (dart:async/future_impl.dart:880)
#12     Future._completeError (dart:async/future_impl.dart:660)
#13     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:564)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
)

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
hiddify.com/fa/manager
