### ISSUE TITLE
تلفیق سایفون و هدیفای

### ISSUE THREAD

**Issue by hamed1363fazli** [hiddify/Hiddify-Manager#4418]
سلام 
ممنون از زحماتتون 
اگه بشه از سایفون هم تو اوتباند ها استفاده کرد خیلی خوب میشه 
الان سایفون رو تو پنل صنایی و علیرضا میشه استفاده کرد حتی قابلیت اینو داره لوکیشن عوض کنیم 
github psiphonelinux هست 
https://github.com/SpherionOS/PsiphonLinux
خدا قوت

**Comment by litoosh13** [comment]
سلام هیدیفای رنج وسیعی از پروتکل های عام رو ساپورت میکنه 
لطفا در صورتی که میتونید اینکارو خودتون انجام بدین و اطلاع بدین تا به پروژه اضافه کنیم تشکر
https://t.me/hiddify_board
