### ISSUE TITLE
مشکل در محاسبه آخرین اتصال کاربران 

### ISSUE THREAD

**Issue by R30na** [hiddify/Hiddify-Manager#442]
به نظر میرسه محاسبه زمان آخرین اتصال کاربران مشکلی داره. من برای تست کاربر ادمین رو قطع کردم و تا ساعتها بهش وصل نشدم ولی همش میزنه چند ثانیه پیش وصل شده. 
 روی کاربرا هم به همین شکله یکی بهم پیام داد من مشکل دارم وصل نمیشم ولی آخرین اتصالشو میزد چند ثانیه پیش. 
میشه بگین مبنای محاسبه این زمان چیه؟

**Comment by NikanMirH** [comment]
موافقم متاسفانه هنوز این مشکل وجود داره

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
