### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by pourmirzai** [hiddify/Hiddify-Manager#4421]
# Bug/Feature: Android TV Support
**Description**:     Hiddify APK can be installed on Android TV box and I can connect to the server very well. However, there are two issues:
1. Using the remote, I can navigate and have access to everything on the left side of the app using my remote control. I can add a server, connect, and check ping. However, I can not access settings, proxies, and everything in the menu on my landscape screen. In fact, up and down buttons work but the Right (and probably left) button won't work. If this problem is solved, I belive the Hiddify app would be completely compatible with Android TV.
2. I can not download it from Playstore and I need to send the APK file to my TV to install or update app. It would be great to be able to install it directly. I'm using Mibox first generation with Android TV 9.
Thanks for all your efforts!

## Details:
**Hiddify Version**: 10.70.4
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-101-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
please use the latest version if problem persist, provide the problem with screenshots in the new issue
