### ISSUE TITLE
The key editing window does not open

### ISSUE THREAD

**Issue by IlyaVas01** [hiddify/Hiddify-Manager#4422]
# Bug/Feature:
Hi.
I ask you to help. After updates, the key editing button stopped working on some of my servers. I ask you to help.  I am attaching a video to clearly explain the problems.

I tried rebooting the server. I checked the pop-up window settings on the site. Cleared browser data. Didn't help

https://github.com/user-attachments/assets/923be21e-b743-44c2-aa55-051e85876094

## Details:
**Hiddify Version**: 10.70.4
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-116-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by Edward-Forix** [comment]
Переключи панель на английский язык и всё заработает, я тоже столкнулся с этой проблемой

**Comment by IlyaVas01** [comment]
> Переключи панель на английский язык и всё заработает, я тоже столкнулся с этой проблемой

Спасибо большое. Помогло

**Comment by litoosh13** [comment]
this issue did report to the developer, please use English version until we fix this...thanks in advance
