### ISSUE TITLE
hiddify-panel-failed

### ISSUE THREAD

**Issue by h291ad** [hiddify/Hiddify-Manager#4424]
سلام وقت بخیر، متاسفانه نصب hiddfy جدید با مشکل مواجه شده به اینصورت که کامند نصب وارد میشه ولی در انتها ، نصب بدرستی انجام نمیشه و سرویسا تو حالت     hiddify-panel                 failed قرار میگیرند ، چندین بار هم تست کردم.

تشکر

**Comment by nimzyC** [comment]
Hi
I have the same problem
checked the panel logs
here is the log :
```
Traceback (most recent call last):
  File "/opt/hiddify-manager/hiddify-panel/app.py", line 6, in <module>
    bjoern.run(wsgi_app=hiddifypanel.create_app(), host="127.0.0.1", port=9000)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/base.py", line 115, in create_app
    hiddifypanel.panel.common.init_app(app)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/common.py", line 186, in init_app
    import hiddifypanel.panel.commercial.telegrambot as telegrambot
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/telegrambot/__init__.py", line 1, in <module>
    from hiddifypanel.panel.commercial.restapi.v1 import bot, register_bot, register_bot_cached
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/__init__.py", line 8, in <module>
    from .tgbot import bot, register_bot, register_bot_cached, TGBotResource
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 17, in <module>
    bot = telebot.TeleBot("", parse_mode="HTML", threaded=False, exception_handler=ExceptionHandler())
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/__init__.py", line 196, in __init__
    util.validate_token(self.token)
  File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/util.py", line 694, in validate_token
    raise ValueError('Token must contain a colon')
ValueError: Token must contain a colon
```
``

**Comment by ShawnJim** [comment]
> Hi I have the same problem checked the panel logs here is the log :
> 
> ```
> Traceback (most recent call last):
>   File "/opt/hiddify-manager/hiddify-panel/app.py", line 6, in <module>
>     bjoern.run(wsgi_app=hiddifypanel.create_app(), host="127.0.0.1", port=9000)
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/base.py", line 115, in create_app
>     hiddifypanel.panel.common.init_app(app)
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/common.py", line 186, in init_app
>     import hiddifypanel.panel.commercial.telegrambot as telegrambot
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/telegrambot/__init__.py", line 1, in <module>
>     from hiddifypanel.panel.commercial.restapi.v1 import bot, register_bot, register_bot_cached
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/__init__.py", line 8, in <module>
>     from .tgbot import bot, register_bot, register_bot_cached, TGBotResource
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 17, in <module>
>     bot = telebot.TeleBot("", parse_mode="HTML", threaded=False, exception_handler=ExceptionHandler())
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/__init__.py", line 196, in __init__
>     util.validate_token(self.token)
>   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/util.py", line 694, in validate_token
>     raise ValueError('Token must contain a colon')
> ValueError: Token must contain a colon
> ```
> 
> ``

same

**Comment by ShawnJim** [comment]
> > Hi I have the same problem checked the panel logs here is the log :
> > ```
> > Traceback (most recent call last):
> >   File "/opt/hiddify-manager/hiddify-panel/app.py", line 6, in <module>
> >     bjoern.run(wsgi_app=hiddifypanel.create_app(), host="127.0.0.1", port=9000)
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/base.py", line 115, in create_app
> >     hiddifypanel.panel.common.init_app(app)
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/common.py", line 186, in init_app
> >     import hiddifypanel.panel.commercial.telegrambot as telegrambot
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/telegrambot/__init__.py", line 1, in <module>
> >     from hiddifypanel.panel.commercial.restapi.v1 import bot, register_bot, register_bot_cached
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/__init__.py", line 8, in <module>
> >     from .tgbot import bot, register_bot, register_bot_cached, TGBotResource
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/commercial/restapi/v1/tgbot.py", line 17, in <module>
> >     bot = telebot.TeleBot("", parse_mode="HTML", threaded=False, exception_handler=ExceptionHandler())
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/__init__.py", line 196, in __init__
> >     util.validate_token(self.token)
> >   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/telebot/util.py", line 694, in validate_token
> >     raise ValueError('Token must contain a colon')
> > ValueError: Token must contain a colon
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ``
> 
> same

The system can be updated to the latest version 10.70.5. The panel appears to be functioning normally now.
