### ISSUE TITLE
direct tls_tcp disabled and can't be re-enabled

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Manager#4428]
برای کانفیگ های direct نمیشه tls_tcp رو استفاده کرد (لیست نمی کنه) و فقط گزینه xtls_tcp قابل انتخاب کردنه که این مدل در اکثر کلاینت های جدید منسوخ شده و اصلا ایمپورت نمیشه. حتی توی v2rayN از بین گزینه ها حذف شده و فقط میشه از tls استفاده کرد.
با این وجود هیدیفای اجازه نمیده کانفیگ های tls_tcp برای متد direct فعال بشه و حتی در صورت فعالسازی از پنجره Modify Proxies، در لیست اضافه نمیشه.
نسخه مورد استفاده: 10.70.5

**Comment by pourmirzai** [comment]
از بخش اقدامات > وضعیت رو ک کردی؟ همه چیز فعاله؟

**Comment by litoosh13** [comment]
به اخرین ورژن اپدیت فرمایید
مطالب آموزش در رابطه با کانفیگ کردن صحیح پنل:
hiddify.com/manager
hiddify.com/fa/manager
