### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Alinik68** [hiddify/Hiddify-Manager#4430]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.6
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-116-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

سلام خسته نباشید

برنامه اینستاگرام قسمت ستینگش باز نمیشه و وقتی کلیک میکنی روی ستینگ گزینه لاگ اوت میاره 
با همه کانفیگ های پنل همین وضعیت هست

هم اندروید هم ایفون

**Comment by litoosh13** [comment]
لطفا به اخرین ورژن اپدیت کنید پنل رو و در صورت ادامه داشتن مشکل میتونید گزینه وارپ روی همه بگذارید
مطالب آموزشی مربوط به پنل رو از اینجا میتونید دنبال کنید:
hiddify.com/fa/manager
