### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by Bankzza555666** [hiddify/Hiddify-Manager#4435]
![Screenshot_20240822_204023_Chrome](https://github.com/user-attachments/assets/9178dd19-c01a-4204-85b7-1f1b543fe073)
![Screenshot_20240822_204045_Chrome](https://github.com/user-attachments/assets/f918594d-c3ca-4ca8-bed3-39188ad7285e)
![Screenshot_20240822_204058_Chrome](https://github.com/user-attachments/assets/d578738a-7f6f-4cbd-a530-207841e155ca)
# Bug/Feature:
**Description**:     i will transfer to used Hiddify 

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-117-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
I'm moving to Hiddify. How can I set it up like the old panel?

**Comment by litoosh13** [comment]
you can follow all learning's material about the panel here:
hiddify.com/manager
