### ISSUE TITLE
قطع شدن یک تعداد از کانفیگ ها 

### ISSUE THREAD

**Issue by alisadeghi1997** [hiddify/Hiddify-Manager#4443]
ورژن 10.70.4
متاسفانه یک سری از کانفیگ ها قطع میشن و باید اعمال تغییرات زد تا مجدد بتونن متصل بشن و باز میبینی یک سری دیگه قطع شدن
سرور هتزنر چهار رم و دو سی پی یو اختصاصی

**Comment by litoosh13** [comment]
به اخرین ورژن اپدیت کنید
