### ISSUE TITLE
خطا هنگام تغییر هسته

### ISSUE THREAD

**Issue by rahmatzadmohammad** [hiddify/Hiddify-Manager#4444]
سلام دوستان 
این مورد رو چندبار چک کردم
وقتی هسته رو از روی xray به singbox تغییر میدیم haproxy غیرفعال میسه و پنل بالا نمیاد
[]گ
![Uploading Screenshot_20240824-013102_Termius.jpg…]()

**Comment by litoosh13** [comment]
ور
