### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by alisadeghi1997** [hiddify/Hiddify-Manager#4448]
آقا لطف کنید قسمت تبلیغاتتون رو از تو پنل کنترل حجم کاربر بردارید
شما وقتی اجازه ساخت پنل رو به ما دادید باید اجازه اینم بدید که  تو صفحه کنترل حجم کاربر اون نوار پایین صفحه که به یوتیوب تلگرام گیت هاب شما اشاره میکنه رو برداریم .
بابتش هزینه هم لازم باشه پرداخت میشه ، بخاطر اون تبلیغات مجبوریمبریم ویزویز و ... نصب کنیم که کلی هم پست سرش باگ هایی میاد که هم مارو درد یر میندازه هم شمارو که نمیدونید باگ هایی که گزارش میشن واقعا مربوط به پنلتونه یا اسکریپت های جانبی .

**Comment by litoosh13** [comment]
امکانش وجود نداره لطفا درخواست نفرمایید
