### ISSUE TITLE
Probably backdoored. 

### ISSUE THREAD

**Issue by snapboss** [hiddify/Hiddify-Manager#4452]
hey there. installed hidify 3 days ago, new vps installation. setup 3 users but never got to share the configs or use them  myself.
 logged in to panel today and to my surprise, all 3 users were online,  traffic was over 20gb in 3 days.

Maybe you backdoored it, or someone else did. Anyway GG, well played.

**Comment by litoosh13** [comment]
Please DO NOT Make accusation on no basis and provide more info about the problem.
 you could see our project is simply "open source", and you could check all the code and everything you need

**Comment by sirpolly** [comment]
Дайте какой-нибудь, блин, нормальный работающий vpn
