### ISSUE TITLE
Real DNS subbdomain won't set on manager panel on started settings...

### ISSUE THREAD

**Issue by alexpebody** [hiddify/Hiddify-Manager#4453]
Hello )

I tried set my subbdomain, what I set on my real DNS hostind and Manager Panes said to me about this domain it was taken... So strabge, I set A record to my real IP server, where installed Hiddify... But https://freedns.afraid.org/ work fine, but this is exactly the same A record subbdomain to my real IP server... What different with my real DNS domain with A record to my real IP server, why Manager Panel won't get it?

Thx.

**Comment by alexpebody** [comment]
And yes I found new Issue with DNS forward - routing:

1. what is SNI eztv.re I can't change it, I was set my SNI inside client v2rayn (example) but not result = cert error

2. ERR_NAME_NOT_RESOLVED - DNS routing issue, in defailt settings Enable DNS Routing is on, but in client for PC Windows Hiddify not working until disable "Enable DNS Routing"

3. If I copy config vless from main page user and using v2rayn (example) Ive got this: ERROR [1911316732 324ms] inbound/tun[tun-in]: download: raw-read (tcp my ip server hiddify here):53051->(tcp my ip server domain hiddify here):443: An existing connection was forcibly closed by the remote host.

How can I resolve it?

Thx.

**Comment by litoosh13** [comment]
> And yes I found new Issue with DNS forward - routing (using too reality XTLS direct vless):
> 
> 1. what is SNI eztv.re I can't change it, I was set my SNI inside client v2rayn (example) but not result = cert error
> 2. ERR_NAME_NOT_RESOLVED - DNS routing issue, in defailt settings Enable DNS Routing is on, but in client for PC Windows Hiddify not working until disable "Enable DNS Routing"
> 3. If I copy config vless from main page user and using v2rayn (example) Ive got this: ERROR [1911316732 324ms] inbound/tun[tun-in]: download: raw-read (tcp my ip server hiddify here):53051->(tcp my ip server domain hiddify here):443: An existing connection was forcibly closed by the remote host.
> 
> How can I resolve it?
> 
> Thx.

Hi,
these errors mainly happened due to bad configurations of the domain or blocking specific protocols for example like Reality by your ISP.
You can follow all learning's material about the panel here:
hiddify.com/manager
