### ISSUE TITLE
عدم وجود دکمه ریست کاربر در بعضی از اکانت ها

### ISSUE THREAD

**Issue by 100chi** [hiddify/Hiddify-Manager#4455]
# Bug/Feature:
با سلام
در هیدیفای منیجر ورژن 8.9.9 در بعضی اکانت ها بخش ریست کاربران وجود ندارد
لطفا راهنمایی کنید
متشکرم
![123](https://github.com/user-attachments/assets/e6247d82-32c5-4529-bee1-37c72e64ccba)

**Comment by litoosh13** [comment]
سلام این ورژن از هیدیفای پشتیبانی نمی شود لطفا به آخرین ورژن بروزرسانی نمایید.
اخرین اطلاعیه ها را از اینجا دریافت نمایید:
https://t.me/hiddify_board/
