### ISSUE TITLE
Changing user doesn't work

### ISSUE THREAD

**Issue by LOBACHEVLV** [hiddify/Hiddify-Manager#4457]
# Bug/Feature:
**Description**:   Good afternoon!
When I click on the pencil in the user's line, nothing appears, the screen dims but no pop-up window appears

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-119-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by MrBr0wn** [comment]
#4466
