### ISSUE TITLE
Docker install stop at Building  (8/10)   every time

### ISSUE THREAD

**Issue by huang5307** [hiddify/Hiddify-Manager#4458]
**Describe the bug**

I used docker installed. every time stop at "Building 741.9s (8/10) " ,

```
Building 741.9s (8/10)                                                           
 => [internal] load build definition from Dockerfile                            0.1s
 => => transferring dockerfile: 635B                                            0.1s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                 1.5s
 => [internal] load .dockerignore                                               0.0s
 => => transferring context: 59B                                                0.0s
 => [1/6] FROM docker.io/library/ubuntu:22.04@sha256:adbb90115a21969d2fe6fa7f9  0.0s
 => [internal] load build context                                               4.4s
 => => transferring context: 81.85MB                                            4.1s
 => CACHED [2/6] RUN apt-get update && apt-get install -y whiptail apt-utils c  0.0s
 => CACHED [3/6] WORKDIR /opt/hiddify-manager/                                  0.0s
 => CACHED [4/6] COPY . .                                                       0.0s
 => [5/6] RUN bash install.sh install-docker                                  735.9s
 => => # Collecting wcwidth                                                         
 => => #   Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)                  
 => => # Installing collected packages: wcwidth, asyncio, argparse, typing-extension
 => => # s, urwid, cli_progress                                                     
 => => # Successfully installed argparse-1.4.0 asyncio-3.4.3 cli_progress-2.0.0 typi
 => => # ng-extensions-4.12.2 urwid-2.6.10 wcwidth-0.2.13    
```                       
OS: Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-1027-oracle x86_64)
Docker Compose version v2.6.1

<img width="640" alt="image" src="https://github.com/user-attachments/assets/467ed636-c259-48e3-8ecc-e11c6b63b237">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huang5307** [comment]
the screen i past is the second time i installed. of course, I followed the steps :
git clone https://github.com/hiddify/hiddify-config
cd hiddify-config
touch hiddify-panel/hiddifypanel.db
docker-compose up -d

**Comment by huang5307** [comment]
<img width="709" alt="image" src="https://github.com/user-attachments/assets/712b1d9c-7bf6-4f60-af4e-6c97f74dbdb4">
another try , the same.

**Comment by litoosh13** [comment]
Hi, please mention which version you tried to install

**Comment by tinternet** [comment]
I tried down to [v10.70.0](https://github.com/hiddify/Hiddify-Manager/releases/tag/v10.70.0)

It blocks on cli_progress and one cpu core stays at 100%.

**Comment by litoosh13** [comment]
We noticed the problem and we will fix it...thanks for Pr

**Comment by minimulin** [comment]
Same problem.

Was trying to add `--no-gui` option. Script continues to next steps.
Next was error while compiling mysqlclient extension. 
After installation `apt install python3-dev` next error was `Can't connect to MySQL server on '127.0.0.1:3306` and I surrendered.
