### ISSUE TITLE
اسکنر ASN

### ISSUE THREAD

**Issue by akv79** [hiddify/Hiddify-Manager#4464]
سلام
قبلا یه بخشی توی پنل بود برای اسکن و پیشنهاد دامنه ریالیتی ولی الان هرچی میگردم نمیتونم پیداش کنم
توی بخش آمزش پنل نوشتید لینک "بررسی و پیشنهاد دامنه" ولی جایی به چشمم نخورد
میشه راهنمایی کنید که کجاست؟

**Comment by litoosh13** [comment]
سلام 
بخش مورد نظر برداشته شده.
آموزش های مورد نیاز برای راه اندازی پروتکل های مختلف رو میتونید اینجا مشاهده کنید:
hiddify.com/manager
hiddify.com/fa/manager
