### ISSUE TITLE
connected but not work / hiddify 2.0.5 متصل میشود ولی کار نمیکند 

### ISSUE THREAD

**Issue by alireza-faze** [hiddify/Hiddify-Manager#4465]
سلام .
از زمانی که قابلیت ساب لینک به هیدیفای اضافه شد همه چیز خوب کار میکرد ولی چند روزه پراکسی ها متصل میشن و پیگ رو نشون میدن ولی کار نمیکنن . سرچ گوگل کار نمیکنه ولی لینک مستقیم سایت های داخلی کار میکنن .

**Comment by Hosseinjeff** [comment]
سلام.
منم همین مشکل رو دارم. عجیبه کس دیگه ای این مشکل رو نداشته. مشکل شما حل شد؟

**Comment by litoosh13** [comment]
این موضوع به موارد بسیاری میتونه مربوط باشه لطفا دقیق تر توضیح بدین
چ کانفیگی دارید و کدوم ساب لینک مد نظرتون هست ؟

**Comment by Hosseinjeff** [comment]
سلام و وقت به خیر،
ممنون از پاسخ دوست عزیز.

مهم نیست چه لینک ساب ی بذارم. متصل میشه و میزنه وصل و پینگ هم نشون میده، ولی داخل هر نرم افزار که فیلتره میرم انگار اصلا فیلتر شکن وصل نیست و اتفاقی نمی افته.

این مشکل رو خیلی گروه ها و کانال های تلگرام دیدم میگن، به طوری که جایی بخوان هیدیفای رو شیر کنن، نسخه 1.5.4 رو که این مشکل رو نداره شیر میکنن.

**Comment by litoosh13** [comment]
عزیز بعید میدونم مشکل از پنل باشه فکر میکنم درست نرم افزار رو تنظیم نکردین از هیدیفیای نکست استفاده میکنید ؟

**Comment by alireza-faze** [comment]
update : 
بعد از ابدیت برنامه تست همه کانفیگ ها و ساب لینک ها یکیشون درست کار کرد و تا الان خوب کارمیکنه (ساب6 برای من ) .
نکته جالب اینجاست که کانفیگ هر ساب لینک کار میکرد و تاخیر رو نشون میداد ولی بازم سایت های فیلتر رو نمیتونستن باز کنن.
من همچنان این تیکت رو باز میزارم تا اگر هنوز مشکل برقرار بود دوستان بگن و سازندگان گرامی اطلاع رسانی کنن

**Comment by litoosh13** [comment]
سلام اینجا مربوط به مشکلات پنل هست مشکل شما از سمت برنامه هست به همین خاطر بسته میشود
