### ISSUE TITLE
مشکل در نصب هیدیفای

### ISSUE THREAD

**Issue by generalcyberi** [hiddify/Hiddify-Manager#4467]
سلام.
سرور اوبونتو 22.10 و 22.4 هم تست کردم
![Screenshot_2024-09-07-08-55-55-058_com server auditor ssh client](https://github.com/user-attachments/assets/d45ff418-0a45-43cf-8789-b272be212230)

پردازنده 1
رم 2

موقع نصب این ارور رو میده

**Comment by litoosh13** [comment]
ارور خاصی نیس اگر منظورتون warn هست اون عادیه
