### ISSUE TITLE
خطا بعد از کلیک: به روز رسانی فوری کاربران

### ISSUE THREAD

**Issue by ramdroid2015** [hiddify/Hiddify-Manager#4469]
در صفحه کاربران بعد از کلیک روی لینک
"مصرف کاربر ها هر ۶ دقیقه یکبار به روز می شود. برای به روز رسانی فوری را کلیک کنید"
چنین صفحه‌ای نمایش داده میشود:
{
  "msg": "last update task is not finished yet."
}

Hiddify Version**: 10.70.7
Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-119-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
بعد از یک بار کلیک روی دکمه "اینجا" و دریافت اطلاعات در صورتی که باز میخواهید از  دکمه "اینجا" استفاده کنید باید چند دقیقه صبر کنید و بعدا باز کلیک نمایید
