### ISSUE TITLE
Can Hiddify support vmess and ss protocols?

### ISSUE THREAD

**Issue by zryyyy** [hiddify/Hiddify-Manager#4470]
**Describe the bug**
Can Hiddify support vmess and ss protocols? I have found that Hiddify does not support these two protocols very well. My subscription link has two ss protocols and four vmess nodes, but the two ss nodes won't connect and only three of the four vmess nodes can be imported. I don't know what's causing this, could you please take a look? Thank you very much!

**Comment by litoosh13** [comment]
Hiddify do support the ss and vmess but it depends on your internet provider and your configs of domain in the panel in order to work!
Follow the learnings material here :
hiddify.com/manager
https://t.me/hiddify_board
