### ISSUE TITLE
کامل کردن فرگمنت

### ISSUE THREAD

**Issue by shehnipoor** [hiddify/Hiddify-Manager#4478]
اگه امکان داره یه اپدیت سریع و اورژانسی برای انتخاب حالت tlshello و 1-1 و 2-1 رو تو پنل اضافه کنید
خیلی حیاتیه -- خیلی از اپراتورها روی این نوع فرگمنت عملکرد بهتری دارن

**Comment by litoosh13** [comment]
این مورد در دست بررسی توسط دولوپرها قرار دارد با تشکر منتظر بمانید
