### ISSUE TITLE
پیشنهادات برای توسعه محصول بهتر

### ISSUE THREAD

**Issue by M-Sadegh-M** [hiddify/Hiddify-Manager#4481]
داخل تلگرام یک صحبتی شد و @lymanjre گفتن ایشو ثبت کنم.

به نظرم هیدیفای باید مثل بقیه پنل ها نوع ساختن کانفیگ را به کاربر واگذار کنه
با محدودیت فعلی خیلی کانفیگ ها را نمیشه داخل هیدیفای ساخت
و روز به روز که روش های جدید بیاد مشکل بزرگ تر می‌شه. 

مثلا الان روش دامین فرانتینگ به کمک فستلی را نمیشه داخل هیدیفای پیاده کرد

نیازه هم sni هم host یک چیزی ثبت بشه و تیک allow insecure هم زده بشه

یا همین روش های httpupgrade بدون tls

مشکل بعدی هم این هست که یک دامنه که اضافه می‌کنیم هر مدل کانفیگ تیک زده باشیم ساخته می‌شه در حالی که اون کانفیگ با یک دامنه دیگه کار می‌کنه
مثلا من یک دامنه فیلتر برای فرگمنت دارم، یک دامنه برای spilit دارم یک دامنه سالم برای httpupgrade ولی از همش برا همه چی کانفیگ خروجی میره داخل لینک ساب

**Comment by ExtremeDot** [comment]
منم چند تا پیشنهاد دارم

---------------
شما وقتی چندین پورت توی پنل تعریف میکنید 

1- دامین ها  گزینه ای با قابلیت ویرایش داشته باشن ، برای اینکه از چه پورتی استفاده کنه

برای مثال ما روی 2 تا پورت سرور رو ران کردیم، پورت 2096 و 1100

توی این حالت دامین های پشت cdn روی پورت 1100 کار نمیکنن در صورتیکه توی ساب لینک برای کاربر نمایش داده میشه

-------------
2- پیشنهاد دوم اینه که دامین ها فقط از طریق لینک سابسکریپشن نشون داده بشه

مثلا برای کاربر لینک سابسکریپشن رو میفرستیم، کاربر میاد آدرس دامین سابسکریپشن  رو با آدرس دامین روی یکی از کانفیگ ها عوض میکنه و تمامی لینک های هیدیفای که تعریف کردیم رو دریافت میکنه

بنظرم باید فقط از طریق لینک سابسکریبشن این کار انجام بشه و کاربر نتونه از طریق آدرس دامین های دیگه به دامین هایی که توی لیست سابسکرایب نیستن دسترسی پیدا کنه

--------------

3- پیشنهاد سوم اینکه کاربر بتونه حداقل کانفیگ های جدید تعریف کنه، توی پنل 10 من هر کاری کردم نتونستم tcp tls رو دریافت کنم، فقط روی http نشون داده میشه که اونم برای من کار نمیکنه

توی کدها هم یه نگاه اجمالی انداختم همه چیز به نظر درست میاد ولی ساخته نمیشه نمیدونم چرا

خیلی خوب میشه اگر یه آموزش ساخت کانفیگ برای هیدیفای بذارید

مثلا بیاید توی یه ویکی  واریابل ها رو تعریف کنید 
بعد ادمین بتونه خودش با استفاده از واریابل ها کانفیگ بنویسه، مسئولیتش هم با خودش

با این اتفاق ادمین ها میتونن تمامی کانفیگ هایی که دلشون میخواد روبسازن


```
{% if hconfigs['vmess_enable'] and hconfigs['grpc_enable'] and hconfigs['h2_enable'] %}
```
--------------------
4- امکان تعریف وارپ روی کانفیگ باشه، مثلا 10 تا کانفیگ دارم ولی میخوام روی 2 تاش ترافیک از طریق وارپ رد بشه

و اینکه قابلیت تعریف geosite توی warp اضافه بشه، در حال حاضر فقط domain ست میشه
-----------------

5- پورت های هیستریا رو بشه تغییر داد

**Comment by ExtremeDot** [comment]
یه پیشنهاد برای نسخه بعدی دارم 

توی نسخه بعدی میتونیم یه پوشه `custom_config` داشته باشیم که توی اون یه فایل example.j2 با توضیحات کامل داشته باشیم که ادمین پنل بتونه کانفیگ های دلخواه خودش رو بسازه.

با هر بار اجرا شدن `hiddify-manager` یا `apply config` کانفیگ ها رو برای هر j2 فایل بسازه

**Comment by ExtremeDot** [comment]
> > 4- امکان تعریف وارپ روی کانفیگ باشه، مثلا 10 تا کانفیگ دارم ولی میخوام روی 2 تاش ترافیک از طریق وارپ رد بشه
> 
> فک نمیکنم این امکانش باشه هسته این قابلیت را نداره، چون outbond ها از داخل بخش routing که مشترک هست تنظیمات مسیربابی را دریافت میکنن و من تو داکیومنت خود xray ندیدم این موضوع را که بشه استثنا قائل شد

> 

اینو میشه یه هسته کاستوم xray جداگونه ساخت ، مثلا xray_hiddify_custom و ازش استفاده کرد و تداخلی با خود xray نمیکنه

خیلی کاربردی میشه اگه اجرا بشه 

بعضی از سایت ها کلا راه نمیدن به خیلی از دیتاسنترها و مجبور میشیم که بندازیم پشت وارپ، مخصوصا برا لاگین کردن سایت ها و سرویس هایی مثل  `facebook`  یا `tiktok` یا `instagram` و `whatsapp` و اسپاتیفای و ...... 

بدی ماجرا اینه که توی بهترین حالت وارپ  میتونه 80 مگابایت ترافیک رو رد کنه و اگه بخوایم کلا ترافیک پرمصرف اینستاگرام رو بندازیم روی وارپ ، خیلی سرعت کند میشه و عملا پهنای گیگاباتی سرور محدود میشه روی 500 مگابایت.

میتونیم کلا یه کانفیگ بذاریم حالا با هر هسته ای ، مثل سینگ باکس یا v2fly و حتی کاستوم شده xray ، کلا کانفیگ هاش رو از روی وارپ رد کنیم برای دور زدن محدودیت های لاگین و استفاده از سرویس های این سایت ها.

> > و اینکه قابلیت تعریف geosite توی warp اضافه بشه، در حال حاضر فقط domain ست میشه
> 
> فک کنم قابلیت تعریف geosite بود من و یک بار تست کردم و جواب داد. ولی دقیق یادم نیست ولی 100% درست میگید.

امکان ویرایش دستی هست برای روتینگ ولی توی پنل، فیلدی برای geosite نداره.

**Comment by ExtremeDot** [comment]
من قبلا این کار رو روی هیستریا و توییک انجام میدادم، کلا روتینگ برای وارپ رو مینداختم روی سینگ باکس، ولی الان هیستریا که خیلی خوب بود دیگه کار نمیده و محدود شده.
یه مشکل دیگه هم که داشت این بود که باید از نرم افزارهای با هسته سینگ باکس استفاده میکردید تا بیاد بالا.

اکثر نرم افزارها با هسته xray هستن و هیستریا و توییک رو اصلا به کاربر نشون نمیدن، مخصوصا توی iOS که اونم فقط karing خوب ساپورتش میکنه ولی با این حال اکثرا قطع و اختلال خیلی روش زیاد هست.


اگه یه هسته کاستوم xray استفاده بشه بنظرم خیلی بهتر میشه

**Comment by litoosh13** [comment]
> با احترام، من فک میکنم این موارد خیلی شخصی هست و عمومیت نداره.
> 
> من پیگیر درخواست های عمومی تر هستم. چیزایی که اغلب افراد در گروه مطرح میکنن و من دیدم همین بحث ایجاد کانفیگ های مختلف با آزادی عمل بیشتر بوده که زیر مجموعه اش میشه:
> 
> * ساخت کانفیگ با تنظیمات مختلف
> * چه کانفیگی از کدوم دامنه استفاده کنه هست.
> 
> و بقیه موارد عمومی که ادمین ها روزانه باهاش درگیر هستند مورد هرچی عمومی تر ارزش کار و توسعه بیشتر

مواری که ذکر کردین به لیست "موارد مورد پیگیری" توسط دولوپرها اضافه شده...تشکر از صبر و شکیبایی شما عزیزان
