### ISSUE TITLE
Unable to Get AllConfigsAPI User

### ISSUE THREAD

**Issue by iegl3** [hiddify/Hiddify-Manager#4482]
Get AllConfigsAPI  give invalid request response

**Comment by litoosh13** [comment]
Please review API documentation then use API

**Comment by iegl3** [comment]
> Please review API documentation then use API

already do, and this what i got
![image](https://github.com/user-attachments/assets/cfe9576f-13e3-408a-9d25-728fd967587b)

**Comment by iegl3** [comment]
> did you read this : https://hiddify.com/manager/contribution/How-to-use-API-in-HiddifyManager-project/?h=api ?? And please be specific about what you want to do ? What is the expected behavior ? And what you get as error ?

i want to get user config list protocol by sorting them with uuid like what you guys provide in API documentation in domain.com/proxy_path/api/docs#/paths/proxy_path---secret_uuid--api-v2-user-all-configs/get. 

when i try to fetch the url like what you guys do in documentation, it always give me status 400 Bad Request, Invalid Request.

the response should be like this right? ![image](https://github.com/user-attachments/assets/7917d33d-3d63-48a7-88ae-2c4f42887026)

but yes, this is what i got..
![image](https://github.com/user-attachments/assets/ebf82ef2-8c2a-4564-b100-754cbb5aa800)

**Comment by litoosh13** [comment]
![Screenshot from 2024-10-06 12-49-59](https://github.com/user-attachments/assets/8b459d2c-7af0-456e-a71d-b5a66eb83f18)
look i tried same thing and i got no error
please read document carefully and add **Hiddify-API-Key** as mentioned here:
https://hiddify.com/manager/contribution/How-to-use-API-in-HiddifyManager-project/
_panel should be at latest version_

**Comment by iegl3** [comment]
> ![Screenshot from 2024-10-06 12-49-59](https://private-user-images.githubusercontent.com/103038572/373935662-8b459d2c-7af0-456e-a71d-b5a66eb83f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjE0MjksIm5iZiI6MTcyODI2MTEyOSwicGF0aCI6Ii8xMDMwMzg1NzIvMzczOTM1NjYyLThiNDU5ZDJjLTdhZjAtNDU2ZS1hNzFkLWI1YTY2ZWI4M2YxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMDMyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDY4OGY3Y2ExZWNkYTdmNTMwNmNiNDRkODUyOWY2ZjI5ODcyOTUwOTliMTI0YmRmODIyNWZjZGU4Y2M5N2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6KPebxa0gemvL5721OqU15teE7ov9dNsNcW2NlZEW-w) look i tried same thing and i got no error please read document carefully and add **Hiddify-API-Key** as mentioned here: https://hiddify.com/manager/contribution/How-to-use-API-in-HiddifyManager-project/ _panel should be at latest version_

thats real weird..
my full url is like this https://domain.com/{proxy_path}/{secret_uuid}/api/v2/user/all-configs/
and i can't even access the full url..
the requirement authentications like proxy path, admin token, etc, i already fill them..
im on version 10.70.7

**Comment by iegl3** [comment]
> > > ![Screenshot from 2024-10-06 12-49-59](https://private-user-images.githubusercontent.com/103038572/373935662-8b459d2c-7af0-456e-a71d-b5a66eb83f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjE0MjksIm5iZiI6MTcyODI2MTEyOSwicGF0aCI6Ii8xMDMwMzg1NzIvMzczOTM1NjYyLThiNDU5ZDJjLTdhZjAtNDU2ZS1hNzFkLWI1YTY2ZWI4M2YxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QwMDMyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDY4OGY3Y2ExZWNkYTdmNTMwNmNiNDRkODUyOWY2ZjI5ODcyOTUwOTliMTI0YmRmODIyNWZjZGU4Y2M5N2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6KPebxa0gemvL5721OqU15teE7ov9dNsNcW2NlZEW-w) look i tried same thing and i got no error please read document carefully and add **Hiddify-API-Key** as mentioned here: https://hiddify.com/manager/contribution/How-to-use-API-in-HiddifyManager-project/ _panel should be at latest version_
> > 
> > thats real weird.. my full url is like this [https://domain.com/{proxy_path}/{secret_uuid}/api/v2/user/all-configs/](https://domain.com/%7Bproxy_path%7D/%7Bsecret_uuid%7D/api/v2/user/all-configs/) and i can't even access the full url.. the requirement authentications like proxy path, admin token, etc, i already fill them.. im on version 10.70.7
> 
> please read the docs and IN CASE OF ERROR make issue !

dude, i already read your docs and stuff about 20 times or more and its not helping at all
