### ISSUE TITLE
tls tcp direct vmess عدم دریافت

### ISSUE THREAD

**Issue by ExtremeDot** [hiddify/Hiddify-Manager#4484]
درود به همه ادمین های عزیز

من توی پنل 10 متاسفانه نمیتونم کانفیگ `trojan` یا `vmess` با `tcp` دریافت کنم.

```
tls tcp direct vmess
```
میخواستم ببینم چطور میتونم این مشکل رو برطرف کنم

```
  /opt/hiddify-manager/xray/configs/05_inbounds_10_vmess_new.json   
```

این فایل رو چک کردم بنظر میاد کانفیگ ساخته شده و کلاینت ها هم تعریف شدن

```
/opt/hiddify-manager/xray/configs/05_inbounds_10_vmess_new.json.j2 
```

```
{% if hconfigs['vmess_enable'] and hconfigs['tcp_enable'] %}
```
توی `hconfig` یه نگاه انداختم و `vmess_enable` و `tcp_enable` هم `true` هستن

```
"vmess_enable": true,
 "tcp_enable": true,
```

ولی توی لیست سابسکریپشن نیستن

چطوری این مشکل رو برطرف کنم؟

کانفیگ های فعال در لیست سابسکریپشن توی چه فایلی اضافه میشه؟ که من خودم دستی بهش اضافه کنم؟

ممنونم

**Comment by litoosh13** [comment]
با سلام به هیچ عنوان نیاز به دستکاری فایل جیسون /json
که گفتین نیست!!!
شما به سادگی میتونید از قسمت تنظیمات بعد بخش پروکسی ها ترو.جان رو فعال کنید 
لطفا اموزش استفاده از پنل رو از کانال یوتوب یا چنل تلگرام هیدیفای دنبال کنید.
https://t.me/hiddify
