### ISSUE TITLE
TCP configs do not work on Hiddify-Next or V2rayNG

### ISSUE THREAD

**Issue by rasoolkhalifa** [hiddify/Hiddify-Manager#4486]
**Describe the bug**
TCP configs do not work on Hiddify-Next or V2rayNG

**Screenshots**
![dsa](https://github.com/user-attachments/assets/cb7abee7-ca87-49b9-931b-62a117e3dc06)

**Additional context**
When using Hiddify-Next which uses singbox TCP configs do not work! when I use the same sub link in Clash-Meta the TCP configs work with no problem. seems like the errors in the hiddify-next log suggest that there is a problem with singbox core and singbox has fixed this in a update I believe? 
All in all I really need TCP though WS and all other protocols are fine but TCP should work as well especially on Hiddify-Next!

Thanks

**Comment by litoosh13** [comment]
Please provide more info about the version of hiddify next and the specification of the sub links and config you've tried to connect
