### ISSUE TITLE
The user's editor is not working

### ISSUE THREAD

**Issue by Khfdd** [hiddify/Hiddify-Manager#4487]
when I want to edit the user, a gray screen appears and that's it. I tried it on my phone and laptop in browsers from Yandex, Opera, DuckDuck and Telegram. It doesn't work the way I would like it to. I thought that users could be configured. Here are the screenshots:
https://github.com/user-attachments/assets/0c1c206b-a945-4c8f-ba57-727d6d50df6f

**Comment by kugona** [comment]
Change your language, you set up Russian, but in this localization it is broken
put it in English

**Comment by Khfdd** [comment]
It worked, thanks
