### ISSUE TITLE
Irresponsible use of panels

### ISSUE THREAD

**Issue by iambabyninja** [hiddify/Hiddify-Manager#4495]
Good afternoon, following recent discussions about panels and their configuration issues, the following was proposed by @rprx:

https://t.me/projectXtls/358

> 请各个面板改为默认不暴露在公网并引导用户使用 ssh 转发，我将于下周一在 README 中 unlink 仍默认暴露在公网的面板，请将此消息转发给各面板的开发者

**Comment by litoosh13** [comment]
Hi,
Could you be more specific about the problem and please ONLY use English

**Comment by litoosh13** [comment]
This issue is transferred to the developers and there is no need to worry. Hiddify does not expose anything publicly
