### ISSUE TITLE
کار نکردن کد شخصی HTML در صفحه کاربران

### ISSUE THREAD

**Issue by mrgeex** [hiddify/Hiddify-Manager#4498]
**توضیحات باگ**
من در بخش "شخصی سازی صفحه کاربران" کد html رو وارد کردم ولی بجای قراردادن همون کد در صفحه کاربر، بجاش کد رو در "" قرار میده و این باعث میشه که بصورت متن به صفحه وارد بشه.

**مراحل**
1. بخش تنظیمات >> شخصی سازی صفحه کاربران >> متن باکس پشتیبانی
2. روی Source کلیک کردم تا سورس کد رو قرار بدم.
3. کلیک روی گزینه "ثبت"
4. بررسی صفحه کاربر

**رفتار مد نظر**
در صورتیکه سورس کد به این بخش اضافه کردیم اون رو عینا بدون تغییر استایل و کدش به صفحه اضافه کنه.

**Devices**
 - server OS: ubuntu 22.04 Hetzner
 - Browser Brave (Google Chrome)
 - Hiddify Version 10.70.7

**Screenshots**
![1](https://github.com/user-attachments/assets/e06943f4-9dcc-46f2-a15a-64dcd0d4b63a)
![2](https://github.com/user-attachments/assets/f4dea56a-a6f6-48ef-bd8c-3355d8607641)
![3](https://github.com/user-attachments/assets/9f9c8eae-0b5a-49e5-9001-bffec7002ff3)

**Comment by litoosh13** [comment]
سلام بله در جریان هستیم
قبلا گزارش شده 
مورد بررسی قرار گرفته این مورد
