### ISSUE TITLE
Number of connections per user

### ISSUE THREAD

**Issue by azatabd** [hiddify/Hiddify-Manager#4500]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-46-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

Is it possible to limit the number of connections per user?

**Comment by litoosh13** [comment]
hello it is not possible and we have no intention to add this feature
