### ISSUE TITLE
User API give 400 Bad Request status

### ISSUE THREAD

**Issue by iegl3** [hiddify/Hiddify-Manager#4502]
# Bug/Feature: BUG
**Description**:    User API is not working at all

## Details: User API always give response 400 Bad Request even if the auth is already filled
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-6.5.0-1025-gcp-x86_64-with-glibc2.35
**User Agent**:      Unknown

![image](https://github.com/user-attachments/assets/cb8a10e5-be3e-4f2a-a956-ac9e0812b0a0)

**Comment by litoosh13** [comment]
you could ask about api here :
https://t.me/hiddify_board
the erorr you make issue about are didicated to you and other users doesnt have this erorr so PLEASE DONT MAKE  new issue

**Comment by iegl3** [comment]
> you could ask about api here :
> https://t.me/hiddify_board
> the erorrs you make issue about are didicated to you and other users doesnt have this erorr so PLEASE DONT MAKE  new issue

no solution huh
