### ISSUE TITLE
Disable Ipv6 will prevent sever to be filtered or detected?

### ISSUE THREAD

**Issue by alexlii1971** [hiddify/Hiddify-Manager#4505]
Hello,

**End-to-End Encryption: IPv6 supports direct, end-to-end connections without the need for intermediate address translation, which can simplify the handling of SSL connections.**

It seems that Hiddify officially do not recommend Ipv6 both on Hiddify server and client.

or, do you recommend disable Ipv6 only on client?

Thanks

**Comment by litoosh13** [comment]
It is completely ok to use ipv6 for both client and server for example you could use it very easily with reality and no need of CDN

**Comment by alexlii1971** [comment]
Hello,

Thanks for reply.

The reason why I submit the post is that I read your tutorial at:
https://hiddify.com/manager/basic-concepts-and-troubleshooting/Basic-Concepts/?h=ipv6#ip-version-6-or-ipv6

```
_Disable IPv6:
If you do not use IPV6, you can disable it in your system settings. IPV6 may cause DNS Leakage, so disabling it can help solve the problem._
```
It seems that IPv6 is quite easy to cause DNS Leakage, and DNS Leak will cause the server IP to be filtered by the goverment firewall, am I right?

If yes, I will disable Ipv6 both on server and client.

Really expect your professional guide.

Thanks

**Comment by litoosh13** [comment]
> Hello,
> 
> Thanks for reply.
> 
> The reason why I submit the post is that I read your tutorial at: https://hiddify.com/manager/basic-concepts-and-troubleshooting/Basic-Concepts/?h=ipv6#ip-version-6-or-ipv6
> 
> ```
> _Disable IPv6:
> If you do not use IPV6, you can disable it in your system settings. IPV6 may cause DNS Leakage, so disabling it can help solve the problem._
> ```
> 
> It seems that IPv6 is quite easy to cause DNS Leakage, and DNS Leak will cause the server IP to be filtered by the goverment firewall, am I right?
> 
> If yes, I will disable Ipv6 both on server and client.
> 
> Really expect your professional guide.
> 
> Thanks

you are right in this matter but some ISP work better with ipv6 than ipv4 so it is a personal choice but the statement about dns Leak is true so it is up to you
