### ISSUE TITLE
Manual routing setup

### ISSUE THREAD

**Issue by kugona** [hiddify/Hiddify-Manager#4510]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I want to see manual routing configuration in the service.

**Describe alternatives you've considered**
As an alternative, I would like to see an addition to routing, adding domains, even if they are blocked

**Additional context**
-

**Comment by litoosh13** [comment]
you should be more specific about your issue !!!!
you didnt say why you need it?
what exactly you need?

**Comment by kugona** [comment]
> you should be more specific about your issue !!!! you didnt say why you need it? what exactly you need?
> 
> you could also consider asking your question here: https://t.me/hiddify_board

this is not a problem, but a wish.
I need this for detailed routing setup, and not the one already prepared by the developers.

now discord has been blocked in the Russian Federation and due to a small problem in routing, users with hiddifymanager cannot access the service.

setting up via 03_routing.json.j2 did not help at all

**Comment by litoosh13** [comment]
> > you should be more specific about your issue !!!! you didnt say why you need it? what exactly you need?
> > you could also consider asking your question here: https://t.me/hiddify_board
> 
> this is not a problem, but a wish. I need this for detailed routing setup, and not the one already prepared by the developers.
> 
> now discord has been blocked in the Russian Federation and due to a small problem in routing, users with hiddifymanager cannot access the service.
> 
> setting up via 03_routing.json.j2 did not help at all

aha for routing problem you could use warp !
just add discord.com to the settings into warp section and there should be no problem

**Comment by kugona** [comment]
> > > you should be more specific about your issue !!!! you didnt say why you need it? what exactly you need?
> > > you could also consider asking your question here: https://t.me/hiddify_board
> > 
> > 
> > this is not a problem, but a wish. I need this for detailed routing setup, and not the one already prepared by the developers.
> > now discord has been blocked in the Russian Federation and due to a small problem in routing, users with hiddifymanager cannot access the service.
> > setting up via 03_routing.json.j2 did not help at all
> 
> aha for routing problem you could use warp ! just add discord.com to the settings into warp section and there should be no problem

1. entering 2ip.ru there is the same, the IP was also transmitted directly
2. passing myip.com to warp, the IP of the vds was transmitted, but not warp's.
3. warp works and the config is working.
4. warp works only with the "all" option, but sites from.ru also do not work.

I insist on adding manual routing, and not using warp
