### ISSUE TITLE
Manual routing settings [v.2]

### ISSUE THREAD

**Issue by kugona** [hiddify/Hiddify-Manager#4513]
**Is your feature request related to a problem? Please describe.**
no problem, this is a request for a future update of hiddifymanager

**Describe the solution you'd like**
good afternoon. yesterday I already created an application here, but unfortunately it was not approved, based on a small amount of data.

today I want to expand and write what I want to see in this project and what I think many people want to see.
the fact is that the service does not have a routing setting (not counting warp), which is a huge problem.

I would like to see the ability to configure routing in the form of:
1. blocking IP or domains
2. skipping IP or domains in proxying
3. proxy IP or domains

and immediately a correction that if we add a site that is not proxied by default due to country settings, then it will be proxied.

for users, it is worth adding a notification that adding their own settings can lead to the disclosure of anonymity and other problems

**Describe alternatives you've considered**
I don't see any alternatives, what I described above should definitely be in hiddifymanager

**Additional context**
n/a

**Comment by litoosh13** [comment]
As mentioned previously, many of our users are using Warp and experiencing no issues. For .ir sites in Iran, our Hiddify-Next app is sufficient for easily bypassing websites.

We'll certainly investigate your proposal, but it won't be our top priority at this time. If you're interested in this feature, you can contribute by creating a pull request. We're always happy to review your code and consider adding it to our project.
hiddify.com/app
https://t.me/hiddify_board

**Comment by kugona** [comment]
> As mentioned previously, many of our users are using Warp and experiencing no issues. For .ir sites in Iran, our Hiddify-Next app is sufficient for easily bypassing websites.
> 
> We'll certainly investigate your proposal, but it won't be our top priority at this time. If you're interested in this feature, you can contribute by creating a pull request. We're always happy to review your code and consider adding it to our project. hiddify.com/app https://t.me/hiddify_board

warp does have a place to be, but there are no domain or IP address blocks in the manager, especially since you need a warp plus key to work, and with my proposal, users do everything personally on their VDS (IP address), but they get a risk.

in general, I think that in the future, blocking, proxying or ignoring proxying should be unambiguous
by blocking I mean total blocking, that when vpn is working, this site will not work at all. but the usual ignoring of proxying will also be very good
