### ISSUE TITLE
remove domains

### ISSUE THREAD

**Issue by hbagheri** [hiddify/Hiddify-Manager#4515]
# Bug/Feature:
**Description**:     While you try to remove a domain a python fatal error shown
 
## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-122-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
