### ISSUE TITLE
عدم کار کردن پروکسی SSH پنل هیدیفای

### ISSUE THREAD

**Issue by mbm13781221** [hiddify/Hiddify-Manager#4518]
با عرض سلام و وقت بخیر خدمت تیم هیدیفای.
مشکل: بعد از فعال کردن پروکسی SSH در پنا هیدیفای ، کانفیگ ارایه شده مخصوص SSH طبق گفته پنل که در نرم افزار Hiddify Next ، 
وارد شود. بعد از کانکت کردن نرم افزار هیدیفای نکست ، دو نوع پروکسی ظاهر می شود که یکی SSH-out و دیگری SSH+UDP می باشد که متاسفانه هیچ کدام از این ها به درستی به اینترنت متصل نمیشود. نوع DNS ها را به صورت TCP://1.1.1.1 تغییر دادم بازم تغییری حاصل نشد.
آی پی سرور من مشکلی ندارد و می توانم با استفاده از نرم افزار هایی نظیر PUTTY به سرور اتصال SSH بزنم . در پنل هیدیفای ، پورت نامبر مربوط به پروکسی SSH را هم عوض کردم ولی تفاوتی حاصل نشد.
کسی می تواند نسبت به عیب یابی این مشکل کمک کند؟

**Comment by litoosh13** [comment]
سلام
لطفا مشکل اتصالات خودتون روی توی گروه تلگرامی مطرح کنید.
https://t.me/hiddify_board
