### ISSUE TITLE
Relay configuration doesn't work, Incorrect configuration!

### ISSUE THREAD

**Issue by kiavash599** [hiddify/Hiddify-Manager#4521]
In Relay configuration the value added in **address** field is also added in **host** and **SNI** fields. However, the direct domain should be added in both **host** and **SNI** fields, which is why the relay configuration doesn't work.

**Comment by litoosh13** [comment]
this is cuz of bad configuration of the server!!
you can follow all learning's material about the panel here:
hiddify.com/manager
