### ISSUE TITLE
یه سری ضعف 

### ISSUE THREAD

**Issue by alisadeghi1997** [hiddify/Hiddify-Manager#4524]
تمامی نسخه های پنل 
هیدیفای بیشتر رو اپش تمرکز کرده تا پنل ، یه سری نقص ها هست که خیلی وقته داریم میگیم اقا مشکل سازه رفع نمیشه، ده خط تو گیت هاب توضیح دادم برام اموزش پنل فرستادن و بستنش.
داخل پنل نمیشه دو نوع سی دی ان ساخت که یکی ws باشه یکی یه مدل دیگه ، برای هر سی دی ان هر دو نوع هم تو لینک ساب قرار میگیره یعنی بجا دوتا کانفیگ  4 تذ میشه،
وقتی پورت 8080 رو تو پنل باز میکنیم لازم نیس تمامی کانفیگا جفت بشن که ،یه 443 و یه 8080 بشه.،فقط کانفیگی که نیاز به پورت 8080 داره باید بشه باز گذاشت.
باگ قسمت ادمین ها هم هست
من میخوام ادمینم فقط به لینک سابی که مربوط به کانفیگای ایرانسله دسترسی داشته باشه و دیگر لینک های سابو دسترسی نداشته باشه ،متاسفانه پنل تمامی لینک های سابی که وجود داره رو برای ادمینم دسترسی میده

**Comment by litoosh13** [comment]
سلام مواردی که قبلا هم گفتین بررسی میشه ولی دو راه برای رسیدن زودتر به خواسته تون هست 
یکی **دونیت کردن** که به ما اجازه مالی بده تا بتونیم با مشکلات کمتری تمرکز کنیم روی توسعه پروژه
 یکی **کانتربیوت** یعنی این چیزایی که فرمودین رو خودتون توسعه بدین و بعدا با تایید ما لحاظ میکنیم توی پروژه و بقیه هم استفاده میکنن 
درک کنید که نیروی ما محدود و خواسته ها فراون پس مجدد تکرار میکنم منتظر باشید بررسی میکنیم
