### ISSUE TITLE
مشکل باز شدن متاتریدر توسط Hiddify

### ISSUE THREAD

**Issue by MrTolou** [hiddify/Hiddify-Manager#4528]
سلام و عرض احترام
متاسفانه وقتی برنامه Hiddify رو اجرا میکنم و به کانفیگ ها وصل میشم برخی برنامه ها از جمله متاتریدر وصل نمیشوند
راهکار متصل شدن در آن چیست؟

**Comment by litoosh13** [comment]
سلام لطفا مدل سیستم تون رو بگید؟
تلاش کردین از حالت وارپ روی همه که توی تنظیمات پنل هست استفاده کنید ؟

**Comment by MrTolou** [comment]
حالت دور زدن لن رو فعال کردم مشکل حل شد 
![Uploading 1.png…]()
