### ISSUE TITLE
از امروز بعد از اپدیت پنل به لینک کاربران دسترسی نمیده و کانفیگ ها اپدیت نمیشه 

### ISSUE THREAD

**Issue by gharachorloo** [hiddify/Hiddify-Manager#4532]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-119-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by gharachorloo** [comment]
![Uploading Screenshot_2024-10-21-00-07-36-373_app.hiddify.com.jpg…]()

**Comment by litoosh13** [comment]
اطلاعات کاملی ارايه دهید 
عکس لود نمیشه و با یه عکس چیزی مشخص نیست کامل توضیح بدین چ اتفاقی افتاده؟
چه رفتاری مد نظر بوده؟
این موضوع روی سرور دیگه امتحان کردین ؟

**Comment by litoosh13** [comment]
بسته میشود در صورت ادامه دار بودن مشکل لطفا مجدد ایشو باز شود
