### ISSUE TITLE
too much cpu usage 

### ISSUE THREAD

**Issue by pooooriya** [hiddify/Hiddify-Manager#4536]
in htop I see too much cpu usage in Singbox

![Screenshot 1403-07-30 at 14 02 59](https://github.com/user-attachments/assets/5ddcd7e2-7d8d-4997-909b-1f0de15b94bd)

version : ۱۰.۷۰.۷
ubuntu : 22

**Comment by litoosh13** [comment]
طبق تست و بررسی ما این مورد وجود ندارد و در صورت پایداری مشکل لطفا ابتدا روی سرور دیگری تست کنید اگر مشکل پا برجا بود نتیجه تست هر دوتا سرور را توی ایشو جدیدی ثبت نمایید
