### ISSUE TITLE
Is it normal to see requesting raw.githubusercontent.com continually?

### ISSUE THREAD

**Issue by IceSandwich** [hiddify/Hiddify-Manager#4544]
Hi! I run the following script to show xray log manually.
```bash
#!/bin/bash
echo '{"log": {"loglevel": "debug"}}' > /opt/hiddify-manager/xray/configs/payload.json
systemctl stop hiddify-xray.service
/opt/hiddify-manager/xray/pre-start.sh
/opt/hiddify-manager/xray/bin/xray run -confdir /opt/hiddify-manager/xray/configs/
```
And it shows:
![log2](https://github.com/user-attachments/assets/ed00d2b8-bbfb-448f-bfab-33cc326854e8)
What's happening? I haved tried the following actions but this problem still exists.
- Change UUID of hiddify user.
- Restart the server.
- Close all proxy applications in my computer.

Hiddify dashboard tells me i haved used 3GB this month but my vps provider shows 10GB haved been used. I don't know if it's the reason.
Is it normal?
> hiddify version: 10.70.7

**Comment by lymanjre** [comment]
Seems the update for Xray is implemented by the panel. There is no need to worry. The traffic of updates is not calculated into the dashboard. The dashboard just shows the VPN traffic used by users

**Comment by IceSandwich** [comment]
> Seems the update for Xray is implemented by the panel. There is no need to worry. The traffic of updates is not calculated into the dashboard. The dashboard just shows the VPN traffic used by users

Thanks for helping. Is there any way to lower the frequency? There are just tooooooooo many. Almost two requests per second.
