### ISSUE TITLE
صفحات اجتماعی

### ISSUE THREAD

**Issue by kazemim99** [hiddify/Hiddify-Manager#4547]
اگه میشه لینک صفحات اجتماعی صفحه کاربران شخصی سازی بشه 
من نمیخوام مشتریام اینو ببینن یا لینکهای خودم رو میخوام بذارم

**Comment by litoosh13** [comment]
سلام شما میتونید به بخش زیر بروید:
تنظیمات >  شخصی‌ سازی صفحه کاربران
از اینجا صفحه مورد نظر خودتون رو قرار بدین
اگر منظورتون حذف لینک های هیدیفای هست به هیچ عنوان امکان پذیر نیس این موضوع
اموزش های پنل رو میتونید اینجا مشاهده نمایید:
https://hiddify.com/

**Comment by litoosh13** [comment]
در صورت که مورد دیگه ای نیس ایشو بسته میشه
