### ISSUE TITLE
Hysteria 2 config problem(OBFS)

### ISSUE THREAD

**Issue by PtDragon** [hiddify/Hiddify-Manager#4548]
**Describe the bug**

**To Reproduce**

1) Enable Hysteria2
2) Disable OBFS
3) Get config for Hysteria2
4) It does not work because OBFS is not enabled on server but is enabled in client config

**Expected behavior**

Match OBFS settings on server and client so it does work like other protocols.

**Comment by litoosh13** [comment]
hi,
did you try this on another server ?

**Comment by PtDragon** [comment]
Hi! 
Yep, same bug on both my servers. 
Hiddify manager 10.70.7 on both servers.

**Comment by litoosh13** [comment]
In Settings -> Proxy Status, check if OBFS or Hysteria2 is active and has a ping.

Please note that this check is only necessary on the panel side, not the user client.

If you see a ping there, the issue may be related to your ISP blocking these protocols.

and for more info provide picture of the proxy status page!!!

**Comment by litoosh13** [comment]
the issue will be closing soon!!!
