### ISSUE TITLE
Use nginx proxy manager, or change configs inside hiddify's nginx and haproxy

### ISSUE THREAD

**Issue by tulcoturo** [hiddify/Hiddify-Manager#4550]
Hi, 
Is it possible to use Nginx Proxy Manager with hiddify manager?
I have a homeserver that I want to also use as a Hiddify node. But Hiddify needs to use port 80 and 443.
I tried to redirect my website by changing the internal haproxy configs, but it doesn't seem to be working for 443.

This is what I did (in haproxy/common.cfg.pj2):

    frontend https-in
    
    {% for port in (["443"] + hconfigs['tls_ports'].split(',')) | unique %}
    bind :{{port}},:::{{port}} v4v6 tfo 
    {%endfor%}

	#acl website
 
	acl app_example hdr(host) -i app.example.com 
	use_backend app_example_backend if app_example

And 

         backend app_example_backend 
	            server app_example 127.0.0.1:2283

This works if I do it on port 80, but is not working for port 443. It keeps redirecting to the decoy website.

Is there any way to do this?

**Comment by lymanjre** [comment]
Due to some complicated matters you can’t use Hiddify Manager next to your website. You have to install it on a seperate server

**Comment by tulcoturo** [comment]
> Due to some complicated matters you can’t use Hiddify Manager next to your website. You have to install it on a seperate server

you mean is not possible to use it on the same network or the same server? would it be possible with virtualization?
