### ISSUE TITLE
2FA auth in panel

### ISSUE THREAD

**Issue by kugona** [hiddify/Hiddify-Manager#4552]
**Describe the solution you'd like**
I would like to see more security in the panel. This is 2fa in the form of login password or other methods of confirmation, for example, entering a secret phrase.

The thing is that the panel is not particularly protected and requires only uuid and administrator patch. But as for me, if we add some other way to confirm your administrative rights in the panel, then we will be able to have more security and worry less about access to the panel falling into the wrong hands

**Comment by litoosh13** [comment]
the panel is open source so you can add this feature to panel the make PR to our project
