### ISSUE TITLE
مشکل سابکریپشن 

### ISSUE THREAD

**Issue by eArash** [hiddify/Hiddify-Manager#4554]
سلام، یک چیز عجیب پیدا کردم، اگر از منو سابکریپشن در v2ray به صورت دستی لینک ساب وارد کنیم و اوکی کنیم، hiddify-cli activating میشه و از کار میوفته! میشه این مورد یک بررسی بکنید

**Comment by litoosh13** [comment]
سلام بررسی شد همچین موردی وجود ندارد جهت اطمینان روی ۲ سرور مجزا تست صورت گرفت
