### ISSUE TITLE
مشکل بات تلگرام 

### ISSUE THREAD

**Issue by eArash** [hiddify/Hiddify-Manager#4555]
سلام، وقتی با استفاده از بات تلگرام کاربر یا کانفیگ میسازم، موقع استفاده پینگ نمیده و باید دستی برم همه اونایی که با تلگرام ساختم رو یکبار از طریق پنل قطع وصل کنم تا اتصال برقرار بشه.

**Comment by litoosh13** [comment]
بررسی شد این مورد وجود نداشت
