### ISSUE TITLE
API Bug

### ISSUE THREAD

**Issue by kazemim99** [hiddify/Hiddify-Manager#4556]
# Bug/Feature:
**Description**:    Get 422 errot
## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-122-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

I get 422 Error when post this data

{"detail":{"json":{"headers":["Unknown field."],"name":["Missing data for required field."]}},"message":"Validation error"}

   added_by_uuid = Guid.Parse("082b6520-62d9-4879-8c21-28f3732efbfa"), // Explicitly use Guid
            comment = (string?)null, // Use nullable type
            current_usage_GB = 0,
            ed25519_private_key = "string",
            ed25519_public_key = "string",
            enable = true,
            id = 6,
            is_active = false,
            lang = "en",
            last_online = DateTime.MinValue, // Use DateTime for date fields
            last_reset_time = DateTime.Parse("2024-10-25"),
            mode = "no_reset",
            name = "string",
            package_days = 0,
            start_date = DateTime.Parse("2019-08-24"),
            telegram_id = (string?)null,
            usage_limit_GB = 0,
            uuid = Guid.Parse("cd3f949f-af5f-4771-b667-618dc6d70def"), // Use Guid explicitly
            wg_pk = "string",
            wg_psk = "string",
            wg_pub = "string"

**Comment by litoosh13** [comment]
please provide more info!!
which path you try ?
what you expected ?
what error you get?
without enough info issue will be closed !!!

**Comment by kazemim99** [comment]
حل مشکل از هدر accept بود که نذاشته بودم

**Comment by litoosh13** [comment]
مشکل از سمت کاربر رفع شده
