### ISSUE TITLE
وصل نشدن به چت جی پی تی و کلاود | Chat GPT and Claude Issue

### ISSUE THREAD

**Issue by Ahmadrezadl** [hiddify/Hiddify-Manager#4564]
حدود 3 ماه بدون مشکل کار میکرد
جدیدا وارد چت جی پی تی میشم میزنه:
Unable to load site
Please try again later. If you are using a VPN, try turning it off.

✅ کار های مربوط به issue های google recaptha رو انجام دادم و مشکل کپچای گوگل حل شد ولی چت جی پی تی همچنان اجازه نمیده وارد شم

**Comment by litoosh13** [comment]
سلام وارپ را روی همه بگذارید و لطفا ایشو در این مورد نزنید چون ما تعهدی نسبت به بالا نیامدن یک سایت خاص نداریم اگر پنل مشکلی داشت میتونید ایشو بزنید در غیر این صورت این مورد میتونه از سرور یا دیتاسنتر شما باشه
