### ISSUE TITLE
قابلیت اتصال یک نود به دو یا چند مرکزی

### ISSUE THREAD

**Issue by umidomm** [hiddify/Hiddify-Manager#4565]
به این دلیل این پیشنهاد رو مطرح کردم که کاربرانی که برای استفاده ی شخصی از هیدیفای منیجر استفاده می کنند اکثرا به تمام سخت افزار و پهنای باند اون سرور احتیاج ندارن،به اشتراک گذاشتن نود ها میتونه به دوستانی که کانفیگ رایگان منتشر میکنن هم کمک کنه

**Comment by litoosh13** [comment]
در دست توسعه قرار دارد...منتظر نسخه های جدیدتر پنل باشید
