### ISSUE TITLE
Domains bug.

### ISSUE THREAD

**Issue by kugona** [hiddify/Hiddify-Manager#4567]
**Describe the bug**
when clicking on the domains tab, the panel crashes into error 504

**To Reproduce**
1. Go to your admin panel
2. Click on Settings -> Domains

**Screenshots**
![image](https://github.com/user-attachments/assets/7b6a4fc7-4ab3-474c-a98b-a275bdd93e97)

**Desktop (please complete the following information):**
whatever

**Smartphone (please complete the following information):**
whatever

**Additional context**

**Comment by litoosh13** [comment]
Make a clean install to solve this issue fast:
1. Make a backup.
2.rebuild server to ubuntu 22
3.restore backup

Please note: This issue often arises from server with poor configuration or datacenter management problems. We strongly suggest considering a VPS from a reputable provider to ensure optimal performance and reliability.
