### ISSUE TITLE
باگ و موارد پیشنهادی

### ISSUE THREAD

**Issue by ali6030** [hiddify/Hiddify-Manager#4570]
عمده پیشنهاد و مشکلات پنل هیدیفای که انشالله تو نسخه ی جدید ارائه و رفع بشن
1.قطع شدن بعضی کانفیگ های جدید و یا تازه تمدید شده و رفع مشکل بعد از اعمال تغییرات.
2.گذاشتن پچ اختیاری همون ed=xxx
3.گذاشتن دامنه ی طولانی با کاراکتر های کوچک و بزرگ
4.گذاشتن دامنه با زبان چینی و غیره.
5.نمایش و عدم نمایش کانفیگ و پورت مورد نظر برا سابسکریپشن یوزر ها
6.اضافه شدن tor و سایفون مثل وارپ به پنل

**Comment by litoosh13** [comment]
سلام عزیز تمامی موارد به دولوپرها پیشنهاد داده شده و مورد بررسی قرار گرفته
لطفا صبور باشید 
تشکر

**Comment by ali6030** [comment]
دمت گرم.سپاسگذارم🙏

Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Nov 6, 2024 at 18:32, ***@***.***> wrote:   


Closed #4570 as completed.
