### ISSUE TITLE
Haproxy not activating issue

### ISSUE THREAD

**Issue by arashveysi3** [hiddify/Hiddify-Manager#4571]
**Describe the bug**
The problem is, when I installing hiddify manager on my ubuntu 22.04 everything goes right but at the end it warns me : an important service hiddify-haproxy is not working again
Installation Failed! 
the panel not goes up too.
any helps???

**Screenshot**

![Screenshot (1)](https://github.com/user-attachments/assets/8ec0c328-561d-4d2f-a1e7-24ed4ec73d0d)

**Comment by litoosh13** [comment]
This can sometimes happen due to low resource VPS or resource management by the data center.
The best way is to reboot the server after every fresh install and then apply the configuration.
