### ISSUE TITLE
مشکل اتصال کانفیگ های tcp+tls

### ISSUE THREAD

**Issue by sinascorpion** [hiddify/Hiddify-Manager#4573]
کانفیگای tcp+tls روی اپ خود هیدیفای نسخه آخر وصل نمیشن که عجیبه و توی برنامه های دیگه مثل v2rayN ویندوز قسمت path رو خالی میذاره. ولی روی v2rayNG هیچ مشکلی ندارن.

**Comment by litoosh13** [comment]
گزینه full xray رو از بخش پروکسی ها روشن کنید و اگر تغییری نداشت خاموش کنید و تست کنید
