### ISSUE TITLE
وضعیت سرویس ها نامشخص

### ISSUE THREAD

**Issue by jacklapid1254** [hiddify/Hiddify-Manager#4575]
**Describe the bug**
بعد از نصب آخرین نسخه روی ubuntu 22.04 یه سری سرویس بالا نمیان و موندن روی activating

- Global IP:
----------------------------------------------------------------
- Services Status:
    hiddify-cli                   active
    hiddify-redis                 active
    hiddify-ssh-liberty-bridge    active
    hiddify-haproxy               activating
    hiddify-panel                 active
    hiddify-nginx                 active
    hiddify-singbox               activating
    hiddify-xray                  activating
----------------------------------------------------------------

اینم لاگ :
![Screenshot (13)](https://github.com/user-attachments/assets/db672e5b-58e3-46dc-9f18-3952cefd602b)

**Comment by litoosh13** [comment]
سیستم رو خاموش روشن کنید بعد از بالا اومدن اپلای کانفیگ بزنید در صورت پایداری مشکل یه بار از اول نصب کنید
