### ISSUE TITLE
قوانین فایروال

### ISSUE THREAD

**Issue by M-Sadegh-M** [hiddify/Hiddify-Manager#4576]
![image](https://github.com/user-attachments/assets/e0868976-86e0-458f-aaff-03303f3e15c3)

قوانینی که هیدیفای برای فایروال اعمال میکنه ایراد داره
دستی هم که تغییر میدی با اپلای کانفیگ دوباره تغییر میکنه

مشکل گویا قوانین تکراری هست و  همچنین قانون زیر که فک کنم ctstate درسته نه ctstatus

-A INPUT -p udp -m conntrack --ctstatus SEEN_REPLY,ASSURED,CONFIRMED -j ACCEPT

ممنون میشم تیم توسعه بررسی کنن

**Comment by litoosh13** [comment]
سلام 
بررسی شده و دستور کاملا صحیح میباشد به هیچ عنوان تغییری توی پنل ایجاد نکنید در غیر این صورت کمکی از دست ما برنمیاد برای مشکلاتی که ممکن هست پیش بیاد
