### ISSUE TITLE
Cannot login the manager pannel in oraclecloud

### ISSUE THREAD

**Issue by HappyPoly** [hiddify/Hiddify-Manager#4578]
I finished installed in oraclecloud. But I can not login the pannel with the link which I get after installed.

**Comment by litoosh13** [comment]
please provide more info 
what is the error?
show some screenshots ?

**Comment by litoosh13** [comment]
will be close soon!!!

**Comment by HappyPoly** [comment]
the problem has been resolved.thx

Mohammad ***@***.***> 于2024年11月13日周三 14:30写道：
