### ISSUE TITLE
limit connection 

### ISSUE THREAD

**Issue by daniyal1396m** [hiddify/Hiddify-Manager#4580]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-116-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown
Hi ,

please add limit connection for users

**Comment by litoosh13** [comment]
hi 
we will not adding this feature any time soon !!!
