### ISSUE TITLE
Bug with "edit user"

### ISSUE THREAD

**Issue by ausypher** [hiddify/Hiddify-Manager#4582]
# Bug/Feature:
 If you click "edit user" in the panel to fix the number of gigabytes, the gray screen appears. It helps to create a new user
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
**OS**:              Linux-5.15.0-125-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
we need more info and screenshots if possible because there is no such a problem as we check

**Comment by litoosh13** [comment]
yo need to upload photos in github not send them by email

**Comment by ausypher** [comment]
photo in sequence :
before clicking edit, and then after - the screen is darker and that's it.  The only way is to create a new user, and it's always like that.
![1](https://github.com/user-attachments/assets/f5eda72c-41c0-45ff-8ac4-fa8163dd041c)
![2](https://github.com/user-attachments/assets/ab2fc95f-1faf-448c-b06a-309ba970455e)

**Comment by litoosh13** [comment]
aha this is a known problem in Russian Panel please use english version
we will fix this later
