### ISSUE TITLE
اشکال سیستم اکانتینگ

### ISSUE THREAD

**Issue by Ariannetflix** [hiddify/Hiddify-Manager#4588]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.7
**Python Version**:  3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
**OS**:              Linux-5.15.0-91-generic-aarch64-with-glibc2.35
**User Agent**:      Unknown
On ubuntu 22
بعضی از اکانت ها بدون علت خاصی قطع میشوند و همه پروکسی ها تایم اوت میشه در حالی که برای بقیه اکانت ها وصل هست. 
فرقی بین برنامه ها و سیستم عامل یوزر ندارد. 
با تغییر جزییات یوزر مثل زمان یا حجم یا ریست کردن یا حتی ریست هفتگی یا ماهیانه ، مشکل حل میشود. اما چند روز بعد دوباره ایجاد میشود. فقط برای تعداد محدودی از یوزر ها اتفاق میوفتد. این باگ از ورژن های قدیمی تر وجود داشت اما الام تشدید شده. من هرچی گشتم نتونستم سیستم redis رو پیدا کنم توی سرور. لاگ redis فقط مینویسه که سیو شده و ارور نمیده. 
لطفا راهنمایی کنید که از کجا لاگ سیستم auth رو بررسی کنم.

**Comment by litoosh13** [comment]
از توی پنل قسمت اقدامات > نمایش لاگ

**Comment by litoosh13** [comment]
این مورد والا روی سرور دیگ گزارش نشده و بهترین راه برای اطمینان یه نصب تمیز هست
ریبیلد کنید مجدد بکاپ بیارید بالا

**Comment by Ariannetflix** [comment]
برای اپدیت مجبور شدم ریبیلد کنم. نسخه اخر را با ریبیلد کل سرور و همچنین هیدیفای انجام دادم ولی بازم ادامه داشت.

**Comment by amineinaloo** [comment]
> # Bug/Feature:
> **Description**: Describe bug or needed feature
> 
> ## Details:
> **Hiddify Version**: 10.70.7 **Python Version**: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] **OS**: Linux-5.15.0-91-generic-aarch64-with-glibc2.35 **User Agent**: Unknown On ubuntu 22 بعضی از اکانت ها بدون علت خاصی قطع میشوند و همه پروکسی ها تایم اوت میشه در حالی که برای بقیه اکانت ها وصل هست. فرقی بین برنامه ها و سیستم عامل یوزر ندارد. با تغییر جزییات یوزر مثل زمان یا حجم یا ریست کردن یا حتی ریست هفتگی یا ماهیانه ، مشکل حل میشود. اما چند روز بعد دوباره ایجاد میشود. فقط برای تعداد محدودی از یوزر ها اتفاق میوفتد. این باگ از ورژن های قدیمی تر وجود داشت اما الام تشدید شده. من هرچی گشتم نتونستم سیستم redis رو پیدا کنم توی سرور. لاگ redis فقط مینویسه که سیو شده و ارور نمیده. لطفا راهنمایی کنید که از کجا لاگ سیستم auth رو بررسی کنم.

این مشکل رو من هم دارم
داستان برای اکانت هایی که تازه میسازم پیش میاد
اکانت های قدیمی مشکلی ندارن
وقتی یه اکانت جدید میسازم و باهاش وصل میشه اوکی هست
اما یه دفعه از کار میوفته و دیگه کار نمیکنه
باید برم یه ویرایش بزنم تا دوباره وصل بشه
اینکه میگم از کار میوفته یعنی وضعیتش هم فعال هست و زمان و حجم هم داره ولی وصل نمیشه
این حتما یه باگ هست برای اکانت های جدید

**Comment by litoosh13** [comment]
عزیز با گزارش یه مشکل ما نمیتونیم همون لحظه بفهمیم داستان چیه ک سریع بیایم فیکس کنیم باید اطلاعات بیشتری اعم از ویدیو و عکس از مورد پیش اومده ارایه بدین تا بررسی بشه دقیق
ما روی بیشتر از ۳ سرور از دوتا دیتاسنتر مختلف بررسی کردیم و این مورد اصن اتفاق نیوفتاده

**Comment by amineinaloo** [comment]
> عزیز با گزارش یه مشکل ما نمیتونیم همون لحظه بفهمیم داستان چیه ک سریع بیایم فیکس کنیم باید اطلاعات بیشتری اعم از ویدیو و عکس از مورد پیش اومده ارایه بدین تا بررسی بشه دقیق ما روی بیشتر از ۳ سرور از دوتا دیتاسنتر مختلف بررسی کردیم و این مورد اصن اتفاق نیوفتاده

بله درست میفرمایید
سعی میکنم اطلاعات بیشتری جمع کنم 
سپاس از پاسخگویی

**Comment by Ariannetflix** [comment]
> عزیز با گزارش یه مشکل ما نمیتونیم همون لحظه بفهمیم داستان چیه ک سریع بیایم فیکس کنیم باید اطلاعات بیشتری اعم از ویدیو و عکس از مورد پیش اومده ارایه بدین تا بررسی بشه دقیق ما روی بیشتر از ۳ سرور از دوتا دیتاسنتر مختلف بررسی کردیم و این مورد اصن اتفاق نیوفتاده

مشخصا با این اطلاعات کم هیچی مشخص نمیشه برای همین دنبال راهنمای هستم که لاگ سیستم authentication که حالا redis یا هر چیز دیگه هست رو در بیارم. ولی نکته جدیدی که فهمیدم اینه که همونجور که دوستمون گفت فقط برای اکانت های جدید هست و تا الان با apply config درست شده. شاید اکانت های جدید توی قسمتی که باید ثبت نمیشوند و temporary هستند و با ریستارت redis یا قسمتی دیگه پاک میشوند. که این با apply config دست میشه

**Comment by Ariannetflix** [comment]
> منم همین مشکل را داشتم و اضافه تر از اون بعضی از کاربر ها را نمایش نمیده و باید به جای دامنه با IP پنل را باز کنم تا همه کاربرا را نمایش بده. درضمن احتمالا دسترسی admin پنل تو نمایش و فعال بودن فیک کاربر تاثیر داشته باشه

مطمئنی ادمین جدا از owner نداری ؟ ممکنه با لینک owner وارد میشی با ای پی  و لینک با دامنه برای ادمین ه

**Comment by litoosh13** [comment]
will be closed if problem exist open new issue ref to this one
