### ISSUE TITLE
مشخص شدن حجم تمام ادمین ها

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#4590]
سلام لطفا در قسمت ادمین ها یک ستون برای مشاهده حجم مصرفی کل هر ادمین بصورت جداگانه اضافه کنید تا هربار برای چک کردن حجم نیاز به باز کردن لینک تک تک ادمین ها نباشد.

**Comment by litoosh13** [comment]
این مورد قبلا مورد بررسی قرار گرفته اما در الویت نیست نسخه های بعدی احتمالا قرار بگیره
