### ISSUE TITLE
پنلم یکباره از کار افتاده بعد از آپدیت خودکار ساعت سه صبح 

### ISSUE THREAD

**Issue by Mamooshi** [hiddify/Hiddify-Manager#4592]
----------------------------------------------------------------
- Services Status:
    hiddify-cli                   activating
    hiddify-redis                 active
    hiddify-ss-faketls            active
    hiddify-ssh-liberty-bridge    active
    hiddify-haproxy               activating
    hiddify-panel                 failed
    hiddify-nginx                 active
    hiddify-singbox               activating
Error: Key not found: warp_mode
    wg-quick@warp                 active
    mtproxy                       active
----------------------------------------------------------------
                                               ▓▓▓
                                             ▓▓▓▓▓
                                        ▓▓▓       
                                      ▓▓▓▓▓  ▓▓▓▓▓
                                 ▓▓▓  ▓▓▓▓▓  ▓▓▓▓▓
                              ▓▓▓▓▓▓  ▓▓▓▓▓  ▓▓▓▓▓
                              ▓▓▓▓▓▓▓▓▓▓▓▓▓  ▓▓▓▓▓

**Comment by Noktomezo** [comment]
same
![{85F8AC5B-BDEB-448B-9E20-66C793E27B73}](https://github.com/user-attachments/assets/b60e5b96-857f-476a-84ef-aff91ce7fc31)

**Comment by Mamooshi** [comment]
آپگرید بتا مال منو درست کرد دوستات

**Comment by karlovm** [comment]
Same issue

**Comment by Mamooshi** [comment]
> Same issue

beta update works

**Comment by Mamooshi** [comment]
به محض بالا اومدن پنل فول بکاپ بگیرید شاید مجبور به نصب دوباره بشیم

**Comment by Noktomezo** [comment]
Nah, the beta version didn't help, only the status of the panel changed to `Active`, but all other services are down, still an error:
```bash
Collecting grpcio-tools==1.51.1 (from xtlsapi==3.1.2->hiddifypanel)
  Using cached grpcio-tools-1.51.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
2024-11-18 05:23:21.662 | WARNING  | hiddifypanel.models.config:hconfig:79 - str db_version not found 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/flask/cli.py", line 611, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/flask/cli.py", line 328, in load_app
    app: Flask | None = self.create_app()
                        ^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/hiddifypanel/base.py", line 70, in create_app_wsgi
    app = create_app(cli=cli)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/hiddifypanel/base.py", line 59, in create_app
    app.config.load_extensions("EXTENSIONS")
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/dynaconf/contrib/flask_dynaconf.py", line 231, in load_extensions
    initializer(app)
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/hiddifypanel/database.py", line 21, in init_app
    init_db()
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/hiddifypanel/panel/init_db.py", line 815, in init_db
    db_version = int(hconfig(ConfigEnum.db_version) or 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis_cache/__init__.py", line 233, in inner
    get_cache_lua_fn(self.client)(keys=[key, self.keys_key], args=[result_serialized, self.ttl, self.limit])
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/commands/core.py", line 5501, in __call__
    return client.evalsha(self.sha, len(keys), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/commands/core.py", line 5710, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/commands/core.py", line 5694, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/connection.py", line 369, in connect
    self.on_connect()
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/connection.py", line 434, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/connection.py", line 592, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hiddify-manager/.venv/lib/python3.12/site-packages/redis/_parsers/resp2.py", line 38, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid username-password pair
===run.sh hiddify-panel
===========================================================
####5####HiddifyPanel####Reading Configs from Panel...####
####8####Applying Configs####...####
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'json5'
Requirement already satisfied: json5 in /usr/local/lib/python3.12/dist-packages (0.9.28)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2) (3.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Traceback (most recent call last):
  File "/opt/hiddify-manager/common/jinja.py", line 4, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by manisafari** [comment]
برای منم همین اتفاق افتاده

**Comment by AndyLin2020** [comment]
Same problem, how to fix it?

**Comment by lloydeastin** [comment]
Same here, seems that it's a universal issue. Please check ASAP. Thank you!

Error: Key not found: warp_mode

**Comment by karlovm** [comment]
For me complete reinstalling ubuntu and using beta version fixed the problem

**Comment by MasterHide** [comment]
Same problem, how to fix it? beta version working but can u fix stable version

**Comment by Noktomezo** [comment]
Ah, rly, I confirm, that beta version + reinstallation (the "install" choice in the main terminal panel) helped

![{320C61F7-C7CE-4B01-8B31-72FCF21F8532}](https://github.com/user-attachments/assets/bd4fde73-0478-4460-9919-81728f341fe2)

**Comment by lloydeastin** [comment]
What is the command to install the beta version? Thanks.

**Comment by karlovm** [comment]
> What is the command to install the beta version? Thanks.

curl -O http://i.hiddify.com/beta
sudo bash beta

**Comment by Noktomezo** [comment]
> What is the command to install the beta version? Thanks.

Type `hiddify` to enter the interactive panel, then `update` -> `beta'. Then

**Comment by Mamooshi** [comment]
after update my issue is ssl

**Comment by Noktomezo** [comment]
> after update my issue is ssl

And proxy label placeholders 😭
![{DAB5B4FE-0238-4E93-82ED-EC258EE28401}](https://github.com/user-attachments/assets/bf68210d-e63b-44c9-b7c8-da35438d96bb)

**Comment by Mamooshi** [comment]
we should turn off auto update at 3 am

**Comment by lloydeastin** [comment]
After install the beta version, I can access the panel, but can't restore the backup file.

Showing this error:

HTTP ERROR 500

**Comment by Mamooshi** [comment]
> After install the beta version, I can access the panel, but can't restore the backup file.
> 
> Showing this error:
> 
> HTTP ERROR 500

i just clean install again and it works

**Comment by Mamooshi** [comment]
به صورت اتوماتیک آپدیتش فعاله ساعت سه صبح ، یک مشکلی توی همین آپدیته احتمالا چند ساعت دیگه درستش کنن حتما بکاپ بگیرید،

**Comment by lloydeastin** [comment]
> > After install the beta version, I can access the panel, but can't restore the backup file.
> > Showing this error:
> > HTTP ERROR 500
> 
> i just clean install again and it works

I tried to fresh install my OS from the scratch, then fresh install the hiddify beta version, same issue persisted.

**Comment by KRU3L** [comment]
I am experiencing the same issue.
Although updating to the beta version partially resolved the problem for me, it only affected Relay connections.
On the beta edition, I encountered DNS resolving issues, which resulted in the disconnection of Cloudflare CDN configurations.
As previously mentioned, the text is scrambled.
Whenever you attempt to set a new domain or append settings to an existing domain, such as CDN domains, you will encounter an “failed to resolve domain” error.

My sincere gratitude to the Hiddify team.

**Comment by djamgo** [comment]
it seems that cloudflare and workers are currently unavailible. only direct links are currently working unproxied.
and only on hiddify manager beta. i also wanted to add a big thank you to the hiddify team for making it so easy for the rest of us.

**Comment by IceSandwich** [comment]
Everything works fine after switching to beta version, even i don't have to recover any configurations. But i still wonder, if i switch to stable version after the author fix the problem, are the configurations still compatible?

**Comment by lloydeastin** [comment]
Try to use below command to install the dev13 version, it works.

bash <(curl https://i.hiddify.com/v10.80.0.dev13)

**Comment by moli1369** [comment]
سلام همگی قبل از اپگرید به این مسیر برید و بکاپ رو بردارید 
/opt/hiddify-manager/hiddify-panel/backup
اخرین فایل رو بردارید و همچنین بعد از کپی کلا میتونید سرور رو پاک و مجدد با این بکاپ برگردانید یا به نسخه جدید بتا و مجدد به نسخه قبل برگردید در کل این مسیر بکاپ گیری خودکار سرور هست.

**Comment by talifan** [comment]
> Try to use below command to install the dev13 version, it works.
> 
> bash <(curl https://i.hiddify.com/v10.80.0.dev13)

It's work for me. thanks.

**Comment by moashrafi** [comment]
1. First of all, take a backup from the following directory:  
   `/opt/hiddify-manager/hiddify-panel/backup`
2. Run the command `sudo hiddify`.
3. Go to the "update" option and select "beta".
4. It’s recommended to restart the server.
5. Run the command `sudo hiddify` again.
6. Then click on "install".

Now everything is correct.

**Comment by UltimateABC** [comment]
نسخه 10.7.9 انتشار داده شده که

اونو نصب کنید

**Comment by moli1369** [comment]
اونم مشکل داره 10.7.9

**Comment by Mamooshi** [comment]
auto update ro stop bayad konim saat 3 har shabe

**Comment by Mamooshi** [comment]
ssl error gereftam az dishab
Domain cannot be resolved! Please check DNS settings

**Comment by moli1369** [comment]
به نسخه بتا اپدیت کن ولی هنوز وارپ کار نمیکنه در بتا

**Comment by moashrafi** [comment]
> ssl error gereftam az dishab Domain cannot be resolved! Please check DNS settings

https://github.com/hiddify/Hiddify-Manager/issues/4533#issuecomment-2426189753

**Comment by Mamooshi** [comment]
> > Try to use below command to install the dev13 version, it works.
> > bash <(curl https://i.hiddify.com/v10.80.0.dev13)
> 
> It's work for me. thanks.

yea its works but it will destroy at 3AM , so turn off auto update
