### ISSUE TITLE
Massive Error

### ISSUE THREAD

**Issue by dugong-lewat** [hiddify/Hiddify-Manager#4594]
**I have 6 VPS using Hiddify Panel and there is a mass error together with the same error, how can this happen?**

![Screenshot_2024-11-18-10-14-03-01_61c78dc80ee02b53007c815fefe993e3](https://github.com/user-attachments/assets/84aa64ba-2092-4991-96e7-2c53ca91f07e)

**Comment by djamgo** [comment]
im facing the same issue. on 4 different servers. it seems i cant connect to cdn or workers but direct still works but only if i update hiddify manager to dev.
when i try to install hiddify on a new server this is where it gets stuck....Building wheel for grpcio-tools....

**Comment by grimpenmire** [comment]
Same here.

**Comment by ninjastrikers** [comment]
same issue. re-installing the script does not work.

**Comment by josephjul40** [comment]
My server is down, i cant access it, what happened there hiddify

**Comment by ExtremeDot** [comment]
Is auto-update enabled in the settings?

**Comment by ExtremeDot** [comment]
its related to python version

i think i had fixed with replacing the python to 3.10

**Comment by d4rkr4in** [comment]
The same problem. Hiddify-manager can't up own services and main functional doesn't woork

**Comment by josephjul40** [comment]
Update the panel through ssh and everything will be allright

**Comment by josephjul40** [comment]
Great!
