### ISSUE TITLE
erros while installing fresh 10.70.9

### ISSUE THREAD

**Issue by UltimateABC** [hiddify/Hiddify-Manager#4598]
UBUNTU 22.04

![{732E011F-9115-4828-A1C1-B2D314ACF473}](https://github.com/user-attachments/assets/26f1c35f-b4ea-4695-b114-c222bd8f5b36)

---
![{7A1A932E-C39E-4AA9-8FF6-02868862115F}](https://github.com/user-attachments/assets/58096939-8466-47ea-93a6-a34bfe0eb9ec)

---
![{D92DCE8D-AFA3-496F-86A0-F3AB3CDB0123}](https://github.com/user-attachments/assets/c122bb3b-33b5-484f-a815-1c080d3e85e6)

---

![{3AF74FAF-97B6-4E60-96CC-816F591C7179}](https://github.com/user-attachments/assets/e56b68b4-5c6d-4f6c-84aa-252bdf1c80a3)

---

**Comment by litoosh13** [comment]
we aware of the problem
here is the solution:
https://t.me/hiddify_board/482495/518026
