### ISSUE TITLE
Hiddify Server stop running

### ISSUE THREAD

**Issue by alexlii1971** [hiddify/Hiddify-Manager#4600]
Hello,

I just note that the Hiddify server is not running, and it shows:

![Screen Shot 2024-11-18 at 14 01 44](https://github.com/user-attachments/assets/2d98bc36-5980-4dd8-815b-db7a253ef466)
![Screen Shot 2024-11-18 at 14 17 37](https://github.com/user-attachments/assets/acc6dce6-4e92-4bb5-8701-3a0115bf88fa)

Does Hiddify server automatically on server? 
If yes, anyway to disable automatically upgrade to avoid such issue?

Thanks

**Comment by UltimateABC** [comment]
SETTINGS > GENERAL SETTINGS > AUTO UPDATE

**Comment by Milka638** [comment]
Ваша поддержка работает просто ужасно, смысл ее давать если отвечают там один раз в неделю ?
