### ISSUE TITLE
how to fix tiktok arent working via hiddify manager and hiddify client

### ISSUE THREAD

**Issue by notqtcris** [hiddify/Hiddify-Manager#4611]
how to fix tiktok arent working via hiddify manager and hiddify client
on browser it is err_connection
app tiktok arent working via vpn
country in hiddify manager is others

**Comment by litoosh13** [comment]
set warp in settings of the panel on all 
then try again

**Comment by litoosh13** [comment]
will be closed soon !!!

**Comment by notqtcris** [comment]
it didnt helped, sorry for taking long time to answer
