### ISSUE TITLE
مشکل در ورژن 10.80.0

### ISSUE THREAD

**Issue by amineinaloo** [hiddify/Hiddify-Manager#4612]
من از چند روز پیش که سیستم ها داون شد اپدیت کردم به ورژن 10.80.0 بعدش هم هرچی تلاش کردم نتونستم برگردم به 10.70.9
حالا تو این ورژن یه سرویس اضافه شده به نام hiddify-panel-background-tasks.service که هر از چند دقیقه یکبار cpu رو میچسبونه به اخر و باعث قطعی سیستم میشه
من فعلا سرویس رو استاپ کردم 
میدونم این نسخه استیبل نیست اما گفتم که در جریان باشید
os : ubuntu 22

این هم اروری که موقع نصب 10.70.9 میگیرم

Created symlink /etc/systemd/system/multi-user.target.wants/hiddify-panel.service → /opt/hiddify-manager/hiddify-panel/hiddify-panel.service.                                                                │ ▒
▒│ Traceback (most recent call last):                                                                                                                                                                           │ ▒
▒│   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                                                                                                                      │ ▒
▒│     return _run_code(code, main_globals, None,                                                                                                                                                               │ ▒
▒│   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code                                                                                                                                                 │ ▒
▒│     exec(code, run_globals)                                                                                                                                                                                  │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/__main__.py", line 13, in <module>                                                                                              │ ▒
▒│     main()                                                                                                                                                                                                   │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__                                                                                                       │ ▒
▒│     return self.main(*args, **kwargs)                                                                                                                                                                        │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main                                                                                                           │ ▒
▒│     rv = self.invoke(ctx)                                                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1682, in invoke                                                                                                         │ ▒
▒│     cmd_name, cmd, args = self.resolve_command(ctx, args)                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command                                                                                                │ ▒
▒│     cmd = self.get_command(ctx, cmd_name)                                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/cli.py", line 611, in get_command                                                                                                      │ ▒
▒│     app = info.load_app()                                                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/flask/cli.py", line 328, in load_app                                                                                                         │ ▒
▒│     app: Flask | None = self.create_app()                                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/base.py", line 70, in create_app_wsgi                                                                                           │ ▒
▒│     app = create_app(cli=cli)                                                                                                                                                                                │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/base.py", line 59, in create_app                                                                                                │ ▒
▒│     app.config.load_extensions("EXTENSIONS")                                                                                                                                                                 │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/dynaconf/contrib/flask_dynaconf.py", line 231, in load_extensions                                                                            │ ▒
▒│     initializer(app)                                                                                                                                                                                         │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/database.py", line 20, in init_app                                                                                              │ ▒
▒│     from hiddifypanel.panel.init_db import init_db                                                                                                                                                           │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/panel/init_db.py", line 9, in <module>                                                                                          │ ▒
▒│     from hiddifypanel import Events, hutils                                                                                                                                                                  │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/__init__.py", line 1, in <module>                                                                                        │ ▒
▒│     from . import network                                                                                                                                                                                    │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/__init__.py", line 2, in <module>                                                                                │ ▒
▒│     from . import auto_ip_selector                                                                                                                                                                           │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/hutils/network/auto_ip_selector.py", line 9, in <module>                                                                        │ ▒
▒│     from hiddifypanel.cache import cache                                                                                                                                                                     │ ▒
▒│   File "/opt/hiddify-manager/.venv/lib/python3.10/site-packages/hiddifypanel/cache.py", line 7, in <module>                                                                                                  │ ▒
▒│     redis_client = redis.from_url(os.environ["REDIS_URI_MAIN"])                                                                                                                                              │ ▒
▒│   File "/usr/lib/python3.10/os.py", line 680, in __getitem__                                                                                                                                                 │ ▒
▒│     raise KeyError(key) from None                                                                                                                                                                            │ ▒
▒│ KeyError: 'REDIS_URI_MAIN'                                                                                                                                                                                   │ ▒
▒│ ===run.sh hiddify-panel                                                                                                                                                                                      │ ▒
▒│ Failed to start hiddify-panel-background-tasks.service: Unit hiddify-panel-background-tasks.service not found

**Comment by litoosh13** [comment]
تشکر بابت اطلاع رسانی در دست بررسی قرار دارد
