### ISSUE TITLE
Anyway to set a Username and password for Admin in Manager UI?

### ISSUE THREAD

**Issue by alexlii1971** [hiddify/Hiddify-Manager#4616]
Hello,

Please check the screenshot:

<img width="1350" alt="Screen Shot 2024-11-24 at 17 50 16" src="https://github.com/user-attachments/assets/c30823c9-b22a-43cb-90bb-708618fbb559">

Anyway to set a Username and password for Admin in Manager UI?

Thanks

**Comment by litoosh13** [comment]
up to this version no it woked with uuid maybe in future version we add this
