### ISSUE TITLE
SingBox & Xray 

### ISSUE THREAD

**Issue by HiddifyApp** [hiddify/Hiddify-Manager#4620]
یه بروزرسانی منتشر کنین برای هسته ها، هم SingBox هم Xray کلی بروزرسانی دادن خصوصا این بروزرسانی 24.11.21 هسته xray کلی تغییرات برا splitHTTP ایجاد کرده و الان دو حالت stream-up و packet-up داره و سرعتش خیلی خیلی بهتر شده

**Comment by litoosh13** [comment]
تشکر از اطلاع رسانی بررسی میشه!
