### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by MetiiteM** [hiddify/Hiddify-Manager#4624]
سلام. کلودفلر جدیدا بازی دراورده و cdn ها پینگ نمیده و ساب دامین ها درست کار نمیکنه.
راهکار پیشنهای چیه؟

**Comment by litoosh13** [comment]
سلام هیدیفای هیچگونه تعهدی نسبت به عملکرد پروتکل یا cdn ها مختلف ندارد لطفا ایشو در این مورد باز نکنید
