### ISSUE TITLE
I can't close 80 port

### ISSUE THREAD

**Issue by lev007-ops** [hiddify/Hiddify-Manager#4625]
**Describe the bug**

Hi, https://2ip.io/privacy/ detects my port 80 as opened:
![2ip.io screenshot](https://github.com/user-attachments/assets/ebd9963e-040f-4c34-b4c7-af34da9c080f)

But I want to close it, because I use only https 443 port.
iptables and ufw can't deny port 80.

**To Reproduce**
1. Install Manager
2. Enable Firewall (not necessary)
3. Deny 80 port in ufw
4. Try `sudo lsof -i :80` or https://2ip.io/check-port/

**Expected behavior**
I want to close port 80.

**Server**
 - OS: Ubuntu 22.04
 - Browser: Arc (Chromium Engine)
 - Version: 10.70.9

**Comment by lev007-ops** [comment]
I can clouse the port 80 by firewall in Digital Ocean, but there is still a bug
![Digital Ocean](https://github.com/user-attachments/assets/9ca63154-998e-48a2-997c-4e93c402bece)

**Comment by litoosh13** [comment]
you should not close 80 port it is essential for hiddify manager
