### ISSUE TITLE
Why the fuck would you redirect http requests to rahavardjournal.org ?!

### ISSUE THREAD

**Issue by koteelok** [hiddify/Hiddify-Manager#4626]
I have Hiddify Manager hosted on my VPS and the FIRST thing I see when I try to open my IP address in a browser is some kind of bullshit [iran newsletter site](https://rahavardjournal.org).

There is not a single warning that your domain and IP address is being used to promote some political bullshit.

What the FUCK is that?

![image](https://github.com/user-attachments/assets/e3267315-62cf-4f49-9b84-0b36a2c44aed)

**Comment by litoosh13** [comment]
it is re-routing to a decoy site
you can change the site in setting 
and dont ever again use f word!!!!
