### ISSUE TITLE
Direct connection to domestic sites

### ISSUE THREAD

**Issue by soroushsafaar** [hiddify/Hiddify-Manager#4627]
# Bug/Feature:      Direct connection to domestic sites
**Description**:     Direct connection to domestic sites which can be set from management panel and proxy core, needed. please add this feature. thanks.

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-5.15.0-126-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
we do have this option on hiddify manager and also on hiddify next
