### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by PhanKOw** [hiddify/Hiddify-Manager#4628]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.70.9
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-5.15.0-122-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

پنل جذابیتش واقعا زیاده
فقط یک مشکل وجود داره

بیشتر توی گوشی این اتفاق میوفته که یهو وقتی بدون مشکل وصل هستش
میشه کانکتینگ یا بعضی وقت تایم اوت میده
که با ی قطع و وصل کردن مشکل حل میشه اما یکم این مورد اذیت کنندس
باز هم بیشترین مشکل روی اندروید هست تا ایفون اما روی ایفون هم هستش

نسخه مورد استفاده از 2.1.5 روی اندروید از پلی استور هستش
و روی ایفون اخرین نسخه اپل استور 

دمتون گم اگه راهنمایی کنید یا بررسی مشکل رو

**Comment by litoosh13** [comment]
اینجا مربوط به پنل هست به تاپیک مربوط به اپ هیدیفای مراجعه کنید
