### ISSUE TITLE
Schedule to stop the User key?

### ISSUE THREAD

**Issue by alexlii1971** [hiddify/Hiddify-Manager#4629]
**Is your feature request related to a problem? Please describe.**
No, no issue, but we would like to allow kids to use vpn. however, would like to stop the keys by schedule like before 10:00PM.

**Describe the solution you'd like**
Daily schedule: 

Valid: 8:00AM-10:00PM

However, it is now much trouble to manager lots of keys one by one manually.

Thanks

**Comment by litoosh13** [comment]
hi as of now this request is impossible due to pressure that make cpu and ram bear...sorry to deny
