### ISSUE TITLE
Custom Timezone

### ISSUE THREAD

**Issue by JeelsBoobz** [hiddify/Hiddify-Manager#4641]
Please allow user for custom timezone

**Comment by litoosh13** [comment]
it is not possible at the moment because time will be automaticaly set by server timezone

**Comment by JeelsBoobz** [comment]
> it is not possible at the moment because time will be automaticaly set by server timezone

No, it's alway change timezone by hiddify every apply config

**Comment by JeelsBoobz** [comment]
> it is not possible at the moment because time will be automaticaly set by server timezone

This is not my server timezone
![Screenshot_2024-12-17-13-19-15-934_com sonelli juicessh](https://github.com/user-attachments/assets/3487f2f1-896d-4c6c-92d5-f29de2bc1f20)

**Comment by JeelsBoobz** [comment]
> > it is not possible at the moment because time will be automaticaly set by server timezone
> 
> No, it's alway change timezone by hiddify every apply config

Always set to Tehran every Apply configs
This VPS same with my region (Jakarta, Indonesia)
![Screenshot_2024-12-17-13-22-06-640_com sonelli juicessh](https://github.com/user-attachments/assets/a237efa1-ec66-421f-941e-47600917c2ed)

**Comment by litoosh13** [comment]
did you try changing time zone by linux command :
sudo timedatectl set-timezone America/New_York
??

**Comment by JeelsBoobz** [comment]
> did you try changing time zone by linux command : sudo timedatectl set-timezone America/New_York ??

Yes, of course
Already change timezone via terminal, but back to Asia/Tehran every Apply configs
