### ISSUE TITLE
erro hiddyfy-nginx in update 10.80.7

### ISSUE THREAD

**Issue by fazelit** [hiddify/Hiddify-Manager#4643]
**Describe the bug**
 sudo tail -n 50 /var/log/nginx/error.log
2024/12/16 11:58:34 [emerg] 25628#25628: unknown directive "http2" in /opt/hiddify-manager/nginx/conf.d/singbox-base.conf:3

**Comment by litoosh13** [comment]
tell us about it in our telegram channel:
https://t.me/hiddify_board
