### ISSUE TITLE
انتخاب پورت دلخواه

### ISSUE THREAD

**Issue by tofane69** [hiddify/Hiddify-Manager#4644]
سلام. لطفا اگر مقدوره امکان ویرایش لیست پراکسی ها رو به تفکیک دامنه قرار بدید مثلا برای یه دامنه میخوایم grpc داشته باشیم برای دامنه دیگه نه

و یا مثلا از یک سی دی ان دیگه میخوایم استفاده کنیم نیاز داریم اون دامنه رو فقط به پورت خاصی متصل کنیم ولی کانفیگا همچنان به 80 و 443 ریدایرکت بشن
اگر میشه این موارد رو هم اضافه کنید تا کارایی پنل بالاتر بره و بتونیم چندین سی دی ان رو استفاده کنیم

**Comment by litoosh13** [comment]
سلام این مورد قبلا در دستور کار قرار گرفته تشکر
