### ISSUE TITLE
عدم نصب نسخه 10.8.7

### ISSUE THREAD

**Issue by moli1369** [hiddify/Hiddify-Manager#4645]
سلام دوستان از دیشب درگیرشم و نمیتونم نسخه جدید رو نصب کنم روی تمامی نسخه ها چک کردم نمیشه 
20
22
24
هر سه رو کلا سیستم عامل رو رینستال کردم و انجامش دادم خیر نصب نمیشه فقط روی نسخه 24 تموم میشه اما سرویس هاش فعال نمیشه 
متاسفانه برگشتم دوباره به نسخه 10.70.9 و روی این نسخه فعال میشه تمامی سرویس ها 
ممنون میشم راهنمایی کنید کلا توی نسخه نسخه جدید روی 98 درصد میره کلا هنگ میکنه و تمام قشنگ 3 ساعت روی همین 98 درصد توقف کرد و نصبش هم برای من تا این درصد 2.30 دقیقه زمان برد و اخرش هم دیس کرد منو از سرور برگشتم دیدم کلا سرور هنگ مجبور شدم برگردم به نسخه قدیمی دوستان اگر موفق شدید ممنون میشم راهنمایی کنید .

**Comment by litoosh13** [comment]
سلام لطفا از سرور دیگری استفاده کنید تا الان روی اکثر دیتاسنترهای معروف ما تست کردیم و نصب موفق بوده

**Comment by moli1369** [comment]
دیتا سنتر های که تست کردید رو ممنون میشم معرفی کنید که هیدیفای روی راحت هندل شه و مشکلی نخور و یا اینکه دیتا سنتر هایی که جواب داده رو ممنون میشم معرفی کنید.

**Comment by behiunforgiven** [comment]
من هم همین مشکل رو دارم. روی ۹۸ درصد گیر می کنه و حتی دیگه سرور غیر قابل دسترس میشه.

**Comment by litoosh13** [comment]
> دیتا سنتر های که تست کردید رو ممنون میشم معرفی کنید که هیدیفای روی راحت هندل شه و مشکلی نخور و یا اینکه دیتا سنتر هایی که جواب داده رو ممنون میشم معرفی کنید.

ovh-hetzner-amazon
و بدون مستندات فقط گفتن اینکه نصب نمیشه کاری از ما برنمیاد عزیز

**Comment by mrgeex** [comment]
برای من هم امازون و هتزنر توی همینجا میمونه و هنگ میکنه تا اینکه خودم کنسلش کردم
![image](https://github.com/user-attachments/assets/2460fd64-b7d1-40ba-a270-22b0b8f9e064)

**Comment by litoosh13** [comment]
ورژن های متفاوت از اوبونتو و سخت افزار های مختلف رو تست کنید مخصوصا مدل پردازنده که اینتل باشه یا چیز دیگ
ببنید مشکل پا برجاس یا ن

**Comment by moli1369** [comment]
اره من اینو تست کردم هم روی بستر داکر هم بردمش نه کلا داستان داره  مجبور شدم با نصب کاستوم برم به نسخه 10.7 و الان هم روی همین نسخه موندم و اپدیت خودکار رو خاموش کردم.

**Comment by litoosh13** [comment]
اوکی منتظر نسخه های بعدی باشید

**Comment by moli1369** [comment]
ممنونم از شما و حتما توی نسخه جدید ذکر کنید با چه سخت افزار همخونی داره که خدایش اسیر نشیم چند ساعت بازم جدا از صحبت ها  اینکه بدون منت دارید این حرکت رو میزنید دمتون گرم سپاس از شما و دوستان هیدیفایی.
