### ISSUE TITLE
مشکل وارپ در هسته سینگ باکس

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4650]
root@Hiddify:/opt/hiddify-manager# nano /opt/hiddify-manager/singbox/configs/03_routing.json.j2

{% set region = {
    'zh': 'cn',
    'cn': 'cn',
    'ir': 'ir',
    'ru': 'ru'
}.get(hconfigs['country'], 'cn') %}

{
  "route": {
    "rule_set":[
         {
            "tag":"geoip-{{region}}",
            "type":"remote",
            "format":"binary",
            "update_interval":"1d",
            "url":"https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-{{region}}.srs"
         },
         {
            "tag":"geosite-{{region}}",
            "type":"remote",
            "format":"binary",
            "update_interval":"1d",
            "url":"https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-{{region}}.srs"
         }
    ],
    // "domainStrategy": "AsIs",
    "final": {% if hconfigs['warp_mode'] == 'all' %}"WARP"{% else %}"freedom"{% endif %},
      "rules": [
        {
            "outbound": "freedom",
            "port": [53]
        },
        {
          "protocol": "quic",
          "port": [443],
          "outbound": "blackhole"
        },
        {
            "outbound": {% if hconfigs['warp_mode'] == 'disable' %}"forbidden_sites"{% else %}"WARP"{% endif %},
             "rule_set":["geoip-{{region}}", "geosite-{{region}}"]
        },
        {
            "outbound": {% if hconfigs['warp_mode'] == 'disable' %}"freedom"{% else %}"WARP"{% endif %},
            "geosite":[
                "hiddify-hetzner-warp",
                "steam",
                "steamunlocked",
                "spotify",
                "scdn.co",
                "spotifycdn.com",
                "spoti.fi",
                "adobe",
                "meta",
                "tiktok",
                "google",
                "openai",
                "reddit",
                "netflix",
                "nvidia",
                "ookla-speedtest"

            ]
        },
        {% if hconfigs['warp_mode'] != 'disable' and hconfigs.get('warp_sites','').split('\n') %}
        {
            "outbound": "WARP",
            "domain":[
                  {%for d in hconfigs.get('warp_sites','').split('\n')%}
                      "{{d.strip()}}",
                  {% endfor %}
            ]
        },
        {% endif %}
        {
          "outbound": "blackhole", "geoip": ["private"]
        }
        // {// Block BitTorrent protocol
        //   "type": "field", "outboundTag": "blackhole", "protocol": ["bittorrent"]
        // },
      ]
    }

}

درود روی هسته ایکس ری این مشکل رو ندارم و اسپاتیفای کار میکنه با وارپ ولی روی سینگ باکس حتی با اعمال تغییرات بالا و اضافه کردن تمام دامنه ها تو پنل بازم اسپاتیفای از وارپ رد نمیشه اگه امکانش هست بررسی کنید

**Comment by litoosh13** [comment]
وارپ روی همه بزارید ببینید نتیجه چیه

**Comment by dahraf** [comment]
روی همه اوکیه ولی وقتی خودم دستی جئو سایت ها رو وارد میکنم و توپنل هم دامنه رو ثبت میکنم اسپاتیفای برام بالا نمیاد نه فقط اسپاتیفای دامنه های پای نتورک و هوش مصنوعی گوگل و ... هم همینطور که روی ایکس ری هم این مشکل رو دارم با پای نتورک و جمنای گوگل این برنامه ها روی دستگاه ها از وارپ رد نمیشن ولی روی همه قرار میدم اوکی میشه

**Comment by litoosh13** [comment]
اگر احیانا تغییری به صورت دستی در فایل های پنل توی سرور انجام دادین مجدد پنل رو نصب کنید 
حتما به اخرین ورژن آپدیت کنید
و در صورت پایداری مشکل در گروه تلگرام مطرح کنید:
https://t.me/hiddify_board/13/523846
