### ISSUE TITLE
باگ ورژن 10.80.8

### ISSUE THREAD

**Issue by tofane69** [hiddify/Hiddify-Manager#4651]
سلام ورژن جدید 10.80.8 مشکل داره برای نصب. اول اپدیت کردم انجام نشد. از اول سرور رو سیستم عامل زدم نصب کردم بازم مرحله اخرش ارور میده. مجبور شدم دانگرید کنم.

**Comment by EmperorOMIDZ** [comment]
درود
دقیقا منم آپدیت کردم و به غلط کردن افتادم
نتیجه آپدیت هم شد این:
![IMG_9173](https://github.com/user-attachments/assets/41b28ff0-5363-473d-
a894-4d33953e1cdd)
بدبختی اینه که گزینه دانگرید هم نداره
پنلم هم بدون یوزر نیست که بتونم پاک کنم از اول نصب کنم
گیر افتادم این وسط
اگه کسی کمک و راهنمایی میتونه بکنه ممنون میشم

**Comment by JeelsBoobz** [comment]
Downgrade
```bash <(curl https://i.hiddify.com/v10.80.7)```

**Comment by EmperorOMIDZ** [comment]
> bash <(curl https://i.hiddify.com/v10.80.7)

اطلاعات پنل پاک نمیشه؟

**Comment by EmperorOMIDZ** [comment]
> Downgrade
> `bash <(curl https://i.hiddify.com/v10.80.7)`

با اجرای این دستور، اطلاعات فعلی موجود در پنل پاک نمیشه؟

**Comment by darkzed-dev** [comment]
من مجبور شدم پاک کنم الان نه نسخه v10.80.8 نصب میشه خطای 21 میگیره نه نسخه v10.80.7 برام کار میکنه بکاپ رو اپلود میکنم غبر فعال میشه

**Comment by EmperorOMIDZ** [comment]
> > > Downgrade
> > > `bash <(curl https://i.hiddify.com/v10.80.7)`
> > 
> > 
> > @JeelsBoobz By executing this command, won't the current information in the panel be deleted?
> 
> Safe, no file deleted

@JeelsBoobz dude you are a life saver 😍😍
Thanks bro 🙏🙏

**Comment by blue-farid** [comment]
uninstalling the hiddify via itself has two options. "uninstall" and "purge". as it says, the uninstall option does not delete the database. so you can uninstall the hiddify version 10.80.8 and install 10.80.7. It worked for me with no data loss.

**Comment by litoosh13** [comment]
لطفا به اخرین نسخه موجود اپگرید کنید:
https://t.me/hiddify_board/482495/522807
