### ISSUE TITLE
Feature downgrade version

### ISSUE THREAD

**Issue by JeelsBoobz** [hiddify/Hiddify-Manager#4652]
add downgrade feature via terminal to overcome bugs in new versions

**Comment by JeelsBoobz** [comment]
Or split different update from release, beta, dev, or anything
So, user stable not update to other version

**Comment by litoosh13** [comment]
belive it or not we have all things about our cli or manager itself in this links:
https://hiddify.com/fa/manager/
https://hiddify.com/en/manager/

but no body seems to read them
