### ISSUE TITLE
10.80.8 

### ISSUE THREAD

**Issue by Afx110** [hiddify/Hiddify-Manager#4653]
Hiddify: Command update
==========================================

\Usage: python -m hiddifypanel [OPTIONS] COMMAND [ARGS]...
Try 'python -m hiddifypanel --help' for help.

Error: No such command 'all-configs'.

Error: Key not found: warp_mode

**Comment by ErtebateWeb** [comment]
Downgrade
bash <(curl https://i.hiddify.com/v10.80.7)

**Comment by litoosh13** [comment]
upgrade to latest version:
https://t.me/hiddify_board/482495/522818
