### ISSUE TITLE
inactive haproxy v10.80.8

### ISSUE THREAD

**Issue by dahraf** [hiddify/Hiddify-Manager#4654]
![image](https://github.com/user-attachments/assets/3947f118-1a94-41ca-ba22-ee79cfcaf3cc)

ورژن جدید آپدیت کردم ولی رفع نشد ریبوت و ریست هم انجام دادم هنوز این مشکل هست و cpu سرور به شدت درگیره

**Comment by ErtebateWeb** [comment]
Downgrade
bash <(curl https://i.hiddify.com/v10.80.7)

**Comment by blue-farid** [comment]
same issue here.

**Comment by dynomake** [comment]
I was gonna say the same thing! I had 20 servers crash overnight.

**Comment by iwanmikhajlov** [comment]
Same here, haproxy keeps failing
The logs suggest that the arguments are being passed incorrectly at startup

`Dec 18 09:04:26 hiddify-manager-node haproxy[5925]: Usage : haproxy [-f <cfgfile|cfgdir>]* [ -vdVD ] [ -n <maxconn> ] [ -N <maxpconn> ] ...`

**Comment by rastegardev** [comment]
> Downgrade bash <(curl https://i.hiddify.com/v10.80.7)

من هم مشکل مشابه داشتم و با Downgrade به ورژن قبلی برطرف شد. تشکر
<img width="590" alt="Screenshot 1403-09-28 at 10 23 51" src="https://github.com/user-attachments/assets/2c66f74a-3c63-4d88-8242-533537b113d5" />

**Comment by litoosh13** [comment]
upgrade to latest version:
https://t.me/hiddify_board/482495/522818
