### ISSUE TITLE
sub-link

### ISSUE THREAD

**Issue by MetiiteM** [hiddify/Hiddify-Manager#4657]
سلام. من از only-sub-link استفاده میکنم اما چند وقته لینکا رو نشون نمیده
اپدیت کردم ری استارت کردم بازم درست نشد
v 10.8.9
![Screenshot 2024-12-18 113907](https://github.com/user-attachments/assets/9c4520e4-b419-4e77-b7ba-545871d6b6e7)

**Comment by litoosh13** [comment]
عزیز شما باید لینک های مورد نیاز رو اضافه کنید به لینک ساب تا نشون بده

**Comment by ReturnFI** [comment]
اگر هر دو دامنه دایرکت و ساب لینک داری
و با دامنه ساب لینک وارد پنل بشید در بخش کاربران بصورت دامنه فعلی نشون میده

**Comment by litoosh13** [comment]
بزودی بسته می شود
