### ISSUE TITLE
ssl certificate renewal 

### ISSUE THREAD

**Issue by Mahdisayiar** [hiddify/Hiddify-Manager#4666]
من مدت زیادی نیست با پنل کار میکنم و تقریبا ۳ یا ۴ ماهی میشه. بعد از تنظیم اولیه پنل فکر میکنم اولین گواهی که برای دامنه ها ثبت میشه ۳ ماهه هستن. چون تقریبا بعد از ۳ ماه دیگه پنل با لینک مخصوص پنل بالا نمیاد. یعنی در واقع با هیچ لینکی. بعد اینکه از طریق آی پی وارد پنل میشم میبینم یکسری از سرویس های پنل یا از کار افتادن یا متوقف شدن.
بعد از اپدیت و چند بار ری استارت و تغییر تنظیمات سرویس ها اوکی میشن ولی همچنان گواهی ssl برای پنل به صورت اتوماتیک گرفته نمیشه.
تقریبا هر ماه باید کل دامنه هارو یک بار از روی پنل حذف و دوباره ثبت کنم تا براشون گواهی گرفته بشه.
![20241219_044610](https://github.com/user-attachments/assets/77bcb9eb-56dc-4835-b2e3-197c961b55df)

تقریبا یک ماهی میشه که وضعیت پروکسی ها از قسمت پنل نمایش داده نمیشه.

**Comment by litoosh13** [comment]
عزیز بعد از هر اپلای کانفیگ دامنه هایی که سرتفیکت نداشته باشن براشون گرفته میشه
مورد دوم در مورد وضعیت پروکسی داریم بررسی میکنیم

**Comment by Mahdisayiar** [comment]
ممنونم از زحماتتون
شاتی که ارسال کردم مربوط به خطای سرت هستش درسته؟
من بعد از نمایش این خطا چندین بار تنظیمات رو تغییر دادم، پنل رو ارتقاع دادم به اخرین نسخه و... ولی هنوزم با دامنه ای که برای پنل تعریف کردم دسترسی ندارم و همون خطا نمایش داده میشه
فکر میکنم دیگه سرت براش نمیگیره
اما موقعی که دامنه دوباره تعریف میشه تو پنل موقع ثبتش براش یه گواهی جدید میگیره اما نهایتا یک ماه بدون مشکل باشه
چون دامنه هایی که به عنوان cdn تنظیم شدن وقتی این خطا میاد کانفیگ هاشونم قطع میشن و پروکسیشون از کار میوفته

**Comment by litoosh13** [comment]
عزیز تست شده این موضوع و هیچ مشکلی برای هیچ مدل دامنه ای وجود نداره
