### ISSUE TITLE
Manage page lost ccs?

### ISSUE THREAD

**Issue by royer** [hiddify/Hiddify-Manager#4667]
**Describe the bug**
the Admin page suddenly looks like this:
<img width="752" alt="Screenshot 2024-12-18 at 9 16 46 PM" src="https://github.com/user-attachments/assets/efd889b3-b1b6-4218-bd2c-414650e3efe3" />

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.1 (24B91)
 - Browser: chrome Version 131.0.6778.140 (Official Build) (arm64)
 - Browser: Safari 

**Smartphone (please complete the following information):**
 - Device: Pixel 9 Pro XL
 - OS: Android 15
 - Browser: Chrome 131.0.6778.136

**Additional context**

**Comment by litoosh13** [comment]
did you try reinstall panel ?
