### ISSUE TITLE
Please fill the title properly

### ISSUE THREAD

**Issue by harnid** [hiddify/Hiddify-Manager#4671]
grammar:
**Description**:     so in the file sent to the telegram bot for insecure admin link it says: do not use it - only if others not work
which is wrong 
suggest u change it to
"Do not use it unless others do not work." or "Use it only if others don't work."
u see u can't say "don't ... only" it should be "don't ... unless" or "do ... only if"
[ty]
![Screenshot_20241220-013353](https://github.com/user-attachments/assets/079c4253-9cd1-4d73-b773-cb92300f1be9)
 @harnid

**Comment by litoosh13** [comment]
thanks for reporting
