### ISSUE TITLE
کار نکردن کانفیگ هایی که از پورت 443 استفاده میکنن

### ISSUE THREAD

**Issue by soshiantmahdavi** [hiddify/Hiddify-Manager#4675]
با سلام و احترام
کانفیگهایی که از پورت 443 استفاده میکنن کار نمیکنن 
سیستم عامل : اوبونتو 22.04
ورژن هیدیفای منیجر : 10.80.11
اینترنت پرووایدر : هتزنر

**Comment by soshiantmahdavi** [comment]
متوجه شدم برای سی دی ان سرتیفیکیت نمیگیره
دامنه رو به عنوان دایرکت به پنل معرفی کردم براش سرت گرفت بعد دامنه رو تبدیل به سی دی ان کردم ، مشکل برطرف شد
بر این اساس ی حرکتی باید صورت بگیره که برای سی دی ان سرت گرفته بشه

**Comment by litoosh13** [comment]
تشکر بررسی میشه
