### ISSUE TITLE
Redirecting to fake site

### ISSUE THREAD

**Issue by iamvany30** [hiddify/Hiddify-Manager#4676]
I want to use my VPS for Hiddify and hosting a site, but when I try to open the website, it sends me to a fake site that was set for . How can I fix this? I tried to change the fake site to another domain, but it still redirected to the fake site.

**Comment by iamvany30** [comment]
Another domain is mine and sends to servers ip.

**Comment by litoosh13** [comment]
it is not recommended to have a website or any other service besides your Hiddify Manager so please stick to the fake site
