### ISSUE TITLE
مشکا در فعال نشدن سرویس تلکرام 

### ISSUE THREAD

**Issue by ahmadas60** [hiddify/Hiddify-Manager#4681]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.80.11
**Python Version**:  3.10.16 (main, Dec  4 2024, 08:53:38) [GCC 13.2.0]
**OS**:              Linux-6.8.0-31-generic-x86_64-with-glibc2.39
**User Agent**:      Unknown

سلام بعد آپدیت سرویس تلگرامم دسگه فعال نمیشه 
![photo_2024-12-22_11-33-07](https://github.com/user-attachments/assets/e57b603e-ba9e-4155-a13f-e0f005112c5f)

**Comment by litoosh13** [comment]
نصب تمیز کنید مورد حل میشه 
ریبیلد کنید و مجدد نصب کنید
بکاپ فراموش نشه
