### ISSUE TITLE
Cloudflare API Token

### ISSUE THREAD

**Issue by JeelsBoobz** [hiddify/Hiddify-Manager#4687]
Can't add domain if set Cloudflare API Token
![Screenshot_2024-12-23-15-39-50-036_com kiwibrowser browser](https://github.com/user-attachments/assets/fe77b3dd-e765-48d4-ace5-694dc355e439)

**Comment by litoosh13** [comment]
that way is not working anymore so please stick to normal method of adding domain
https://hiddify.com
check out our website for all tutorial

**Comment by JeelsBoobz** [comment]
> that way is not working anymore so please stick to normal method of adding domain https://hiddify.com check out our website for all tutorial

Okay, thanks for information
Please, remove all deprecated feature like this
