### ISSUE TITLE
از کار افتادن ربات بعد از آپدیت

### ISSUE THREAD

**Issue by mokhtarabdi** [hiddify/Hiddify-Manager#4690]
سلام خسته نباشید  از وقتی این آپدیت جدید (۱۰.۸۰.۹ و ۱۰.۸۰.۱۱) اومد رباتم فقط بکاپ واسش میاد واسه بقیه چیزا کار نمیکنه..

**Comment by litoosh13** [comment]
سلام روی نسخه اخر تست کردیم این مورد رو هیچ مشکلی وجود ندارد
