### ISSUE TITLE
High cpu usage high ram and telegram bot dont response 

### ISSUE THREAD

**Issue by Sadiqira** [hiddify/Hiddify-Manager#4691]
# Bug/Feature:
**Description**:     Describe bug or needed feature

## Details:
**Hiddify Version**: 10.80.11
**Python Version**:  3.10.16 (main, Dec  4 2024, 08:53:38) [GCC 13.2.0]
**OS**:              Linux-6.8.0-39-generic-x86_64-with-glibc2.39
**User Agent**:      Unknown

**Comment by Vitstark** [comment]
+

**Comment by svegan** [comment]
Same. At some point, overloaded and just stuck. Even ssh can't get in. Only hard reload helps. 

Also there is an issue with mtproxy permissions setting:
`mtg: error: cannot init config: cannot read config file: open /opt/hiddify-manager/other/telegram/tgo/mtg.toml: permission denied`
Once those allowed it works for about a day and after that stuck again.

**Comment by litoosh13** [comment]
we checked several servers and we dont face this problem on our latest version of panel please do this step:
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
