### ISSUE TITLE
mtproxy is not started automatically after apply config changes

### ISSUE THREAD

**Issue by atomic-dz** [hiddify/Hiddify-Manager#4692]
# Bug/Feature:
**Description**:   mtproxy is not started automatically
- Services Status:
    hiddify-cli                                            active 
    hiddify-haproxy                                        active 
    hiddify-redis                                          active 
    hiddify-nginx                                          active 
    hiddify-ssh-liberty-bridge                             active 
    hiddify-panel-background-tasks                         active 
    mtproxy                                            activating 
    hiddify-xray                                           active 
    hiddify-singbox                                        active 
    hiddify-panel                                          active 

wrong permissions

ls -la /opt/hiddify-manager/other/telegram/tgo/mtg.toml
-rw------- 1 root root 8685 Dec 24 17:09 /opt/hiddify-manager/other/telegram/tgo/mtg.toml

After change 
chmod a+rw /opt/hiddify-manager/other/telegram/tgo/mtg.toml

Everything is starting.

- Services Status:
    hiddify-cli                                            active 
    hiddify-ssh-liberty-bridge                             active 
    hiddify-redis                                          active 
    hiddify-haproxy                                        active 
    hiddify-panel-background-tasks                         active 
    hiddify-singbox                                        active 
    hiddify-xray                                           active 
    hiddify-nginx                                          active 
    hiddify-panel                                          active 
    mtproxy                                                active 

## Details:
**Hiddify Version**: 10.80.11
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-6.8.12-4-pve-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
1.Make a backup
2. rebuild server to ubuntu 22.04
3. install latest version of the panel
4.restore backup
you can follow all learning's material about the panel here:
hiddify.com/manager
