### ISSUE TITLE
SSL Error using ipv6

### ISSUE THREAD

**Issue by JeelsBoobz** [hiddify/Hiddify-Manager#4694]
Can't access some http server ipv6 (Example: https://ipv6.google.com/generate_204)

Client:
![Screenshot_2024-12-25-08-23-42-648_com termux](https://github.com/user-attachments/assets/fd7ce64c-e8d8-433b-bc97-ffa898ccc708)

VPS:
![Screenshot_2024-12-25-08-47-56-124_com sonelli juicessh](https://github.com/user-attachments/assets/73415f46-0b55-4718-a5c6-11bcb2a7b133)

**Comment by litoosh13** [comment]
you can try 
`curl -6 ip.sb`
