### ISSUE TITLE
عدم گرفتن سرتیفیکیت در نسخه 10.80.11

### ISSUE THREAD

**Issue by soshiantmahdavi** [hiddify/Hiddify-Manager#4698]
با سلام و درود
متاسفانه توی گرفتن سرتیفیکیت در دامنه های از جنس php hosting و همچنین cdn خالی (cdn خودکار اوکیه) و همچنین دامنه های فیک مشکل داره
دامنه فیک رو برای سی دی ان فستلی نیاز داریم
لطفا ی کاری کنید که هر نوع دامنه ای رو بتونیم سرتیفیکیت بگیریم
سپاس از زحماتتون
OS : Ubuntu 22.04
V : 10.80.11
ISP : Hetzner

**Comment by litoosh13** [comment]
بله این موضوع در دست توسعه هست
