### ISSUE TITLE
Keep activating sing-box core

### ISSUE THREAD

**Issue by pichoko** [hiddify/Hiddify-Manager#4702]
![5AE42209-4F1D-4D55-AB91-A1AE3C8338EC](https://github.com/user-attachments/assets/af6a92cd-ce9e-4ea1-bbd3-29af878b2e76)
# Bug/Feature:
**Description**:     مطابق تصویر که فرستادم هسته سینگ باکس فعال نمیشه برام و کارایی که کردم مثل چندین بار ریستارت کردن پنل و پاک کردن پنل و نصب اون هیچکدوم فعالش نکرد

## Details:
**Hiddify Version**: 10.80.11
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-5.15.0-46-generic-x86_64-with-glibc2.35
**User Agent**:      Unknown

**Comment by litoosh13** [comment]
عزیز توی گروه هم پیام دادین یک جا مطرح کنید و منتظر جواب بمونید
روی آخرین ورژن این موردی که فرمودین تست شده و هیچ مشکلی وجود نداشته 
لطفا نصب تمیز کنید و در صورت امکان با سرور دیگری تست کنید

**Comment by pichoko** [comment]
ممنون فقط میشه راهنمایی کنین که نصب تمیز چجوری هست؟

**Comment by litoosh13** [comment]
ریبیلد کنید سرور رو مجدد نصب کنید اخرین ورژن پنل رو
موقع برگرداندن بکاپ فقط کاربران رو برگردونید بعدا دستی تنظیمات و دامنه ها رو ست کنید
