### ISSUE TITLE
نمایش آمار کاربران غیر فعال، منقضی

### ISSUE THREAD

**Issue by Alirezamoradi20** [hiddify/Hiddify-Manager#4706]
سلام لطفا آمار کاربران غیرفعال یا منقضی شده بصورت تجمیعی در پنل نمایش داده بشه. مثلا ۱۰ کاربر از ۵۰ کاربر غیرفعال هستند یا تاریخ سرویسشون تموم شده.
با تعداد کاربر کم خودمون میتونیم آمار دربیاریم ولی وقتی تعداد کل کاربران زیاد میشه این کار کمی سخت میشه.

**Comment by litoosh13** [comment]
عزیز شما روی فعال کلیک کنید کاربران  برحسب فعال و غیرفعال به صورت اتومات لیست میشن
