### ISSUE TITLE
Adding Token to prevent connecting multiple devices

### ISSUE THREAD

**Issue by Sooshka-X** [hiddify/Hiddify-Manager#4711]
#Feature:

We have implemented it for a limited number of users, but since configurations can be copied and shared, it can lead to excessive traffic. This increases the risk of the domain and panel being blocked. To address this, please consider adding a feature like a token system that allows us to specify the number of devices permitted to connect simultaneously.

## Details:
**Hiddify Version**: 10.80.11
**Python Version**:  3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
**OS**:              Linux-5.15.0-130-generic-x86_64-with-glibc2.35

Regards,
Sooshka

**Comment by litoosh13** [comment]
hi 
this is not our goal to develope in any near future
so you can just restrict your users using traffic !
