### ISSUE TITLE
کارنکردن همه ی کانفیگ کلود

### ISSUE THREAD

**Issue by devopsy-ir** [hiddify/Hiddify-Manager#69]
برای من قسمت runcmd کانفیگ  cloud config داخل هتزنر کار نکرد!  شاید نسخه ی cloud init فرق کرده باشه در هتزنر جدیدا!

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس

**Comment by malkhamed** [comment]
سلام من می‌خوام hiddify رو حذف کنم از چه کامندی استفده کنم متاسفانه هر کامندی تست کردم نشد

**Comment by absoonoo** [comment]
> سلام من می‌خوام hiddify رو حذف کنم از چه کامندی استفده کنم متاسفانه هر کامندی تست کردم نشد

cd  /opt/hiddify-config/
./uninstall.sh
